import { useCallback, useEffect, useMemo, useRef, useState, type FormEvent, type ReactNode } from "react";
import { AllToAllError, canonicalId, createAllToAllClient, errorExplanation, metric, readable, validateDevelopmentSession, type AllToAllClient, type DevelopmentSession, type IntentInput, type IntentReceipt, type Pair, type Status } from "./tendermatch-all-to-all-api.ts";
import "./tendermatch-all-to-all.css";

type Route = { direction: "supplier" | "tender"; focusId: string; cursor: string | null; supplierId: string | null; tenderId: string | null };
type Bootstrap = { session: DevelopmentSession; client: AllToAllClient } | null;
let captured: Bootstrap | undefined;
function bootstrap(): Bootstrap {
  if (captured !== undefined) return captured;
  captured = null;
  if (!["localhost", "127.0.0.1", "[::1]"].includes(window.location.hostname)) return null;
  const element = document.getElementById("tendermatch-all-to-all-session");
  try { if (element?.textContent && element.textContent.length <= 8192) { const session=validateDevelopmentSession(JSON.parse(element.textContent)); captured={session,client:createAllToAllClient(session)}; } }
  catch { /* Unavailable is explicit; never load a different dataset. */ }
  finally { element?.remove(); }
  return captured;
}
function route(session: DevelopmentSession): Route {
  const p=new URL(window.location.href).searchParams,direction=p.get('direction')==='tender'?'tender':'supplier';
  return {direction,focusId:p.get('focus')??(direction==='supplier'?session.initialSupplierId:session.initialTenderId),cursor:p.get('cursor'),supplierId:p.get('pairSupplier'),tenderId:p.get('pairTender')};
}
function Shell({children,source}:{children:ReactNode;source?:string}) { return <main className="tm9-page" data-tendermatch-mode="all-to-all-development">
  <header className="tm9-header"><div><span className="tm9-kicker">TenderMatch · All-to-all development</span><h1>Review one focus. Inspect one pair.</h1><p>Ranked, bounded access to the sealed pipeline. Formula, retrieval, escalation and human decisions stay separate.</p></div><span className="tm9-environment">{source==='synthetic-local-postgresql'?'Synthetic local PostgreSQL · Not Neon':source==='hosted-development-stage8'?'Hosted Neon development · Read only · Not production':'Isolated development · Not deployed'}</span></header>
  <nav className="tm9-reference-nav" aria-label="Preserved TenderMatch reference pages"><a href="/tendermatch?view=dashboard">Overview</a><a href="/tendermatch?view=formula">Formula</a><span>These preserved reference pages exit development mode explicitly.</span></nav>{children}
</main>; }
function Failure({error,retry,firstPage}:{error:unknown;retry?:()=>void;firstPage?:()=>void}) { const failure=errorExplanation(error);return <section className="tm9-failure" role="alert"><h2>Development environment unavailable</h2><p>{failure.message}</p><code>{failure.code}</code><p>No static snapshot or full matrix has been loaded. No execution authority or model result is implied.</p><div>{retry&&<button type="button" onClick={retry}>Retry bounded request</button>}{failure.staleCursor&&firstPage&&<button type="button" onClick={firstPage}>Start from the first page</button>}</div></section>; }
const shortId=(id:string)=>id.slice(0,8)+'…'+id.slice(-4);
function useBoundedResource<T>(key:string|null,load:(signal:AbortSignal)=>Promise<T>) {
  const [settled,setSettled]=useState<{key:string;data:T|null;error:unknown}|null>(null);
  useEffect(()=>{if(key===null)return;const abort=new AbortController();load(abort.signal).then(data=>{if(!abort.signal.aborted)setSettled({key,data,error:null});}).catch(error=>{if(!abort.signal.aborted)setSettled({key,data:null,error});});return()=>abort.abort();},[key,load]);
  return key!==null&&settled?.key===key?{data:settled.data,error:settled.error,loading:false}:{data:null,error:null,loading:key!==null};
}
function StateMeaning() {return <details className="tm9-meaning"><summary>Missing, measured zero and outside scope are different</summary><p><b>Pair Score 0</b> is an exact calculated result, not a Non-match decision. <b>Missing</b> criterion evidence has null fit and contributes zero points while the denominator stays 100. <b>Outside Formula scope</b> is an original eligibility state: this sealed all-to-all population leaves its score null/unscored, not measured zero. The unchanged Formula reference page retains its earlier display-policy explanation; this workspace shows the actual sealed records.</p><p>Retrieval relevance is a separate lexical/structured ranking value, not Formula fit. An audit-only pair is not labelled promising. Human disposition is never inferred from any number.</p></details>;}
function Signal({label,value,note}:{label:string;value:ReactNode;note?:string}) { return <div className="tm9-signal"><dt>{label}</dt><dd>{value}</dd>{note&&<small>{note}</small>}</div>; }
function Signals({pair}:{pair:Pair}) { const f=pair.formula;return <dl className="tm9-signals">
  <Signal label="Formula v1.1 Pair Score" value={metric(f.pairScore)} note={f.state==='SCORED'?'Exact score / 100 · No threshold':'Unscored · Original scope retained'} />
  <Signal label="Data Coverage" value={metric(f.dataCoverage,true)} note="Assessed criterion weight" />
  <Signal label="Assessed-only Fit" value={metric(f.assessedFitScore)} note={f.assessedFitState==='NO_ASSESSED_CRITERIA'?'Stored diagnostic 0 · No assessed criteria':'Separate diagnostic / 100'} />
  <Signal label="Evidence Confidence" value={metric(f.evidenceConfidence,true)} note={f.evidenceConfidenceState==='NO_ASSESSED_CRITERIA'?'Stored diagnostic 0 · No assessed evidence':'Formula evidence diagnostic, not TORS confidence'} />
  <Signal label="Retrieval Relevance" value={pair.retrieval.relevance===null?'Not ranked':String(pair.retrieval.relevance)} note="Lexical/structured · Separate 0–1 value" />
</dl>; }
function PairDetail({pair,client,session}:{pair:Pair;client:AllToAllClient;session:DevelopmentSession}) {
  const [kind,setKind]=useState<IntentInput['kind']>(pair.shortlist.tier==='AUDIT_ONLY'?'AUDIT_REQUEST':'USER_REVIEW'),[justification,setJustification]=useState(''),[receipt,setReceipt]=useState<IntentReceipt|null>(null),[status,setStatus]=useState<Status|null>(null),[error,setError]=useState<unknown>(null),[submitting,setSubmitting]=useState(false),[uncertain,setUncertain]=useState(false),[statusLoading,setStatusLoading]=useState(false);
  const candidate=pair.eligibility.state==='CANDIDATE_ELIGIBLE_WITH_LIMITATIONS',audit=pair.shortlist.tier==='AUDIT_ONLY',scope=kind==='AUDIT_REQUEST'?'request-audit':'request-review',permitted=candidate&&session.scopes.includes(scope),detailRef=useRef<HTMLElement>(null);
  useEffect(()=>{const element=detailRef.current;element?.focus({preventScroll:true});element?.scrollIntoView({block:'start',behavior:'instant'});},[]);
  async function submit(event:FormEvent) {event.preventDefault();if(!permitted||submitting)return;setSubmitting(true);setError(null);try{const r=await client.intent({supplierId:pair.supplierId,tenderId:pair.tenderId,kind,justification});setReceipt(r);setUncertain(false);}catch(e){setError(e);setUncertain(true);}finally{setSubmitting(false);}}
  async function refreshStatus() {if(!receipt||statusLoading)return;setStatusLoading(true);setError(null);try{setStatus(await client.status(receipt.requestId));}catch(e){setError(e);}finally{setStatusLoading(false);}}
  return <section className="tm9-detail" aria-labelledby="tm9-detail-title" ref={detailRef} tabIndex={-1} data-selected-pair={pair.supplierId+':'+pair.tenderId}>
    <header><span className="tm9-kicker">Selected-pair detail · Frozen evidence</span><h2 id="tm9-detail-title">Supplier × Tender</h2><p><b>Supplier</b> <code>{pair.supplierId}</code><br/><b>Tender</b> <code>{pair.tenderId}</code></p></header>
    <Signals pair={pair}/>
    <dl className="tm9-states"><div><dt>Eligibility / scope</dt><dd>{readable(pair.eligibility.state)}</dd>{pair.eligibility.reasons?.length&&<small>{pair.eligibility.reasons.map(readable).join(' · ')}</small>}</div><div><dt>Shortlist tier</dt><dd>{readable(pair.shortlist.tier??pair.shortlist.state)}</dd><small>{audit?'Audit only · Not promising or automatically AI-ready':'Shortlist membership is not a decision'}</small></div><div><dt>Escalation state</dt><dd>{readable(pair.escalation.state)}</dd><small>{pair.escalation.reasons.map(readable).join(' · ')||'No automatic escalation reason'}</small>{pair.escalation.omissions.length>0&&<small>Omissions: {pair.escalation.omissions.map(readable).join(' · ')}</small>}</div><div><dt>Main limitation</dt><dd>{pair.formula.mainLimitation?readable(pair.formula.mainLimitation.criterion):'Formula not scored'}</dd><small>{pair.formula.mainLimitation?.limitations.map(readable).join(' · ')}</small></div><div><dt>Human disposition</dt><dd>{pair.humanDisposition.value===null?'Unavailable in this versioned contract':readable(pair.humanDisposition.value)}</dd><small>Human only · No decision has been inferred</small></div><div><dt>Execution authorization</dt><dd>No authority granted by this view</dd><small>Actual authorization is not loaded; an intent does not authorize a job</small></div></dl>
    {pair.criteria&&pair.criteria.length>0&&<details className="tm9-criteria"><summary>Inspect {pair.criteria.length} criterion contributions and evidence references</summary>{pair.criteria.map(c=><article key={c.code}><h3>{readable(c.code)}</h3><p><b>{c.points} / {c.maxPoints} points</b> · {c.state==='MISSING'?'Missing · Fit unknown':`Assessed fit ${c.fit} / 5`} · Evidence Confidence {c.evidenceConfidence===null?'Missing':`${c.evidenceConfidence}%`}</p><p>{c.limitations.map(readable).join(' · ')}</p>{c.references.length?<><ul>{c.references.slice(0,25).map((r,i)=><li key={r.id+':'+i}><code>{r.id}</code></li>)}</ul>{c.references.length>25&&<small>Showing the first 25 of {c.references.length} references already present in this bounded detail response.</small>}</>:<p>No supported supplier evidence reference for this criterion.</p>}</article>)}</details>}
    {session.hosted?<section className="tm9-intent" aria-label="Read-only AI and human authority boundary"><h3>AI / Full TORS status: unavailable</h3><p>{readable(pair.aiTors.state)}. No AI result, artifact or execution authority exists in this host.</p><p><b>Read only.</b> Review intents, report/audit requests, Human Disposition changes and all execution routes are disabled. Shortlist and escalation metadata describe sealed records, not new actions.</p></section>:<section className="tm9-intent" aria-labelledby="tm9-intent-title"><h3 id="tm9-intent-title">Selective Full TORS / AI request</h3><p>{candidate?audit?'Requestable only through an explicit audit trigger. This pair is not promoted as promising.':'An explicit justified review or report intent may be recorded. No model is called by this view.':'This original scope outcome is inspectable but is not requestable under the sealed Stage 7 candidate policy.'}</p><p><b>Provider execution unavailable here.</b> Request → authorization → queue → assessment are distinct states. This action records only the request.</p>
      <form onSubmit={submit}><label>Intent kind<select value={kind} disabled={!candidate||submitting||uncertain||!!receipt} onChange={e=>setKind(e.target.value as IntentInput['kind'])}>{!audit&&<><option value="USER_REVIEW">User review</option><option value="REPORT_REQUEST">Report request</option></>}<option value="AUDIT_REQUEST">Audit request</option></select></label><label>Why this explicit pair needs review<textarea value={justification} minLength={3} maxLength={2000} disabled={!candidate||submitting||uncertain||!!receipt} onChange={e=>setJustification(e.target.value)} placeholder="An attributed user assertion, not source evidence" /></label><p>Attributed by the server to <b>{session.subject}</b>. Maximum 100 on-demand intents per plan, across all users.</p><button type="submit" disabled={!permitted||justification.trim().length<3||submitting||!!receipt}>{submitting?'Recording intent…':uncertain?'Retry the same attributed intent':audit?'Record audit intent':'Record review/report intent'}</button>{!permitted&&<small>{candidate?'This session lacks the required intent scope.':'Outside the requestable candidate population.'}</small>}</form>
      {uncertain&&<p role="status">Outcome not confirmed. The same unchanged content retains its idempotency key on retry; no model execution is implied.</p>}
      {receipt&&<div className="tm9-receipt" role="status"><b>Intent recorded{receipt.reused?' · Existing request reused':''}</b><code>{receipt.requestId}</code><p>Execution authority not implied · 0 jobs queued by this action · 0 model calls.</p>{session.scopes.includes('assessment-read')?<button type="button" disabled={statusLoading} onClick={refreshStatus}>{statusLoading?'Reading status…':'Read existing request/job status'}</button>:<small>Assessment-read permission is required to inspect future jobs.</small>}</div>}
      {Boolean(error)&&<Failure error={error}/>}
      {status&&<section className="tm9-job-status" aria-label="Existing request and future job status"><h4>Existing status, not generated work</h4><p>Request: {readable(status.request.state)} · Authorization: {readable(status.request.executionAuthorization)}</p>{status.jobs.length?<ul>{status.jobs.map(j=><li key={j.job_id}><b>{readable(j.state)}</b><code>{j.job_id}</code><span>Provider {j.provider_version} · Model {j.model_version}</span><span>Prompt {j.prompt_version} · Schema {j.schema_version}</span><span>Input tokens: {j.input_tokens??'Unknown'} · Output tokens: {j.output_tokens??'Unknown'} · Cost (micro-USD): {j.cost_microusd??'Unknown'}</span><small>Advisory assessment state, not Formula or human disposition. No artifact generated by viewing this status.</small></li>)}</ul>:<p>No existing jobs for this frozen request input. Recorded is not queued, running or complete.</p>}{status.moreJobs&&<p>Only ten existing jobs are shown. Additional known job IDs require explicit authorized API lookup.</p>}</section>}
    </section>}
  </section>;
}
function FocusForm({value,onFocus}:{value:Route;onFocus:(id:string)=>void}) { const [id,setId]=useState(value.focusId),[invalid,setInvalid]=useState(false);return <form className="tm9-focus-form" onSubmit={e=>{e.preventDefault();if(!canonicalId(id.trim())){setInvalid(true);return;}setInvalid(false);onFocus(id.trim());}}><label htmlFor="tm9-focus-id">Canonical {value.direction} ID<input id="tm9-focus-id" value={id} onChange={e=>setId(e.target.value)} aria-invalid={invalid} aria-describedby="tm9-focus-help" spellCheck={false} autoComplete="off" /></label><button type="submit">Load ranked candidates</button><small id="tm9-focus-help">The Stage 8 contract currently exposes canonical IDs, not an entity-name catalogue. No full-universe lookup is performed.{invalid&&' Enter a lowercase canonical UUID.'}</small></form>; }
export default function TenderMatchAllToAll() {
  const [connection,setConnection]=useState(bootstrap),session=connection?.session,client=connection?.client;
  const [expired,setExpired]=useState(false);
  const [value,setValue]=useState<Route|null>(()=>session?route(session):null),[healthRetry,setHealthRetry]=useState(0),[retry,setRetry]=useState(0);
  const pairKey=value?.supplierId&&value?.tenderId?value.supplierId+':'+value.tenderId:null;
  const health=useBoundedResource(client?String(healthRetry):null,useCallback(signal=>client!.health(signal),[client])),context=health.data,healthError=health.error;
  const direction=value?.direction??'supplier',focusId=value?.focusId??'',cursor=value?.cursor??null,supplierId=value?.supplierId??'',tenderId=value?.tenderId??'';
  const pageResource=useBoundedResource(context?[context.bindingId,direction,focusId,cursor,retry].join(':'):null,useCallback(signal=>client!.page(direction,focusId,cursor,25,signal),[client,direction,focusId,cursor])),page=pageResource.data,pageError=pageResource.error,pageLoading=pageResource.loading;
  const pairResource=useBoundedResource(context&&pairKey?[context.bindingId,pairKey,retry].join(':'):null,useCallback(signal=>client!.detail(supplierId,tenderId,signal),[client,supplierId,tenderId])),pair=pairResource.data,pairError=pairResource.error,pairLoading=pairResource.loading;
  useEffect(()=>{
    if(!session)return;
    const clear=()=>{captured=null;setConnection(null);setExpired(true);};
    if([healthError,pageError,pairError].some(e=>e instanceof AllToAllError&&e.status===401)){clear();return;}
    const timer=setTimeout(clear,Math.max(0,session.expiresAt-Date.now()));return()=>clearTimeout(timer);
  },[session,healthError,pageError,pairError]);
  useEffect(()=>{if(!session)return;const pop=()=>setValue(route(session));window.addEventListener('popstate',pop);return()=>window.removeEventListener('popstate',pop);},[session]);
  const navigate=(update:Partial<Route>)=>{if(!session||!value)return;const next={...value,...update},u=new URL(window.location.href);u.search=new URLSearchParams({mode:'all-to-all-dev',direction:next.direction,focus:next.focusId,...(next.cursor?{cursor:next.cursor}:{}),...(next.supplierId&&next.tenderId?{pairSupplier:next.supplierId,pairTender:next.tenderId}:{})}).toString();window.history.pushState(null,'',u);setValue(route(session));};
  const metadata=useMemo(()=>context?Object.entries(context.population).map(([name,count])=>({name:readable(name),count:count.toLocaleString('en-US')})):[],[context]);
  if(!session||!client||!value)return <Shell><Failure error={new AllToAllError(expired?'INVALID_OR_EXPIRED_SESSION':'DEVELOPMENT_SESSION_UNAVAILABLE')}/></Shell>;
  return <Shell source={session.sourceMode}>{healthError?<Failure error={healthError} retry={()=>setHealthRetry(n=>n+1)}/>:!context?<p className="tm9-loading" role="status">Checking the exact sealed development environment…</p>:<>
    {session.hosted&&<p className="tm9-session" role="status">Development reader: {session.subject} · Session expires {new Date(session.expiresAt).toLocaleTimeString()} · Memory only; operator renewal required. No writes or model calls.</p>}
    <section className="tm9-population" aria-label="Pinned population counts">{metadata.map(m=><div key={m.name}><span>{m.name}</span><b>{m.count}</b></div>)}<small>Version-pinned metadata only · Not a matrix download</small></section>
    <details className="tm9-binding"><summary>Inspect environment and run identity</summary><p>Source: {session.sourceMode} · Service: {context.version}</p><dl>{Object.entries({binding:context.bindingId,eligibility:context.eligibilityRunId,formula:context.formulaRunId,ranking:context.rankingRunId,shortlist:context.shortlistRunId,escalationPlan:context.planId}).map(([key,id])=><div key={key}><dt>{readable(key)}</dt><dd><code>{id}</code></dd></div>)}</dl></details>
    <nav className="tm9-focus-nav" aria-label="Ranked focus direction"><button type="button" aria-current={value.direction==='supplier'?'page':undefined} onClick={()=>navigate({direction:'supplier',focusId:session.initialSupplierId,cursor:null,supplierId:null,tenderId:null})}>Supplier-focused results</button><button type="button" aria-current={value.direction==='tender'?'page':undefined} onClick={()=>navigate({direction:'tender',focusId:session.initialTenderId,cursor:null,supplierId:null,tenderId:null})}>Tender-focused results</button></nav>
    <FocusForm key={value.direction+':'+value.focusId} value={value} onFocus={id=>navigate({focusId:id,cursor:null,supplierId:null,tenderId:null})}/><StateMeaning/>
    <section className="tm9-results" aria-labelledby="tm9-results-title" aria-busy={pageLoading}><header><div><span className="tm9-kicker">25 candidates per page · Maximum API page 100</span><h2 id="tm9-results-title">{value.direction==='supplier'?'Tenders for this supplier':'Suppliers for this tender'}</h2><p>Ordered by Retrieval Relevance, then canonical ID. Pair Score is unchanged and is not the ranking value.</p></div></header>
      {pageLoading&&<p role="status">Loading one bounded candidate page…</p>}{Boolean(pageError)&&<Failure error={pageError} retry={()=>setRetry(n=>n+1)} firstPage={()=>navigate({cursor:null})}/>}
      {page&&<><div className="tm9-table-scroll"><table className="tm9-table"><caption className="tm9-visually-hidden">One bounded ranked focus page. Every row retains independent Formula and retrieval values.</caption><thead><tr><th scope="col">{value.direction==='supplier'?'Tender':'Supplier'} ID</th><th scope="col">Pair Score</th><th scope="col">Data Coverage</th><th scope="col">Assessed-only Fit</th><th scope="col">Evidence Confidence</th><th scope="col">Retrieval Relevance</th><th scope="col">Shortlist tier</th><th scope="col">Detail</th></tr></thead><tbody>{page.results.map(p=>{const id=value.direction==='supplier'?p.tenderId:p.supplierId;return <tr key={p.supplierId+':'+p.tenderId} data-pair-score={p.formula.pairScore} className={pairKey===p.supplierId+':'+p.tenderId?'tm9-selected':''}><th scope="row"><code title={id}>{shortId(id)}</code></th><td data-label="Pair Score"><b>{metric(p.formula.pairScore)}</b><small>/ 100</small></td><td data-label="Data Coverage">{metric(p.formula.dataCoverage,true)}</td><td data-label="Assessed-only Fit">{metric(p.formula.assessedFitScore)}</td><td data-label="Evidence Confidence">{metric(p.formula.evidenceConfidence,true)}</td><td data-label="Retrieval Relevance">{p.retrieval.relevance===null?'Not ranked':String(p.retrieval.relevance)}</td><td data-label="Shortlist tier">{readable(p.shortlist.tier??'NOT_SHORTLISTED')}{p.shortlist.tier==='AUDIT_ONLY'&&<small>Not promising / not AI-ready</small>}</td><td><button type="button" aria-label={'Open pair detail for '+id} onClick={()=>navigate({supplierId:p.supplierId,tenderId:p.tenderId})}>Inspect pair</button></td></tr>;})}</tbody></table></div>{page.results.length===0&&<p className="tm9-empty" role="status">No eligible candidate rows exist for this pinned focus. Empty does not mean Non-match.</p>}<nav className="tm9-pager" aria-label="Candidate pagination"><span>{page.results.length} candidates loaded{page.hasMore?' · More available':' · End of this focus'}</span><button type="button" disabled={!value.cursor||pageLoading} onClick={()=>navigate({cursor:null})}>First page</button><button type="button" disabled={!page.nextCursor||pageLoading} onClick={()=>navigate({cursor:page.nextCursor})}>Next page</button><small>Browser Back/Forward preserves cursor and focus.</small></nav></>}
    </section>
    {pairLoading&&<p role="status">Loading only the selected pair and its criterion references…</p>}{Boolean(pairError)&&<Failure error={pairError} retry={()=>setRetry(n=>n+1)}/>}{pair&&<PairDetail key={pair.supplierId+':'+pair.tenderId} pair={pair} client={client} session={session}/>}
    {session.hosted&&<details className="tm9-binding" data-development-observations><summary>Development request observations · Not an SLA</summary><p>Only this tab since reload; at most 50 recent records, no tokens or response bodies.</p><pre>{JSON.stringify(client.observations(),null,2)}</pre></details>}
    {!pairKey&&<section className="tm9-detail-placeholder"><h2>Inspect a selected pair</h2><p>Open one row for scope, all five independent metrics, main limitation and frozen evidence.{session.hosted?' This hosted connection is strictly read-only.':' Explicit review intent is separate from execution.'} No full TORS artifact or human decision is invented.</p></section>}
  </>}</Shell>;
}
