import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createHash,randomBytes} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {ALL_TO_ALL_FORMULA,ALL_TO_ALL_VERSION,ALL_TO_ALL_PREFIX,createAllToAllClient,validateDevelopmentSession,validatePair,validatePage,metric,errorExplanation,AllToAllError} from '../apps/tender-apps/src/tendermatch-all-to-all-api.ts';
import {SERVICE_VERSION,API_PREFIX} from '../packages/tendermatch/src/service-stage8.ts';
import {FORMULA} from '../packages/tendermatch/src/formula-stage4-adapter.ts';
import {createStage9FixtureServer} from '../scripts/serve-tendermatch-stage9-fixture.mjs';
import {id} from './fixtures/tendermatch-stage9.mjs';
const sha=s=>createHash('sha256').update(s.replaceAll('\r\n','\n')).digest('hex'),read=async path=>{
  const source=await readFile(new URL('../'+path,import.meta.url),'utf8');
  if(path!=='apps/tender-apps/src/main.tsx')return source;
  const wiring='  const surfaceStatus = path === "/tendermatch" && new URL(window.location.href).searchParams.get("mode") === "all-to-all-dev" ? "All-to-all development · Version-pinned API · No model execution" : route.surfaceStatus;\n';
  assert.ok(source.replaceAll('\r\n','\n').includes(wiring));
  // Only these two exact conditional status-wiring edits are allowed in the shared shell.
  return source.replaceAll('\r\n','\n').replace(wiring,'').replace('<small>{route.label} · {surfaceStatus}</small>','<small>{route.label} · {route.surfaceStatus}</small>');
},credential=()=>randomBytes(32).toString('base64url');
const session=()=>({schemaVersion:'tendermatch-browser-session/1.0.0',sourceMode:'synthetic-local-postgresql',bindingId:'a'.repeat(64),token:credential(),csrfToken:credential(),subject:'synthetic-reviewer',scopes:['read','request-review','request-audit','assessment-read'],expiresAt:Date.now()+3600000,initialSupplierId:id(2),initialTenderId:id(10000)});
test('Stage 9 transport uses the exact Stage 8 and Formula identities without browser server imports',async()=>{
  assert.equal(ALL_TO_ALL_VERSION,SERVICE_VERSION);assert.equal(ALL_TO_ALL_PREFIX,API_PREFIX);assert.equal(ALL_TO_ALL_FORMULA,FORMULA);const source=await read('apps/tender-apps/src/tendermatch-all-to-all-api.ts');assert.doesNotMatch(source,/node:|from ['"]pg|connectStage3|loadTenderMatchRuntime|staticPartition|pair-index|localStorage|sessionStorage/);assert.match(source,/credentials:'omit'/);assert.match(source,/redirect:'error'/);
});
test('Overview and Formula retain d230590; reviewed sibling changes retain release checkpoint 56c22f4',async()=>{
  const files={'tendermatch-formula-view.tsx':'c2246e4db42bcd6803c9c73017b531f35f6f1d154774d4ff14d5e399c3522662','tendermatch-formula-contract.ts':'bccf7f66d7d0dc20e193798187f508f7c0d48f46f84c293fa1303f453fca7d92','tendermatch.css':'e1797c6b755d485009e25920043c7d0d137a2c2c6eb3d875fe588c246a89193c','main.tsx':'0cfc4975576a9e03412d0e9c413365a88abfd7bdc24e53c4f4d3603dd02eb8a9','client-shell.css':'001788f24d0376c9422987074aacc1959068fe1b222edb66bff929ead83ef9b9','balance-sheet-app.tsx':'1fb006d8098b102fc1fb3042d61198177422992a42b717df489918af8f383d12','logistics-costing-app.tsx':'07711dd3b5a03aec2fc572b81127ad5a19010aaf9b7a9111adf07bb78d1eb6cb'};for(const [file,expected] of Object.entries(files)){ if(['main.tsx','balance-sheet-app.tsx','logistics-costing-app.tsx'].includes(file)){ const baseline=execFileSync('git',['show','56c22f49b5e176ef5e428c91b7424593a069f03a:apps/tender-apps/src/'+file],{encoding:'utf8'}); assert.equal(sha(await readFile(new URL('../apps/tender-apps/src/'+file,import.meta.url),'utf8')),sha(baseline),file); }else assert.equal(sha(await read('apps/tender-apps/src/'+file)),expected,file); }
  const app=await read('apps/tender-apps/src/tendermatch-app.tsx');assert.equal(sha(app.slice(app.indexOf('function DashboardView('),app.indexOf('type GeographicRadarMarker'))),'47d8ee49d399d5e639184469b6f8243ce79da27722d5f1951ea0c7ee18f6d7de');
  const wrapper=app.slice(app.indexOf('export default function TenderMatchApp()'),app.indexOf('function TenderMatchLegacyApp()'));assert.match(wrapper,/searchParams\.get\("mode"\) === "all-to-all-dev"/);assert.doesNotMatch(wrapper,/loadTenderMatchRuntime|fetch\(|runtimeTenders/);assert.match(app,/lazy\(\(\) => import\("\.\/tendermatch-all-to-all.tsx"\)\)/);
});
test('development session is explicit, expiring and cannot be mistaken for a database credential',()=>{
  const s=session();assert.equal(validateDevelopmentSession(s).sourceMode,'synthetic-local-postgresql');assert.throws(()=>validateDevelopmentSession({...s,token:'postgres://no-browser-db'}),/SESSION/);assert.throws(()=>validateDevelopmentSession({...s,csrfToken:s.token}),/SESSION/);assert.throws(()=>validateDevelopmentSession({...s,expiresAt:0}),/SESSION/);assert.throws(()=>validateDevelopmentSession({...s,bindingId:'latest'}),/SESSION/);assert.equal(metric(0),'0');assert.equal(metric(0,true),'0%');assert.equal(metric(null),'Not scored');assert.equal(errorExplanation(new AllToAllError('INVALID_CURSOR')).staleCursor,true);
});
test('network, malformed, oversized and timeout responses fail closed without secondary fetch',async()=>{
  for(const response of [()=>{throw new TypeError('private internal origin');},()=>new Response('not-json',{status:503,headers:{'Content-Type':'text/html'}}),()=>new Response('x'.repeat(524289),{headers:{'Content-Type':'application/json'}}),()=>new Response(JSON.stringify({error:{code:'PINNED_SCHEMA_UNAVAILABLE'}}),{status:503,headers:{'Content-Type':'application/json'}})]){let calls=0;const c=createAllToAllClient(session(),async()=>{calls++;return response();});await assert.rejects(()=>c.health(),AllToAllError);assert.equal(calls,1);}
  let calls=0;const timeout=createAllToAllClient(session(),async(_url,init)=>{calls++;return new Promise((_,reject)=>init.signal.addEventListener('abort',()=>reject(new Error('aborted')),{once:true}));},15);await assert.rejects(()=>timeout.health(),e=>e.code==='API_TIMEOUT');assert.equal(calls,1);
  const cancelled=createAllToAllClient(session(),async()=>{throw new Error('cancelled');}),abort=new AbortController();abort.abort();await assert.rejects(()=>cancelled.health(abort.signal),e=>e.code==='REQUEST_CANCELLED');
});
test('invalid IDs/direction/page limits cannot cause a network request',async()=>{
  let calls=0;const c=createAllToAllClient(session(),async()=>{calls++;throw new Error('unexpected');});for(const limit of [0,101,-1,Infinity])await assert.rejects(()=>c.page('supplier',id(2),null,limit));await assert.rejects(()=>c.page('supplier;DROP',id(2)));await assert.rejects(()=>c.detail("' OR true--",id(1)));assert.equal(calls,0);
});
test('actual browser transport to authenticated local PostgreSQL preserves all dimensions and bounded traversal',{skip:!process.env.TENDERMATCH_PGLITE_ROOT},async()=>{
  const server=await createStage9FixtureServer({localFixture:true});try{
    const observed=[],fetcher=async(url,init)=>{observed.push({url,method:init.method,credentials:init.credentials,headers:init.headers,body:init.body});return fetch(server.origin+url,{...init,headers:{...init.headers,...(init.method==='POST'?{Origin:server.origin}:{})}});},client=createAllToAllClient(server.bootstrap,fetcher),context=await client.health();assert.equal(context.population.universe,240);assert.equal(context.population.candidates,182);
    let cursor=null,rows=[];do{const page=await client.page('supplier',id(2),cursor,25);rows.push(...page.results);cursor=page.nextCursor;}while(cursor);assert.equal(rows.length,36);assert.equal(new Set(rows.map(p=>p.tenderId)).size,36);const tenderPage=await client.page('tender',id(10000));assert.equal(tenderPage.results.length,5);assert.equal((await client.page('tender',server.fixture.outsideTenderId)).results.length,0);
    const zero=await client.detail(server.fixture.zeroSupplierId,id(10000));assert.equal(zero.formula.pairScore,0);assert.equal(zero.retrieval.units,0);assert.ok(zero.criteria.some(c=>c.state==='MISSING'&&c.fit===null&&c.points===0));const outside=await client.detail(id(2),server.fixture.outsideTenderId);assert.equal(outside.eligibility.state,'OUTSIDE_FORMULA_V1_1_SCOPE');assert.equal(outside.formula.pairScore,null);const scope=await client.detail(id(2),server.fixture.scopeTenderId);assert.equal(scope.eligibility.state,'SCOPE_NOT_DEMONSTRATED');assert.equal(scope.formula.pairScore,null);
    const detail=await client.detail(rows[0].supplierId,rows[0].tenderId);assert.deepEqual(detail.formula,rows[0].formula);assert.deepEqual(detail.retrieval,rows[0].retrieval);assert.equal(detail.humanDisposition.value,null);
    assert.throws(()=>validatePair({...detail,formula:{...detail.formula,pairScore:99}}),/RESPONSE/);assert.throws(()=>validatePair({...zero,formula:{...zero.formula,fit:[0,0,0,0,0]}}),/RESPONSE/);assert.throws(()=>validatePair({...outside,formula:{...outside.formula,pairScore:0}}),/RESPONSE/);const page=await client.page('supplier',id(2),null,1);assert.throws(()=>validatePage({...page,results:[page.results[0],page.results[0]]},server.bootstrap,'supplier',id(2),2),/RESPONSE/);await assert.rejects(()=>client.page('supplier',id(1),page.nextCursor),e=>e.code==='CURSOR_SCOPE_OR_EXPIRY');
    const input={supplierId:server.fixture.reviewPair.supplierId,tenderId:server.fixture.reviewPair.tenderId,kind:'USER_REVIEW',justification:'Explicit local transport test, not evidence'},first=await client.intent(input),again=await client.intent(input);assert.equal(first.requestId,again.requestId);assert.equal(again.reused,true);assert.equal(first.queuedExecutions,0);const writes=observed.filter(r=>r.method==='POST');assert.equal(writes[0].headers['Idempotency-Key'],writes[1].headers['Idempotency-Key']);assert.ok(writes.every(r=>r.headers['X-CSRF-Token']===server.bootstrap.csrfToken));assert.ok(writes.every(r=>!JSON.parse(r.body).actor&&!JSON.parse(r.body).tenantId));const status=await client.status(first.requestId);assert.deepEqual(status.jobs,[]);
    const audit={...input,supplierId:server.fixture.auditPair.supplierId,tenderId:server.fixture.auditPair.tenderId};await assert.rejects(()=>client.intent(audit),e=>e.code==='AUDIT_TRIGGER_REQUIRED');assert.equal((await client.intent({...audit,kind:'AUDIT_REQUEST'})).state,'RECORDED');assert.ok(observed.every(r=>r.url.startsWith(API_PREFIX)&&r.credentials==='omit'&&!r.url.includes(server.bootstrap.token)));assert.ok(observed.every(r=>!r.url.includes('/matrix')&&!r.url.includes('/data/')));assert.equal(server.metrics.staticRequests.length,0);
    for(const table of ['escalation_authorization','escalation_job','escalation_artifact'])assert.equal((await server.c.query('SELECT count(*)::int n FROM tendermatch_retrieval.'+table)).rows[0].n,0);
  }finally{await server.close();}
});
test('actual absent Stage 7 dependency is unavailable to the frontend client without fixture fallback',{skip:!process.env.TENDERMATCH_PGLITE_ROOT},async()=>{
  const server=await createStage9FixtureServer({localFixture:true,missingStage7:true});try{const client=createAllToAllClient(server.bootstrap,(url,init)=>fetch(server.origin+url,init));await assert.rejects(()=>client.health(),e=>e.code==='PINNED_SCHEMA_UNAVAILABLE');assert.equal(server.metrics.apiRequests.length,1);assert.equal(server.metrics.staticRequests.length,0);}finally{await server.close();}
});
