import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import path from 'node:path';
import {main} from '../scripts/tendermatch-stage7.mjs';
import {TENANT} from '../scripts/lib/tendermatch-input-manifest.mjs';
import {hash,BUDGETS,SECTIONS,PROMPT_VERSION,TORS_SCHEMA,planEscalations,assessmentInputIdentity,validateTorsOutput,validateTrigger} from '../packages/tendermatch/src/escalation-stage7.ts';
import {providerInspection} from '../scripts/lib/tendermatch-stage7.mjs';
import {createEscalationPlan,prepareEscalationPlan,automaticRequests,persistRequests,readDecisions,selectedEscalationPair,queryRequests,enqueueAuthorized,claimJob,executeLeasedJob,persistValidatedArtifact,queryJobs,failJob,cancelJob,onDemandRequest,selectedArtifact,TABLES} from '../scripts/lib/tendermatch-stage7-queue.mjs';
import {initializeStage7Fixture} from './fixtures/tendermatch-stage7.mjs';
import {requestColumns} from '../scripts/lib/tendermatch-stage7-queue.mjs';
import {stage7CodeIdentity} from '../scripts/lib/tendermatch-stage7.mjs';
import {main as auditMain,referenceAllocation} from '../scripts/tendermatch-validate-stage7.mjs';
const id=n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
const input=(s,t,tier=1)=>({pairKey:hash([s,t]),supplierId:id(s),tenderId:id(t),tier,supplierProfile:hash(s),tenderProfile:hash(t),methodHash:hash('method'),formulaPolicy:hash('formula'),units:tier===1?10000:0,score:0,coverage:0,confidence:0,states:[0,0,0,0,0],selection:{supplierNominationRank:1,tenderNominationRank:1,supplierTieSize:2,tenderTieSize:2,reasonMask:tier===1?3:12}});
const output=()=>({schemaVersion:TORS_SCHEMA,authority:'ADVISORY_ONLY',summary:'Synthetic boundary fixture, not an actual assessment',sections:SECTIONS.map(code=>({code,findings:[{statement:'No supported conclusion in this synthetic test',state:'MISSING',evidenceIds:[]}]})),limitations:['Synthetic local fixture; no model or external service called'],humanReviewRequired:true});
test('Stage 7 default is disconnected and configured path has no executable provider',async()=>{assert.equal((await main()).connects,false);await assert.rejects(()=>main(['compare']),/approval/);const p=await providerInspection();assert.equal(p.registeredExecutableAdapters,0);assert.equal(p.credentialLoaded,false);});
test('hard budgets, deterministic supplier round-robin, audit separation and explainable omissions',()=>{
 const rows=[];for(let s=1;s<=10;s++)for(let t=20;t<=40;t++)rows.push(input(s,t));rows.push(input(11,41,2));const before=hash(rows),budget={name:'fixture',total:25,supplier:4,tender:2},a=planEscalations(rows,budget),b=planEscalations([...rows].reverse(),budget);assert.equal(a.summary.outcomeHash,b.summary.outcomeHash);assert.equal(hash(rows),before);assert.equal(a.summary.selected,25);assert.ok(a.summary.maxSupplier<=4&&a.summary.maxTender<=2);assert.equal(a.summary.suppliers,10);assert.ok(a.rows.filter(r=>r.state==='DEFERRED_BUDGET').every(r=>r.omissions.length));assert.equal(a.rows.find(r=>r.tier===2).state,'AUDIT_EXPLICIT_ONLY');assert.equal(a.summary.executionAuthorized,0);assert.throws(()=>planEscalations(rows,{name:'huge',total:1001,supplier:4,tender:2}),/budget/);assert.throws(()=>planEscalations([rows[0],rows[0]],BUDGETS[0]),/Duplicate/);
});
test('input reuse excludes allocation identity and evidence changes affect only endpoint pairs',()=>{const p=input(1,20),identity=assessmentInputIdentity(p);assert.equal(hash(identity),hash(assessmentInputIdentity({...p,pairKey:hash('changed shortlist'),selection:{...p.selection,tenderTieSize:90}})));assert.notEqual(hash(identity),hash(assessmentInputIdentity({...p,supplierProfile:hash('changed')})));assert.throws(()=>validateTrigger({kind:'USER_REVIEW',actor:'abc',requestId:'req',justification:'review'},2),/audit/);assert.equal(validateTrigger({kind:'AUDIT_REQUEST',actor:'abc',requestId:'req',justification:'inspect blind spot'},2).automaticPromising,false);});
test('Full TORS validation preserves sections, missingness, evidence references and separate scores',()=>{const e=[{id:'e1',content:{}}],valid=output();assert.deepEqual(validateTorsOutput(valid,e),valid);assert.throws(()=>validateTorsOutput({...valid,pairScore:90},e),/SCHEMA/);const bad=structuredClone(valid);bad.sections[0].findings[0]={statement:'Unsupported positive',state:'SUPPORTED',evidenceIds:[]};assert.throws(()=>validateTorsOutput(bad,e),/LINKAGE/);bad.sections[0].findings[0].evidenceIds=['unknown'];assert.throws(()=>validateTorsOutput(bad,e),/LINKAGE/);assert.throws(()=>validateTorsOutput({...valid,sections:[]},e),/SCHEMA/);});
test('supplier and tender invalidation is strictly pair-local despite global allocation changes',()=>{const rows=[input(1,20),input(1,21),input(2,20),input(2,21)];for(const [field,changedId,profile] of [['supplierId',id(1),'supplierProfile'],['tenderId',id(20),'tenderProfile']]){const changed=rows.map(p=>p[field]===changedId?{...p,[profile]:hash('changed-frozen-identity')}:p);assert.equal(changed.filter((p,i)=>hash(assessmentInputIdentity(p))!==hash(assessmentInputIdentity(rows[i]))).length,2);assert.equal(changed.filter((p,i)=>p[field]!==changedId&&hash(assessmentInputIdentity(p))===hash(assessmentInputIdentity(rows[i]))).length,2);}});
test('independent audit defaults disconnected and independently reproduces all allocation fields',async()=>{assert.equal((await auditMain([])).connects,false);await assert.rejects(()=>auditMain(['verify']),/approval/);const rows=[];for(let s=1;s<=8;s++)for(let t=20;t<=60;t++)rows.push(input(s,t,(s+t)%5===0?2:1));for(const budget of BUDGETS)assert.deepEqual(referenceAllocation([...rows].reverse(),budget),planEscalations(rows,budget).rows);});
test('recorded Stage 7 real comparison and local benchmark bind final code and zero AI calls',{skip:!process.env.TENDERMATCH_STAGE7_EVIDENCE},async()=>{
 const root=new URL('../',import.meta.url),p=JSON.parse(await readFile(new URL('docs/evidence/tendermatch-stage7-comparison.json',root),'utf8')),b=JSON.parse(await readFile(new URL('docs/evidence/tendermatch-stage7-benchmark.json',root),'utf8')),code=await stage7CodeIdentity();assert.deepEqual(p.code,code);assert.deepEqual(b.code,code);assert.deepEqual(p.protectedBefore,p.protectedAfter);assert.equal(p.expectedPersistence.planId,hash(p.expectedPersistence.identity));assert.equal(p.chosen.population,28034);assert.equal(p.chosen.selected,500);assert.deepEqual(p.chosen.byState,{DEFERRED_BUDGET:18031,AUDIT_EXPLICIT_ONLY:9503,PLANNED_REVIEW:500});assert.equal(p.chosen.suppliers,99);assert.equal(p.chosen.tenders,377);assert.equal(p.chosen.maxSupplier,6);assert.equal(p.chosen.maxTender,2);for(const r of p.results)assert.equal(r.replayIdentical,true);assert.equal(p.committedWrites,0);assert.equal(p.modelCalls,0);assert.equal(p.sourceConnections,0);assert.equal(p.provider.registeredExecutableAdapters,0);assert.equal(p.provider.credentialLoaded,false);assert.equal(b.execution.inserted,80);assert.equal(b.readback.outcomeHash,b.execution.outcomeHash);assert.equal(b.replay.inserted,0);assert.equal(b.replay.reused,80);assert.equal(b.rows.escalation_job,0);assert.equal(b.rows.escalation_artifact,0);assert.equal(b.sourceConnections,0);assert.equal(b.modelCalls,0);assert.equal(b.queries.supplier.fullTraversal,10);assert.equal(b.queries.tender.fullTraversal,2);for(const direction of ['supplier','tender'])assert.match(JSON.stringify(b.queries[direction].indexEligibilityDiagnostic),new RegExp(`escalation_request_${direction}`));
});
test('Stage 7 actual local SQL request/authorization/queue/artifact boundary',{skip:!process.env.TENDERMATCH_PGLITE_ROOT},async(t)=>{
 const {PGlite}=await import(pathToFileURL(path.join(process.env.TENDERMATCH_PGLITE_ROOT,'@electric-sql/pglite/dist/index.js')).href),db=new PGlite(),c={query:async(q,v)=>{const r=await db.query(q,v);return {...r,rowCount:r.affectedRows??r.rows.length};}};
 try{await assert.rejects(async()=>db.exec(await readFile(new URL('../db/tendermatch-dev/100-escalation-up.sql',import.meta.url),'utf8')),/development target mismatch/);const loaded=await initializeStage7Fixture(db,c),plan=createEscalationPlan(loaded,{hash:hash('synthetic-code')});await db.exec('SET ROLE tendermatch_result_writer');await c.query("SELECT set_config('tendermatch.tenant_id',$1,false)",[TENANT]);let requests;
  await t.test('all decisions seal atomically, requests are idempotent and no AI job is implied',async()=>{await prepareEscalationPlan(c,plan);assert.equal((await readDecisions(c,plan)).count,loaded.rows.length);requests=await automaticRequests(c,plan,loaded);const first=await persistRequests(c,requests);assert.ok(first.inserted>0);assert.equal((await persistRequests(c,requests)).inserted,0);assert.equal((await persistRequests(c,requests,{readOnly:true})).outcomeHash,first.outcomeHash);assert.equal((await c.query('SELECT count(*)::int n FROM tendermatch_retrieval.escalation_job')).rows[0].n,0);assert.deepEqual(await prepareEscalationPlan(c,plan),{insertedPlan:0,insertedDecisions:0});});
  await t.test('post-install independent SQL and installed function audits execute locally',async()=>{
   const source=await readFile(new URL('../scripts/tendermatch-validate-stage7.mjs',import.meta.url),'utf8'),sql=source.split('report.sql=(await c.query(`')[1]?.split('`,[TENANT,planId]')[0];assert.ok(sql?.startsWith('SELECT'));const counts=(await c.query(sql,[TENANT,plan.planId])).rows[0];assert.equal(counts.total,loaded.rows.length);assert.equal(counts.unique_pairs,loaded.rows.length);assert.equal(counts.planned,requests.length);assert.equal(counts.invalid_reasons,0);
   const migration=(await readFile(new URL('../db/tendermatch-dev/100-escalation-up.sql',import.meta.url),'utf8')).replaceAll('\r\n','\n');let n=0;for(const match of migration.matchAll(/CREATE FUNCTION tendermatch_retrieval\.(\w+)\(\) RETURNS trigger[\s\S]*?AS \$\$([\s\S]*?)\$\$;/g)){const f=(await c.query(`SELECT prosrc,prosecdef,has_function_privilege(current_user,p.oid,'EXECUTE') executable FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='tendermatch_retrieval' AND proname=$1`,[match[1]])).rows[0];assert.equal(f.prosrc.replaceAll('\r\n','\n'),match[2]);assert.equal(f.prosecdef,match[1]==='log_escalation_job');assert.equal(f.executable,false);n++;}assert.equal(n,7);
  });
  await t.test('selected original signals, bounded request pages and explicit provider/owner gate',async()=>{const r=requests[0],d=await selectedEscalationPair(c,plan,r);assert.equal(d.formula.denominator,100);assert.equal(d.aiTors,null);const page=await queryRequests(c,plan,{direction:'supplier',focusId:r.supplierId,limit:1});assert.equal(page.requests.length,1);assert.equal(page.requests[0].requestState,'RECORDED');await assert.rejects(()=>enqueueAuthorized(c,r,'none',null),/PROVIDER/);await assert.rejects(()=>c.query("INSERT INTO tendermatch_retrieval.escalation_authorization(tenant_id) VALUES($1)",[TENANT]),/permission/);});
  await t.test('owner grant enables only bounded matching provider execution, real output validation is separate',async()=>{await db.exec('RESET ROLE');await c.query(`INSERT INTO tendermatch_retrieval.escalation_authorization(tenant_id,authorization_id,plan_id,actor,rationale,provider_version,model_version,prompt_version,schema_version,max_jobs,max_calls,max_concurrency,max_output_tokens,expires_at) VALUES($1,'fixture-grant',$2,'fixture-owner','Synthetic boundary test only','synthetic-provider','synthetic-model',$3,$4,10,20,1,4096,clock_timestamp()+interval '1 hour')`,[TENANT,plan.planId,PROMPT_VERSION,TORS_SCHEMA]);await db.exec('SET ROLE tendermatch_result_writer');let calls=0;const provider={version:'synthetic-provider',modelVersion:'synthetic-model',promptVersion:PROMPT_VERSION,assess:async()=>{calls++;return {output:output(),usage:{inputTokens:0,outputTokens:0,costMicroUsd:0}};}};const job=await enqueueAuthorized(c,requests[0],'fixture-grant',provider);assert.equal(job.state,'QUEUED');const leased=await claimJob(c,'fixture-grant','fixture-worker');assert.equal(leased.attempts,1);assert.equal(await claimJob(c,'fixture-grant','other-worker'),null);await assert.rejects(()=>persistValidatedArtifact(c,{...leased,lease_token:'wrong'},output()),/row|lease|Lease|P0002|query/i);const complete=await executeLeasedJob(c,leased,provider);assert.equal(complete.state,'SUCCEEDED');assert.equal(calls,1);assert.equal((await enqueueAuthorized(c,requests[0],'fixture-grant',provider)).state,'SUCCEEDED');assert.equal(calls,1);assert.equal((await queryJobs(c,'fixture-grant')).length,1);assert.equal((await selectedArtifact(c,job.job_id,complete.artifact_id)).output.authority,'ADVISORY_ONLY');assert.equal((await c.query('SELECT count(*)::int n FROM tendermatch_retrieval.escalation_event')).rows[0].n,4);});
  await t.test('distinct audit and omitted-pair on-demand requests preserve original evidence',async()=>{const audit=loaded.rows.find(p=>p.tier===2);await assert.rejects(()=>onDemandRequest(c,plan,audit,{kind:'USER_REVIEW',actor:'test-reviewer',requestId:'audit-1',justification:'inspect this pair'}),/audit/);const request=await onDemandRequest(c,plan,audit,{kind:'AUDIT_REQUEST',actor:'test-auditor',requestId:'audit-2',justification:'investigate retrieval blind spot'});assert.equal(request.kind,'AUDIT_REQUEST');assert.equal(request.trigger.automaticPromising,false);let omitted;for(const s of [2,4])for(const t of [20,21,24,25,26]){const p=await selectedEscalationPair(c,plan,{supplierId:id(s),tenderId:id(t)});if(p&&!p.tier)omitted=p;}assert.ok(omitted);const user=await onDemandRequest(c,plan,omitted,{kind:'USER_REVIEW',actor:'test-reviewer',requestId:'omitted-1',justification:'explicit review of an existing candidate'});assert.equal(user.input.identity.supplierId,omitted.supplierId);await assert.rejects(()=>onDemandRequest(c,plan,{supplierId:id(1),tenderId:id(22)},{kind:'USER_REVIEW',actor:'test-reviewer',requestId:'outside',justification:'request outside Formula scope'}),/NOT_A_FORMULA_CANDIDATE/);});
  await t.test('lease expiry, safe retry, cancellation, invalid output and unknown provider outcome never fabricate success',async()=>{const provider={version:'synthetic-provider',modelVersion:'synthetic-model',promptVersion:PROMPT_VERSION,assess:async()=>({output:{},usage:{}})};await enqueueAuthorized(c,requests[1],'fixture-grant',provider);const first=await claimJob(c,'fixture-grant','w1',{leaseMs:10});await new Promise(resolve=>setTimeout(resolve,20));const second=await claimJob(c,'fixture-grant','w2');assert.equal(second.attempts,2);assert.notEqual(second.lease_token,first.lease_token);await assert.rejects(()=>failJob(c,first,'TRANSIENT_NETWORK'),/LEASE_LOST/);const retry=await failJob(c,second,'CONFIRMED_TRANSIENT_FAILURE',{retryable:true});assert.equal(retry.state,'RETRY_WAIT');assert.equal(await claimJob(c,'fixture-grant','early'),null);assert.equal((await cancelJob(c,retry.job_id)).state,'CANCELLED');await enqueueAuthorized(c,requests[2],'fixture-grant',provider);const malformed=await claimJob(c,'fixture-grant','validator');assert.equal((await executeLeasedJob(c,malformed,provider)).last_error,'TORS_OUTPUT_VALIDATION_FAILED');await enqueueAuthorized(c,requests[3],'fixture-grant',provider);const failed=await claimJob(c,'fixture-grant','provider');assert.equal((await executeLeasedJob(c,failed,{...provider,assess:async()=>{throw new Error('private raw provider error');}})).last_error,'PROVIDER_OUTCOME_UNKNOWN');assert.equal((await c.query('SELECT count(*)::int n FROM tendermatch_retrieval.escalation_artifact')).rows[0].n,1);});
  requests.push(...(await c.query(`SELECT ${requestColumns} FROM tendermatch_retrieval.escalation_request WHERE kind IN ('AUDIT_REQUEST','USER_REVIEW') ORDER BY kind`)).rows);
  await t.test('direct malformed or orphan artifacts cannot bypass output validation and atomic completion',async()=>{const provider={version:'synthetic-provider',modelVersion:'synthetic-model',promptVersion:PROMPT_VERSION,assess:async()=>({output:output()})};await enqueueAuthorized(c,requests[4],'fixture-grant',provider);const lease=await claimJob(c,'fixture-grant','negative-output');const variants=[{...output(),limitations:null},{...output(),pairScore:99},output()];variants[2].sections[0].findings[0].state='UNSUPPORTED_STATE';for(const value of variants)await assert.rejects(()=>c.query('INSERT INTO tendermatch_retrieval.escalation_artifact(tenant_id,artifact_id,job_id,input_hash,lease_token,output) VALUES($1,$2,$3,$4,$5,$6)',[TENANT,hash(value),lease.job_id,lease.input_hash,lease.lease_token,JSON.stringify(value)]),/TORS|artifact|dimension/i);await assert.rejects(()=>c.query('INSERT INTO tendermatch_retrieval.escalation_artifact(tenant_id,artifact_id,job_id,input_hash,lease_token,output) VALUES($1,$2,$3,$4,$5,$6)',[TENANT,hash('orphan'),lease.job_id,lease.input_hash,lease.lease_token,JSON.stringify(output())]),/atomically/);await cancelJob(c,lease.job_id);let staleCalls=0;await assert.rejects(()=>executeLeasedJob(c,lease,{...provider,assess:async()=>{staleCalls++;return {output:output()};}}),/LIVE_AUTHORIZED_LEASE_REQUIRED/);assert.equal(staleCalls,0);});
  await t.test('owner hard job/call/concurrency caps and lease exhaustion are enforced in SQL',async()=>{await db.exec('RESET ROLE');await c.query(`INSERT INTO tendermatch_retrieval.escalation_authorization(tenant_id,authorization_id,plan_id,actor,rationale,provider_version,model_version,prompt_version,schema_version,max_jobs,max_calls,max_concurrency,max_output_tokens,expires_at) VALUES($1,'budget-grant',$2,'fixture-owner','Synthetic hard budget test','budget-provider','budget-model',$3,$4,2,1,1,4096,clock_timestamp()+interval '1 hour')`,[TENANT,plan.planId,PROMPT_VERSION,TORS_SCHEMA]);await db.exec('SET ROLE tendermatch_result_writer');const provider={version:'budget-provider',modelVersion:'budget-model',promptVersion:PROMPT_VERSION,assess:async()=>({output:output()})};const first=await enqueueAuthorized(c,requests[0],'budget-grant',provider),second=await enqueueAuthorized(c,requests[1],'budget-grant',provider);await assert.rejects(()=>enqueueAuthorized(c,requests[2],'budget-grant',provider),/job budget/);const leased=await claimJob(c,'budget-grant','budget-worker');await assert.rejects(()=>claimJob(c,'budget-grant','parallel-worker'),/budget/);await failJob(c,leased,'CONFIRMED_RETRYABLE',{retryable:true});await assert.rejects(()=>claimJob(c,'budget-grant','over-budget'),/budget/);await cancelJob(c,first.job_id);await cancelJob(c,second.job_id);const ordinary={version:'synthetic-provider',modelVersion:'synthetic-model',promptVersion:PROMPT_VERSION,assess:async()=>({output:output()})};const exhausted=await enqueueAuthorized(c,requests[5],'fixture-grant',ordinary);for(let n=1;n<=3;n++){const j=await claimJob(c,'fixture-grant','expiry-worker',{leaseMs:10});assert.equal(j.attempts,n);await new Promise(resolve=>setTimeout(resolve,20));}assert.equal(await claimJob(c,'fixture-grant','no-fourth-attempt'),null);assert.equal((await c.query('SELECT state,last_error FROM tendermatch_retrieval.escalation_job WHERE job_id=$1',[exhausted.job_id])).rows[0].last_error,'LEASE_EXPIRED_ATTEMPTS_EXHAUSTED');});
  await t.test('sealed plans, forged evidence, direct events and cross-tenant writes fail closed',async()=>{await assert.rejects(()=>c.query('INSERT INTO tendermatch_retrieval.escalation_decision SELECT * FROM tendermatch_retrieval.escalation_decision LIMIT 1'),/row|query/i);for(const table of TABLES.filter(n=>n!=='escalation_job'))await assert.rejects(()=>c.query(`DELETE FROM tendermatch_retrieval.${table} WHERE false`),/permission/);await assert.rejects(()=>c.query('INSERT INTO tendermatch_retrieval.escalation_event SELECT * FROM tendermatch_retrieval.escalation_event LIMIT 1'),/permission/);const bad=structuredClone(requests[0]);bad.requestId=hash('forged');bad.input.evidence[0].content.projection={invented:true};await assert.rejects(()=>persistRequests(c,[bad]),/frozen evidence/);await c.query('BEGIN');try{await c.query("SELECT set_config('tendermatch.tenant_id','other-stage7-tenant',true)");for(const table of TABLES)assert.equal((await c.query(`SELECT count(*)::int n FROM tendermatch_retrieval.${table}`)).rows[0].n,0);await assert.rejects(()=>c.query('INSERT INTO tendermatch_retrieval.escalation_plan(tenant_id,plan_id,shortlist_run_id,identity) VALUES($1,$2,$3,$4)',[TENANT,hash('cross-tenant'),plan.identity.shortlistRunId,JSON.stringify(plan.identity)]),/row-level security/);}finally{await c.query('ROLLBACK');}});
  await t.test('new allocation plans reuse unchanged successful evidence and preserve old artifacts',async()=>{
   const next=createEscalationPlan(loaded,{hash:hash('next-policy-code')});await prepareEscalationPlan(c,next);const nextRequests=await automaticRequests(c,next,loaded);await persistRequests(c,nextRequests);assert.equal(nextRequests[0].inputHash,requests[0].inputHash);assert.notEqual(nextRequests[0].requestId,requests[0].requestId);
   await db.exec('RESET ROLE');await c.query(`INSERT INTO tendermatch_retrieval.escalation_authorization SELECT tenant_id,'next-grant',$1,actor,rationale,provider_version,model_version,prompt_version,schema_version,max_jobs,max_calls,max_concurrency,max_output_tokens,expires_at,created_at FROM tendermatch_retrieval.escalation_authorization WHERE authorization_id='fixture-grant'`,[next.planId]);await db.exec('SET ROLE tendermatch_result_writer');
   const prior=await enqueueAuthorized(c,nextRequests[0],'next-grant',{version:'synthetic-provider',modelVersion:'synthetic-model',promptVersion:PROMPT_VERSION,assess:async()=>{throw new Error('Must not call');}});assert.equal(prior.state,'SUCCEEDED');assert.equal((await selectedArtifact(c,prior.job_id,prior.artifact_id)).output.authority,'ADVISORY_ONLY');assert.equal((await readDecisions(c,plan)).count,loaded.rows.length);assert.equal((await readDecisions(c,next)).count,loaded.rows.length);
  });
  await t.test('single durable dispatch and expired unknown outcomes cannot call twice',async()=>{
   await db.exec('RESET ROLE');await c.query(`INSERT INTO tendermatch_retrieval.escalation_authorization SELECT tenant_id,'dispatch-grant',plan_id,actor,rationale,'dispatch-provider','dispatch-model',prompt_version,schema_version,max_jobs,max_calls,max_concurrency,max_output_tokens,expires_at,created_at FROM tendermatch_retrieval.escalation_authorization WHERE authorization_id='fixture-grant'`);await db.exec('SET ROLE tendermatch_result_writer');
   let calls=0,release,started;const began=new Promise(resolve=>{started=resolve;}),provider={version:'dispatch-provider',modelVersion:'dispatch-model',promptVersion:PROMPT_VERSION,assess:async()=>{calls++;started();return new Promise(resolve=>{release=()=>resolve({output:output()});});}};
   const job=await enqueueAuthorized(c,requests[0],'dispatch-grant',provider),leased=await claimJob(c,'dispatch-grant','dispatch-worker',{leaseMs:300}),pending=executeLeasedJob(c,leased,provider);await began;await assert.rejects(()=>executeLeasedJob(c,leased,provider),/LIVE_AUTHORIZED_LEASE_REQUIRED/);await new Promise(resolve=>setTimeout(resolve,350));assert.equal(await claimJob(c,'dispatch-grant','retry-worker'),null);assert.equal((await c.query('SELECT last_error FROM tendermatch_retrieval.escalation_job WHERE job_id=$1',[job.job_id])).rows[0].last_error,'PROVIDER_OUTCOME_UNKNOWN');release();await assert.rejects(()=>pending,/row|lease|Lease|query/i);assert.equal(calls,1);
  });
 }finally{await db.close();}
});
test('Stage 7 SQL final focus caps and exact hundred on-demand intents fail closed',{skip:!process.env.TENDERMATCH_PGLITE_ROOT},async()=>{
 const {PGlite}=await import(pathToFileURL(path.join(process.env.TENDERMATCH_PGLITE_ROOT,'@electric-sql/pglite/dist/index.js')).href),db=new PGlite(),c={query:async(q,v)=>{const r=await db.query(q,v);return {...r,rowCount:r.affectedRows??r.rows.length};}};
 try{const loaded=await initializeStage7Fixture(db,c,{supplierCount:12,tenderCount:40}),plan=createEscalationPlan(loaded,{hash:hash('hard-focus-budget-fixture')});await db.exec('SET ROLE tendermatch_result_writer');await c.query("SELECT set_config('tendermatch.tenant_id',$1,false)",[TENANT]);
  for(const direction of ['supplier','tender']){const focus=loaded.rows.find(p=>p.tier===1)[direction+'Id'],keys=new Set(loaded.rows.filter(p=>p.tier===1&&p[direction+'Id']===focus).map(p=>p.pairKey));assert.ok(keys.size>(direction==='supplier'?10:2));let n=0;const decisions=plan.decisions.map(d=>({...d,position:keys.has(d.pairKey)?++n:null,state:d.tier===2?'AUDIT_EXPLICIT_ONLY':keys.has(d.pairKey)?'PLANNED_REVIEW':'DEFERRED_BUDGET'})),identity={...plan.identity,selected:n,allocationHash:hash(decisions)},bad={...plan,planId:hash(identity),identity,decisions};await assert.rejects(()=>prepareEscalationPlan(c,bad),/hard budget exceeded/);}
  await prepareEscalationPlan(c,plan);assert.ok(loaded.rows.length>100);for(let i=0;i<100;i++){const p=loaded.rows[i];await onDemandRequest(c,plan,p,{kind:p.tier===2?'AUDIT_REQUEST':'REPORT_REQUEST',actor:'fixture-reviewer',requestId:'bounded-'+i,justification:'Synthetic explicit review budget check'});}const p=loaded.rows[100];await assert.rejects(()=>onDemandRequest(c,plan,p,{kind:p.tier===2?'AUDIT_REQUEST':'REPORT_REQUEST',actor:'fixture-reviewer',requestId:'over-budget',justification:'Synthetic request exceeding the hard cap'}),/Hard durable request budget exhausted/);assert.equal((await c.query('SELECT count(*)::int n FROM tendermatch_retrieval.escalation_request')).rows[0].n,100);assert.equal((await c.query('SELECT count(*)::int n FROM tendermatch_retrieval.escalation_job')).rows[0].n,0);
 }finally{await db.close();}
});
