import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {evaluateEligibility,scopeInputKey,validateScopeInput,encodeOutcome,decodeOutcome,eligibilityCacheKey,reasonCodes} from '../packages/tendermatch/src/eligibility-scope.ts';
import {createRun,prepareRun,executeUniverse,completeRun,retryAtomic,eligibilityCodeIdentity} from '../scripts/lib/tendermatch-eligibility.mjs';
import {TENANT,sha} from '../scripts/lib/tendermatch-input-manifest.mjs';
const id=n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
const evidence={id:id(50),sourceRecordId:id(51),artifactId:id(52),status:'INFERRED',valueClass:'SOURCE'};
function input(kind,n,category='GOODS',edit={}){const body={kind,id:id(n),featureKey:sha([kind,n]),featureHash:sha(['body',n]),sourceHash:sha(['source',n]),sourceVersion:'synthetic/1',category,
 profileState:kind==='supplier'?'PINNED':null,candidateScope:kind==='supplier'?category:null,signals:kind==='supplier'&&category?[category]:[],scopeEvidence:kind==='supplier'?[evidence]:[],readinessId:null,readinessHash:null,readinessState:'NEEDS_EVIDENCE',classificationValueClass:'ESTIMATED',candidateReasons:[],deadline:'2020-01-01T00:00:00',timezone:null,requirementsMissing:true,hardEvidence:[],...edit};return {...body,key:scopeInputKey(body)};}
const supplier=(scope='GOODS',edit={})=>input('supplier',1,scope,edit),tender=(scope='GOODS',edit={})=>input('tender',2,scope,edit);
const rekey=x=>{const body={...x};delete body.key;return {...body,key:scopeInputKey(body)};};
for(const category of ['SERVICES','CONSULTING','OTHER','EOI','PREQUAL','PREQUALIFICATION','UNRECOGNIZED'])test(`${category} stays outside Formula, never zero/non-match`,()=>{
 const o=evaluateEligibility(supplier(),tender(category));assert.equal(o.state,'OUTSIDE_FORMULA_V1_1_SCOPE');assert.equal(o.scoringState,'NOT_SCORED');assert.ok(!('pairScore' in o));assert.equal(o.hardGate,'NOT_ASSESSED');
});
test('Goods and Works evidence may enter candidate-only later experiments, not ELIGIBLE approval',()=>{for(const scope of ['GOODS','WORKS']){const o=evaluateEligibility(supplier(scope),tender(scope));assert.equal(o.state,'CANDIDATE_ELIGIBLE_WITH_LIMITATIONS');assert.equal(o.hardGate,'NOT_ASSESSED');assert.ok(reasonCodes(o.reasonMask).includes('PROVISIONAL_SCOPE_REQUIRES_REVIEW'));}});
test('source classification and provisional candidate remain separate',()=>{const s=supplier(null,{signals:['GOODS'],candidateScope:'GOODS'}),before=sha(s);assert.equal(evaluateEligibility(s,tender()).state,'CANDIDATE_ELIGIBLE_WITH_LIMITATIONS');assert.equal(s.category,null);assert.equal(sha(s),before);});
test('mixed Goods/Works is evaluated on both evidenced scopes',()=>{const s=supplier('GOODS',{signals:['GOODS','WORKS'],candidateScope:'MIXED'});for(const scope of ['GOODS','WORKS']){const o=evaluateEligibility(s,tender(scope));assert.equal(o.state,'CANDIDATE_ELIGIBLE_WITH_LIMITATIONS');assert.ok(reasonCodes(o.reasonMask).includes('MIXED_SCOPE_REVIEW_REQUIRED'));}});
test('service and consulting potential survives outside Formula',()=>{for(const sc of ['SERVICES','CONSULTING'])for(const tc of ['SERVICES','CONSULTING'])assert.equal(evaluateEligibility(supplier(sc),tender(tc)).servicePotential,'POTENTIALLY_RELEVANT_OUTSIDE_FORMULA');assert.equal(evaluateEligibility(supplier('GOODS',{signals:['GOODS','SERVICES'],candidateScope:'MIXED'}),tender('SERVICES')).servicePotential,'POTENTIALLY_RELEVANT_OUTSIDE_FORMULA');});
test('scope difference is not hard exclusion or known incompatibility',()=>{const o=evaluateEligibility(supplier('GOODS'),tender('WORKS'));assert.equal(o.state,'SCOPE_NOT_DEMONSTRATED');assert.equal(o.hardGate,'NOT_ASSESSED');});
test('absent category/profile/evidence remains needs evidence',()=>{for(const [s,t] of [[supplier(),tender(null)],[supplier(null,{signals:[]}),tender()],[supplier('GOODS',{profileState:'MISSING'}),tender()],[supplier('GOODS',{scopeEvidence:[]}),tender()],[supplier('GOODS',{scopeEvidence:[{...evidence,status:'UNKNOWN'}]}),tender()]])assert.equal(evaluateEligibility(s,t).state,'NEEDS_EVIDENCE');});
test('explicit evidenced hard exclusion has independent reason and gate',()=>{const h={reason:'DEBARMENT',applies:true,evidence:[{...evidence,status:'VERIFIED'}]};const o=evaluateEligibility(supplier('GOODS',{hardEvidence:[h]}),tender());assert.equal(o.state,'HARD_EXCLUDED');assert.equal(o.hardGate,'EXCLUDED');const unsupported=evaluateEligibility(supplier('GOODS',{hardEvidence:[h]}),tender('EOI'));assert.equal(unsupported.state,'OUTSIDE_FORMULA_V1_1_SCOPE');assert.equal(unsupported.hardGate,'EXCLUDED');});
test('unverified, null, absent-artifact hard claims cannot become exclusions',()=>{for(const h of [{reason:'DEBARMENT',applies:true,evidence:[evidence]},{reason:'DEBARMENT',applies:null,evidence:[{...evidence,status:'VERIFIED'}]},{reason:'DEBARMENT',applies:true,evidence:[{...evidence,status:'VERIFIED',artifactId:null}]}]){const o=evaluateEligibility(supplier('GOODS',{hardEvidence:[h]}),tender());assert.equal(o.state,'NEEDS_EVIDENCE');assert.equal(o.hardGate,'UNRESOLVED');}});
test('false hard fact is not positive clearance or restriction',()=>{assert.equal(evaluateEligibility(supplier('GOODS',{hardEvidence:[{reason:'DEBARMENT',applies:false,evidence:[evidence]}]}),tender()).hardGate,'NOT_ASSESSED');});
test('names/IDs/country/budget zero-null/readiness labels do not decide eligibility',()=>{const baseline=evaluateEligibility(supplier(),tender());for(const v of [0,null,999])assert.deepEqual(evaluateEligibility({...supplier(),id:id(555),name:'Unknown',country:'Forbidden',readinessState:'ready',budget:v},{...tender(),country:'Other',budget:v}),baseline);});
test('deadline without timezone is not silently UTC or an exclusion',()=>{assert.ok(reasonCodes(evaluateEligibility(supplier(),tender()).reasonMask).includes('DEADLINE_TIMEZONE_UNRESOLVED'));assert.equal(evaluateEligibility(supplier(),tender(null)).state,'NEEDS_EVIDENCE');});
test('compact dictionary roundtrip retains all states without numeric scoring',()=>{for(const pair of [[supplier(),tender()],[supplier(),tender('EOI')],[supplier(),tender('WORKS')],[supplier(),tender(null)]]){const o=evaluateEligibility(...pair);assert.deepEqual(decodeOutcome(encodeOutcome(o)),o);}for(const bad of [[0,0,0,0,0],[9,1,0,0,0],[0,1,9,0,0],[0,null,0,0,0]])assert.throws(()=>decodeOutcome(bad));});
test('identity validates payload and preserves null distinct from zero',()=>{assert.equal(validateScopeInput(supplier()).category,'GOODS');assert.throws(()=>validateScopeInput({...supplier(),category:'WORKS'}));assert.notEqual(scopeInputKey({...supplier(),category:null}),scopeInputKey({...supplier(),category:0}));});
test('exact full-universe accounting and changed-entity invalidation without matrix allocation',()=>{
 const s=Array.from({length:117},(_,n)=>input('supplier',n+1)),t=Array.from({length:17333},(_,n)=>input('tender',n+1000));
 const keys=(a,b)=>eligibilityCacheKey(a.key,b.key,'a'.repeat(64));assert.equal(s.length*t.length,2027961);
 const changedSupplier=rekey({...s[0],readinessHash:sha('changed evidence')});let affected=0;for(const tender of t)affected+=keys(s[0],tender)!==keys(changedSupplier,tender);assert.equal(affected,17333);
 const changedTender=rekey({...t[0],sourceHash:sha('changed tender')});assert.equal(s.filter(i=>keys(i,t[0])!==keys(i,changedTender)).length,117);
 assert.equal(keys(s[1],t[1]),keys(s[1],t[1]));assert.notEqual(keys(s[0],t[0]),eligibilityCacheKey(s[0].key,t[0].key,'b'.repeat(64)));
});
test('duplicate population and changed policy/source run identity fail or invalidate explicitly',()=>{const x=[supplier(),tender()],code={hash:sha('code')};const r=createRun(x,{normalizationId:sha('norm')},code);assert.throws(()=>createRun([...x,supplier()],{},code));assert.notEqual(createRun(x,{normalizationId:sha('norm2')},code).runId,r.runId);assert.notEqual(createRun(x,{}, {hash:sha('changed')}).policyHash,r.policyHash);});
test('bounded atomic retry; deterministic/auth/network failures are not retried',async()=>{let n=0,retries=0;assert.equal(await retryAtomic(async()=>{if(++n<3)throw Object.assign(new Error('retry'),{code:'40001'});return 42;},()=>retries++),42);assert.equal(retries,2);for(const code of ['42501','23505','08006']){let calls=0;await assert.rejects(()=>retryAtomic(async()=>{calls++;throw Object.assign(new Error('stop'),{code});}));assert.equal(calls,1);}let calls=0;await assert.rejects(()=>retryAtomic(async()=>{calls++;throw Object.assign(new Error('stop'),{code:'40P01'});}));assert.equal(calls,3);});
test('protected Formula, Stage 2 and Stage 2A source/evidence are byte-identical to approved checkpoint',async()=>{for(const file of ['packages/tendermatch/src/exploratory-matching.ts','packages/tendermatch/src/input-normalization.ts','packages/tendermatch/src/supplier-readiness.ts','docs/evidence/tendermatch-development-stage2.json','docs/evidence/tendermatch-stage2a-readiness.json']){
 const expected=execFileSync('git',['show',`5a7f0a9124ada9053f5b1b466d79148cae6ccc16:${file}`],{maxBuffer:5*1024*1024});const current=await readFile(new URL('../'+file,import.meta.url));assert.equal(current.toString().replaceAll('\r\n','\n'),expected.toString().replaceAll('\r\n','\n'));}});
test('Stage 3 source contains no scorer, provider, UI or source-database mutation',async()=>{for(const file of ['packages/tendermatch/src/eligibility-scope.ts','scripts/lib/tendermatch-eligibility.mjs','scripts/lib/tendermatch-eligibility-inputs.mjs']){const source=await readFile(new URL('../'+file,import.meta.url),'utf8');assert.doesNotMatch(source,/evaluateExploratory|evaluatePrepared|embeddingProvider|INSERT INTO public\.|UPDATE registry\.|fetch\(/);}const sql=await readFile(new URL('../db/tendermatch-dev/060-eligibility-up.sql',import.meta.url),'utf8');assert.doesNotMatch(sql,/CREATE ROLE|ALTER ROLE|CREATE DATABASE|pair_score|CASCADE/);});
const stage3Evidence = async name => JSON.parse(await readFile(new URL(`../docs/evidence/tendermatch-stage3-${name}.json`,import.meta.url),'utf8'));
test('recorded real execution, independent readback and cache replay match the isolated policy experiment',async()=>{
 const actual=await stage3Evidence('execute'),isolated=await stage3Evidence('isolated-experiment');
 assert.deepEqual(actual.code,await eligibilityCodeIdentity());assert.deepEqual(actual.identity,isolated.identity);
 assert.equal(actual.runId,sha(actual.identity));assert.equal(actual.runId,isolated.runId);
 const migration=await readFile(new URL('../db/tendermatch-dev/060-eligibility-up.sql',import.meta.url),'utf8');assert.equal(actual.migrationHash,sha(migration.replaceAll('\r\n','\n')));
 for(const phase of [actual.execution,actual.readback,actual.rerun]){assert.equal(phase.total,2027961);assert.equal(phase.outcomeHash,isolated.experiment.outcomeHash);assert.deepEqual(phase.counts,isolated.experiment.counts);}
 assert.deepEqual(actual.completion,{fullReadback:true,pairs:2027961,outcomeHash:isolated.experiment.outcomeHash});
 assert.equal(actual.execution.inserted,2027961);assert.equal(actual.readback.reused,2027961);
 assert.equal(actual.rerun.reused,2027961);assert.equal(actual.rerun.evaluated,0);assert.equal(actual.rerun.inserted,0);
});
test('recorded full universe preserves exact states, service potential and all accounting axes',async()=>{
 const actual=await stage3Evidence('execute'),c=actual.execution.counts;
 assert.equal(actual.inputs.supplier,117);assert.equal(actual.inputs.tender,17333);assert.equal(actual.inputs.pairs,117*17333);
 assert.deepEqual(c.state,{OUTSIDE_FORMULA_V1_1_SCOPE:905697,SCOPE_NOT_DEMONSTRATED:414604,CANDIDATE_ELIGIBLE_WITH_LIMITATIONS:707660});
 for(const axis of ['state','hardGate','scopeRelation','servicePotential','byTenderCategory','bySupplierSource','bySupplierCandidate','bySourceCandidateCategoryState'])assert.equal(Object.values(c[axis]).reduce((a,b)=>a+b,0),2027961,axis);
 assert.equal(c.servicePotential.POTENTIALLY_RELEVANT_OUTSIDE_FORMULA,140600);assert.deepEqual(c.hardGate,{NOT_ASSESSED:2027961});
 assert.equal(c.reasons.PROVISIONAL_SCOPE_REQUIRES_REVIEW+c.reasons.SOURCE_SCOPE_WITH_LIMITATIONS,707660);
 assert.deepEqual(actual.rows,{eligibility_input:17450,eligibility_run:1,eligibility_member:17450,eligibility_pair:2027961,eligibility_completion:1});
});
test('recorded source drift, business-table boundary and denial evidence remain explicit',async()=>{
 const actual=await stage3Evidence('execute');
 for(const kind of ['supplier','tender']){const d=actual.sourceDrift[kind];assert.deepEqual(d.observed,d.pinned);for(const field of ['added','removed','changed'])assert.equal(d[field],0);assert.equal(d.observation.read_only,'on');assert.equal(d.observation.isolation,'repeatable read');}
 assert.equal(Object.keys(actual.protectedBefore).length,15);assert.deepEqual(actual.protectedAfter,actual.protectedBefore);assert.ok(Object.values(actual.protectedAfter).every(n=>n===0));
 assert.deepEqual(actual.negativeChecks,{updateDeleteTruncateDdl:'denied',crossTenantRead:'zero',crossTenantWrite:'denied',sealedMembership:'denied',committedProbeRows:0,tenantBoundary:'TRUSTED_SERVICE_GUC_NOT_USER_AUTHENTICATION'});
 for(const key of ['noScores','noFrontend','noSourceWrites','noDeployment'])assert.equal(actual[key],true);
 assert.equal(actual.identity.scoring,'NOT_SCORED');assert.equal(actual.identity.maturity,'DEVELOPMENT_EXPERIMENT');
});
test('ephemeral eligibility persistence and security contract',{skip:!process.env.TENDERMATCH_PGLITE_ROOT},async(t)=>{
 const {PGlite}=await import(pathToFileURL(path.join(process.env.TENDERMATCH_PGLITE_ROOT,'@electric-sql/pglite/dist/index.js')).href);const db=new PGlite();const c={query:async(q,v)=>{const r=await db.query(q,v);return {...r,rowCount:r.affectedRows??r.rows.length};}};
 try{
  await db.exec(`CREATE SCHEMA tendermatch_retrieval;CREATE ROLE tendermatch_result_writer NOLOGIN;GRANT USAGE ON SCHEMA tendermatch_retrieval TO tendermatch_result_writer;CREATE TABLE tendermatch_retrieval.schema_migration(version text primary key);CREATE FUNCTION tendermatch_retrieval.reject_immutable_change() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Immutable'; END $$;
 CREATE TABLE tendermatch_retrieval.normalized_feature(tenant_id text,feature_key text,PRIMARY KEY(tenant_id,feature_key));
 CREATE TABLE tendermatch_retrieval.normalization_snapshot(tenant_id text,normalization_id text,supplier_count int,tender_count int,PRIMARY KEY(tenant_id,normalization_id));
 CREATE TABLE tendermatch_retrieval.normalization_member(tenant_id text,normalization_id text,kind text,entity_id uuid,feature_key text);`);
  const sql=await readFile(new URL('../db/tendermatch-dev/060-eligibility-up.sql',import.meta.url),'utf8');await assert.rejects(()=>db.exec(sql),/target mismatch/);await db.exec(sql.slice(sql.indexOf('CREATE TABLE')));
  const inputs=[supplier(),input('supplier',3,'WORKS'),tender(),input('tender',4,'WORKS'),input('tender',5,'SERVICES')],norm=sha('norm');
  for(const i of inputs){await db.query('INSERT INTO tendermatch_retrieval.normalized_feature VALUES($1,$2)',[TENANT,i.featureKey]);await db.query('INSERT INTO tendermatch_retrieval.normalization_member VALUES($1,$2,$3,$4,$5)',[TENANT,norm,i.kind,i.id,i.featureKey]);}
  await db.query('INSERT INTO tendermatch_retrieval.normalization_snapshot VALUES($1,$2,2,3)',[TENANT,norm]);
  await db.exec('GRANT SELECT ON tendermatch_retrieval.normalization_snapshot,tendermatch_retrieval.normalization_member TO tendermatch_result_writer;SET ROLE tendermatch_result_writer;');await db.query("SELECT set_config('tendermatch.tenant_id',$1,false)",[TENANT]);
  const run=createRun(inputs,{normalizationId:norm},{hash:sha('code')});
  await t.test('all unique pairs, full deterministic readback and unchanged cache reuse',async()=>{assert.equal((await prepareRun(c,run)).runInserted,1);const first=await executeUniverse(c,run);assert.equal(first.total,6);assert.equal(first.evaluated,6);assert.equal(first.inserted,6);const rb=await executeUniverse(c,run,{readOnly:true,verifyCalculation:true});assert.equal(rb.outcomeHash,first.outcomeHash);assert.equal(rb.reused,6);assert.equal(rb.evaluated,0);await completeRun(c,run,rb);assert.equal((await prepareRun(c,run)).inputInserted,0);assert.equal((await executeUniverse(c,run)).inserted,0);});
  await t.test('changed supplier invalidates its three pairs only; historical run survives',async()=>{const changed=[rekey({...inputs[0],readinessHash:sha('new')}),...inputs.slice(1)],next=createRun(changed,{normalizationId:norm},{hash:sha('code')});await prepareRun(c,next);const r=await executeUniverse(c,next);assert.equal(r.evaluated,3);assert.equal(r.reused,3);assert.equal((await executeUniverse(c,run,{readOnly:true})).total,6);});
  await t.test('changed tender invalidates two pairs only, without duplicate intersections',async()=>{const changed=inputs.map(i=>i.id===id(2)?rekey({...i,sourceHash:sha('changed source evidence')}):i),next=createRun(changed,{normalizationId:norm},{hash:sha('code')});await prepareRun(c,next);const r=await executeUniverse(c,next);assert.equal(r.evaluated,2);assert.equal(r.reused,4);const again=await executeUniverse(c,next,{readOnly:true,verifyCalculation:true});assert.equal(again.outcomeHash,r.outcomeHash);});
  await t.test('incomplete membership/coverage cannot be marked complete',async()=>{const incomplete=createRun(inputs.slice(0,-1),{normalizationId:norm},{hash:sha('new')});await assert.rejects(()=>prepareRun(c,incomplete),/Incomplete/);const fresh=createRun(inputs,{normalizationId:norm},{hash:sha('different')});await prepareRun(c,fresh);await assert.rejects(()=>completeRun(c,fresh,{outcomeHash:sha('empty'),total:6,counts:{}}),/Incomplete/);});
  await t.test('writer cannot mutate, delete, truncate, DDL or append sealed membership',async()=>{for(const q of ["UPDATE tendermatch_retrieval.eligibility_pair SET state=0","DELETE FROM tendermatch_retrieval.eligibility_input","TRUNCATE tendermatch_retrieval.eligibility_run","CREATE TABLE tendermatch_retrieval.forbidden(id int)"])await assert.rejects(()=>db.query(q),/permission denied/);await assert.rejects(()=>db.query('INSERT INTO tendermatch_retrieval.eligibility_member SELECT * FROM tendermatch_retrieval.eligibility_member LIMIT 1'),/sealed/);});
  await t.test('cross-tenant rows invisible and inserts denied',async()=>{await db.query("SELECT set_config('tendermatch.tenant_id','other',false)");assert.equal((await db.query('SELECT count(*)::int n FROM tendermatch_retrieval.eligibility_pair')).rows[0].n,0);await assert.rejects(()=>prepareRun(c,run),/row-level security/);});
 }finally{await db.close();}
});
