import test from 'node:test';
import assert from 'node:assert/strict';
import {randomBytes} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import path from 'node:path';
import {request as rawRequest} from 'node:http';
import {API_PREFIX,createSessionRegistry,createCursorCodec,ServiceError,SCOPES,pageLimit,intentInput} from '../packages/tendermatch/src/service-stage8.ts';
import {hash,PROMPT_VERSION,TORS_SCHEMA,SECTIONS} from '../packages/tendermatch/src/escalation-stage7.ts';
import {TENANT} from '../scripts/lib/tendermatch-input-manifest.mjs';
import {bindPin,createStage8Store,rankingQuery} from '../scripts/lib/tendermatch-stage8-store.mjs';
import {createStage8HttpServer} from '../scripts/lib/tendermatch-stage8-http.mjs';
import {main,developmentPin,createApprovedNeonStage8Store,stage8CodeIdentity} from '../scripts/tendermatch-stage8.mjs';
import {initializeStage8Fixture} from './fixtures/tendermatch-stage8.mjs';
import {initializeStage6Fixture,id} from './fixtures/tendermatch-stage6.mjs';
import {enqueueAuthorized,claimJob,executeLeasedJob,requestColumns} from '../scripts/lib/tendermatch-stage7-queue.mjs';
const credential=()=>randomBytes(32).toString('base64url');
const seed=(extra={})=>({token:credential(),csrfToken:credential(),subject:'fixture-reviewer',tenantId:TENANT,scopes:[...SCOPES],expiresAt:Date.now()+3600000,...extra});
const fakePin=()=>({tenantId:TENANT,...Object.fromEntries(['planId','shortlistRunId','shortlistOutcomeHash','rankingRunId','rankingOutcomeHash','formulaRunId','formulaOutcomeHash','eligibilityRunId','eligibilityOutcomeHash','methodHash','formulaPolicy','eligibilityPolicy','planCodeHash','allocationHash'].map(k=>[k,hash(k)])),automaticRequests:0});
async function pgFixture(){const {PGlite}=await import(pathToFileURL(path.join(process.env.TENDERMATCH_PGLITE_ROOT,'@electric-sql/pglite/dist/index.js')).href),db=new PGlite(),metrics={queries:0,responseBytes:0,maxResponseBytes:0};const c={query:async(q,v)=>{metrics.queries++;const r=await db.query(q,v),bytes=Buffer.byteLength(JSON.stringify(r.rows));metrics.responseBytes+=bytes;metrics.maxResponseBytes=Math.max(metrics.maxResponseBytes,bytes);return {...r,rowCount:r.affectedRows??r.rows.length};},end:async()=>{}};return {db,c,metrics};}
async function httpFixture(store,seeds){const sessions=createSessionRegistry(seeds),server=createStage8HttpServer({store,sessions,allowedOrigins:['http://127.0.0.1:43123']});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin='http://127.0.0.1:'+server.address().port;return {server,sessions,origin,close:async()=>{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}};}

test('Stage 8 default is disconnected; approved dev pins preserve exact prior outcomes',async()=>{
  assert.equal(main().connects,false);assert.equal(main().listens,false);await assert.rejects(()=>createApprovedNeonStage8Store({cursors:createCursorCodec(randomBytes(32))}),/approval/);
  const pin=bindPin(await developmentPin());assert.equal(pin.formulaOutcomeHash,'b7a12c75afc68f241ce740eaf557ada12abb79159406c1ebf6471e69ed6e5df6');assert.equal(pin.rankingOutcomeHash,'1a7cc57af3cf1d06824700cfc4c367658b9abc67519d372a8e77fc1f4c123b47');assert.equal(pin.automaticRequests,500);
});
test('opaque sessions expire/revoke, enforce scopes and CSRF, and rate limit without plaintext output',()=>{
  let now=Date.now();const s=seed(),registry=createSessionRegistry([s],()=>now),p=registry.authenticate('Bearer '+s.token);assert.equal(p.tenantId,TENANT);registry.csrf(p,s.csrfToken);assert.throws(()=>registry.csrf(p,credential()),/CSRF/);assert.throws(()=>registry.authenticate('Bearer wrong'),/AUTHENTICATION/);assert.throws(()=>registry.authorize({...p,scopes:['read']},'request-review'),/SCOPE/);assert.ok(!JSON.stringify(p).includes(s.token));registry.revoke(s.token);assert.throws(()=>registry.authenticate('Bearer '+s.token),/SESSION/);
  const next=createSessionRegistry([s],()=>now);now+=3600001;assert.throws(()=>next.authenticate('Bearer '+s.token),/SESSION/);now=Date.now();const limited=createSessionRegistry([s],()=>now);for(let i=0;i<120;i++)limited.authenticate('Bearer '+s.token);assert.throws(()=>limited.authenticate('Bearer '+s.token),/RATE_LIMIT/);
});
test('signed cursors bind tenant/version/focus and expire; numeric/query/body limits fail closed',()=>{
  let now=Date.now();const codec=createCursorCodec(randomBytes(32),()=>now),token=codec.encode('scope-a',0,id(1));assert.equal(codec.decode(token,'scope-a').units,0);assert.throws(()=>codec.decode(token,'scope-b'),/SCOPE/);assert.throws(()=>codec.decode(token.slice(0,-1)+(token.endsWith('a')?'b':'a'),'scope-a'),/CURSOR/);now+=900001;assert.throws(()=>codec.decode(token,'scope-a'),/EXPIRY/);
  for(const x of ['0','101','1000000','1 OR 1=1','-1'])assert.throws(()=>pageLimit(x),/LIMIT/);assert.equal(pageLimit(null),25);assert.equal(pageLimit('100'),100);assert.throws(()=>intentInput({supplierId:id(1),tenderId:id(20),kind:'USER_REVIEW',justification:'review',actor:'spoof'},'request-123'),/FIELDS/);
});
test('adapter bounds survive direct callers and failed connections release bounded capacity',async()=>{
  for(const limit of [0,101,Infinity,NaN,'1'])assert.throws(()=>rankingQuery(fakePin(),Buffer.alloc(32),{direction:'supplier',focusId:id(1),limit},null),/LIMIT/);
  assert.throws(()=>rankingQuery(fakePin(),Buffer.alloc(32),{direction:'supplier; DROP TABLE',focusId:id(1),limit:1},null),/DIRECTION/);
  let rejectConnection,connections=0;const store=createStage8Store({connect:()=>{connections++;return new Promise((_,reject)=>{rejectConnection=reject;});},pins:[fakePin()],cursors:createCursorCodec(randomBytes(32)),connectionLimit:1}),p={tenantId:TENANT},binding=bindPin(fakePin()).bindingId;
  const first=store.health(p,binding),caught=assert.rejects(()=>first,e=>e.code==='SEALED_BACKEND_UNAVAILABLE');await assert.rejects(()=>store.health(p,binding),e=>e.code==='BOUNDED_SERVICE_BUSY');assert.equal(connections,1);rejectConnection(new Error('credential-like-private-backend-error'));await caught;
  const second=store.health(p,binding),caughtSecond=assert.rejects(()=>second,e=>e.code==='SEALED_BACKEND_UNAVAILABLE');assert.equal(connections,2);rejectConnection(new Error('safe failure'));await caughtSecond;
});
test('actual HTTP hard body/response/header bounds and safe error output',{timeout:10000},async()=>{
  const s=seed(),pin=bindPin(fakePin()),store={health:async()=>({payload:'x'.repeat(524288)}),intent:async()=>{throw new Error('postgres://DO_NOT_DISCLOSE_INTERNAL_CREDENTIAL');}},web=await httpFixture(store,[s]);
  try{
    const url=web.origin+API_PREFIX+'/intents?binding='+pin.bindingId,headers={Authorization:'Bearer '+s.token,Origin:'http://127.0.0.1:43123','X-CSRF-Token':s.csrfToken,'Idempotency-Key':'bounded-001','Content-Type':'application/json'},send=async(body,extra={})=>{const r=await fetch(url,{method:'POST',headers:{...headers,...extra},body});return {status:r.status,text:await r.text()};};
    const giant=await fetch(web.origin+API_PREFIX+'/health?binding='+pin.bindingId,{headers:{Authorization:'Bearer '+s.token}});assert.equal(giant.status,503);assert.equal((await giant.json()).error.code,'BOUNDED_RESPONSE_UNAVAILABLE');
    assert.equal((await send('x'.repeat(8193))).status,413);assert.equal((await send('invalid JSON')).status,400);assert.equal((await send('{}',{'Content-Encoding':'gzip'})).status,415);assert.equal((await send('{}',{'Content-Type':'text/plain'})).status,415);
    const failure=await send(JSON.stringify({supplierId:id(1),tenderId:id(20),kind:'USER_REVIEW',justification:'Fixture safe error'}));assert.equal(failure.status,503);assert.ok(!failure.text.includes('DO_NOT_DISCLOSE'));assert.ok(!failure.text.includes(s.token));assert.ok(!failure.text.includes(s.csrfToken));
    const duplicate=await new Promise((resolve,reject)=>{const req=rawRequest(web.origin,{path:API_PREFIX+'/health?binding='+pin.bindingId,headers:['Authorization','Bearer '+s.token,'Authorization','Bearer '+s.token]},r=>{r.resume();r.on('end',()=>resolve(r.statusCode));});req.on('error',reject);req.end();});assert.equal(duplicate,400);
  }finally{await web.close();}
});
test('missing Stage 7 schema is explicitly unavailable through actual HTTP, not legacy/static fallback',{skip:!process.env.TENDERMATCH_PGLITE_ROOT},async()=>{
  const {db,c}=await pgFixture();let web;try{await initializeStage6Fixture(db);await db.exec('SET ROLE tendermatch_result_writer');const pin=fakePin(),store=createStage8Store({connect:async()=>c,pins:[pin],cursors:createCursorCodec(randomBytes(32)),connectionLimit:1}),s=seed();web=await httpFixture(store,[s]);const response=await fetch(web.origin+API_PREFIX+'/health?binding='+bindPin(pin).bindingId,{headers:{Authorization:'Bearer '+s.token}}),body=await response.json();assert.equal(response.status,503);assert.equal(body.error.code,'PINNED_SCHEMA_UNAVAILABLE');assert.equal(body.legacyFallback,false);assert.equal(body.modelCalls,0);}finally{await web?.close();await db.close();}
});
test('authenticated Stage 8 actual HTTP/PostgreSQL contract',{skip:!process.env.TENDERMATCH_PGLITE_ROOT},async(t)=>{
  const {db,c,metrics}=await pgFixture();let web;try{
    const fixture=await initializeStage8Fixture(db,c),pin=fixture.pin,binding=bindPin(pin).bindingId,s=seed(),readOnly=seed({subject:'fixture-reader',scopes:['read']}),other=seed({tenantId:'other-tenant',subject:'other-reviewer'});await db.exec('SET ROLE tendermatch_result_writer');
    const store=createStage8Store({connect:async()=>c,pins:[pin,{...pin,tenantId:'other-tenant'}],cursors:createCursorCodec(randomBytes(32)),connectionLimit:1});web=await httpFixture(store,[s,readOnly,other]);
    const call=async(route,{token=s.token,method='GET',input,headers={},version=binding}={})=>{const url=web.origin+API_PREFIX+route+(route.includes('?')?'&':'?')+'binding='+version,response=await fetch(url,{method,headers:{...(token?{Authorization:'Bearer '+token}:{}),...(input?{'Content-Type':'application/json'}:{}),...headers},...(input?{body:JSON.stringify(input)}:{})});return {status:response.status,headers:response.headers,body:await response.json()};};
    let reviewedRequest;
    await t.test('authentication, explicit pin, role and tenant checks occur before data disclosure',async()=>{
      const before=metrics.queries;assert.equal((await call('/health',{token:null})).status,401);assert.equal(metrics.queries,before);assert.equal((await call('/health',{token:credential()})).status,401);assert.equal((await call('/health',{version:hash('stale')})).status,409);const wrong=await call('/health',{token:other.token,version:bindPin({...pin,tenantId:'other-tenant'}).bindingId});assert.equal(wrong.status,503);assert.equal(wrong.body.error.code,'PINNED_PIPELINE_INCOMPLETE');const ok=await call('/health');assert.equal(ok.status,200);assert.equal(ok.body.context.population.universe,28);assert.equal(ok.body.context.capabilities.executionAuthority,false);assert.equal(ok.headers.get('cache-control'),'no-store');
    });
    await t.test('ranked supplier/tender pages and selected detail preserve exact Formula and missing/zero semantics',async()=>{
      for(const [direction,focus] of [['suppliers',id(1)],['tenders',id(20)]]){const all=[];let cursor=null;do{const page=await call('/'+direction+'/'+focus+'/results?limit=1'+(cursor?'&cursor='+encodeURIComponent(cursor):''));assert.equal(page.status,200);all.push(...page.body.results);cursor=page.body.nextCursor;}while(cursor);assert.equal(new Set(all.map(p=>p.supplierId+':'+p.tenderId)).size,all.length);assert.ok(all.length);for(let i=1;i<all.length;i++)assert.ok(all[i-1].retrieval.units>=all[i].retrieval.units);const detail=await call('/pairs/'+all[0].supplierId+'/'+all[0].tenderId);assert.equal(detail.status,200);assert.deepEqual(detail.body.pair.formula,all[0].formula);assert.deepEqual(detail.body.pair.retrieval,all[0].retrieval);assert.deepEqual(detail.body.pair.shortlist,all[0].shortlist);assert.equal(detail.body.pair.formula.denominator,100);assert.ok(detail.body.pair.criteria.some(x=>x.state==='MISSING'&&x.fit===null&&x.points===0));assert.equal(detail.body.pair.humanDisposition.value,null);}
      const zero=await call('/pairs/'+id(2)+'/'+id(20));assert.equal(zero.status,200);assert.equal(zero.body.pair.formula.pairScore,0);assert.equal(zero.body.pair.retrieval.units,0);assert.equal(zero.body.pair.formula.assessedFitState,'NO_ASSESSED_CRITERIA');
      const outside=await call('/pairs/'+id(1)+'/'+id(22));assert.equal(outside.status,200);assert.equal(outside.body.pair.eligibility.state,'OUTSIDE_FORMULA_V1_1_SCOPE');assert.equal(outside.body.pair.formula.pairScore,null);assert.equal(outside.body.pair.retrieval.units,null);
      const scope=await call('/pairs/'+id(1)+'/'+id(23));assert.equal(scope.body.pair.eligibility.state,'SCOPE_NOT_DEMONSTRATED');assert.equal(scope.body.pair.formula.pairScore,null);
    });
    await t.test('bounded routes reject injection, excessive pages, stale/forged cursors and full-matrix requests',async()=>{
      for(const route of ['/suppliers/'+id(1)+'/results?limit=101','/suppliers/'+id(1)+'/results?limit=1&limit=2','/suppliers/'+id(1)+'/results?tenantId=other','/suppliers/'+encodeURIComponent("1' OR true--")+'/results'])assert.equal((await call(route)).status,400);
      assert.equal((await call('/matrix')).status,404);const page=await call('/suppliers/'+id(1)+'/results?limit=1');assert.ok(page.body.nextCursor);assert.equal((await call('/suppliers/'+id(2)+'/results?cursor='+encodeURIComponent(page.body.nextCursor))).status,400);assert.equal((await call('/suppliers/'+id(1)+'/results?cursor=forged')).status,400);
    });
    await t.test('CSRF, attribution, audit trigger and idempotency guard durable intents without jobs',async()=>{
      const p=fixture.loaded.rows.find(p=>p.tier===1),input={supplierId:p.supplierId,tenderId:p.tenderId,kind:'USER_REVIEW',justification:'Explicit synthetic selected-pair review'},headers={Origin:'http://127.0.0.1:43123','X-CSRF-Token':s.csrfToken,'Idempotency-Key':'review-key-001'};
      assert.equal((await call('/intents',{method:'POST',input})).status,403);assert.equal((await call('/intents',{method:'POST',input,headers:{...headers,Origin:'https://untrusted.invalid'}})).status,403);assert.equal((await call('/intents',{method:'POST',input,headers:{...headers,'X-CSRF-Token':credential()}})).status,403);assert.equal((await call('/intents',{method:'POST',input:{...input,actor:'spoof'},headers})).status,400);assert.equal((await call('/intents',{token:readOnly.token,method:'POST',input,headers:{...headers,'X-CSRF-Token':readOnly.csrfToken}})).status,403);
      const first=await call('/intents',{method:'POST',input,headers});assert.equal(first.status,200);assert.equal(first.body.intent.actor,s.subject);assert.equal(first.body.intent.queuedExecutions,0);reviewedRequest=first.body.intent.requestId;const again=await call('/intents',{method:'POST',input,headers});assert.equal(again.body.intent.requestId,reviewedRequest);assert.equal(again.body.intent.reused,true);assert.equal((await call('/intents',{method:'POST',input:{...input,justification:'Different body for same key'},headers})).status,409);
      const report=await call('/intents',{method:'POST',input:{...input,kind:'REPORT_REQUEST'},headers:{...headers,'Idempotency-Key':'report-key-001'}});assert.equal(report.status,200);assert.equal(report.body.intent.kind,'REPORT_REQUEST');assert.equal(report.body.intent.queuedExecutions,0);
      const audit=fixture.loaded.rows.find(p=>p.tier===2),auditInput={...input,supplierId:audit.supplierId,tenderId:audit.tenderId};assert.equal((await call('/intents',{method:'POST',input:auditInput,headers:{...headers,'Idempotency-Key':'audit-key-001'}})).status,403);assert.equal((await call('/intents',{method:'POST',input:{...auditInput,kind:'AUDIT_REQUEST'},headers:{...headers,'Idempotency-Key':'audit-key-001'}})).status,200);
      assert.equal((await call('/intents',{method:'POST',input:{...input,supplierId:id(1),tenderId:id(22)},headers:{...headers,'Idempotency-Key':'outside-key-001'}})).status,409);assert.equal((await c.query('SELECT count(*)::int n FROM tendermatch_retrieval.escalation_job')).rows[0].n,0);assert.equal((await c.query('SELECT count(*)::int n FROM tendermatch_retrieval.escalation_authorization')).rows[0].n,0);
    });
    await t.test('future explicit job/artifact reads require scope and exact pinned input; service never creates them',async()=>{
      const empty=await call('/intents/'+reviewedRequest);assert.equal(empty.status,200);assert.deepEqual(empty.body.jobs,[]);assert.equal((await call('/intents/'+reviewedRequest,{token:readOnly.token})).status,403);assert.equal((await call('/jobs/'+hash('absent'))).status,404);
      await db.exec('RESET ROLE');await c.query(`INSERT INTO tendermatch_retrieval.escalation_authorization(tenant_id,authorization_id,plan_id,actor,rationale,provider_version,model_version,prompt_version,schema_version,max_jobs,max_calls,max_concurrency,max_output_tokens,expires_at) VALUES($1,'stage8-fixture-grant',$2,'fixture-owner','Synthetic future status only','fixture-provider','fixture-model',$3,$4,1,1,1,4096,clock_timestamp()+interval '1 hour')`,[TENANT,pin.planId,PROMPT_VERSION,TORS_SCHEMA]);await db.exec('SET ROLE tendermatch_result_writer');await c.query("SELECT set_config('tendermatch.tenant_id',$1,false)",[TENANT]);
      const request=(await c.query(`SELECT ${requestColumns} FROM tendermatch_retrieval.escalation_request WHERE request_id=$1`,[reviewedRequest])).rows[0],output={schemaVersion:TORS_SCHEMA,authority:'ADVISORY_ONLY',summary:'Synthetic future artifact boundary',sections:SECTIONS.map(code=>({code,findings:[{statement:'No supported fixture assessment',state:'MISSING',evidenceIds:[]}]})),limitations:['Synthetic local provider stub, not an AI result'],humanReviewRequired:true},provider={version:'fixture-provider',modelVersion:'fixture-model',promptVersion:PROMPT_VERSION,assess:async()=>({output})};
      const job=await enqueueAuthorized(c,request,'stage8-fixture-grant',provider),lease=await claimJob(c,'stage8-fixture-grant','fixture-worker'),complete=await executeLeasedJob(c,lease,provider);const status=await call('/jobs/'+job.job_id);assert.equal(status.status,200);assert.equal(status.body.job.state,'SUCCEEDED');const artifact=await call('/artifacts/'+complete.artifact_id+'?jobId='+job.job_id);assert.equal(artifact.status,200);assert.equal(artifact.body.artifact.output.authority,'ADVISORY_ONLY');assert.equal(artifact.body.job.input_tokens,null);assert.equal((await call('/artifacts/'+complete.artifact_id+'?jobId='+hash('wrong'))).status,404);
    });
    await t.test('missing marker and forged completion binding fail closed without static fallback',async()=>{
      await db.exec('RESET ROLE');await c.query('DELETE FROM tendermatch_retrieval.schema_migration WHERE version=$1',['20260907-escalation-stage7-v1']);await db.exec('SET ROLE tendermatch_result_writer');const missing=await call('/health');assert.equal(missing.status,503);assert.equal(missing.body.error.code,'REQUIRED_MIGRATION_UNAVAILABLE');await db.exec('RESET ROLE');await c.query('INSERT INTO tendermatch_retrieval.schema_migration(version) VALUES($1)',['20260907-escalation-stage7-v1']);await db.exec('SET ROLE tendermatch_result_writer');
      const bad={...pin,formulaOutcomeHash:hash('incorrect')},wrongStore=createStage8Store({connect:async()=>c,pins:[bad],cursors:createCursorCodec(randomBytes(32)),connectionLimit:1});await assert.rejects(()=>wrongStore.health({tenantId:TENANT},bindPin(bad).bindingId),e=>e instanceof ServiceError&&e.code==='PINNED_PIPELINE_IDENTITY_MISMATCH');
      const absent={...pin,planId:hash('absent-plan')},absentStore=createStage8Store({connect:async()=>c,pins:[absent],cursors:createCursorCodec(randomBytes(32)),connectionLimit:1});await assert.rejects(()=>absentStore.health({tenantId:TENANT},bindPin(absent).bindingId),e=>e.code==='PINNED_PIPELINE_INCOMPLETE');
      const incomplete={...pin,automaticRequests:pin.automaticRequests+1},incompleteStore=createStage8Store({connect:async()=>c,pins:[incomplete],cursors:createCursorCodec(randomBytes(32)),connectionLimit:1});await assert.rejects(()=>incompleteStore.health({tenantId:TENANT},bindPin(incomplete).bindingId),e=>e.code==='PINNED_PIPELINE_IDENTITY_MISMATCH');
      await db.exec('RESET ROLE');await assert.rejects(()=>store.health({tenantId:TENANT},binding),e=>e.code==='UNSAFE_BACKEND_ROLE');await db.exec('SET ROLE tendermatch_result_writer');
    });
  }finally{await web?.close();await db.close();}
});
test('Stage 8 evidence is bound to final service code and local-only/no-call contract',{skip:!process.env.TENDERMATCH_STAGE8_EVIDENCE},async()=>{
  const evidence=JSON.parse(await readFile(new URL('../docs/evidence/tendermatch-stage8-benchmark.json',import.meta.url),'utf8'));assert.deepEqual(evidence.code,await stage8CodeIdentity());assert.equal(evidence.evidenceClass,'SYNTHETIC_LOCAL_PGLITE_HTTP_NOT_NEON');assert.equal(evidence.modelCalls,0);assert.equal(evidence.neonConnections,0);assert.equal(evidence.sourceConnections,0);assert.equal(evidence.localRows.escalation_authorization,0);assert.equal(evidence.localRows.escalation_job,0);assert.equal(evidence.localRows.escalation_artifact,0);assert.equal(evidence.priorStateUnchanged,true);assert.equal(evidence.intent.replay.reused,true);assert.ok(evidence.http.maximumResponseBytes<524288);assert.equal(evidence.traversal.supplier.count,120);assert.equal(evidence.traversal.tender.count,12);
  assert.equal(evidence.intent.omittedCandidateWasRequestable,true);assert.equal(evidence.intent.onDemandInserted,100);assert.equal(evidence.intent.capResponse,'REQUEST_BUDGET_EXHAUSTED');assert.equal(evidence.intent.reusedAtCap,true);
  const nodes=x=>!x||typeof x!=='object'?[]:[...(x['Node Type']?[x]:[]),...Object.values(x).flatMap(nodes)];for(const [direction,plans] of Object.entries(evidence.queries))for(const plan of Object.values(plans)){assert.ok(nodes(plan).some(n=>n['Index Name']==='ranking_pair_'+direction));assert.ok(!nodes(plan).some(n=>n['Relation Name']==='formula_pair'&&n['Node Type']==='Seq Scan'));}
});
