import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {pathToFileURL} from 'node:url';
import path from 'node:path';
import {POLICIES,nominate,simulatePolicy,validateSelectionInput,keyOf} from '../packages/tendermatch/src/shortlist-stage6.ts';
import {main} from '../scripts/tendermatch-stage6.mjs';
import {main as auditMain} from '../scripts/tendermatch-validate-stage6.mjs';
import {TENANT,sha} from '../scripts/lib/tendermatch-input-manifest.mjs';
import {createShortlistRun,prepareShortlistRun,executeShortlist,completeShortlistRun,queryShortlist,selectedShortlistDetail,insertShortlistBatch,loadContextCache,stage6CodeIdentity} from '../scripts/lib/tendermatch-stage6.mjs';
import {initializeStage6Fixture,sealSyntheticRanking,supplier,tender} from './fixtures/tendermatch-stage6.mjs';
const id=n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
const pair=(s,t,units=0,extra={})=>({supplierId:id(s),tenderId:id(t),units,score:0,coverage:0,confidence:0,mask:2,limitation:0,...extra});
test('Stage 6 defaults disconnected and rejects unauthorized comparison',async()=>{assert.equal((await main([])).connects,false);assert.equal((await auditMain([])).connects,false);await assert.rejects(()=>main(['compare']),/approval/);await assert.rejects(()=>auditMain(['verify']),/approval/);await assert.rejects(()=>main(['ddl']),/Unknown/);});
test('shortlist separate ordered dimensions, explicit zero audit, deterministic ties and review budgets',()=>{
 const rows=[pair(1,20,100,{score:20,coverage:40,confidence:30}),pair(1,21,100,{score:20,coverage:40,confidence:30}),pair(1,22,100,{score:10,coverage:100,confidence:100}),pair(1,23,0,{score:100,coverage:100,confidence:100}),pair(1,24,0)],policy={name:'fixture',supplierReview:2,tenderReview:1,supplierAudit:1,tenderAudit:1};
 const before=JSON.stringify(rows),result=nominate(rows,'supplier',policy);assert.equal(result.length,3);assert.equal(result[0].tenderId,id(20));assert.equal(result[1].tenderId,id(21));assert.equal(result[0].tieSize,2);assert.equal(result[2].tier,'AUDIT_ONLY');assert.match(result[2].reason,/ZERO_RETRIEVAL_AUDIT/);assert.equal(JSON.stringify(rows),before);assert.deepEqual(nominate([...rows].reverse(),'supplier',policy),result);
 for(const p of POLICIES){const a=simulatePolicy(rows,p),b=simulatePolicy([...rows].reverse(),p);assert.equal(a.summary.outcomeHash,b.summary.outcomeHash);assert.equal(a.summary.actualAiTorsReady,0);assert.equal(new Set(a.values.map(v=>keyOf(v.input))).size,a.values.length);}
});
test('shortlist missing/zero never becomes incompatibility, nonmembership never changes frozen evidence',()=>{
 const rows=[pair(1,20),pair(2,20)],a=simulatePolicy(rows,POLICIES[0]);assert.equal(a.summary.selected,0);assert.deepEqual(rows,[pair(1,20),pair(2,20)]);assert.throws(()=>validateSelectionInput(pair(1,20,-1)),/Invalid/);assert.throws(()=>simulatePolicy([rows[0],rows[0]],POLICIES[0]),/Duplicate/);
});
test('focus caches bind all consumed identity/dimensions, reject corruption, and ignore unrelated global run labels',()=>{
 const members=[['supplier',1],['supplier',2],['tender',20],['tender',21]].map(([kind,n])=>({kind,id:id(n),profile_key:sha(['profile',n]),input_key:sha(['input',n])})),loaded={members,pairs:[pair(1,20,100),pair(2,21)],rankingRunId:sha('ranking1'),rankingIdentity:{methodHash:sha('method'),formulaPolicy:sha('formula')},rankingOutcomeHash:sha('ranking outcome'),inputHash:sha('projection')},code={hash:sha('code')},first=createShortlistRun(loaded,code);
 const same=createShortlistRun({...loaded,rankingRunId:sha('equivalent-history-run')},code,{contextCache:first.contexts});assert.deepEqual(same.extraction,{extracted:0,reused:4});assert.deepEqual(same.pairs,first.pairs);assert.notEqual(same.runId,first.runId);
 const changed=createShortlistRun({...loaded,members:members.map((m,i)=>i===0?{...m,profile_key:sha('changed profile')}:m)},code,{contextCache:first.contexts});assert.deepEqual(changed.extraction,{extracted:2,reused:2});assert.equal(changed.pairs.filter(p=>first.pairs.some(old=>old.key===p.key)).length,1);
 assert.equal(createShortlistRun({...loaded,rankingIdentity:{...loaded.rankingIdentity,methodHash:sha('new method')}},code,{contextCache:first.contexts}).extraction.extracted,4);
 const cache=structuredClone(first.contexts);cache.find(c=>c.nominations.length).nominations[0].rank+=1;assert.throws(()=>createShortlistRun(loaded,code,{contextCache:cache}),/Corrupt/);
});
test('Stage 6 preserves every approved Formula/ranking implementation and evidence file',async()=>{
 const root=new URL('../',import.meta.url);for(const file of ['packages/tendermatch/src/formula-stage4-adapter.ts','packages/tendermatch/src/retrieval-stage5.ts','scripts/lib/tendermatch-stage5.mjs','scripts/tendermatch-stage5.mjs','db/tendermatch-dev/080-ranking-up.sql','docs/evidence/tendermatch-stage5-execute.json','docs/evidence/tendermatch-stage5-validation.json'])assert.equal((await readFile(new URL(file,root),'utf8')).replaceAll('\r\n','\n'),execFileSync('git',['show',`263389a58674484cbdae4539e8edeb95c9f2f215:${file}`],{maxBuffer:12*1024*1024}).toString().replaceAll('\r\n','\n'));
});
test('recorded real comparison and synthetic SQL benchmark bind the final Stage 6 implementation',{skip:!process.env.TENDERMATCH_STAGE6_EVIDENCE},async()=>{
 const root=new URL('../',import.meta.url),p=JSON.parse(await readFile(new URL('docs/evidence/tendermatch-stage6-comparison.json',root),'utf8')),b=JSON.parse(await readFile(new URL('docs/evidence/tendermatch-stage6-benchmark.json',root),'utf8')),code=await stage6CodeIdentity();assert.deepEqual(p.code,code);assert.deepEqual(b.code,code);assert.equal(p.runId,sha(p.identity));assert.deepEqual(p.protectedBefore,p.protectedAfter);assert.equal(p.identity.candidates,707660);assert.equal(p.identity.selected,28034);assert.equal(p.identity.reviewCandidates,18531);assert.equal(p.identity.auditOnly,9503);assert.equal(p.identity.actualAiTorsReady,0);assert.deepEqual(p.reuse,{extracted:0,reused:17450});assert.equal(p.committedWrites,0);assert.equal(p.sourceConnections,0);assert.equal(p.modelCalls,0);
 for(const policy of p.results)assert.equal(policy.replayIdentical,true);assert.equal(b.identity.candidates,4000);assert.equal(b.identity.selected,1450);assert.equal(b.readback.outcomeHash,b.execution.outcomeHash);assert.equal(b.replay.inserted,0);assert.equal(b.replay.reused,1450);assert.equal(b.omittedCandidate.onDemandEscalationEligible,true);assert.equal(b.omittedCandidate.aiAuthorized,false);assert.match(JSON.stringify(b.queries.supplierPlan),/shortlist_pair_supplier/);assert.match(JSON.stringify(b.queries.tenderPlan),/shortlist_pair_tender/);
});
test('recorded full Stage 6 Neon persistence and independent audit bind the final implementation',{skip:!process.env.TENDERMATCH_STAGE6_EXECUTION_EVIDENCE},async()=>{
 const root=new URL('../',import.meta.url),p=JSON.parse(await readFile(new URL('docs/evidence/tendermatch-stage6-execute.json',root),'utf8')),v=JSON.parse(await readFile(new URL('docs/evidence/tendermatch-stage6-validation.json',root),'utf8')),code=await stage6CodeIdentity();
 assert.deepEqual(p.code,code);assert.deepEqual(v.code,code);assert.equal(p.runId,sha(p.identity));assert.equal(v.runId,p.runId);assert.equal(v.validatorHash,sha((await readFile(new URL('scripts/tendermatch-validate-stage6.mjs',root),'utf8')).replaceAll('\r\n','\n')));
 for(const r of [p.execution,p.readback,p.rerun,v.fullReadback]){assert.equal(r.count,28034);assert.equal(r.outcomeHash,p.identity.outcomeHash);}assert.equal(p.execution.inserted,28034);assert.equal(p.rerun.inserted,0);assert.equal(p.rerun.reused,28034);assert.equal(v.fullReadback.inserted,0);
 assert.deepEqual(p.preparation,{insertedContexts:17450,insertedMembers:17450,insertedRun:1});assert.deepEqual(v.contextReuse,{extracted:0,reused:17450});assert.equal(v.freshReversedReplay.identical,true);assert.equal(v.sql.total,28034);assert.equal(v.sql.unique_pairs,28034);assert.equal(v.sql.union_pairs,28034);assert.equal(v.sql.review,18531);assert.equal(v.sql.audit,9503);
 for(const k of ['missing_prior','invalid_tier','invalid_reasons','invalid_nomination'])assert.equal(v.sql[k],0);assert.equal(v.independentSqlNominations.contexts,17450);assert.equal(v.independentSqlNominations.candidates,707660);assert.equal(v.independentSqlNominations.mismatches,0);assert.equal(v.independentSqlNominations.nominations,v.sql.nominations);
 assert.deepEqual(p.protectedBefore,p.protectedAfter);assert.deepEqual(v.protectedBefore,v.protectedAfter);assert.deepEqual(v.protectedBefore,p.protectedBefore);assert.equal(v.committedWrites,0);assert.equal(v.sourceConnections,0);assert.equal(v.modelCalls,0);assert.equal(p.sourceConnections,0);assert.equal(p.modelCalls,0);assert.equal(p.identity.actualAiTorsReady,0);
 assert.deepEqual(v.rows,{shortlist_context:17450,shortlist_run:1,shortlist_member:17450,shortlist_pair:28034,shortlist_completion:1});assert.equal(v.fullTraversals.supplier.rows,2361);assert.equal(v.fullTraversals.tender.rows,49);for(const direction of ['supplier','tender'])assert.match(JSON.stringify(v.plans[direction]),new RegExp(`shortlist_pair_${direction}`));assert.equal(v.omittedCandidate.onDemandEscalationEligible,true);assert.equal(v.omittedCandidate.aiAuthorized,false);assert.ok(v.privileges.every(p=>p.relrowsecurity&&!p.extra));assert.equal(p.security.committedProbeRows,0);assert.equal(v.migrationBindings.exactBodies,true);assert.equal(v.migrationBindings.functions.length,7);
});
test('isolated shortlist SQL policy, cache reuse, dependencies, security and paging',{skip:!process.env.TENDERMATCH_PGLITE_ROOT},async(t)=>{
 const {PGlite}=await import(pathToFileURL(path.join(process.env.TENDERMATCH_PGLITE_ROOT,'@electric-sql/pglite/dist/index.js')).href),db=new PGlite(),c={query:async(q,v)=>{const r=await db.query(q,v);return {...r,rowCount:r.affectedRows??r.rows.length};}};
 try{await assert.rejects(async()=>db.exec(await readFile(new URL('../db/tendermatch-dev/090-shortlist-up.sql',import.meta.url),'utf8')),/development target mismatch/);await initializeStage6Fixture(db);const seeds=[supplier(1),supplier(2,[]),supplier(3,undefined,'WORKS'),tender(20),tender(21,'GOODS','medical'),tender(22,'SERVICES'),tender(23,'WORKS','construction')],loaded=await sealSyntheticRanking(c,seeds,{register:true}),code={hash:sha('Stage6 synthetic code')},run=createShortlistRun(loaded,code);
  await db.exec('SET ROLE tendermatch_result_writer');await c.query("SELECT set_config('tendermatch.tenant_id',$1,false)",[TENANT]);let first;
  await t.test('SQL independently confirms exact nominations; full readback and unchanged reuse',async()=>{assert.equal(run.identity.candidates,5);assert.equal(run.identity.contexts,7);await prepareShortlistRun(c,run);first=await executeShortlist(c,run);assert.ok(first.count>0);assert.equal(first.inserted,first.count);await completeShortlistRun(c,run);const readback=await executeShortlist(c,run,{readOnly:true});assert.equal(readback.outcomeHash,first.outcomeHash);const reused=createShortlistRun(loaded,code,{contextCache:await loadContextCache(c)});assert.deepEqual(reused.extraction,{extracted:0,reused:7});assert.equal(reused.runId,run.runId);assert.deepEqual(await prepareShortlistRun(c,reused),{insertedContexts:0,insertedMembers:0,insertedRun:0});const replay=await executeShortlist(c,reused);assert.equal(replay.inserted,0);assert.equal(replay.reused,first.count);});
  await t.test('supplier/tender bounded pages, detail parity, explicit on-demand unlisted candidate',async()=>{
   for(const [direction,focusId] of [['supplier',id(1)],['tender',id(20)]]){let cursor=null,all=[];do{const p=await queryShortlist(c,run,{direction,focusId,limit:1,cursor});all.push(...p.results);cursor=p.nextCursor;}while(cursor);assert.equal(new Set(all.map(keyOf)).size,all.length);for(const p of all){const d=await selectedShortlistDetail(c,run,p);assert.deepEqual(d.formula,p.formula);assert.deepEqual(d.shortlist,p.shortlist);assert.equal(d.aiAuthorized,false);}}
   const empty=await queryShortlist(c,run,{direction:'tender',focusId:id(22)});assert.equal(empty.results.length,0);assert.equal((await selectedShortlistDetail(c,run,{supplierId:id(1),tenderId:id(22)})).onDemandEscalationEligible,false);
   const page=await queryShortlist(c,run,{direction:'supplier',focusId:id(1),limit:1});await assert.rejects(()=>queryShortlist(c,run,{direction:'supplier',focusId:id(2),cursor:page.nextCursor}),/cursor/);await assert.rejects(()=>queryShortlist(c,run,{direction:'supplier',focusId:id(1),limit:101}),/bounded/);
  });
  await t.test('changed supplier/tender invalidates direct focus dependency closure, not disjoint scope history',async()=>{
   const cache=await loadContextCache(c);for(const index of [0,3]){const nextSeeds=seeds.map((p,i)=>i===index?(index===0?supplier(1,[['product_families','medical equipment']]):tender(20,'GOODS','medical')):p);const nextLoaded=await sealSyntheticRanking(c,nextSeeds),next=createShortlistRun(nextLoaded,code,{contextCache:cache});assert.equal(next.extraction.extracted,3);assert.equal(next.extraction.reused,4);await prepareShortlistRun(c,next);
    const stale=run.contextById.get(index===0?'tender:'+id(20):'supplier:'+id(1)),badIdentity={...next.identity,contextHash:sha(['stale-context-probe',index])},bad={...next,runId:sha(badIdentity),identity:badIdentity,contexts:next.contexts.map(c=>c.kind===stale.kind&&c.id===stale.id?stale:c)};await assert.rejects(()=>prepareShortlistRun(c,bad),/Stale shortlist context dependency/);
    const wrote=await executeShortlist(c,next);assert.ok(wrote.reused>=1);await completeShortlistRun(c,next);const oldWorks=run.contextById.get('supplier:'+id(3));assert.equal(next.contextById.get('supplier:'+id(3)).key,oldWorks.key);}
   assert.equal((await executeShortlist(c,run,{readOnly:true})).outcomeHash,first.outcomeHash);
  });
  await t.test('DB rejects fabricated nominees/ranks, wrong audit tier and incomplete completion',async()=>{
   await assert.rejects(()=>insertShortlistBatch(c,run,[{...run.pairs[0],selection:{...run.pairs[0].selection,reasonMask:99}}]),/reasons/);
   await assert.rejects(()=>insertShortlistBatch(c,run,[{...run.pairs[0],tier:run.pairs[0].tier===1?2:1}]),/audit tier/);
   const context=run.contexts.find(x=>x.nominations.length),fake={...context,nominations:[]};await assert.rejects(()=>c.query(`INSERT INTO tendermatch_retrieval.shortlist_context(tenant_id,context_key,policy_hash,source_run_id,kind,entity_id,profile_key,input_hash,context) VALUES($1,decode($2,'hex'),decode($3,'hex'),$4,$5,$6,decode($7,'hex'),decode($8,'hex'),$9)`,[TENANT,context.key,context.policyHash,loaded.rankingRunId,context.kind,context.id,context.profileKey,context.inputHash,JSON.stringify(fake)]),/exact nomination/);
   const next=createShortlistRun(loaded,{hash:sha('different shortlist code')});await prepareShortlistRun(c,next);await assert.rejects(()=>completeShortlistRun(c,next),/Incomplete/);
  });
  await t.test('writer cannot mutate sealed history, append membership, execute DDL or cross tenant boundaries',async()=>{
   for(const sql of ['UPDATE tendermatch_retrieval.shortlist_pair SET tier=2','DELETE FROM tendermatch_retrieval.shortlist_context','TRUNCATE tendermatch_retrieval.shortlist_pair','CREATE TABLE tendermatch_retrieval.forbidden(id int)'])await assert.rejects(()=>c.query(sql),/permission denied/);
   await assert.rejects(()=>c.query('INSERT INTO tendermatch_retrieval.shortlist_member SELECT * FROM tendermatch_retrieval.shortlist_member LIMIT 1'),/no rows|sealed/);
   await c.query("SELECT set_config('tendermatch.tenant_id','other',false)");assert.equal((await c.query('SELECT count(*)::int n FROM tendermatch_retrieval.shortlist_pair')).rows[0].n,0);await assert.rejects(()=>prepareShortlistRun(c,run),/row-level|no rows/);await c.query("SELECT set_config('tendermatch.tenant_id',$1,false)",[TENANT]);
  });
 }finally{await db.close();}
});
