export type TenderGlossaryCategory = "process" | "actors" | "agents" | "control" | "evidence" | "visual";

export type TenderGlossaryTerm = {
  term: string;
  translation: string;
  explanation: string;
  simpleExplanation: string;
  example: string;
  notToConfuseWith: string;
  category: TenderGlossaryCategory;
  aliases?: string[];
};

export const tenderGlossaryCategoryLabels: Record<TenderGlossaryCategory, string> = {
  process: "Процесс",
  actors: "Участники",
  agents: "Агенты",
  control: "Управление",
  evidence: "Данные и evidence",
  visual: "Визуальные модели",
};

export const tenderGlossaryTerms: TenderGlossaryTerm[] = [
  {
    term: "Case",
    translation: "Кейс / экземпляр тендерного процесса",
    explanation: "Конкретная работа TenderLab по одной тендерной возможности и компании, объединяющая участников, события, действия, состояния, доказательства, решения и итог.",
    simpleExplanation: "Отдельное досье одного тендера: что произошло, кто участвовал и чем всё закончилось.",
    example: "Case GE-MES-2026-017 связывает закупку школьной мебели, компанию, 20 событий и итог исполнения контракта.",
    notToConfuseWith: "Workflow задаёт повторяемую модель, Case является одним её выполнением, а Event — отдельным фактом внутри Case.",
    category: "process",
    aliases: ["кейс", "tender case"],
  },
  {
    term: "Workflow",
    translation: "Рабочий процесс",
    explanation: "Повторяемая модель Activity, условий, Input, Output, Dependency и Decision Gate с последовательными, параллельными и условными ветвями.",
    simpleExplanation: "Карта движения работы от начала до результата, а не обязательно прямая цепочка шагов.",
    example: "Workflow подготовки заявки разветвляет проверку компании и документов, затем объединяет результаты перед Bid / No-Bid.",
    notToConfuseWith: "Case — конкретное выполнение, а Workflow — правила, по которым могут выполняться многие Case.",
    category: "process",
    aliases: ["рабочий процесс", "процесс"],
  },
  {
    term: "Event",
    translation: "Событие процесса",
    explanation: "Зафиксированное изменение или происшествие внутри Case, имеющее время, источник и последствия для дальнейшего процесса.",
    simpleExplanation: "Значимый факт: тендер опубликован, получен clarification или объявлен award.",
    example: "Публикация notice заказчиком является Event, запускающим сбор и классификацию документов.",
    notToConfuseWith: "Event фиксирует факт, Activity описывает выполняемую работу, а Trigger запускает эту работу.",
    category: "process",
    aliases: ["событие"],
  },
  {
    term: "Activity",
    translation: "Действие / работа в процессе",
    explanation: "Ограниченная единица работы внутри Case с ответственным Actor, исполнителями, входами, выходами и состоянием выполнения.",
    simpleExplanation: "Конкретная работа, например разобрать документы или проверить квалификацию компании.",
    example: "Извлечение 164 требований — Activity, которую совместно выполняют несколько document agents.",
    notToConfuseWith: "Event сообщает, что произошло; Activity показывает, какая работа выполняется; Workflow связывает множество Activity.",
    category: "process",
    aliases: ["действие", "операция"],
  },
  {
    term: "Actor",
    translation: "Участник процесса",
    explanation: "Человек, организация, роль или внешняя система, которая инициирует, выполняет, утверждает либо получает результат Activity.",
    simpleExplanation: "Тот, кто участвует: заказчик, компания, консультант, TenderLab, банк или портал.",
    example: "Коммерческий директор компании — Actor, разрешающий углублённую оценку тендера.",
    notToConfuseWith: "Actor определяет ответственность участника, а AI Agent обозначает системную способность, выполняющую работу.",
    category: "actors",
    aliases: ["участник", "роль"],
  },
  {
    term: "AI Agent",
    translation: "ИИ-агент / системная роль",
    explanation: "Каноническая способность TenderLab, которая получает Input, выполняет ограниченную функцию и производит конкретный Output внутри оркестрируемого Workflow.",
    simpleExplanation: "Цифровой специалист с определённой ответственностью и ожидаемым результатом.",
    example: "Requirement Parser Agent превращает tender package в структурированный реестр требований.",
    notToConfuseWith: "Actor отвечает за участие или полномочия, а AI Agent выполняет системную функцию; один Actor может использовать несколько AI Agent.",
    category: "agents",
    aliases: ["Agent", "агент", "ИИ-агент"],
  },
  {
    term: "Main Agent",
    translation: "Основной агент",
    explanation: "AI Agent, который обычно ведёт ключевую часть тендерного Workflow и формирует результат, необходимый для следующей важной точки процесса.",
    simpleExplanation: "Агент, без которого основной маршрут тендера обычно не складывается.",
    example: "Tender Readiness Score Agent — Main Agent, потому что его карта готовности влияет на дальнейший отбор возможностей.",
    notToConfuseWith: "Main Agent обозначает центральность в Workflow, а не административный уровень или постоянное выполнение в каждом Case.",
    category: "agents",
    aliases: ["Main", "основной агент"],
  },
  {
    term: "Specialized Agent",
    translation: "Специализированный агент",
    explanation: "AI Agent с узкой профессиональной функцией, который поддерживает один или несколько Main Agent и активируется при наличии подходящих данных или задачи.",
    simpleExplanation: "Узкий специалист, которого подключают к конкретной части работы.",
    example: "Evidence & Provenance Agent поддерживает scoring, compliance и human approval проверяемыми источниками.",
    notToConfuseWith: "Specialized Agent не является менее важным; его отличие от Main Agent — более узкая ответственность.",
    category: "agents",
    aliases: ["Specialized", "специализированный агент"],
  },
  {
    term: "Optional Agent",
    translation: "Опциональный / ситуационный агент",
    explanation: "AI Agent, который включается только при выполнении конкретного условия Case и корректно пропускается, когда его функция не требуется.",
    simpleExplanation: "Специалист, нужный только в определённых тендерах.",
    example: "JV & Consortium Optimization Agent не запускается, если компания участвует самостоятельно.",
    notToConfuseWith: "Optional означает условную применимость, а не низкую ценность: редкий агент может быть критичным при срабатывании условия.",
    category: "agents",
    aliases: ["Optional", "ситуационный агент"],
  },
  {
    term: "Shared Agent",
    translation: "Совместно используемый агент",
    explanation: "AI Agent, чьи функции и Output используются несколькими сторонами платформы или workflows без дублирования канонической роли.",
    simpleExplanation: "Один цифровой специалист помогает и консультанту, и компании, но остаётся одним агентом.",
    example: "Company-to-Tender Match Score Agent обслуживает Command Center и Client Side одним расчётом соответствия.",
    notToConfuseWith: "Shared Agent описывает стороны использования, а Cross-Stage Agent — повторное участие в разных стадиях.",
    category: "agents",
    aliases: ["shared", "общий агент"],
  },
  {
    term: "Cross-Stage Agent",
    translation: "Агент сквозного участия",
    explanation: "AI Agent, который выполняет разные Activity в нескольких событиях или стадиях одного Case и не принадлежит навсегда одному шагу.",
    simpleExplanation: "Один агент возвращается в разных частях кейса, не превращаясь в несколько агентов.",
    example: "Evidence & Provenance Agent участвует в profile, matching, compliance и clarification.",
    notToConfuseWith: "Cross-Stage описывает участие во времени, Shared Agent — использование разными сторонами платформы.",
    category: "agents",
    aliases: ["сквозной агент"],
  },
  {
    term: "Agent Registry",
    translation: "Канонический реестр агентов",
    explanation: "Единый источник идентификаторов, названий, ролей, классов, outputs и постоянных характеристик всех AI Agent TenderLab.",
    simpleExplanation: "Главный каталог, где каждый агент определён один раз.",
    example: "Case Audit и Agent Catalog используют одни и те же 64 записи Agent Registry.",
    notToConfuseWith: "Agent Registry хранит постоянные определения, а Agent Run фиксирует конкретное выполнение агента в Case.",
    category: "agents",
    aliases: ["canonical agent registry", "реестр агентов"],
  },
  {
    term: "Agent Engagement",
    translation: "Участие агента в Case",
    explanation: "Контекстное решение о том, требуется ли AI Agent в конкретном Case: Required, Conditional либо Not involved, с объяснением условия и роли.",
    simpleExplanation: "Ответ на вопрос: нужен ли этот агент именно в данном тендере и почему.",
    example: "В Case 1 Local Service & Representation Agent Conditional, потому что он активируется требованием локального сервиса.",
    notToConfuseWith: "Agent Engagement относится к конкретному Case, а Agent Type является постоянной классификацией роли.",
    category: "agents",
    aliases: ["engagement", "вовлечение агента"],
  },
  {
    term: "Orchestration",
    translation: "Оркестрация",
    explanation: "Управление активацией, зависимостями, состояниями, повторами, ветвями, handoff и human approval между Actors, Activities и AI Agent.",
    simpleExplanation: "Диспетчеризация всей работы: кто, когда и на каком основании должен действовать.",
    example: "TenderLab Orchestrator запускает параллельную проверку компании и документов, затем ждёт оба Output.",
    notToConfuseWith: "Workflow описывает правила процесса, а Orchestration применяет эти правила к текущему Case.",
    category: "control",
    aliases: ["оркестрация", "orchestrator"],
  },
  {
    term: "Human-in-the-Loop",
    translation: "Обязательное участие человека",
    explanation: "Контрольная точка, где ответственному Actor передаются evidence и recommendation, а продолжение зависит от его явного решения.",
    simpleExplanation: "Система готовит материалы, но окончательное решение принимает человек.",
    example: "После Bid / No-Bid recommendation коммерческий директор утверждает участие и ценовые пороги.",
    notToConfuseWith: "Human-in-the-Loop требует решения человека, а Human Approval является конкретным зафиксированным результатом этой точки.",
    category: "actors",
    aliases: ["HITL", "human review", "человек в контуре"],
  },
  {
    term: "Human Approval",
    translation: "Человеческое согласование",
    explanation: "Зафиксированное решение уполномоченного Actor с условиями, ответственным лицом, временем и разрешённым следующим действием.",
    simpleExplanation: "Проверяемое «да», «нет» или «да, при таких условиях» от ответственного человека.",
    example: "Утверждение финальной цены открывает Document Assembly & Submission Agent доступ к подаче.",
    notToConfuseWith: "Decision Gate может быть автоматическим, а Human Approval всегда содержит явное решение человека.",
    category: "actors",
    aliases: ["approval", "согласование"],
  },
  {
    term: "Input",
    translation: "Входные данные процесса",
    explanation: "Данные, документы, решения или State, которые Activity должна получить до начала либо продолжения работы.",
    simpleExplanation: "Всё, что исполнитель должен получить перед работой.",
    example: "Для Match Score нужны проверенный профиль компании, требования тендера и evidence.",
    notToConfuseWith: "Input является содержанием для работы, Trigger даёт сигнал начать, а Dependency определяет предпосылку.",
    category: "evidence",
    aliases: ["вход", "входные данные"],
  },
  {
    term: "Output",
    translation: "Результат / выход процесса",
    explanation: "Конкретный проверяемый результат Activity или AI Agent: объект данных, документ, score, решение, State либо evidence package.",
    simpleExplanation: "То, что реально осталось после работы: score, shortlist, документ или решение.",
    example: "Output сопоставления — Match 88%, объяснение факторов и план закрытия двух gaps.",
    notToConfuseWith: "Output является результатом, Artifact — его сохраняемой формой, а Handoff передаёт его дальше.",
    category: "evidence",
    aliases: ["результат", "выход"],
  },
  {
    term: "Artifact",
    translation: "Артефакт / сохраняемый результат",
    explanation: "Именованный, версионируемый и повторно используемый Output: документ, dataset, scorecard, matrix, report или structured object.",
    simpleExplanation: "Материальный след работы, который можно открыть, проверить и передать дальше.",
    example: "Compliance Matrix — Artifact, связывающий 164 требования с ответами, evidence и статусами.",
    notToConfuseWith: "Output обозначает любой результат выполнения, а Artifact — сохранённый и управляемый результат.",
    category: "evidence",
    aliases: ["deliverable", "артефакт"],
  },
  {
    term: "Evidence",
    translation: "Проверяемое доказательство",
    explanation: "Источник или документ, подтверждающий факт, вывод, соответствие либо принятое решение и пригодный для повторной проверки.",
    simpleExplanation: "Основание, по которому другой человек может проверить, почему системе следует верить.",
    example: "Сертификат FSC и ссылка на реестр подтверждают claim о происхождении материалов.",
    notToConfuseWith: "Evidence является подтверждением, а Provenance показывает его происхождение и цепочку использования.",
    category: "evidence",
    aliases: ["доказательство", "источник"],
  },
  {
    term: "Provenance",
    translation: "Происхождение данных и выводов",
    explanation: "Трассируемая запись о том, откуда пришли данные, кто и когда их изменил и какие выводы или решения на них опираются.",
    simpleExplanation: "Паспорт результата: источник, версия и путь до текущего вывода.",
    example: "Match 88% связан с конкретными пунктами тендера, профилем компании и версиями evidence.",
    notToConfuseWith: "Evidence подтверждает факт, а Provenance объясняет происхождение и движение этого evidence.",
    category: "evidence",
    aliases: ["происхождение", "source trace"],
  },
  {
    term: "Dependency",
    translation: "Зависимость процесса",
    explanation: "Типизированное условие между элементами процесса, показывающее, что одна Activity, Event или Decision зависит от другого результата, состояния либо внешнего факта.",
    simpleExplanation: "Правило, объясняющее, почему работу нельзя или не нужно продолжать раньше.",
    example: "Match Score зависит одновременно от verified company profile и structured requirements.",
    notToConfuseWith: "Dependency описывает обязательную связь, Handoff передаёт работу, а Trigger сообщает, когда запускать её.",
    category: "control",
    aliases: ["зависимость"],
  },
  {
    term: "Sequential Dependency",
    translation: "Последовательная зависимость",
    explanation: "Dependency, при которой downstream Activity может начаться только после завершения предыдущей Activity или получения её Output.",
    simpleExplanation: "Следующая работа действительно нуждается в результате предыдущей.",
    example: "Финальный Match нельзя рассчитать до получения профиля компании и реестра требований.",
    notToConfuseWith: "Parallel Execution допускает перекрытие работ, а Sequential Dependency требует причинного порядка.",
    category: "control",
    aliases: ["последовательная зависимость"],
  },
  {
    term: "Blocking Dependency",
    translation: "Блокирующая зависимость",
    explanation: "Dependency, запрещающая переход Activity в running или completed, пока обязательный Output, approval, внешний факт либо State не подтверждён.",
    simpleExplanation: "Без конкретного документа или решения продолжать нельзя.",
    example: "Финальная подача заблокирована до Human Approval цены и закрытия red-team замечаний.",
    notToConfuseWith: "Blocking Dependency является причиной запрета, а Waiting State — текущим состоянием ожидающей работы.",
    category: "control",
    aliases: ["блокирующая зависимость", "blocker"],
  },
  {
    term: "External Dependency",
    translation: "Внешняя зависимость",
    explanation: "Dependency от Actor, организации, портала, банка или другого условия вне прямого управления TenderLab.",
    simpleExplanation: "TenderLab может контролировать срок, но не может сам заставить банк или заказчика ответить.",
    example: "Подтверждение bid security банком является External Dependency для окончательного решения BID.",
    notToConfuseWith: "External Dependency описывает внешнюю предпосылку, а Blocking Dependency — её влияние на процесс.",
    category: "control",
    aliases: ["внешняя зависимость"],
  },
  {
    term: "Trigger",
    translation: "Триггер / условие запуска",
    explanation: "Событие, время, решение или изменение State, которое запускает либо возобновляет Activity по правилам Workflow.",
    simpleExplanation: "Сигнал «можно начинать» или «пора продолжить».",
    example: "Официальный clarification request заказчика запускает Post-Bid Clarification Response Agent.",
    notToConfuseWith: "Event может породить сигнал, Trigger запускает действие, а Dependency проверяет готовность к старту.",
    category: "process",
    aliases: ["триггер", "условие запуска"],
  },
  {
    term: "State",
    translation: "Состояние процесса",
    explanation: "Текущее каноническое положение Case, Activity или Agent Run: ready, running, waiting, blocked, completed, skipped либо failed.",
    simpleExplanation: "Честный ответ на вопрос «что с работой сейчас».",
    example: "После submission Case переходит в waiting до решения evaluation committee.",
    notToConfuseWith: "State показывает текущее положение, а Event фиксирует изменение этого положения.",
    category: "process",
    aliases: ["статус", "состояние"],
  },
  {
    term: "Waiting State",
    translation: "Состояние ожидания",
    explanation: "State, в котором Activity или Case временно не выполняет работу и ожидает определённый Trigger, внешний ответ, время либо Human Approval.",
    simpleExplanation: "Процесс поставлен на управляемую паузу и знает, чего именно ждёт.",
    example: "После submission Case ждёт решение комиссии; clarification не запускается без официального запроса.",
    notToConfuseWith: "Waiting State описывает паузу, Blocking Dependency — обязательную причину этой паузы.",
    category: "process",
    aliases: ["ожидание", "waiting"],
  },
  {
    term: "Decision Gate",
    translation: "Точка решения / шлюз выбора",
    explanation: "Контрольная точка Workflow, которая оценивает правила и evidence, фиксирует решение и открывает разрешённые ветви.",
    simpleExplanation: "Управляемый перекрёсток, выбирающий допустимую дорогу дальше.",
    example: "Bid / No-Bid является Decision Gate, после которого открывается подготовка заявки либо Case закрывается.",
    notToConfuseWith: "Decision Gate принимает решение, Conditional Branch представляет выбранный путь, Human Approval требует человека.",
    category: "control",
    aliases: ["точка решения", "шлюз решения"],
  },
  {
    term: "Conditional Branch",
    translation: "Условная ветвь",
    explanation: "Ветка Workflow, активируемая только при истинности явного условия, результате Decision Gate или наличии определённого Event.",
    simpleExplanation: "Дорога, которая открывается только при нужном условии.",
    example: "Local Service & Representation Agent активируется только при требовании локального сервиса.",
    notToConfuseWith: "Decision Gate выбирает путь, Conditional Branch является условным путём, Parallel Execution запускает несколько ветвей вместе.",
    category: "process",
    aliases: ["условная ветвь", "branch"],
  },
  {
    term: "Parallel Execution",
    translation: "Параллельное выполнение",
    explanation: "Одновременное или перекрывающееся по времени выполнение независимых Activity либо ветвей одного Case.",
    simpleExplanation: "Несколько команд работают одновременно, не ожидая друг друга без реальной необходимости.",
    example: "Проверка company profile и структурирование tender package идут параллельно после открытия Case.",
    notToConfuseWith: "Parallel Execution описывает одновременность, Fan-Out / Fan-In — структуру разветвления и объединения.",
    category: "process",
    aliases: ["параллельное выполнение", "parallel"],
  },
  {
    term: "Fan-Out / Fan-In",
    translation: "Разветвление и объединение ветвей",
    explanation: "Паттерн, при котором одна Activity запускает несколько независимых ветвей, а последующая точка объединяет их по правилу all, any или n-of-m.",
    simpleExplanation: "Работа раздаётся нескольким исполнителям, затем их результаты собираются вместе.",
    example: "После разрешения на анализ параллельно проверяются компания и документы, а Match объединяет оба Output.",
    notToConfuseWith: "Parallel Execution описывает одновременность, Handoff — передачу, а Fan-Out / Fan-In — структуру ветвей.",
    category: "process",
    aliases: ["fan-out", "fan-in", "разветвление", "объединение"],
  },
  {
    term: "Handoff",
    translation: "Передача работы и контекста",
    explanation: "Управляемая передача Output, ответственности, State и ожидаемого следующего действия от одного Agent, Activity или Actor к другому.",
    simpleExplanation: "Не просто пересылка файла, а передача результата вместе с объяснением, что делать дальше.",
    example: "Requirement Parser Agent передаёт реестр требований в Eligibility и Compliance Matrix agents.",
    notToConfuseWith: "Output является передаваемым результатом, Dependency требует его наличия, а Handoff выполняет саму передачу.",
    category: "process",
    aliases: ["передача", "handover"],
  },
  {
    term: "Feedback Loop",
    translation: "Контур обратной связи",
    explanation: "Связь, при которой поздний Output или outcome обновляет данные, правила или решения более ранней части текущего либо будущего Workflow.",
    simpleExplanation: "Результат в конце помогает точнее работать в следующих кейсах.",
    example: "Tender Outcome Learning Agent возвращает цену победы и данные исполнения в discovery и scoring models.",
    notToConfuseWith: "Feedback Loop улучшает будущую работу, Rework Loop исправляет текущий Output, Retry повторяет операцию после сбоя.",
    category: "control",
    aliases: ["обратная связь", "feedback"],
  },
  {
    term: "Retry",
    translation: "Повтор выполнения после сбоя",
    explanation: "Повторный запуск той же Activity с тем же намерением после временной технической ошибки или недоступности источника.",
    simpleExplanation: "Система пробует ту же работу ещё раз, не меняя задание.",
    example: "Tender Source Acquisition Agent повторяет загрузку временно недоступного вложения.",
    notToConfuseWith: "Retry повторяет неизменную операцию, Rework Loop меняет результат по содержательным замечаниям.",
    category: "control",
    aliases: ["повтор", "повторная попытка"],
  },
  {
    term: "Rework Loop",
    translation: "Цикл доработки результата",
    explanation: "Возврат Output на предыдущую Activity для содержательного исправления после проверки, замечания или изменившегося требования.",
    simpleExplanation: "Проверяющий вернул материал на исправление, затем новая версия снова проходит контроль.",
    example: "Bid QA & Red Team Agent возвращает замечания авторам proposal до окончательной сборки.",
    notToConfuseWith: "Rework Loop изменяет текущий Output, Retry повторяет ту же операцию после временного сбоя.",
    category: "control",
    aliases: ["доработка", "rework"],
  },
  {
    term: "Critical Path",
    translation: "Критический путь процесса",
    explanation: "Самая длинная цепочка обязательных Blocking Dependency, определяющая минимально возможное время завершения Case.",
    simpleExplanation: "Цепочка работ без запаса времени: задержка в ней задерживает весь тендерный процесс.",
    example: "Гарантия, Human Approval, сборка и submission могут образовать Critical Path к deadline.",
    notToConfuseWith: "Sequential Dependency задаёт порядок двух работ, а Critical Path определяет срок всего Case.",
    category: "control",
    aliases: ["критический путь"],
  },
  {
    term: "Dependency Graph",
    translation: "Граф зависимостей",
    explanation: "Графовая модель, где узлы представляют элементы процесса, а типизированные направленные связи показывают зависимости, выполнение, передачу и orchestration.",
    simpleExplanation: "Карта реальных many-to-many связей между работами, результатами и агентами.",
    example: "Agent Catalog Network показывает, какие agents производят и потребляют outputs и кто их orchestrates.",
    notToConfuseWith: "Dependency Graph показывает рабочие зависимости, Knowledge Graph связывает предметные сущности, Taxonomy классифицирует элементы.",
    category: "visual",
    aliases: ["граф зависимостей", "DAG", "network"],
  },
  {
    term: "Swimlane",
    translation: "Дорожка ответственности",
    explanation: "Полоса процессной диаграммы, группирующая Event и Activity по ответственному Actor, роли или системе.",
    simpleExplanation: "Каждому участнику выделена строка, поэтому видно, кто за что отвечает.",
    example: "Case Orchestration Map размещает Buyer, Client Company, TenderLab и External Actors в отдельных swimlanes.",
    notToConfuseWith: "Swimlane показывает ответственность, Dependency Graph хранит причинные связи, Actor является участником.",
    category: "visual",
    aliases: ["дорожка", "swim lane"],
  },
  {
    term: "Event-driven Workflow",
    translation: "Событийно-управляемый процесс",
    explanation: "Workflow, в котором новые Activity запускаются событиями и изменениями State, а не только заранее заданной последовательностью или таймером.",
    simpleExplanation: "Процесс реагирует на факты по мере их появления.",
    example: "Post-Bid Clarification Response Agent активируется после официального buyer request, а не на фиксированном шаге.",
    notToConfuseWith: "Workflow задаёт полную модель, Event-driven Workflow подчёркивает способ запуска его Activity через Event.",
    category: "process",
    aliases: ["event-driven", "событийный процесс"],
  },
];

export const contextualGlossaryTermsByPath: Record<string, string[]> = {
  "/": ["Case", "Workflow", "AI Agent", "Orchestration", "Decision Gate", "Output"],
  "/architecture": ["Workflow", "Orchestration", "Main Agent", "Specialized Agent", "Optional Agent", "Dependency Graph"],
  "/workflow": ["Workflow", "Event", "Activity", "Trigger", "Parallel Execution", "Conditional Branch", "Fan-Out / Fan-In"],
  "/agents": ["AI Agent", "Agent Registry", "Main Agent", "Specialized Agent", "Optional Agent", "Shared Agent", "Cross-Stage Agent", "Agent Engagement"],
  "/case-simulation": ["Case", "Event", "Actor", "Dependency", "Waiting State", "Decision Gate", "Critical Path", "Dependency Graph", "Swimlane"],
  "/main-agents-run": ["State", "Input", "Output", "Handoff", "Human Approval", "Waiting State", "Retry"],
};

const normalize = (value: string) => value.toLocaleLowerCase("ru-RU").replace(/[–—/·(),.:]/g, " ").replace(/\s+/g, " ").trim();

export function scoreTenderGlossaryTerm(item: TenderGlossaryTerm, query: string) {
  const normalizedQuery = normalize(query);
  if (!normalizedQuery) return 1;
  const term = normalize(item.term);
  if (term === normalizedQuery) return 100;
  if (term.startsWith(normalizedQuery)) return 94;
  if (term.includes(normalizedQuery)) return 88;
  if (item.aliases?.some((alias) => normalize(alias).includes(normalizedQuery))) return 84;
  if (normalize(item.translation).includes(normalizedQuery)) return 80;
  const searchable = normalize([item.explanation, item.simpleExplanation, item.example, item.notToConfuseWith].join(" "));
  if (searchable.includes(normalizedQuery)) return 68;
  const words = normalizedQuery.split(" ").filter((word) => word.length > 2);
  if (words.length && words.every((word) => `${term} ${searchable}`.includes(word))) return 56;
  return 0;
}

const duplicateTerms = tenderGlossaryTerms.filter((item, index) =>
  tenderGlossaryTerms.findIndex((candidate) => normalize(candidate.term) === normalize(item.term)) !== index,
);
if (duplicateTerms.length) throw new Error(`Duplicate TenderLab glossary terms: ${duplicateTerms.map((item) => item.term).join(", ")}`);

