/** Stage 6 immutable focus contexts and compact union membership. Results only. */
import {readFile} from 'node:fs/promises';
import {TENANT,sha} from './tendermatch-input-manifest.mjs';
import {resultColumns,rowResult} from './tendermatch-formula.mjs';
import {expandCriterionAudit} from '../../packages/tendermatch/src/formula-stage4-adapter.ts';
import {POLICIES,SHORTLIST_VERSION,SHORTLIST_SCHEMA,nominate,keyOf,validateSelectionInput} from '../../packages/tendermatch/src/shortlist-stage6.ts';
export const BASE='263389a58674484cbdae4539e8edeb95c9f2f215';
export const TABLES=['shortlist_context','shortlist_run','shortlist_member','shortlist_pair','shortlist_completion'];
export const POLICY=Object.freeze({...POLICIES.find(p=>p.name==='balanced-100-3'),version:SHORTLIST_VERSION,combination:'UNION_OF_DIRECTIONAL_NOMINATIONS',reviewOrder:['retrieval_units DESC','formula_score DESC','data_coverage DESC','evidence_confidence DESC','opposite_uuid ASC'],auditOrder:'SHA256_VERSION_PAIR_ID_ASC',aiAuthorization:false});
const root=new URL('../../',import.meta.url),buf=h=>Buffer.from(h,'hex'),cmp=(a,b)=>a<b?-1:a>b?1:0;
const contextSort=(a,b)=>cmp(a.kind,b.kind)||cmp(a.id,b.id);
export async function stage6CodeIdentity(){const files={};for(const f of ['packages/tendermatch/src/shortlist-stage6.ts','scripts/lib/tendermatch-stage6.mjs','scripts/tendermatch-stage6.mjs','db/tendermatch-dev/090-shortlist-up.sql'])files[f]=sha((await readFile(new URL(f,root),'utf8')).replaceAll('\r\n','\n'));return {files,hash:sha(files)};}
export function createShortlistRun(loaded,code,{contextCache=[]}={}){
 const policy={...POLICY,codeHash:code.hash},policyHash=sha(policy),memberById=new Map(loaded.members.map(m=>[`${m.kind}:${m.id}`,m]));
 if(memberById.size!==loaded.members.length)throw new Error('Duplicate shortlist member identity');
 const groups=new Map(loaded.members.map(m=>[`${m.kind}:${m.id}`,[]])),byPair=new Map();
 for(const row of loaded.pairs){validateSelectionInput(row);if(byPair.has(keyOf(row)))throw new Error('Duplicate shortlist candidate');byPair.set(keyOf(row),row);for(const kind of ['supplier','tender']){const key=`${kind}:${row[`${kind}Id`]}`;if(!groups.has(key))throw new Error('Unpinned shortlist candidate');groups.get(key).push(row);}}
 const cache=new Map(contextCache.map(c=>[c.key,c]));if(cache.size!==contextCache.length)throw new Error('Duplicate shortlist context cache');
 let extracted=0,reused=0;const contexts=[];
 for(const m of loaded.members){const rows=groups.get(`${m.kind}:${m.id}`).sort((a,b)=>cmp(keyOf(a),keyOf(b)));
  const inputHash=sha(rows.map(p=>[memberById.get(`supplier:${p.supplierId}`).profile_key,memberById.get(`tender:${p.tenderId}`).profile_key,p]));
  const identity={policyHash,methodHash:loaded.rankingIdentity.methodHash,formulaPolicy:loaded.rankingIdentity.formulaPolicy,kind:m.kind,id:m.id,profileKey:m.profile_key,inputHash};
  const key=sha(identity),prior=cache.get(key);let context;
  if(prior){const {key:oldKey,nominations,candidateCount,positiveCount,resultHash,...oldIdentity}=prior;
   if(oldKey!==key||sha(oldIdentity)!==key||candidateCount!==rows.length||positiveCount!==rows.filter(r=>r.units>0).length||resultHash!==sha({key,nominations,candidateCount,positiveCount}))throw new Error('Corrupt shortlist context cache');context=prior;reused++;
  }else{context={...identity,key,candidateCount:rows.length,positiveCount:rows.filter(r=>r.units>0).length,nominations:nominate(rows,m.kind,POLICY)};context.resultHash=sha({key,nominations:context.nominations,candidateCount:context.candidateCount,positiveCount:context.positiveCount});extracted++;}
  contexts.push(context);
 }
 contexts.sort(contextSort);const contextById=new Map(contexts.map(c=>[`${c.kind}:${c.id}`,c])),nominations=new Map();
 for(const context of contexts)for(const n of context.nominations){const p=byPair.get(keyOf(n));if(!p||n[`${context.kind}Id`]!==context.id)throw new Error('Unpinned shortlist nomination');let nom=nominations.get(keyOf(n));if(!nom)nominations.set(keyOf(n),nom={});if(nom[context.kind])throw new Error('Duplicate directional nomination');nom[context.kind]=n;}
 const pairs=[];for(const [key,nom] of nominations){const p=byPair.get(key),s=contextById.get(`supplier:${p.supplierId}`),t=contextById.get(`tender:${p.tenderId}`),tier=p.units>0?1:2;
  if(Object.values(nom).some(n=>n.tier!==(tier===1?'REVIEW_CANDIDATE':'AUDIT_ONLY')))throw new Error('Shortlist tier disagrees with retrieval evidence');
  const selection={reasonMask:(nom.supplier?(tier===1?1:4):0)|(nom.tender?(tier===1?2:8):0),supplierNominationRank:nom.supplier?.rank??null,tenderNominationRank:nom.tender?.rank??null,supplierTieSize:nom.supplier?.tieSize??null,tenderTieSize:nom.tender?.tieSize??null};
  pairs.push({key:sha([policyHash,s.key,t.key]),policyHash,supplierContext:s.key,tenderContext:t.key,supplierId:s.id,tenderId:t.id,methodHash:s.methodHash,formulaPolicy:s.formulaPolicy,supplierProfile:s.profileKey,tenderProfile:t.profileKey,tier,selection});
 }
 pairs.sort((a,b)=>cmp(keyOf(a),keyOf(b)));const outcomeHash=sha(pairs),contextHash=sha(contexts.map(c=>[c.kind,c.id,c.key]));
 const identity={schema:SHORTLIST_SCHEMA,policy,policyHash,rankingRunId:loaded.rankingRunId,rankingOutcomeHash:loaded.rankingOutcomeHash,projectionHash:loaded.inputHash,contextHash,candidates:loaded.pairs.length,contexts:contexts.length,selected:pairs.length,reviewCandidates:pairs.filter(p=>p.tier===1).length,auditOnly:pairs.filter(p=>p.tier===2).length,outcomeHash,actualAiTorsReady:0};
 return {runId:sha(identity),identity,policyHash,contexts,pairs,extraction:{extracted,reused},contextById};
}
export async function loadContextCache(c){const all=[];let after=null;while(true){const rows=(await c.query(`SELECT context,encode(context_key,'hex') key FROM tendermatch_retrieval.shortlist_context WHERE tenant_id=$1 AND ($2::bytea IS NULL OR context_key>$2) ORDER BY context_key LIMIT 500`,[TENANT,after&&buf(after)])).rows;all.push(...rows.map(r=>r.context));if(rows.length<500)break;after=rows.at(-1).key;}return all;}
export async function prepareShortlistRun(c,run){
 const existing=new Set((await loadContextCache(c)).map(p=>p.key)),pending=run.contexts.filter(p=>!existing.has(p.key));let insertedContexts=0,insertedMembers=0;
 await c.query('BEGIN');try{
  for(let i=0;i<pending.length;i+=100)insertedContexts+=(await c.query(`INSERT INTO tendermatch_retrieval.shortlist_context(tenant_id,context_key,policy_hash,source_run_id,kind,entity_id,profile_key,input_hash,context) SELECT $1,decode(x->>'key','hex'),decode(x->>'policyHash','hex'),$2,x->>'kind',(x->>'id')::uuid,decode(x->>'profileKey','hex'),decode(x->>'inputHash','hex'),x FROM jsonb_array_elements($3::jsonb) x ON CONFLICT DO NOTHING`,[TENANT,run.identity.rankingRunId,JSON.stringify(pending.slice(i,i+100))])).rowCount;
  const header=await c.query(`INSERT INTO tendermatch_retrieval.shortlist_run(tenant_id,run_id,ranking_run_id,policy_hash,identity) VALUES($1,$2,$3,decode($4,'hex'),$5) ON CONFLICT DO NOTHING`,[TENANT,run.runId,run.identity.rankingRunId,run.policyHash,JSON.stringify(run.identity)]);
  const [actual]=(await c.query('SELECT identity FROM tendermatch_retrieval.shortlist_run WHERE tenant_id=$1 AND run_id=$2',[TENANT,run.runId])).rows;if(!actual||sha(actual.identity)!==run.runId)throw new Error('Shortlist run collision');
  if(header.rowCount)for(let i=0;i<run.contexts.length;i+=500)insertedMembers+=(await c.query(`INSERT INTO tendermatch_retrieval.shortlist_member(tenant_id,run_id,kind,entity_id,context_key) SELECT $1,$2,x->>'kind',(x->>'id')::uuid,decode(x->>'key','hex') FROM jsonb_array_elements($3::jsonb) x`,[TENANT,run.runId,JSON.stringify(run.contexts.slice(i,i+500))])).rowCount;
  await c.query('COMMIT');return {insertedContexts,insertedMembers,insertedRun:header.rowCount};
 }catch(e){await c.query('ROLLBACK');throw e;}
}
export async function insertShortlistBatch(c,run,pairs){return (await c.query(`INSERT INTO tendermatch_retrieval.shortlist_pair(tenant_id,pair_key,policy_hash,supplier_context,tender_context,supplier_id,tender_id,method_hash,formula_policy,supplier_profile,tender_profile,tier,selection)
 SELECT $1,decode(x->>'key','hex'),decode(x->>'policyHash','hex'),decode(x->>'supplierContext','hex'),decode(x->>'tenderContext','hex'),(x->>'supplierId')::uuid,(x->>'tenderId')::uuid,decode(x->>'methodHash','hex'),decode(x->>'formulaPolicy','hex'),decode(x->>'supplierProfile','hex'),decode(x->>'tenderProfile','hex'),(x->>'tier')::smallint,x->'selection' FROM jsonb_array_elements($2::jsonb) x ON CONFLICT DO NOTHING`,[TENANT,JSON.stringify(pairs)])).rowCount;}
export const pairColumns=`encode(p.pair_key,'hex') key,encode(p.policy_hash,'hex') "policyHash",encode(p.supplier_context,'hex') "supplierContext",encode(p.tender_context,'hex') "tenderContext",p.supplier_id::text "supplierId",p.tender_id::text "tenderId",encode(p.method_hash,'hex') "methodHash",encode(p.formula_policy,'hex') "formulaPolicy",encode(p.supplier_profile,'hex') "supplierProfile",encode(p.tender_profile,'hex') "tenderProfile",p.tier,p.selection`;
export async function executeShortlist(c,run,{readOnly=false}={}){const start=performance.now();let reused=0,inserted=0,maxBatchBytes=0;const actual=[];
 for(let i=0;i<run.pairs.length;i+=500){const batch=run.pairs.slice(i,i+500),stored=(await c.query(`SELECT ${pairColumns} FROM tendermatch_retrieval.shortlist_pair p WHERE p.tenant_id=$1 AND p.pair_key=ANY($2::bytea[])`,[TENANT,batch.map(p=>buf(p.key))])).rows,cache=new Map(stored.map(p=>[p.key,p])),pending=[];
  for(const p of batch){const old=cache.get(p.key);if(old){if(sha(old)!==sha(p))throw new Error('Persisted shortlist result differs');reused++;actual.push(old);}else{if(readOnly)throw new Error('Missing shortlist row');pending.push(p);actual.push(p);}}
  maxBatchBytes=Math.max(maxBatchBytes,Buffer.byteLength(JSON.stringify(pending)));if(pending.length)inserted+=await insertShortlistBatch(c,run,pending);
 }
 const outcomeHash=sha(actual);if(outcomeHash!==run.identity.outcomeHash)throw new Error('Shortlist outcome differs');return {count:actual.length,reused,inserted,outcomeHash,elapsedMs:Math.round(performance.now()-start),maxBatchBytes};
}
export async function completeShortlistRun(c,run){await c.query(`INSERT INTO tendermatch_retrieval.shortlist_completion(tenant_id,run_id,outcome_hash,pair_count,review_count,audit_count) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT DO NOTHING`,[TENANT,run.runId,run.identity.outcomeHash,run.identity.selected,run.identity.reviewCandidates,run.identity.auditOnly]);const [r]=(await c.query('SELECT outcome_hash,pair_count::int,review_count::int,audit_count::int FROM tendermatch_retrieval.shortlist_completion WHERE tenant_id=$1 AND run_id=$2',[TENANT,run.runId])).rows;if(!r||r.outcome_hash!==run.identity.outcomeHash||r.pair_count!==run.identity.selected||r.review_count!==run.identity.reviewCandidates||r.audit_count!==run.identity.auditOnly)throw new Error('Shortlist completion collision');return r;}
export function shortlistPageSpec(run,{direction,focusId,limit=25,cursor=null}){
 if(!['supplier','tender'].includes(direction)||!Number.isInteger(limit)||limit<1||limit>100)throw new Error('Invalid bounded shortlist request');const context=run.contextById.get(`${direction}:${focusId}`);if(!context)throw new Error('Unpinned shortlist focus');const scope=sha([run.runId,direction,focusId]);let after=null;
 if(cursor!==null){try{if(typeof cursor!=='string'||cursor.length>1024)throw 0;after=JSON.parse(Buffer.from(cursor,'base64url').toString());}catch{throw new Error('Malformed shortlist cursor');}if(after.scope!==scope||![1,2].includes(after.tier)||!/^[a-f0-9]{8}(-[a-f0-9]{4}){3}-[a-f0-9]{12}$/.test(after.id??''))throw new Error('Shortlist cursor scope/value differs');}
 const opposite=direction==='supplier'?'tender':'supplier';return {scope,limit,direction,opposite,text:`SELECT ${pairColumns} FROM tendermatch_retrieval.shortlist_pair p JOIN tendermatch_retrieval.shortlist_member m ON m.tenant_id=p.tenant_id AND m.run_id=$1 AND m.kind='${opposite}' AND m.context_key=p.${opposite}_context WHERE p.tenant_id=$2 AND p.policy_hash=decode($3,'hex') AND p.${direction}_context=decode($4,'hex') AND ($5::smallint IS NULL OR (p.tier,p.${opposite}_id)>($5::smallint,$6::uuid)) ORDER BY p.tier,p.${opposite}_id LIMIT $7`,values:[run.runId,TENANT,run.policyHash,context.key,after?.tier??null,after?.id??null,limit+1]};
}
export async function queryShortlist(c,run,request){const completion=(await c.query('SELECT outcome_hash FROM tendermatch_retrieval.shortlist_completion WHERE tenant_id=$1 AND run_id=$2',[TENANT,run.runId])).rows;if(completion.length!==1)throw new Error('Shortlist run incomplete');const spec=shortlistPageSpec(run,request);
 const rows=(await c.query(`WITH page AS MATERIALIZED (${spec.text}) SELECT page.*,r.relevance_units,r.limitation_mask,${resultColumns.split(',').map(x=>'f.'+x).join(',')} FROM page JOIN tendermatch_retrieval.ranking_pair r ON r.tenant_id=$2 AND r.method_hash=decode(page."methodHash",'hex') AND r.formula_policy=decode(page."formulaPolicy",'hex') AND r.supplier_profile=decode(page."supplierProfile",'hex') AND r.tender_profile=decode(page."tenderProfile",'hex') JOIN tendermatch_retrieval.formula_pair f ON f.tenant_id=r.tenant_id AND f.policy_hash=r.formula_policy AND f.supplier_key=r.supplier_key AND f.tender_key=r.tender_key ORDER BY page.tier,page."${spec.opposite}Id"`,spec.values)).rows;
 const hasMore=rows.length>spec.limit,kept=rows.slice(0,spec.limit),last=kept.at(-1);return {runId:run.runId,rankingRunId:run.identity.rankingRunId,policyVersion:SHORTLIST_VERSION,results:kept.map(p=>({supplierId:p.supplierId,tenderId:p.tenderId,shortlist:{tier:p.tier===1?'REVIEW_CANDIDATE':'AUDIT_ONLY',...p.selection},retrieval:{units:p.relevance_units,relevance:p.relevance_units/1000000,limitationMask:p.limitation_mask,semanticSimilarity:null,semanticState:'MISSING'},formula:rowResult(p),eligibility:'CANDIDATE_ELIGIBLE_WITH_LIMITATIONS',humanDisposition:null,aiTors:null,aiAuthorized:false,onDemandEscalationEligible:true})),hasMore,nextCursor:hasMore?Buffer.from(JSON.stringify({scope:spec.scope,tier:last.tier,id:last[`${spec.opposite}Id`]})).toString('base64url'):null,limitations:['SHORTLIST_NOT_A_MATCH_DECISION','AUDIT_ONLY_NOT_PROMISING_OR_AI_READY','FUTURE_ESCALATION_REQUIRES_SEPARATE_GATE','HUMAN_DISPOSITION_AND_AI_TORS_NOT_LOADED']};
}
export async function selectedShortlistDetail(c,run,{supplierId,tenderId}){
 const s=run.contextById.get(`supplier:${supplierId}`),t=run.contextById.get(`tender:${tenderId}`);if(!s||!t)throw new Error('Explicit pinned shortlist pair required');
 if(!(await c.query('SELECT 1 FROM tendermatch_retrieval.shortlist_completion WHERE tenant_id=$1 AND run_id=$2',[TENANT,run.runId])).rows.length)throw new Error('Shortlist run incomplete');
 const [pair]=(await c.query(`SELECT ${pairColumns} FROM tendermatch_retrieval.shortlist_pair p WHERE tenant_id=$1 AND pair_key=decode($2,'hex')`,[TENANT,sha([run.policyHash,s.key,t.key])])).rows;
 const [r]=(await c.query(`SELECT r.relevance_units,r.limitation_mask,${resultColumns.split(',').map(x=>'f.'+x).join(',')} FROM tendermatch_retrieval.ranking_pair r JOIN tendermatch_retrieval.formula_pair f ON f.tenant_id=r.tenant_id AND f.policy_hash=r.formula_policy AND f.supplier_key=r.supplier_key AND f.tender_key=r.tender_key WHERE r.tenant_id=$1 AND r.method_hash=decode($2,'hex') AND r.formula_policy=decode($3,'hex') AND r.supplier_profile=decode($4,'hex') AND r.tender_profile=decode($5,'hex')`,[TENANT,s.methodHash,s.formulaPolicy,s.profileKey,t.profileKey])).rows;
 const inputs=r?(await c.query(`SELECT p.kind,i.projection FROM tendermatch_retrieval.ranking_profile p JOIN tendermatch_retrieval.formula_input i ON i.tenant_id=p.tenant_id AND i.input_key=p.input_key WHERE p.tenant_id=$1 AND p.profile_key=ANY($2::bytea[])`,[TENANT,[buf(s.profileKey),buf(t.profileKey)]])).rows:[],formula=r?rowResult(r):null;
 return {runId:run.runId,supplierId,tenderId,shortlist:pair?{tier:pair.tier===1?'REVIEW_CANDIDATE':'AUDIT_ONLY',...pair.selection}:null,state:r?(pair?'SHORTLISTED':'NOT_STORED_IN_SHORTLIST'):'NOT_A_FORMULA_CANDIDATE',onDemandEscalationEligible:!!r,aiAuthorized:false,retrieval:r?{units:r.relevance_units,relevance:r.relevance_units/1000000,limitationMask:r.limitation_mask,semanticSimilarity:null,semanticState:'MISSING'}:null,formula,criteria:r?expandCriterionAudit(formula,inputs.find(i=>i.kind==='supplier')?.projection,inputs.find(i=>i.kind==='tender')?.projection):[],contexts:{supplier:s,tender:t},humanDisposition:null,aiTors:null};
}
