export type EngagementStatus = "required" | "conditional" | "not-involved";
export type ConditionalActivation = "triggered" | "standby";

export type CaseStage = {
  id: string;
  number: string;
  title: string;
  description: string;
  handoff: string;
};

export type CaseAgentEngagement = {
  agentId: number;
  status: EngagementStatus;
  stageId: string;
  when: string;
  why: string;
  input?: string;
  output?: string;
  next?: string;
  condition?: string;
  activation?: ConditionalActivation;
  coveredBy?: string;
};

export const case1 = {
  id: "GE-MES-2026-017",
  name: "Международная поставка школьной мебели",
  company: "Anatolia Workspace A.Ş.",
  companyType: "Опытный производитель и экспортёр мебели",
  companyCountry: "Турция",
  organizer: "Министерство образования и науки Грузии",
  organizerCountry: "Грузия",
  funding: "Всемирный банк",
  tenderType: "Товары",
  procurementMethod: "Открытый международный тендер",
  subject: "Производство и поставка комплектов мебели для 180 государственных школ",
  lot: "1 тендер · 1 лот",
  budget: "$3,85 млн",
  quantity: "26 130 изделий",
  submissionWindow: "28 дней",
  deliveryWindow: "150 дней",
  situation: "Строгие спецификации, крупный объём, распределённая доставка и высокая ценовая конкуренция.",
  outcome: "DEMO: заявка признана соответствующей, контракт присуждён компании.",
} as const;

export const caseStages: CaseStage[] = [
  { id: "control", number: "00", title: "Сквозной контроль", description: "Маршрут, доказательства, версии и согласования сопровождают весь кейс.", handoff: "Управляемый контекст кейса и журнал доказательств" },
  { id: "discovery", number: "01", title: "Поиск возможности", description: "Закупка собирается, классифицируется, фильтруется и ставится на контроль.", handoff: "Приоритетная карточка тендера и календарь" },
  { id: "company", number: "02", title: "Компания и готовность", description: "Проверяются компания, каталог, мощности, опыт и документы готовности.", handoff: "Верифицированный профиль и готовность 84/100" },
  { id: "documents", number: "03", title: "Документы и требования", description: "Пакет структурируется до требований, форм, критериев и условий допуска.", handoff: "164 требования, 68 строк BOQ и решение о допуске" },
  { id: "matching", number: "04", title: "Соответствие и маршрут", description: "Профиль сопоставляется с тендером, определяются пробелы и модель участия.", handoff: "Match 88% и маршрут prime + local service" },
  { id: "decision", number: "05", title: "Решение Bid / No-Bid", description: "Сводятся выполнимость, экономика, риски и управленческое решение.", handoff: "Утверждённое BID с порогами цены и риска" },
  { id: "solution", number: "06", title: "Решение и партнёры", description: "Формируются продуктовая конфигурация, доставка, монтаж и локальный сервис.", handoff: "Архитектура решения и подтверждённая сервисная модель" },
  { id: "compliance", number: "07", title: "Комплаенс и цена", description: "Требования связываются с ответами, рассчитываются себестоимость и BOQ.", handoff: "164/164 и цена заявки $3,61 млн" },
  { id: "proposal", number: "08", title: "Предложение и подача", description: "Готовятся техническая и коммерческая части, QA и финальная подача.", handoff: "31 подписанный файл и квитанция портала" },
  { id: "evaluation", number: "09", title: "Оценка и уточнения", description: "Комиссия оценивает заявку; при запросе готовится доказательный ответ.", handoff: "Принятый ответ на clarification" },
  { id: "award", number: "10", title: "Присуждение и контракт", description: "Уведомление превращается в контролируемый план подписания.", handoff: "Подписанный контракт и план мобилизации" },
  { id: "delivery", number: "11", title: "Исполнение и обучение", description: "Производство, поставка, монтаж, платежи и результат возвращаются в систему.", handoff: "Закрытый контракт и обновлённые модели" },
];

export const case1Engagements: CaseAgentEngagement[] = [
  { agentId: 1, status: "required", stageId: "control", when: "От регистрации возможности до закрытия контракта", why: "Нужен единый условный маршрут вместо запуска всех 64 агентов.", input: "Карточка компании, тендер GE-MES-2026-017 и правила контроля.", output: "Маршрут из 12 этапов, статусы 64 агентов, точки повторов и согласований.", next: "Все активированные агенты и Human Approval Agent." },
  { agentId: 2, status: "required", stageId: "decision", when: "На решении BID, утверждении цены, подаче и принятии award conditions", why: "Критические коммерческие и договорные решения нельзя принимать без ответственного человека.", input: "Scorecard, риск-регистр, цена $3,61 млн и финальный пакет.", output: "Четыре протокола решения с ответственными, условиями и временем утверждения.", next: "TenderLab Orchestrator, Pricing & BOQ Agent, Document Assembly & Submission Agent и Award & Contract Agent." },
  { agentId: 3, status: "required", stageId: "control", when: "При каждом выводе о компании, требовании, score и соответствии", why: "Международная заявка должна связывать утверждения с проверяемыми источниками.", input: "27 исходных документов, профиль компании, сертификаты и протоколы испытаний.", output: "Evidence ledger для 164 требований, scorecards и управленческих решений.", next: "Eligibility, Scoring, Compliance, Bid QA и Human Approval." },
  { agentId: 4, status: "required", stageId: "control", when: "При каждом изменении документов, данных или решения", why: "Нужна воспроизводимая история актуальной версии заявки.", input: "Версии тендерных файлов, профиля, BOQ, предложения и approvals.", output: "Журнал версий, redline и неизменяемая история подачи.", next: "TenderLab Orchestrator, Bid QA, Submission и аудит контракта." },
  { agentId: 5, status: "required", stageId: "control", when: "При создании и обновлении сущностей кейса", why: "Компания, заказчик, тендер, документы, школы, award и контракт должны оставаться связанными.", input: "Проверенные сущности и provenance от активных агентов.", output: "Граф Case 1: компания → тендер → 180 школ → документы → award → контракт.", next: "Discovery, Matching и Outcome Learning." },

  { agentId: 6, status: "required", stageId: "company", when: "До оценки готовности и соответствия", why: "Без структурированного профиля невозможно доказать способность компании исполнить контракт.", input: "Регистрация, каталог, мощности, география, команда и референсы.", output: "Проверенный профиль Anatolia Workspace A.Ş. с мощностью 12 000 изделий в месяц.", next: "Tender Readiness Score Agent, Tender Discovery Agent и Company-to-Tender Match Score Agent." },
  { agentId: 7, status: "required", stageId: "company", when: "При нормализации каталога и производственных возможностей", why: "Нужно сопоставить конкретные виды школьной мебели, параметры и доступную мощность.", input: "Каталог, спецификации моделей, станочный парк и производственный календарь.", output: "Нормализованный каталог 68 BOQ-позиций и карта производственных ограничений.", next: "Company Profile, Readiness, Match Score и Solution Architecture." },
  { agentId: 8, status: "required", stageId: "company", when: "До допуска и tender-specific scoring", why: "Заявленный опыт и производство должны быть подтверждены, а не приняты со слов компании.", input: "Юридические данные, фабрика, четыре аналогичных контракта и акты завершения.", output: "Верифицированное досье производителя с подтверждёнными референсами.", next: "Company Profile, Eligibility и Match Score." },
  { agentId: 9, status: "required", stageId: "company", when: "После формирования профиля, до глубокой обработки заявки", why: "Общая готовность отделяется от соответствия конкретному тендеру.", input: "Профиль, команда, финансы, сертификаты, опыт и шаблоны документов.", output: "Готовность 84/100; пробелы — подтверждение гарантии и локального сервиса.", next: "Gap Analysis, Tender Discovery и Human Approval." },
  { agentId: 10, status: "required", stageId: "company", when: "При проверке допуска и подготовке evidence pack", why: "FSC, ISO 9001 и протоколы материалов должны действовать на дату подачи и поставки.", input: "Сертификаты, области действия, владельцы и даты истечения.", output: "Реестр действующих credentials с предупреждениями по срокам.", next: "Eligibility, Compliance Matrix, Credentials & Experience и Submission." },
  { agentId: 11, status: "not-involved", stageId: "solution", when: "Не запускается", why: "Компания производит предмет закупки сама; отдельная tender-specific база внешних поставщиков не нужна.", coveredBy: "Product & Capability Agent и Capacity & Execution Agent подтверждают собственное производство." },
  { agentId: 12, status: "conditional", activation: "triggered", stageId: "solution", when: "После выявления требования локального монтажа и сервиса", why: "Нужно проверить, какую часть исполнения может закрыть грузинский сервисный партнёр.", condition: "Активирован: локальная сервисная линия является условием допуска.", input: "Профиль кандидата из Тбилиси, география, монтажная команда и SLA.", output: "Карта покрытия партнёра: доставка последней мили, монтаж, гарантийные выезды.", next: "Participation Route Agent и Solution Architecture Agent." },

  { agentId: 13, status: "required", stageId: "discovery", when: "При публикации notice и документов", why: "Нужны оригинальные источники, а не перепечатанная карточка закупки.", input: "Портал заказчика и публикация Всемирного банка.", output: "Нормализованный notice, 27 вложений, URL и source metadata.", next: "Tender Discovery Agent и Document Intake Agent." },
  { agentId: 14, status: "required", stageId: "discovery", when: "После первичного фильтра возможностей", why: "Нужно определить, стоит ли компаниям показывать именно эту возможность.", input: "Профиль компании и нормализованная карточка закупки.", output: "Приоритетная возможность с релевантностью 92% и объяснением факторов.", next: "Document Intake Agent и Company-to-Tender Match Score Agent." },
  { agentId: 15, status: "required", stageId: "discovery", when: "Сразу после получения notice", why: "Процедура и категория определяют дальнейший маршрут обработки.", input: "Notice, страна, заказчик, CPV/категория и условия процедуры.", output: "Классификация: товары · школьная мебель · Грузия · open international · один лот.", next: "Tender Filtering Agent и Tender Discovery Agent." },
  { agentId: 16, status: "required", stageId: "discovery", when: "До включения тендера в shortlist", why: "Система должна отсечь неподходящие географии, категории и масштабы до дорогого анализа.", input: "Классификация тендера и фильтры компании.", output: "Pass: категория, бюджет, география и сроки находятся в допустимом диапазоне.", next: "Tender Discovery Agent и Tender Alert & Deadline Agent." },
  { agentId: 17, status: "required", stageId: "discovery", when: "С момента shortlist до подачи", why: "28-дневное окно требует контроля гарантии, вопросов, документов и загрузки.", input: "Notice, тендерный календарь и ответственные компании.", output: "Календарь из 6 контрольных дат с owners и предупреждениями.", next: "TenderLab Orchestrator, Document Intake и Submission." },
  { agentId: 18, status: "conditional", activation: "triggered", stageId: "discovery", when: "Перед коммерческим решением", why: "Высокая ценовая конкуренция требует рыночного ориентира, но не блокирует допуск.", condition: "Активирован: конкурентная цена названа ключевой сложностью кейса.", input: "Поток сопоставимых мебельных закупок в Грузии и соседних рынках.", output: "Market brief с ценовыми диапазонами, спросом и логистическими факторами.", next: "Commercial Attractiveness Agent и Proposal Strategy Agent." },
  { agentId: 19, status: "conditional", activation: "triggered", stageId: "discovery", when: "При подготовке конкурентного benchmark", why: "История присуждений помогает оценить цену и тип победителей, если данные доступны.", condition: "Активирован: найдено шесть сопоставимых award notices.", input: "Notice и awards по школьной мебели за три года.", output: "Dataset шести присуждений с победителями, ценами и моделями локального исполнения.", next: "Buyer & Competitor Intelligence Agent и TenderScore / Bid-No-Bid Agent." },
  { agentId: 20, status: "conditional", activation: "triggered", stageId: "discovery", when: "До Bid / No-Bid и proposal strategy", why: "Нужно понимать закупочные предпочтения заказчика и вероятное конкурентное поле.", condition: "Активирован: ожидается высокая международная конкуренция.", input: "Buyer history, award dataset и открытые данные потенциальных участников.", output: "Досье заказчика и shortlist из пяти вероятных конкурентов с price bands.", next: "Match Score, Bid / No-Bid и Proposal Strategy." },

  { agentId: 21, status: "required", stageId: "documents", when: "После подтверждения релевантности", why: "Полный пакет должен быть получен, проиндексирован и зафиксирован по версиям.", input: "27 файлов из оригинальных URL.", output: "Версионированный корпус: условия, спецификации, BOQ, формы и чертежи.", next: "Tender Structure Agent, Requirement Parser Agent и Compliance Matrix Agent." },
  { agentId: 22, status: "conditional", activation: "standby", stageId: "documents", when: "Только при появлении сканов или грузиноязычного приложения", why: "Основной пакет цифровой и англоязычный; OCR и перевод сейчас не создают полезного результата.", condition: "Резерв: запускается для нечитаемого скана или документа без английской версии.", input: "Проблемный файл, если он появится.", output: "Поисковый OCR-текст и контролируемый перевод.", next: "Tender Structure Agent и Requirement Parser Agent." },
  { agentId: 23, status: "required", stageId: "documents", when: "После индексации пакета", why: "Даже один лот содержит BOQ, формы, приложения и 180 точек поставки.", input: "Версионированный корпус из 27 файлов.", output: "Структурная карта: 1 лот, 68 BOQ-позиций, 180 школ и 27 обязательных форм.", next: "Requirement Parser Agent, Deliverables & Forms Agent и Document Assembly." },
  { agentId: 24, status: "required", stageId: "documents", when: "После построения структуры пакета", why: "Все дальнейшие проверки зависят от полного реестра условий.", input: "Структурированные документы, BOQ, спецификации и формы.", output: "164 требования с source clause, типом, приоритетом и ответственным.", next: "Eligibility, Evaluation Criteria, Compliance Matrix и Solution Architecture." },
  { agentId: 25, status: "required", stageId: "documents", when: "До окончательного решения об участии", why: "Компания должна пройти обязательные критерии до затрат на полное предложение.", input: "164 требования, проверенный профиль и credentials.", output: "Условный Pass: требуется гарантия 2% и подтверждённая локальная сервисная линия.", next: "Gap Analysis, Bid / No-Bid, Compliance Matrix и Human Approval." },
  { agentId: 26, status: "required", stageId: "documents", when: "До match scoring и proposal strategy", why: "Нужно отделить pass/fail, rated criteria и evaluated price.", input: "Инструкции участникам и раздел оценки.", output: "Формальная модель оценки с критериями, весами, thresholds и правилами цены.", next: "Match Score, Bid / No-Bid и Proposal Strategy." },
  { agentId: 27, status: "required", stageId: "documents", when: "После извлечения требований", why: "Пропущенная форма может дисквалифицировать технически сильную заявку.", input: "Структурная карта и реестр требований.", output: "Реестр 27 форм и deliverables с owners, сроками и статусом.", next: "Compliance Matrix Agent и Document Assembly & Submission Agent." },
  { agentId: 28, status: "required", stageId: "documents", when: "При фиксации технической базы", why: "Строгие размеры, материалы и допуски нельзя заменять предположениями.", input: "Исходные спецификации, чертежи и BOQ.", output: "Source-locked набор 68 спецификаций с единицами, tolerances и запретами substitutions.", next: "Requirement Parser, Technical Compliance и Bid QA." },
  { agentId: 29, status: "conditional", activation: "standby", stageId: "documents", when: "После официальной поправки заказчика", why: "Без новой версии сравнивать нечего; агент остаётся в резерве.", condition: "Резерв: активируется при addendum или замене файла.", input: "Текущая и новая версии тендерного пакета.", output: "Redline и перечень затронутых требований, BOQ и действий.", next: "TenderLab Orchestrator, Compliance Matrix и proposal owners." },
  { agentId: 30, status: "conditional", activation: "standby", stageId: "documents", when: "При обнаружении материального противоречия", why: "В текущем пакете нет блокирующей неоднозначности; вопросы не следует создавать искусственно.", condition: "Резерв: активируется при конфликте BOQ, чертежа или спецификации.", input: "Конфликтующие clauses с provenance.", output: "Buyer-ready clarification question и оценка влияния.", next: "Human Approval, заказчик и Compliance Matrix." },

  { agentId: 31, status: "required", stageId: "matching", when: "После профиля и реестра требований", why: "Tender Readiness не отвечает, насколько компания подходит именно этому тендеру.", input: "Проверенный профиль, 164 требования, eligibility и evidence.", output: "Match 88%: сильны производство, FSC, опыт и срок; два контролируемых gaps.", next: "Solution-Based Matching Agent и TenderScore / Bid-No-Bid Agent." },
  { agentId: 32, status: "required", stageId: "matching", when: "После match score", why: "Участие включает не только мебель, но и доставку, монтаж и сервис по 180 школам.", input: "Match score, gaps и service requirements.", output: "Solution-fit: прямой поставщик из Турции + локальный subcontractor по монтажу и сервису.", next: "Participation Route Agent и Solution Architecture Agent." },
  { agentId: 33, status: "required", stageId: "matching", when: "До окончательного Bid / No-Bid", why: "Нужно формально выбрать роль компании и не превращать локального исполнителя в ненужный JV.", input: "Solution-fit и карта локального покрытия.", output: "Маршрут: Anatolia — prime bidder; грузинский партнёр — service subcontractor.", next: "Gap Analysis, Bid / No-Bid и Solution Architecture." },
  { agentId: 34, status: "required", stageId: "matching", when: "После readiness, eligibility и match scoring", why: "Два пробела должны иметь владельцев и срок закрытия до подачи.", input: "Readiness 84/100, conditional Pass и match 88%.", output: "План: банк подтверждает гарантию; local service partner проходит проверку до D-14.", next: "Human Approval, Participation Route и Solution Architecture." },

  { agentId: 35, status: "required", stageId: "decision", when: "После технического, коммерческого и риск-анализа", why: "Нужна объяснимая развилка BID / NO-BID, а не автоматическое продолжение.", input: "Readiness, match, eligibility, capacity, business case и риски.", output: "BID: вероятность победы 61%, минимальная маржа 13%, четыре условия контроля.", next: "Human Approval Agent, Solution Architecture Agent и Proposal Strategy Agent." },
  { agentId: 36, status: "required", stageId: "decision", when: "До BID и построения графика поставки", why: "26 130 изделий и 180 школ могут превысить реальную производственную и монтажную способность.", input: "Объёмы, мощность 12 000 изделий/месяц, сроки и логистические окна.", output: "Feasibility Pass: шесть волн производства и поставки за 150 дней, два buffer windows.", next: "Bid / No-Bid, Solution Architecture и Execution & Logistics." },
  { agentId: 37, status: "required", stageId: "decision", when: "До утверждения цены", why: "Соответствующая заявка не должна создавать неприемлемую маржу или кассовый разрыв.", input: "Budget $3,85 млн, cost model, платежные условия и working capital.", output: "Business case: цена $3,61 млн, маржа 13%, максимальный cash gap 42 дня.", next: "Bid / No-Bid, Pricing & BOQ и Human Approval." },
  { agentId: 38, status: "required", stageId: "decision", when: "Перед BID и contract acceptance", why: "Нужны санкционная, integrity, страновая и регуляторная проверки.", input: "Компания, заказчик, партнёр, страна, банк и договорные условия.", output: "Риск-регистр: sanctions clear; умеренные payment, logistics и local-subcontractor risks с mitigations.", next: "Bid / No-Bid, Human Approval и Legal & Contract Review." },

  { agentId: 39, status: "required", stageId: "solution", when: "После утверждения BID", why: "Нужно собрать единое изделие–логистика–монтаж–гарантия решение.", input: "164 требования, product catalog, capacity plan и partner route.", output: "Архитектура: 4 продуктовые семьи, 6 волн поставки, монтаж по 180 школам и пятилетний сервис.", next: "Technical Compliance, Cost & Landed-Price и Technical Proposal." },
  { agentId: 40, status: "not-involved", stageId: "solution", when: "Не запускается", why: "Нужен именно локальный сервисный представитель, поэтому широкий международный поиск партнёров дублировал бы более точный маршрут.", coveredBy: "Local Representation Agent выполняет узкий поиск; Partner Capability Graph Agent проверяет найденного кандидата." },
  { agentId: 41, status: "not-involved", stageId: "solution", when: "Не запускается", why: "Компания соответствует как prime bidder; консорциум не требуется и усложнил бы qualification.", coveredBy: "Participation Route Agent фиксирует модель prime + service subcontractor без JV." },
  { agentId: 42, status: "conditional", activation: "triggered", stageId: "solution", when: "После выявления обязательного локального сервиса", why: "У компании нет собственной грузинской сервисной сети.", condition: "Активирован: service coverage является условием допуска.", input: "География 180 школ, SLA, монтажные объёмы и гарантийные требования.", output: "Shortlist из трёх грузинских сервисных компаний; выбран и подтверждён партнёр из Тбилиси.", next: "Partner Capability Graph Agent и Solution Architecture Agent." },
  { agentId: 43, status: "not-involved", stageId: "solution", when: "Не запускается", why: "Все товары одного лота входят в собственный каталог производителя.", coveredBy: "Product & Capability Agent подтверждает полное продуктовое покрытие." },
  { agentId: 44, status: "not-involved", stageId: "solution", when: "Не запускается", why: "Дополнительный внешний поставщик не выбран, поэтому supplier due diligence не имеет объекта.", coveredBy: "Company Verification Agent проверяет самого bidder; партнёр проверяется через partner route." },
  { agentId: 45, status: "not-involved", stageId: "solution", when: "Не запускается", why: "Заявка не зависит от tender-specific закупки товаров у внешних производителей.", coveredBy: "Cost model строится на подтверждённой внутренней себестоимости компании." },
  { agentId: 46, status: "not-involved", stageId: "solution", when: "Не запускается", why: "Нет нескольких внешних supplier quotations для нормализации.", coveredBy: "Cost & Landed-Price Agent использует внутренние калькуляции и подтверждённые логистические ставки." },

  { agentId: 47, status: "required", stageId: "compliance", when: "С начала подготовки ответа до финального QA", why: "Каждое из 164 требований должно иметь ответ, evidence, owner и статус.", input: "Реестр требований, solution architecture, формы и evidence ledger.", output: "Матрица 164 строк: 156 закрыты сразу, 8 закрыты до red team review.", next: "Technical Compliance, Proposal agents и Bid QA." },
  { agentId: 48, status: "required", stageId: "compliance", when: "После фиксации технического решения", why: "Мебель должна соответствовать размерам, материалам, безопасности и durability requirements.", input: "Source-locked specs, чертежи, test reports и compliance matrix.", output: "Техническое заключение 164/164 после семи корректировок конструкции и evidence.", next: "Technical Proposal Agent, Bid QA и Human Approval." },
  { agentId: 49, status: "required", stageId: "compliance", when: "До финализации commercial proposal", why: "Цена, налоги, валюта, гарантия и платежные условия должны отвечать инструкции.", input: "Commercial clauses, price model, bank guarantee и delivery terms.", output: "Commercial compliance Pass с подтверждёнными USD, taxes, 2% bid security и payment milestones.", next: "Commercial Proposal, Legal Review и Bid QA." },
  { agentId: 50, status: "required", stageId: "compliance", when: "После утверждения решения и маршрута поставки", why: "Нужна полная, а не только заводская себестоимость.", input: "Производство, упаковка, фрахт, пошлины, last mile, монтаж и risk reserve.", output: "Landed cost $3,14 млн, включая резерв риска 4,2%.", next: "Pricing & BOQ Agent и Commercial Proposal Agent." },
  { agentId: 51, status: "required", stageId: "compliance", when: "После cost model и утверждения margin threshold", why: "Каждая строка одного лота должна дать согласованную итоговую цену.", input: "68 BOQ-строк, landed cost, budget и минимальная маржа 13%.", output: "Проверенная BOQ и цена заявки $3,61 млн без арифметических расхождений.", next: "Commercial Proposal, Bid QA и Submission." },

  { agentId: 52, status: "required", stageId: "proposal", when: "После BID и до написания предложения", why: "Нужны доказательные темы победы, связанные с критериями оценки.", input: "Evaluation model, competitor brief, match strengths, solution и price position.", output: "Стратегический бриф: долговечность, быстрый rollout, low-emission materials и local service.", next: "Technical Proposal, Commercial Proposal и Bid QA." },
  { agentId: 53, status: "required", stageId: "proposal", when: "После strategy и technical compliance", why: "Заказчику нужен связный технический ответ, а не набор документов.", input: "Solution architecture, compliance matrix, график и evidence.", output: "42-страничное техническое предложение с методологией производства, доставки, монтажа и гарантии.", next: "Bid QA & Red Team Agent и Document Assembly & Submission Agent." },
  { agentId: 54, status: "required", stageId: "proposal", when: "После commercial compliance и pricing", why: "Коммерческие формы и допущения должны соответствовать утверждённой цене.", input: "BOQ $3,61 млн, taxes, Incoterms, payments и assumptions.", output: "Заполненное коммерческое предложение и price schedules без отклонений.", next: "Bid QA & Red Team Agent и Document Assembly & Submission Agent." },
  { agentId: 55, status: "required", stageId: "proposal", when: "При формировании qualification и technical evidence", why: "Опыт, команда и сертификаты должны быть выбраны под требования Case 1.", input: "Реестр credentials, четыре аналогичных проекта, CV и completion certificates.", output: "Credentials pack с четырьмя релевантными контрактами, CV и mapped certificates.", next: "Technical Proposal, Bid QA и Document Assembly." },
  { agentId: 56, status: "required", stageId: "proposal", when: "После сборки полного черновика", why: "Независимая проверка должна найти слабые ответы и несогласованности до подачи.", input: "Технический, коммерческий, qualification и legal package.", output: "Red-team log: шесть замечаний исправлены; 164/164 подтверждены.", next: "Proposal owners, Document Assembly и Human Approval." },
  { agentId: 57, status: "required", stageId: "proposal", when: "До submission approval и после award", why: "Штрафы, гарантии, liability и изменения договора требуют управленческого решения.", input: "Draft contract, commercial terms, risk register и proposed delivery model.", output: "Contract risk memo с пятью mitigations и утверждённым deviation schedule.", next: "Human Approval, Bid QA и Award & Contract Agent." },
  { agentId: 58, status: "required", stageId: "proposal", when: "После QA и approvals", why: "Финальный пакет должен быть подписан, проверен и подан без технических пропусков.", input: "Утверждённые техническая и коммерческая части, формы, гарантия и подписи.", output: "31 файл загружен за 18 часов до срока; manifest, checksums и receipt сохранены.", next: "Портал заказчика, Audit & Version Control и этап оценки." },

  { agentId: 59, status: "conditional", activation: "triggered", stageId: "evaluation", when: "После запроса комиссии на этапе оценки", why: "Ответ должен подтверждать факты и не создавать новых неутверждённых обязательств.", condition: "Активирован: комиссия запросила подтверждение эмиссии материалов и графика монтажа.", input: "Buyer question, submitted bid, test reports и approved schedule.", output: "Утверждённый clarification package с source-linked доказательствами.", next: "Портал заказчика, Audit & Version Control и evaluation record." },
  { agentId: 60, status: "not-involved", stageId: "evaluation", when: "Не запускается", why: "Открытая процедура товаров не предусматривает презентацию или переговоры до award.", coveredBy: "Clarification Response Agent отвечает только на формальный письменный запрос комиссии." },

  { agentId: 61, status: "required", stageId: "award", when: "После уведомления о присуждении", why: "Award создаёт обязательства по performance security, подписанию и мобилизации.", input: "Award notice, final bid, contract conditions и approval limits.", output: "Award-to-contract plan: performance guarantee, signing checklist и mobilization date.", next: "Legal & Contract Review, Execution & Logistics и Contract Administration." },
  { agentId: 62, status: "required", stageId: "delivery", when: "После подписания контракта", why: "Контракт охватывает производство, QC, шесть волн поставки и монтаж в 180 школах.", input: "Signed contract, solution architecture, capacity plan и site schedule.", output: "План исполнения и live status по производству, доставке, монтажу и warranty handover.", next: "Payment & Contract Administration Agent и Outcome Learning Agent." },
  { agentId: 63, status: "required", stageId: "delivery", when: "На каждом milestone и изменении контракта", why: "Платежи зависят от документов поставки, установки, удержаний и гарантий.", input: "Milestones, acceptance certificates, invoices, retention и variations.", output: "Реестр исполнения: шесть milestones, invoices, guarantees, retention и variation log.", next: "Finance, Audit & Version Control и Outcome Learning." },
  { agentId: 64, status: "required", stageId: "delivery", when: "После award и закрытия исполнения", why: "Фактический результат должен улучшить следующие discovery и scoring решения.", input: "Award, evaluation feedback, цена, delivery performance и contract outcome.", output: "Outcome record: контракт выигран, оценка 91/100, факторы победы и corrections моделей.", next: "Tender Knowledge Graph, Discovery и scoring models." },
];

const ids = case1Engagements.map((engagement) => engagement.agentId);
if (ids.length !== 64 || new Set(ids).size !== 64 || ids.some((id) => id < 1 || id > 64)) {
  throw new Error("Case 1 needs exactly one engagement record for every canonical agent.");
}

const stageIds = new Set(caseStages.map((stage) => stage.id));
if (case1Engagements.some((engagement) => !stageIds.has(engagement.stageId))) {
  throw new Error("Every Case 1 engagement must reference a known workflow stage.");
}

if (case1Engagements.some((engagement) => engagement.status !== "not-involved" && (!engagement.input || !engagement.output || !engagement.next))) {
  throw new Error("Every involved Case 1 agent needs an input, output, and handoff.");
}
