import type { CaseProcess, ProcessActivityKind, ProcessRelationship } from "../process-model.ts";

export type Case10EventBlueprint = {
  step: number; period: string; phase: string; title: string; initiator: string; narrative: string; result: string; next: string;
  agentIds: number[]; standbyAgentIds?: number[]; responsibleActorId: string; actorIds: string[]; kind?: ProcessActivityKind;
  trigger: string; startDay: number; endDay: number; column: number; lane: "buyer" | "client" | "tenderlab" | "consultant" | "external";
  critical?: boolean; scopeBoundary: string; missingAgentFinding: string;
};
export type Case10RelationshipSpec = { from: number; to: number; type?: ProcessRelationship["type"]; label: string; condition?: string; blocking?: boolean; joinPolicy?: ProcessRelationship["joinPolicy"] };

export const case10EventBlueprints: Case10EventBlueprint[] = [
  { step: 1, period: "Day −120", phase: "Procurement signal", title: "Buyer publishes PIN/RFI and prior-award reference pack", initiator: "Moldova National Cyber Resilience Office", narrative: "The Buyer announces a five-year sovereign SOC programme. The pack includes a machine-readable PIN, Romanian scan PDFs and links to legacy award notices. Publication creates an intelligence trigger, not permission to contact the Buyer or any partner.", result: "Typed procurement-plan signal and source manifest with separate notice, award and scan items.", next: "E02 acquires/OCRs sources while E03 builds the historical market pattern.", agentIds: [13, 15, 17, 18, 19], responsibleActorId: "buyer", actorIds: ["buyer", "tenderlab", "external"], kind: "external-event", trigger: "Official PIN/RFI publication", startDay: -120, endDay: -120, column: 0, lane: "buyer", critical: true, scopeBoundary: "Buyer owns publication; Agents may collect and classify public items but cannot infer consent, eligibility or misconduct.", missingAgentFinding: "No missing capability at public-signal boundary." },
  { step: 2, period: "Day −120 to −112", phase: "Source reconstruction", title: "Plan, notice, scans and awards become one source-locked corpus", initiator: "TenderLab / Source Operations", narrative: "Source Acquisition fetches originals; Document Intake hashes them; OCR & Translation reconstructs Romanian scans into aligned text; Classification distinguishes procurement plan, RFI, award notice and supporting annex. Evidence and Audit preserve raw files and transformations.", result: "Bilingual source corpus, item-type ledger, provenance links and confidence flags.", next: "E03 uses only evidence-linked award records; E07 later appends the invitation package.", agentIds: [13, 15, 21, 22, 3, 4], responsibleActorId: "tenderlab", actorIds: ["tenderlab", "consultant"], trigger: "E01 source manifest", startDay: -120, endDay: -112, column: 1, lane: "tenderlab", critical: true, scopeBoundary: "OCR/translation may recover text; it cannot convert uncertain statements into verified ownership facts.", missingAgentFinding: "No missing source capability; publication-type classification is distinct from business classification." },
  { step: 3, period: "Day −111 to −96", phase: "Award intelligence", title: "Comparable awards reveal incumbent and local-operator patterns", initiator: "TenderLab Market Intelligence", narrative: "Knowledge Graph links Buyer, awards, suppliers and local operators. Award Intelligence normalises eight comparable SOC contracts; Buyer & Competitor and Supplier Intelligence identify recurring subcontract relationships. The result is a research hypothesis requiring later consented verification.", result: "Comparable-award benchmark, incumbent network hypothesis and local-operator longlist.", next: "E04 prioritises SentinelGrid; E09 starts partner diligence without treating hypotheses as facts.", agentIds: [5, 11, 18, 19, 20, 3], responsibleActorId: "tenderlab", actorIds: ["tenderlab", "consultant"], trigger: "E02 bilingual award corpus", startDay: -111, endDay: -96, column: 2, lane: "tenderlab", critical: true, scopeBoundary: "Public relationship patterns support targeting only; beneficial ownership and conflicts require permitted evidence and human review.", missingAgentFinding: "Agent 19 becomes a primary analytical owner rather than a passive background feed." },
  { step: 4, period: "Day 0", phase: "Restricted invitation", title: "SentinelGrid receives the restricted tender invitation", initiator: "Buyer e-Procurement Portal", narrative: "The official invitation defines one lot, mandatory local security operator, sovereign hosting, clearance and 35-day final-offer clock. Discovery and Filtering test the opportunity against SentinelGrid; Match and Solution-Fit remain preliminary scores with explicit evidence denominators.", result: "Prioritised opportunity card: relevance 86/100 and preliminary solution fit 82/100.", next: "E05 requests a bounded company assessment mandate.", agentIds: [14, 16, 17, 31, 32], responsibleActorId: "buyer", actorIds: ["buyer", "client", "tenderlab"], kind: "external-event", trigger: "Official restricted invitation", startDay: 0, endDay: 0, column: 3, lane: "buyer", critical: true, scopeBoundary: "High fit is not Bid authority and does not validate the local operator.", missingAgentFinding: "No missing capability; score semantics remain separated." },
  { step: 5, period: "Day 1", phase: "Mandate", title: "SentinelGrid authorises tender-specific assessment only", initiator: "SentinelGrid Bid Director", narrative: "The company permits TenderLab to examine private capability and credential evidence and to research partner options. Contacting candidates, asking the Buyer questions and submitting a bid each require later human authority.", result: "Signed assessment mandate, access matrix and prohibited-action list.", next: "E06 verifies company readiness; E07 structures the invitation corpus in parallel.", agentIds: [1, 2, 4, 6], responsibleActorId: "client", actorIds: ["client", "consultant", "tenderlab"], kind: "decision", trigger: "E04 prioritised opportunity", startDay: 1, endDay: 1, column: 4, lane: "client", critical: true, scopeBoundary: "Assessment consent does not authorise partner outreach, clarification or bid submission.", missingAgentFinding: "No missing authority capability; human permission is explicit." },
  { step: 6, period: "Day 1–6", phase: "Company readiness", title: "Company, credentials and security capacity are verified", initiator: "SentinelGrid Compliance Lead", narrative: "Company Profile, Product & Capability, Verification, Readiness and Credential Agents check identity, managed-SOC references, ISO certificates, staffing and clearance evidence. Readiness is 78/100 because the local-operator requirement remains open; this is not the 86/100 Match score.", result: "Verified SentinelGrid profile, credential register and readiness 78/100 with two controlled gaps.", next: "E08 eligibility and E15 feasibility consume the verified baseline.", agentIds: [6, 7, 8, 9, 10, 3], responsibleActorId: "client", actorIds: ["client", "consultant", "tenderlab"], trigger: "E05 private-evidence mandate", startDay: 1, endDay: 6, column: 5, lane: "client", critical: true, scopeBoundary: "Agents verify evidence and gaps; national security clearance remains an external authority decision.", missingAgentFinding: "No missing company-readiness capability." },
  { step: 7, period: "Day 1–8", phase: "Tender model", title: "Invitation package becomes a governed requirement and evaluation model", initiator: "TenderLab / Document Intelligence", narrative: "Document, OCR, Structure, Requirement, Criteria, Forms, Fidelity and Legal Agents model security, data residency, local-operator lock, source-code escrow, evidence forms and evaluation logic. Pre-Bid Clarification logs ambiguity without interpreting law for the company.", result: "Source-locked corpus: 137 requirements, 24 forms, 11 security gates and 7 clarification candidates.", next: "E08 tests eligibility; E13 uses approved questions only.", agentIds: [21, 22, 23, 24, 26, 27, 28, 30, 57], responsibleActorId: "tenderlab", actorIds: ["client", "consultant", "tenderlab"], trigger: "E05 access + official invitation files", startDay: 1, endDay: 8, column: 5, lane: "tenderlab", critical: true, scopeBoundary: "Structured clauses are not legal advice; counsel owns legal interpretation and Client owns any clarification request.", missingAgentFinding: "Cyber/data-residency expertise remains human; a repeated gap is assessed later." },
  { step: 8, period: "Day 8–10", phase: "Qualification gate", title: "Eligibility confirms that a cleared local operator is mandatory", initiator: "SentinelGrid Bid Office", narrative: "Eligibility & Qualification tests 11 gates against the verified company and tender model. SentinelGrid passes nine; local operator and national incident-response accreditation are unmet but remediable only before the named-subcontractor deadline.", result: "Conditional eligibility: 9/11 passed, two linked local-operator gaps with Day 16 deadline.", next: "E09 opens a governed partner-search branch.", agentIds: [24, 25, 26, 30, 3, 4], responsibleActorId: "client", actorIds: ["client", "consultant", "tenderlab"], kind: "decision", trigger: "E06 verified company + E07 requirement model", startDay: 8, endDay: 10, column: 6, lane: "client", critical: true, scopeBoundary: "Conditional eligibility authorises remediation analysis, not partner selection or representation.", missingAgentFinding: "No missing qualification capability." },
  { step: 9, period: "Day 9–13", phase: "Partner search", title: "Local-operator candidates are shortlisted and outreach is approved", initiator: "TenderLab Consultant", narrative: "Partner Capability Graph, Discovery, Local Service, Supplier Discovery and Supplier Verification create a five-candidate longlist and three-candidate shortlist. Human Approval authorises bounded outreach only after purpose, data request and conflict questions are approved.", result: "Approved three-candidate local-operator shortlist and consent-safe outreach pack.", next: "E10 records candidate responses and permitted evidence.", agentIds: [2, 11, 12, 40, 42, 43, 44], responsibleActorId: "consultant", actorIds: ["client", "consultant", "tenderlab", "external"], trigger: "E08 local-operator gaps", startDay: 9, endDay: 13, column: 7, lane: "consultant", critical: true, scopeBoundary: "Agents rank and verify; Client authorises outreach and no Agent appoints a partner.", missingAgentFinding: "Partner ownership screening spans several Agents; boundary is tested at E11." },
  { step: 10, period: "Day 14", phase: "Partner consent", title: "CivicShield grants limited diligence consent", initiator: "CivicShield Security SRL Director", narrative: "The candidate independently agrees to a limited capability, ownership and conflict check and supplies signed declarations, licences and references. Other candidates remain unselected; no exclusivity or bid commitment exists.", result: "Consented partner dossier V1, stated UBO chain and permitted-use register.", next: "E11 verifies claims against independent sources.", agentIds: [2, 3, 4, 12, 44], responsibleActorId: "external", actorIds: ["external", "client", "consultant", "tenderlab"], kind: "external-event", trigger: "Human outreach under E09 approval", startDay: 14, endDay: 14, column: 8, lane: "external", critical: true, scopeBoundary: "Candidate consent permits diligence only; it is not selection, accusation or authority to share private data with the Buyer.", missingAgentFinding: "No missing consent record; cross-Actor data rights are explicit." },
  { step: 11, period: "Day 14–18", phase: "Integrity evidence", title: "Verification finds an undisclosed ownership and award-network conflict", initiator: "TenderLab Integrity Review", narrative: "Supplier Verification, Company Verification, Supplier/Award Intelligence and Knowledge Graph compare consented declarations with registries and award evidence. A beneficial owner is linked to the incumbent subcontract network and the disclosure is incomplete. Risk & Integrity marks HIGH risk; humans must investigate and decide meaning.", result: "Source-linked UBO/conflict evidence package, confidence levels and unresolved factual questions.", next: "E12 tests replacement/remediation; E16 receives the unresolved integrity package.", agentIds: [5, 8, 11, 12, 19, 38, 44, 3], responsibleActorId: "tenderlab", actorIds: ["client", "consultant", "tenderlab", "external"], trigger: "E10 consented dossier + independent registries/award records", startDay: 14, endDay: 18, column: 9, lane: "tenderlab", critical: true, scopeBoundary: "Agents surface evidence and inconsistency; authorised humans and competent bodies determine wrongdoing, conflict or exclusion.", missingAgentFinding: "Potential gap: no explicit Beneficial Ownership / Sanctions / Integrity Due Diligence Agent; Agent 38 is broad." },
  { step: 12, period: "Day 18–20", phase: "Route remediation", title: "Replacement, subcontract and JV routes are tested", initiator: "SentinelGrid Bid Director", narrative: "Participation Route, Gap Remediation, Execution Feasibility, Solution Architecture and Partner Discovery test replacement operator and delivery options. The tender locks the named operator on Day 16; JV & Consortium Optimization remains standby because the procedure does not permit conversion to a JV after that date.", result: "Route memo: technical delivery feasible, but partner replacement/JV route unavailable without Buyer relief.", next: "E13 asks a bounded clarification; E15 continues independent economics/feasibility.", agentIds: [33, 34, 36, 39, 40, 42], standbyAgentIds: [41], responsibleActorId: "client", actorIds: ["client", "consultant", "tenderlab"], trigger: "E11 high-risk partner evidence + Day 16 lock", startDay: 18, endDay: 20, column: 10, lane: "client", critical: true, scopeBoundary: "Agents test routes; only Buyer can relax rules and only Client can change partner/participation form.", missingAgentFinding: "No new Agent needed; JV/subcontract boundary is explicit." },
  { step: 13, period: "Day 20", phase: "Clarification authority", title: "Client approves and submits a bounded clarification", initiator: "SentinelGrid Authorised Signatory", narrative: "Pre-Bid Clarification and Legal Review prepare questions on operator substitution, disclosure cure, data access and source-code escrow. Human Approval checks wording and authority; the authorised signatory transmits through the portal.", result: "Official clarification request with receipt and no admission or allegation.", next: "E14 waits for the Buyer response; no proposal branch starts.", agentIds: [2, 30, 57, 4], responsibleActorId: "client", actorIds: ["client", "consultant", "buyer", "tenderlab"], kind: "external-event", trigger: "E12 bounded route memo", startDay: 20, endDay: 20, column: 11, lane: "client", critical: true, scopeBoundary: "Only Client signatory communicates; Agents neither negotiate nor accuse a third party.", missingAgentFinding: "No missing clarification capability." },
  { step: 14, period: "Day 24", phase: "Buyer answer", title: "Buyer declines post-deadline operator substitution", initiator: "Buyer Clarification Committee", narrative: "The official response confirms that the named local operator cannot be replaced after Day 16, source-code escrow remains mandatory and no bidder-specific conflict view will be provided. The answer changes neither evidence nor Client authority; it closes the only practical remediation route.", result: "Source-locked clarification response and closed replacement-route condition.", next: "E16 joins response, evidence and feasibility for the Board gate.", agentIds: [17, 30, 57, 3, 4], responsibleActorId: "buyer", actorIds: ["buyer", "client", "consultant", "tenderlab"], kind: "external-event", trigger: "E13 official clarification", startDay: 24, endDay: 24, column: 12, lane: "buyer", critical: true, scopeBoundary: "Buyer owns procedural answer; Agents record impact but do not reinterpret it as an exclusion decision.", missingAgentFinding: "No missing capability; negotiation is correctly not activated." },
  { step: 15, period: "Day 18–25", phase: "Independent fit/economics", title: "Technical feasibility and economics remain attractive despite integrity risk", initiator: "SentinelGrid Solution & Commercial Leads", narrative: "Match, Solution-Fit, Feasibility, Commercial Attractiveness and Solution Architecture validate a feasible sovereign SOC design and five-year economics. Risk & Integrity keeps integrity/data clauses separate. The case demonstrates that high fit and positive economics do not override a fatal governance condition.", result: "Technical feasibility 82/100, commercial attractiveness 74/100 and integrity risk 91/100 HIGH.", next: "E16 receives three separate decision dimensions.", agentIds: [31, 32, 36, 37, 38, 39], responsibleActorId: "client", actorIds: ["client", "consultant", "tenderlab"], trigger: "E06 company + E07 tender + E12 route assumptions", startDay: 18, endDay: 25, column: 12, lane: "client", critical: true, scopeBoundary: "Scores are decision inputs; they cannot authorise Bid, waive evidence or select a partner.", missingAgentFinding: "No missing scoring capability; denominators remain distinct." },
  { step: 16, period: "Day 27", phase: "No-Bid gate", title: "Board approves No-Bid before proposal production", initiator: "SentinelGrid Board", narrative: "Orchestrator assembles the decision pack; Evidence and Audit preserve sources/versions; Bid/No-Bid and Risk present options; Legal sets boundaries. The Board concludes that non-remediable partner disclosure and data/contract exposure exceed risk appetite despite attractive fit and economics.", result: "Signed No-Bid decision, reasons, approvers, retention instructions and zero-submission authority state.", next: "E17 freezes the bid branch; E18 awaits external procurement action.", agentIds: [1, 2, 3, 4, 35, 38, 57], responsibleActorId: "client", actorIds: ["client", "consultant", "tenderlab"], kind: "decision", trigger: "ALL: E11 evidence + E14 response + E15 fit/economics", startDay: 27, endDay: 27, column: 13, lane: "client", critical: true, scopeBoundary: "Only the Board decides No-Bid. Agents recommend, preserve evidence and enforce the resulting stop state.", missingAgentFinding: "Canonical No-Bid Agent is sufficient; integrity-investigation ownership remains a gap." },
  { step: 17, period: "Day 27–28", phase: "Controlled stop", title: "Proposal and submission branches are explicitly frozen", initiator: "TenderLab Orchestrator", narrative: "The Case state blocks compliance, pricing, proposal, QA, submission, post-bid, award and execution Agents. Deadline monitoring records withdrawal/no-submission status. No draft package is represented as a bid and no partner evidence is transmitted beyond authorised retention.", result: "No-submission freeze record, closed clocks and access-controlled evidence archive.", next: "E19 can close the Case only after external cancellation state is known.", agentIds: [1, 4, 17, 35], responsibleActorId: "tenderlab", actorIds: ["client", "consultant", "tenderlab"], trigger: "E16 signed No-Bid", startDay: 27, endDay: 28, column: 14, lane: "tenderlab", critical: true, scopeBoundary: "Stopped downstream Agents are not participants merely because their branch is displayed as blocked.", missingAgentFinding: "No missing stop-control capability; this Event validates honest non-participation." },
  { step: 18, period: "Day 63", phase: "External cancellation", title: "Financier review triggers official tender cancellation", initiator: "EU Programme Integrity Office / Buyer", narrative: "An external review independent of TenderLab leads the Buyer to cancel the procurement and announce a future clean reissue. Source Acquisition and Classification ingest the cancellation as a new publication type; triggered Amendment & Change closes the old tender state. This confirms but does not retroactively create the Board decision.", result: "Verified cancellation notice, closed tender version and future-reissue signal.", next: "E19 updates learning and controlled watch records.", agentIds: [13, 15, 17, 29, 3, 4], responsibleActorId: "buyer", actorIds: ["buyer", "external", "tenderlab"], kind: "external-event", trigger: "Official cancellation publication", startDay: 63, endDay: 63, column: 15, lane: "buyer", critical: true, scopeBoundary: "External bodies cancel/investigate; Agent 29 manages state change and never claims causal authority.", missingAgentFinding: "No missing cancellation capability; source-item and business classification remain separate." },
  { step: 19, period: "Day 64–66", phase: "Learning and handoff", title: "Case closes with a governed reissue watch", initiator: "TenderLab / SentinelGrid Review Panel", narrative: "Outcome Learning compares initial scores, partner evidence, Board decision and cancellation. Market, Award and Buyer Intelligence update reusable patterns without publishing private partner data. Knowledge Graph stores permitted relationships and a future reissue watch with explicit ownership.", result: "Closed Case 10 audit, verified No-Bid outcome, privacy-safe learning and reissue watch.", next: "Any future reissue starts a new Case; no Case 11 is created in this programme.", agentIds: [1, 4, 5, 18, 19, 20, 64], responsibleActorId: "tenderlab", actorIds: ["client", "consultant", "tenderlab"], trigger: "E17 stop state + E18 official cancellation", startDay: 64, endDay: 66, column: 16, lane: "tenderlab", critical: true, scopeBoundary: "Learning may reuse verified, permitted facts only; private diligence evidence follows the Board retention decision.", missingAgentFinding: "Final gap: no dedicated privacy/retention governance Agent; human data owner and platform policy remain explicit." },
];

export const case10RelationshipSpecs: Case10RelationshipSpec[] = [
  { from: 1, to: 2, label: "Source manifest", blocking: true }, { from: 2, to: 3, label: "Bilingual award corpus", blocking: true },
  { from: 3, to: 4, label: "Market and incumbent context", blocking: false }, { from: 4, to: 5, label: "Prioritised opportunity", blocking: true },
  { from: 5, to: 6, type: "branches-to", label: "Private company evidence", blocking: true }, { from: 5, to: 7, type: "branches-to", label: "Tender access", blocking: true },
  { from: 6, to: 8, type: "joins-at", label: "Verified company", blocking: true, joinPolicy: "ALL" }, { from: 7, to: 8, type: "joins-at", label: "Requirement model", blocking: true, joinPolicy: "ALL" },
  { from: 8, to: 9, label: "Local-operator gaps", blocking: true }, { from: 9, to: 10, type: "waits-for", label: "Human outreach + candidate consent", blocking: true },
  { from: 10, to: 11, label: "Permitted partner evidence", blocking: true }, { from: 11, to: 12, label: "High-risk evidence", blocking: true },
  { from: 12, to: 13, label: "Bounded questions", blocking: true }, { from: 13, to: 14, type: "waits-for", label: "Buyer response", blocking: true },
  { from: 12, to: 15, type: "branches-to", label: "Feasible solution/economics", blocking: false },
  { from: 11, to: 16, type: "joins-at", label: "Integrity evidence", blocking: true, joinPolicy: "ALL" },
  { from: 14, to: 16, type: "joins-at", label: "Closed remediation route", blocking: true, joinPolicy: "ALL" },
  { from: 15, to: 16, type: "joins-at", label: "Fit and economics", blocking: true, joinPolicy: "ALL" },
  { from: 16, to: 17, label: "Signed No-Bid", blocking: true }, { from: 17, to: 19, type: "joins-at", label: "Frozen branch", blocking: true, joinPolicy: "ALL" },
  { from: 18, to: 19, type: "joins-at", label: "Official cancellation", blocking: true, joinPolicy: "ALL" },
];

export const case10Processes: CaseProcess[] = [
  { id: "C10-P01", name: "Governance, authority, evidence and versions", ownerActorId: "tenderlab", agentIds: [1, 2, 3, 4], kind: "persistent", timing: "Day −120 to 66", trigger: "First official signal", purpose: "Preserve authority, provenance, versions and stop state.", inputs: [{ name: "Policy and Case state", sourceKind: "case-state", availability: "Always", blocking: true }], outputArtifactIds: ["c10-artifact-p01-governance"], consumerRefs: ["case10-activity-05", "case10-activity-16", "case10-activity-19"], blocking: true, state: "completed" },
  { id: "C10-P02", name: "Source, deadline and publication-type lifecycle", ownerActorId: "tenderlab", agentIds: [13, 15, 17, 21, 22, 29], kind: "persistent", timing: "Day −120 to 66", trigger: "PIN/RFI source", purpose: "Maintain raw source, OCR/translation, deadlines and cancellation/reissue state.", inputs: [{ name: "Official publications", sourceKind: "external", availability: "On publication", blocking: true }], outputArtifactIds: ["c10-artifact-p02-source"], consumerRefs: ["case10-activity-03", "case10-activity-08", "case10-activity-18"], blocking: true, state: "completed" },
  { id: "C10-P03", name: "Market, award, Buyer and graph intelligence", ownerActorId: "tenderlab", agentIds: [5, 11, 18, 19, 20], kind: "persistent", timing: "Day −112 to 66", trigger: "Source-locked award corpus", purpose: "Produce benchmark and relationship hypotheses without converting them into verified accusations.", inputs: [{ name: "Award and supplier records", sourceKind: "process", sourceRef: "C10-P02", availability: "After OCR/provenance", blocking: true }], outputArtifactIds: ["c10-artifact-p03-intelligence"], consumerRefs: ["case10-activity-04", "case10-activity-09", "case10-activity-19"], blocking: false, state: "completed" },
  { id: "C10-P04", name: "Company and credential readiness", ownerActorId: "client", agentIds: [6, 7, 8, 9, 10], kind: "case-scoped", timing: "Day 1–10", trigger: "Assessment mandate", purpose: "Maintain verified company, capability and security evidence.", inputs: [{ name: "Private company evidence", sourceKind: "actor", sourceRef: "client", availability: "After E05 mandate", blocking: true }], outputArtifactIds: ["c10-artifact-p04-company"], consumerRefs: ["case10-activity-08", "case10-activity-15"], blocking: true, state: "completed" },
  { id: "C10-P05", name: "Partner rights, capability and verification", ownerActorId: "consultant", agentIds: [2, 3, 11, 12, 40, 42, 43, 44], kind: "parallel", timing: "Day 9–20", trigger: "Conditional eligibility", purpose: "Separate discovery, consent, capability, verification and Client selection authority.", inputs: [{ name: "Partner requirement", sourceKind: "event", sourceRef: "case10-activity-08", availability: "Day 10", blocking: true }, { name: "Candidate consented dossier", sourceKind: "event", sourceRef: "case10-activity-10", availability: "Day 14", blocking: true }], outputArtifactIds: ["c10-artifact-p05-partner"], consumerRefs: ["case10-activity-11", "case10-activity-12"], blocking: true, state: "completed" },
  { id: "C10-P06", name: "Fit, feasibility, integrity and remediation", ownerActorId: "consultant", agentIds: [31, 32, 33, 34, 36, 37, 38, 39, 57], kind: "parallel", timing: "Day 14–27", trigger: "Verified company + tender + partner evidence", purpose: "Keep capability, economics, integrity and legal boundaries as separate decision dimensions.", inputs: [{ name: "Company and tender baselines", sourceKind: "case-state", availability: "Day 10", blocking: true }, { name: "Partner evidence", sourceKind: "process", sourceRef: "C10-P05", availability: "Day 18", blocking: true }], outputArtifactIds: ["c10-artifact-p06-decision-inputs"], consumerRefs: ["case10-activity-13", "case10-activity-16"], blocking: true, state: "completed" },
  { id: "C10-P07", name: "Bid-branch and no-submission state", ownerActorId: "client", agentIds: [1, 2, 4, 35], kind: "case-scoped", timing: "Day 27–28", trigger: "Board No-Bid", purpose: "Freeze downstream execution without assigning stopped Agents as participants.", inputs: [{ name: "Signed No-Bid", sourceKind: "event", sourceRef: "case10-activity-16", availability: "Day 27", blocking: true }], outputArtifactIds: ["c10-artifact-p07-stop"], consumerRefs: ["case10-activity-17", "case10-activity-19"], blocking: true, state: "completed" },
  { id: "C10-P08", name: "Outcome learning and reissue watch", ownerActorId: "tenderlab", agentIds: [5, 18, 19, 20, 64], kind: "persistent", timing: "Day 63 onward", trigger: "Official cancellation + frozen Case", purpose: "Create privacy-safe learning and future watch without reopening Case 10.", inputs: [{ name: "Terminal Case and cancellation", sourceKind: "event", sourceRef: "case10-activity-19", availability: "Day 66", blocking: true }], outputArtifactIds: ["c10-artifact-p08-learning"], consumerRefs: ["future-reissue-case"], blocking: false, state: "completed" },
];
