/** Results-only Stage 6 policy experiment. Default disconnected. */
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
import {executionAuthority,expectDenied,RESULT_TABLES} from './lib/tendermatch-dev-contract.mjs';
import {connectStage3} from './lib/tendermatch-eligibility-inputs.mjs';
import {TENANT,sha} from './lib/tendermatch-input-manifest.mjs';
import {stage5CodeIdentity} from './lib/tendermatch-stage5.mjs';
import {POLICIES,simulatePolicy} from '../packages/tendermatch/src/shortlist-stage6.ts';
import {BASE,TABLES,stage6CodeIdentity,createShortlistRun,prepareShortlistRun,loadContextCache,executeShortlist,completeShortlistRun,queryShortlist,selectedShortlistDetail,shortlistPageSpec} from './lib/tendermatch-stage6.mjs';
const root=new URL('../',import.meta.url);
export async function loadShortlistInputs(c){
 const proof=JSON.parse(await readFile(new URL('docs/evidence/tendermatch-stage5-execute.json',root),'utf8'));
 if(sha(proof.code)!==sha(await stage5CodeIdentity()))throw new Error('Approved Stage 5 code differs');
 const [run]=(await c.query(`SELECT r.*,c.outcome_hash,c.pair_count::int,c.zero_count::int FROM tendermatch_retrieval.ranking_run r JOIN tendermatch_retrieval.ranking_completion c USING(tenant_id,run_id) WHERE r.tenant_id=$1 AND r.run_id=$2`,[TENANT,proof.runId])).rows;
 if(!run||run.outcome_hash!==proof.execution.outcomeHash||run.pair_count!==707660||run.zero_count!==683653||sha(run.identity)!==proof.runId)throw new Error('Approved Stage 5 completion differs');
 const members=(await c.query(`SELECT kind,entity_id::text id,encode(profile_key,'hex') profile_key,encode(input_key,'hex') input_key FROM tendermatch_retrieval.ranking_member WHERE tenant_id=$1 AND run_id=$2 ORDER BY kind,entity_id`,[TENANT,run.run_id])).rows;
 const pairs=[],digest=createHash('sha256');let pages=0;const start=performance.now();
 for(const supplier of members.filter(m=>m.kind==='supplier')){let after=null;while(true){const rows=(await c.query(`SELECT p.supplier_id::text "supplierId",p.tender_id::text "tenderId",p.relevance_units units,p.limitation_mask mask,f.pair_score score,f.data_coverage coverage,f.evidence_confidence confidence,f.limitation FROM tendermatch_retrieval.ranking_pair p JOIN tendermatch_retrieval.ranking_member t ON t.tenant_id=p.tenant_id AND t.run_id=$2 AND t.kind='tender' AND t.profile_key=p.tender_profile JOIN tendermatch_retrieval.formula_pair f ON f.tenant_id=p.tenant_id AND f.policy_hash=p.formula_policy AND f.supplier_key=p.supplier_key AND f.tender_key=p.tender_key WHERE p.tenant_id=$1 AND p.method_hash=decode($3,'hex') AND p.formula_policy=decode($4,'hex') AND p.supplier_profile=decode($5,'hex') AND ($6::uuid IS NULL OR p.tender_id>$6::uuid) ORDER BY p.tender_id LIMIT 5000`,[TENANT,run.run_id,run.identity.methodHash,run.identity.formulaPolicy,supplier.profile_key,after])).rows;pages++;
  for(const p of rows){pairs.push(p);digest.update(JSON.stringify(p)+'\n');}if(pages%25===0)console.log(JSON.stringify({stage:6,phase:'read-only-projection',pages,rows:pairs.length}));if(rows.length<5000)break;after=rows.at(-1).tenderId;
 }}
 if(pairs.length!==707660||pairs.filter(p=>p.units>0).length!==24007)throw new Error('Shortlist candidate projection differs');
 return {rankingRunId:run.run_id,rankingIdentity:run.identity,rankingOutcomeHash:run.outcome_hash,members,pairs,inputHash:digest.digest('hex'),metrics:{elapsedMs:Math.round(performance.now()-start),pages}};
}
export async function protectedStage6State(c){
 const legacy={};for(const table of RESULT_TABLES.filter(t=>!['normalized_feature','schema_migration'].includes(t))){legacy[table]=(await c.query(`SELECT count(*)::int n FROM tendermatch_retrieval.${table}`)).rows[0].n;if(legacy[table])throw new Error('Unexpected prior model/human/legacy state');}
 const formula=(await c.query('SELECT run_id,outcome_hash,scored_count::text,unscored_count::text FROM tendermatch_retrieval.formula_completion ORDER BY run_id')).rows,ranking=(await c.query('SELECT run_id,outcome_hash,pair_count::text,zero_count::text FROM tendermatch_retrieval.ranking_completion ORDER BY run_id')).rows;
 const priorRows=(await c.query(`SELECT (SELECT count(*)::int FROM tendermatch_retrieval.formula_pair) formula,(SELECT count(*)::int FROM tendermatch_retrieval.ranking_pair) ranking,(SELECT count(*)::int FROM tendermatch_retrieval.ranking_profile) profiles`)).rows[0];return {legacy,formula,ranking,priorRows};
}
export async function stage6NegativeChecks(c,run){
 for(const table of TABLES){const [p]=(await c.query(`SELECT has_table_privilege(current_user,$1,'SELECT') s,has_table_privilege(current_user,$1,'INSERT') i,has_table_privilege(current_user,$1,'UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER') extra`,[`tendermatch_retrieval.${table}`])).rows;if(!p.s||!p.i||p.extra)throw new Error('Unsafe shortlist grants');for(const q of [`UPDATE tendermatch_retrieval.${table} SET tenant_id=tenant_id WHERE false`,`DELETE FROM tendermatch_retrieval.${table} WHERE false`,`TRUNCATE tendermatch_retrieval.${table}`])await expectDenied(c,q);}
 await expectDenied(c,'CREATE TABLE tendermatch_retrieval.stage6_forbidden(id int)');await expectDenied(c,'INSERT INTO tendermatch_retrieval.shortlist_member SELECT * FROM tendermatch_retrieval.shortlist_member LIMIT 1',['P0002','P0001']);
 await c.query('BEGIN');try{await c.query("SELECT set_config('tendermatch.tenant_id','stage6-other-tenant-probe',true)");for(const table of TABLES)if((await c.query(`SELECT count(*)::int n FROM tendermatch_retrieval.${table}`)).rows[0].n)throw new Error('Cross-tenant shortlist read');let code;try{await c.query(`INSERT INTO tendermatch_retrieval.shortlist_completion(tenant_id,run_id,outcome_hash,pair_count,review_count,audit_count) VALUES($1,$2,$3,0,0,0)`,[TENANT,run.runId,sha('probe')]);}catch(e){code=e.code;}if(!['42501','P0001'].includes(code))throw new Error('Cross-tenant shortlist write allowed');}finally{await c.query('ROLLBACK');}
 return {grants:'SELECT INSERT only',mutationsAndDdl:'denied',sealedMembership:'denied',crossTenantRead:'zero',crossTenantWrite:'denied',committedProbeRows:0,tenantBoundary:'TRUSTED_SERVICE_GUC_NOT_USER_AUTHENTICATION'};
}
async function queryEvidence(c,run){const report={};for(const direction of ['supplier','tender']){const counts=new Map();for(const p of run.pairs)counts.set(p[`${direction}Id`],(counts.get(p[`${direction}Id`])??0)+1);const [focusId,expected]=[...counts].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]))[0],started=performance.now(),page=await queryShortlist(c,run,{direction,focusId});report[direction]={focusId,defaultRows:page.results.length,bytes:Buffer.byteLength(JSON.stringify(page)),elapsedMs:Math.round(performance.now()-started)};
 for(const p of page.results){const d=await selectedShortlistDetail(c,run,p);if(sha(d.formula)!==sha(p.formula)||sha(d.shortlist)!==sha(p.shortlist)||d.criteria.reduce((sum,c)=>sum+c.points,0)!==p.formula.pairScore)throw new Error('Shortlist page/detail parity differs');}
 const seen=new Set();let cursor=null;do{const p=await queryShortlist(c,run,{direction,focusId,limit:100,cursor});for(const row of p.results){const key=row[direction==='supplier'?'tenderId':'supplierId'];if(seen.has(key))throw new Error('Duplicate shortlist keyset row');seen.add(key);}cursor=p.nextCursor;}while(cursor);if(seen.size!==expected)throw new Error('Incomplete shortlist traversal');report[direction].fullTraversal=seen.size;
 const spec=shortlistPageSpec(run,{direction,focusId});report[`${direction}Plan`]=(await c.query('EXPLAIN (ANALYZE,BUFFERS,FORMAT JSON) '+spec.text,spec.values)).rows[0]['QUERY PLAN'];}return report;}
export async function main(args=process.argv.slice(2)){
 const mode=args[0]??'plan';if(mode==='plan')return {stage:6,base:BASE,connects:false,ownerDdlAutomatic:false,modes:['compare','inspect','execute','replay']};
 if(!['compare','inspect','execute','replay'].includes(mode))throw new Error('Unknown Stage 6 mode');executionAuthority(args,process.env);
 const c=await connectStage3(),start=performance.now();let transaction=false;try{
  if(mode!=='execute'){await c.query('BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY');transaction=true;}
  const before=await protectedStage6State(c),loaded=await loadShortlistInputs(c),code=await stage6CodeIdentity(),availability=(await c.query("SELECT to_regclass('tendermatch_retrieval.shortlist_run')::text shortlist_run,current_database() database,current_user role")).rows[0];
  const run=createShortlistRun(loaded,code,{contextCache:availability.shortlist_run?await loadContextCache(c):[]});
  const report={stage:6,mode,base:BASE,code,runId:run.runId,identity:run.identity,availability,startedAt:new Date().toISOString(),protectedBefore:before,inputMetrics:loaded.metrics,extraction:run.extraction};
  if(['compare','inspect'].includes(mode)){
   report.evidenceClass='READ_ONLY_REAL_DATA_POLICY_COMPARISON';report.results=[];
   for(const policy of POLICIES){const begun=performance.now(),first=simulatePolicy(loaded.pairs,policy),replay=simulatePolicy([...loaded.pairs].reverse(),policy);if(first.summary.outcomeHash!==replay.summary.outcomeHash)throw new Error('Shortlist deterministic replay differs');report.results.push({...first.summary,elapsedMs:Math.round(performance.now()-begun),replayIdentical:true,samples:first.values.slice(0,3)});}
   const rerun=createShortlistRun({...loaded,pairs:[...loaded.pairs].reverse(),members:[...loaded.members].reverse()},code,{contextCache:run.contexts});if(rerun.runId!==run.runId||rerun.extraction.extracted)throw new Error('Shortlist context replay differs');report.reuse=rerun.extraction;
   report.incremental=[];for(const kind of ['supplier','tender']){const focus=loaded.members.find(m=>m.kind===kind&&loaded.pairs.some(p=>p[`${kind}Id`]===m.id));const nextLoaded={...loaded,members:loaded.members.map(m=>m===focus?{...m,profile_key:sha(['SIMULATED_PROFILE_IDENTITY_CHANGE',m.profile_key])}:m)},next=createShortlistRun(nextLoaded,code,{contextCache:run.contexts}),keys=new Set(run.pairs.map(p=>p.key));report.incremental.push({evidenceClass:'IN_MEMORY_IDENTITY_CHANGE_NOT_SOURCE_MUTATION',kind,focusId:focus.id,...next.extraction,unchangedPairIdentities:next.pairs.filter(p=>keys.has(p.key)).length,changedPairIdentities:next.pairs.filter(p=>!keys.has(p.key)).length,selectionCountsUnchanged:next.identity.selected===run.identity.selected,scope:'FOCUS_AND_INCIDENT_OPPOSITE_CONTEXTS_NO_CASCADE'});}
   report.payload={contextsBytes:Buffer.byteLength(JSON.stringify(run.contexts)),pairsBytes:Buffer.byteLength(JSON.stringify(run.pairs)),maxContextBytes:Math.max(...run.contexts.map(x=>Buffer.byteLength(JSON.stringify(x)))),estimateClass:'SERIALIZED_PAYLOAD_NOT_DATABASE_SIZE'};report.committedWrites=0;
   const selected=new Map(run.pairs.map(p=>[`${p.supplierId}:${p.tenderId}`,p])),seen=new Set();report.selectedSamples=[];
   for(const input of loaded.pairs){const p=selected.get(`${input.supplierId}:${input.tenderId}`);if(!p)continue;const stratum=`${p.tier}:${p.selection.reasonMask}:${input.score===0}:${input.coverage===0}:${Math.max(p.selection.supplierTieSize??0,p.selection.tenderTieSize??0)>1}`;if(!seen.has(stratum)&&report.selectedSamples.length<24){seen.add(stratum);report.selectedSamples.push({input,shortlist:{tier:p.tier===1?'REVIEW_CANDIDATE':'AUDIT_ONLY',...p.selection},aiAuthorized:false,onDemandEscalationEligible:true});}}
  }else{
   if(!availability.shortlist_run)throw new Error('Owner-only 090 migration required; writer must not execute DDL');
   if(mode==='execute')report.preparation=await prepareShortlistRun(c,run);report.execution=await executeShortlist(c,run,{readOnly:mode==='replay'});report.readback=await executeShortlist(c,run,{readOnly:true});if(report.execution.outcomeHash!==report.readback.outcomeHash)throw new Error('Shortlist full readback differs');
   if(mode==='execute'){report.completion=await completeShortlistRun(c,run);report.rerun=await executeShortlist(c,run);if(report.rerun.inserted||report.rerun.reused!==run.pairs.length)throw new Error('Shortlist cache replay differs');report.security=await stage6NegativeChecks(c,run);}
   report.queries=await queryEvidence(c,run);report.rows={};for(const table of TABLES)report.rows[table]=(await c.query(`SELECT count(*)::int n FROM tendermatch_retrieval.${table}`)).rows[0].n;
   report.storage=(await c.query(`SELECT c.relname table_name,pg_total_relation_size(c.oid)::text total_bytes,pg_relation_size(c.oid)::text heap_bytes FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='tendermatch_retrieval' AND c.relname=ANY($1::text[]) ORDER BY c.relname`,[TABLES])).rows;
  }
  report.protectedAfter=await protectedStage6State(c);if(sha(before)!==sha(report.protectedAfter))throw new Error('Protected prior-stage state changed');report.metrics={elapsedMs:Math.round(performance.now()-start),connection:c.metrics,memory:process.memoryUsage()};report.finishedAt=new Date().toISOString();report.sourceConnections=0;report.modelCalls=0;report.noFrontend=true;report.noDeployment=true;
  if(transaction){await c.query('ROLLBACK');transaction=false;}
  await mkdir(new URL('outputs/stage6/',root),{recursive:true});if(['compare','inspect'].includes(mode))await writeFile(new URL('outputs/stage6/frozen-inputs.json',root),JSON.stringify(loaded));await writeFile(new URL(`docs/evidence/tendermatch-stage6-${mode==='compare'?'comparison':mode}.json`,root),JSON.stringify(report,null,2)+'\n');return {runId:run.runId,identity:run.identity,extraction:run.extraction,results:report.results?.map(p=>Object.fromEntries(Object.entries(p).filter(([k])=>k!=='samples'))),rows:report.rows,metrics:report.metrics};
 }catch(e){if(transaction)await c.query('ROLLBACK');throw e;}finally{await c.end();}
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href)main().then(r=>console.log(JSON.stringify(r,null,2))).catch(e=>{console.error(JSON.stringify({status:'FAILED',message:e.message?.replace(/postgres(?:ql)?:\/\/\S+/gi,'[redacted]'),code:e.code??'STAGE6_FAILED'}));process.exitCode=1;});
