/** Default disconnected; Stage 7 experiment is read-only over sealed results. */
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import {executionAuthority,expectDenied} from './lib/tendermatch-dev-contract.mjs';
import {connectStage3} from './lib/tendermatch-eligibility-inputs.mjs';
import {protectedStage6State} from './tendermatch-stage6.mjs';
import {sha} from './lib/tendermatch-input-manifest.mjs';
import {TENANT} from './lib/tendermatch-input-manifest.mjs';
import {BUDGETS,planEscalations,assessmentInputIdentity,hash} from '../packages/tendermatch/src/escalation-stage7.ts';
import {BASE,root,LIMITS,providerInspection,stage7CodeIdentity,loadEscalationInputs,prepareEvidence} from './lib/tendermatch-stage7.mjs';
import {TABLES,createEscalationPlan,prepareEscalationPlan,automaticRequests,persistRequests,readDecisions,queryRequests,requestPageSpec,selectedEscalationPair} from './lib/tendermatch-stage7-queue.mjs';
import {requestEnvelope} from './lib/tendermatch-stage7-queue.mjs';
export async function protectedStage7State(c){return {prior:await protectedStage6State(c),shortlist:(await c.query('SELECT run_id,outcome_hash,pair_count::int,review_count::int,audit_count::int FROM tendermatch_retrieval.shortlist_completion ORDER BY run_id')).rows,shortlistRows:(await c.query('SELECT (SELECT count(*)::int FROM tendermatch_retrieval.shortlist_pair) pairs,(SELECT count(*)::int FROM tendermatch_retrieval.shortlist_context) contexts,(SELECT count(*)::int FROM tendermatch_retrieval.shortlist_member) members')).rows[0]};}
export async function stage7Security(c){const privileges=[];for(const table of TABLES){const [p]=(await c.query(`SELECT $1::text table_name,has_table_privilege(current_user,$1,'SELECT') s,has_table_privilege(current_user,$1,'INSERT') i,has_table_privilege(current_user,$1,'DELETE,TRUNCATE,REFERENCES,TRIGGER') extra,has_column_privilege(current_user,$1,'tenant_id','UPDATE') identity_update`,['tendermatch_retrieval.'+table])).rows;if(!p.s||p.i===['escalation_authorization','escalation_event'].includes(table)||p.extra||p.identity_update)throw new Error('Unsafe Stage 7 grant');privileges.push(p);await expectDenied(c,`DELETE FROM tendermatch_retrieval.${table} WHERE false`);await expectDenied(c,`TRUNCATE tendermatch_retrieval.${table}`);}
 await expectDenied(c,'CREATE TABLE tendermatch_retrieval.stage7_forbidden(id int)');await expectDenied(c,'INSERT INTO tendermatch_retrieval.escalation_decision SELECT * FROM tendermatch_retrieval.escalation_decision LIMIT 1',['P0002','P0001']);await expectDenied(c,'INSERT INTO tendermatch_retrieval.escalation_authorization(tenant_id) VALUES(\'forbidden\')');await expectDenied(c,'INSERT INTO tendermatch_retrieval.escalation_event(tenant_id) VALUES(\'forbidden\')');
 const [plan]=(await c.query('SELECT * FROM tendermatch_retrieval.escalation_plan WHERE tenant_id=$1 LIMIT 1',[TENANT])).rows;
 await c.query('BEGIN');try{await c.query("SELECT set_config('tendermatch.tenant_id','stage7-other-tenant',true)");for(const table of TABLES)if((await c.query(`SELECT count(*)::int n FROM tendermatch_retrieval.${table}`)).rows[0].n)throw new Error('Cross-tenant Stage7 read');let denied=false;try{await c.query('INSERT INTO tendermatch_retrieval.escalation_plan(tenant_id,plan_id,shortlist_run_id,identity) VALUES($1,$2,$3,$4)',[TENANT,hash('cross-tenant-denied-probe'),plan.shortlist_run_id,JSON.stringify(plan.identity)]);}catch(e){if(e.code!=='42501')throw e;denied=true;}if(!denied)throw new Error('Cross-tenant Stage7 write allowed');}finally{await c.query('ROLLBACK');}return {privileges,sealedPlans:'DENIED',ownerOnlyAuthorization:'DENIED_TO_WRITER',eventForgery:'DENIED',deleteTruncateDdl:'DENIED',crossTenantReads:0,crossTenantWrites:'DENIED',committedProbeRows:0,tenantBoundary:'TRUSTED_SERVICE_GUC_NOT_END_USER_AUTHENTICATION'};
}
export async function main(args=process.argv.slice(2)){
 const mode=args[0]??'plan';if(mode==='plan')return {stage:7,base:BASE,connects:false,providerExecutable:false,ownerDdlAutomatic:false,modes:['compare','execute','replay']};if(!['compare','execute','replay'].includes(mode))throw new Error('Unknown Stage 7 mode');executionAuthority(args,process.env);
 const c=await connectStage3(),start=performance.now();try{if(mode!=='execute')await c.query('BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY');const before=await protectedStage7State(c),loaded=await loadEscalationInputs(c),code=await stage7CodeIdentity(),provider=await providerInspection();
  const report={stage:7,mode,evidenceClass:mode==='compare'?'READ_ONLY_REAL_SHORTLIST_POLICY_COMPARISON':'GUARDED_RESULTS_ONLY_REQUEST_PERSISTENCE_NO_AI',base:BASE,code,provider,inputHash:loaded.inputHash,shortlistRunId:loaded.shortlistRunId,inputMetrics:loaded.metrics,protectedBefore:before,results:[],limits:LIMITS};
  if(mode==='compare'){
  for(const budget of BUDGETS){const began=performance.now(),first=planEscalations(loaded.rows,budget),again=planEscalations([...loaded.rows].reverse(),budget);if(first.summary.outcomeHash!==again.summary.outcomeHash)throw new Error('Allocation replay differs');report.results.push({...first.summary,budget,elapsedMs:Math.round(performance.now()-began),replayIdentical:true});}
  const selectedPlan=planEscalations(loaded.rows,BUDGETS[1]),selectedKeys=new Set(selectedPlan.rows.filter(p=>p.position!==null).map(p=>p.pairKey)),selected=loaded.rows.filter(p=>selectedKeys.has(p.pairKey)),evidence=await prepareEvidence(c,selected);
  const plan=createEscalationPlan(loaded,code),requests=selected.map((p,i)=>requestEnvelope(plan,p,evidence[i],{kind:'AUTOMATIC_REVIEW',actor:'VERSIONED_POLICY_NOT_USER_AUTHORIZATION'}));report.expectedPersistence={planId:plan.planId,identity:plan.identity,plans:1,decisions:plan.decisions.length,requests:requests.length,requestHash:hash(requests),authorizations:0,jobs:0,artifacts:0,events:0};
  report.chosen=selectedPlan.summary;report.population={formulaCandidates:707660,shortlist:28034,reviewTier:18531,auditTier:9503,selectedRequests:selected.length,onDemandFormulaCandidatePopulation:707660,automaticExecutionAuthorized:0,providerExecutable:0,actualCalls:0,actualInputTokens:0,actualOutputTokens:0,actualCost:0};
  report.workload={distinctSupplierProfiles:new Set(selected.map(p=>p.supplierProfile)).size,distinctTenderProfiles:new Set(selected.map(p=>p.tenderProfile)).size,inputBytes:evidence.reduce((n,p)=>n+p.bytes,0),maxInputBytes:Math.max(...evidence.map(p=>p.bytes)),potentialInitialCalls:selected.length,potentialCallsAtThreeAttempts:selected.length*LIMITS.attemptsPerJob,maxOutputTokenReservation:selected.length*LIMITS.outputTokens,inputTokenEstimate:null,costEstimate:null,limitation:'NO_PROVIDER_TOKENIZER_OR_PRICING_CONFIGURED_BYTE_COUNTS_ARE_NOT_TOKEN_COUNTS'};
  report.samples=selectedPlan.rows.filter(p=>p.position!==null).sort((a,b)=>a.position-b.position).slice(0,12).map(d=>({decision:d,input:loaded.rows.find(p=>p.pairKey===d.pairKey)}));
  const first=loaded.rows[0],prior=new Map(loaded.rows.map(p=>[p.pairKey,hash(assessmentInputIdentity(p))]));report.incremental=['supplier','tender'].map(kind=>{const field=`${kind}Id`,profile=`${kind}Profile`,changed=loaded.rows.map(p=>p[field]===first[field]?{...p,[profile]:hash(['SIMULATED_CHANGED_PROFILE',p[profile]])}:p);return {kind,focusId:first[field],evidenceClass:'IN_MEMORY_IDENTITY_CHANGE_ONLY',changedAssessmentIdentities:changed.filter(p=>prior.get(p.pairKey)!==hash(assessmentInputIdentity(p))).length,unchangedAssessmentIdentities:changed.filter(p=>prior.get(p.pairKey)===hash(assessmentInputIdentity(p))).length,scope:'ASSESSMENT_INPUT_PAIR_LOCAL_ALLOCATION_PLAN_MAY_REBALANCE'};});
  report.committedWrites=0;
  }else{
   const comparison=JSON.parse(await readFile(new URL('docs/evidence/tendermatch-stage7-comparison.json',root),'utf8'));if(sha(comparison.code)!==sha(code)||comparison.inputHash!==loaded.inputHash)throw new Error('Final real experiment binding differs');
   if(!(await c.query("SELECT to_regclass('tendermatch_retrieval.escalation_plan') relation")).rows[0].relation)throw new Error('Owner-only 100 migration required; writer cannot run DDL');
   const plan=createEscalationPlan(loaded,code),requests=await automaticRequests(c,plan,loaded);report.planId=plan.planId;report.identity=plan.identity;report.summary=plan.summary;if(mode==='execute')report.preparation=await prepareEscalationPlan(c,plan);report.decisions=await readDecisions(c,plan);report.execution=await persistRequests(c,requests,{readOnly:mode==='replay'});report.readback=await persistRequests(c,requests,{readOnly:true});report.replay=await persistRequests(c,requests,{readOnly:true});if(mode==='execute')report.security=await stage7Security(c);
   report.queries={};for(const direction of ['supplier','tender']){const counts=new Map();for(const r of requests)counts.set(r[`${direction}Id`],(counts.get(r[`${direction}Id`])??0)+1);const [focusId,expected]=[...counts].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]))[0],began=performance.now(),page=await queryRequests(c,plan,{direction,focusId}),spec=requestPageSpec(plan,{direction,focusId});report.queries[direction]={focusId,expected,rows:page.requests.length,bytes:Buffer.byteLength(JSON.stringify(page)),elapsedMs:Math.round(performance.now()-began),plan:(await c.query('EXPLAIN (ANALYZE,BUFFERS,FORMAT JSON) '+spec.text,spec.values)).rows[0]['QUERY PLAN']};}
   report.detail=await selectedEscalationPair(c,plan,requests[0]);report.rows={};for(const table of TABLES)report.rows[table]=(await c.query(`SELECT count(*)::int n FROM tendermatch_retrieval.${table}`)).rows[0].n;if(report.rows.escalation_request!==500||['escalation_authorization','escalation_job','escalation_artifact','escalation_event'].some(t=>report.rows[t]!==0))throw new Error('Unexpected request or AI/authorization population');report.storage=(await c.query(`SELECT relname table_name,pg_total_relation_size(oid)::text total_bytes,pg_relation_size(oid)::text heap_bytes FROM pg_class WHERE relnamespace='tendermatch_retrieval'::regnamespace AND relname=ANY($1::text[]) ORDER BY relname`,[TABLES])).rows;report.actual={modelCalls:0,inputTokens:0,outputTokens:0,cost:0,executionAuthorized:0,queuedExecutions:0,fullTorsArtifacts:0,providerBlocker:'UNCONFIGURED'};
  }
  report.protectedAfter=await protectedStage7State(c);if(sha(before)!==sha(report.protectedAfter))throw new Error('Protected state changed');report.metrics={elapsedMs:Math.round(performance.now()-start),connection:c.metrics,memory:process.memoryUsage()};report.finishedAt=new Date().toISOString();report.sourceConnections=0;report.modelCalls=0;
  if(mode!=='execute')await c.query('ROLLBACK');await mkdir(new URL('outputs/stage7/',root),{recursive:true});if(mode==='compare')await writeFile(new URL('outputs/stage7/frozen-inputs.json',root),JSON.stringify(loaded));await writeFile(new URL(`docs/evidence/tendermatch-stage7-${mode==='compare'?'comparison':mode}.json`,root),JSON.stringify(report,null,2)+'\n');return report;
 }finally{await c.end();}
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href)main().then(r=>console.log(JSON.stringify(r,null,2))).catch(e=>{console.error(JSON.stringify({status:'FAILED',message:e.message?.replace(/postgres(?:ql)?:\/\/\S+/gi,'[redacted]'),code:e.code??'STAGE7_FAILED'}));process.exitCode=1;});
