-- Generated by scripts/generate-tendermatch-stage8-reader-sql.mjs; do not edit.
-- Execute only inside a separately approved, attested owner transaction.
DO $$ BEGIN
 IF current_database()<>'tendermatch_results_dev' OR current_user<>'neondb_owner'
 OR current_setting('tendermatch.approved_branch_id',true) IS DISTINCT FROM 'br-polished-boat-b1qddx0m'
 OR (SELECT shobj_description(oid,'pg_database') FROM pg_database WHERE datname=current_database())
 IS DISTINCT FROM 'TenderMatch development result store; prepared contract 20260906; branch br-polished-boat-b1qddx0m'
 THEN RAISE EXCEPTION 'Stage 8 development target mismatch'; END IF;
END $$;
REVOKE tendermatch_stage8_reader FROM tendermatch_stage8_reader_dev; REVOKE CONNECT ON DATABASE tendermatch_results_dev FROM tendermatch_stage8_reader_dev;
DROP VIEW tendermatch_stage8_v1.escalation_artifact;
DROP VIEW tendermatch_stage8_v1.escalation_job;
DROP VIEW tendermatch_stage8_v1.escalation_authorization;
DROP VIEW tendermatch_stage8_v1.escalation_request;
DROP VIEW tendermatch_stage8_v1.escalation_decision;
DROP VIEW tendermatch_stage8_v1.escalation_plan;
DROP VIEW tendermatch_stage8_v1.shortlist_completion;
DROP VIEW tendermatch_stage8_v1.shortlist_pair;
DROP VIEW tendermatch_stage8_v1.shortlist_run;
DROP VIEW tendermatch_stage8_v1.ranking_profile;
DROP VIEW tendermatch_stage8_v1.formula_input;
DROP VIEW tendermatch_stage8_v1.ranking_completion;
DROP VIEW tendermatch_stage8_v1.ranking_pair;
DROP VIEW tendermatch_stage8_v1.ranking_member;
DROP VIEW tendermatch_stage8_v1.ranking_run;
DROP VIEW tendermatch_stage8_v1.formula_completion;
DROP VIEW tendermatch_stage8_v1.formula_pair;
DROP VIEW tendermatch_stage8_v1.formula_member;
DROP VIEW tendermatch_stage8_v1.formula_run;
DROP VIEW tendermatch_stage8_v1.eligibility_completion;
DROP VIEW tendermatch_stage8_v1.eligibility_pair;
DROP VIEW tendermatch_stage8_v1.eligibility_member;
DROP VIEW tendermatch_stage8_v1.eligibility_run;
DROP VIEW tendermatch_stage8_v1.schema_migration;
REVOKE USAGE ON SCHEMA tendermatch_stage8_v1 FROM tendermatch_stage8_reader; DROP SCHEMA tendermatch_stage8_v1; DROP ROLE tendermatch_stage8_reader_dev; DROP ROLE tendermatch_stage8_reader;
