import type { ActorType, Directness, TenderSide } from "../../catalog-schema/src";

const updatedAt = "2026-08-22";
const version = "1.0.0-draft";

type ActorSeed = Omit<ActorType, "catalogue" | "status" | "version" | "aliases" | "sourceRefs" | "updatedAt"> & {
  aliases?: string[];
};

const actor = (seed: ActorSeed): ActorType => ({
  catalogue: "actor-types",
  status: "draft",
  version,
  aliases: [],
  sourceRefs: [],
  updatedAt,
  ...seed,
});

export const actorTypes: ActorType[] = [
  actor({ id: "actor-type:TEA-AT-PROCURING-ENTITY", slug: "procuring-entity", name: { en: "Procuring Entity", ru: "Закупающая организация" }, summary: "Организация, формально проводящая закупку.", sideIds: ["side:TEA-S01"], directness: "direct", represents: "Публичного или частного покупателя", role: "Инициирует и администрирует процедуру, заключает контракт.", stages: ["Planning", "Tender", "Evaluation", "Award", "Contract"], authority: "A5", contractualPosition: "Заказчик или contracting authority", typicalInputs: ["Потребность", "Бюджет", "Правила закупки"], typicalOutputs: ["Тендер", "Решение о присуждении", "Контракт"] }),
  actor({ id: "actor-type:TEA-AT-PROCUREMENT-UNIT", slug: "procurement-unit", name: { en: "Procurement Unit", ru: "Закупочное подразделение" }, summary: "Профессионально организует и документирует процедуру.", sideIds: ["side:TEA-S01"], directness: "direct", represents: "Procuring Entity", role: "Готовит процедуру, публикации, разъяснения и административный record.", stages: ["Planning", "Tender", "Evaluation", "Award"], authority: "A3", contractualPosition: "Внутреннее подразделение заказчика", typicalInputs: ["Procurement plan", "Specification", "Approvals"], typicalOutputs: ["Notice", "Tender dossier", "Procedure record"] }),
  actor({ id: "actor-type:TEA-AT-PROJECT-OWNER", slug: "project-owner", name: { en: "Project Owner / Sponsor", ru: "Владелец или спонсор проекта" }, summary: "Определяет бизнес-потребность, ожидаемый результат и финансирование проекта.", sideIds: ["side:TEA-S01"], directness: "context-dependent", represents: "Организацию-владельца результата", role: "Устанавливает цели, бюджет и ключевые project constraints.", stages: ["Project", "Planning", "Approval", "Implementation"], authority: "A4", contractualPosition: "Может совпадать или не совпадать с Procuring Entity", typicalInputs: ["Project mandate", "Funding envelope"], typicalOutputs: ["Approved need", "Project scope", "Outcome criteria"] }),
  actor({ id: "actor-type:TEA-AT-EVALUATION-COMMITTEE", slug: "evaluation-committee", name: { en: "Evaluation Committee", ru: "Оценочная комиссия" }, summary: "Оценивает заявки по заранее установленным критериям.", sideIds: ["side:TEA-S01"], directness: "direct", represents: "Procuring Entity", role: "Проверяет допуск, техническую и финансовую часть, документирует выводы.", stages: ["Evaluation", "Clarification", "Recommendation"], authority: "A4", contractualPosition: "Назначенный коллегиальный орган", typicalInputs: ["Bids", "Evaluation criteria", "Clarifications"], typicalOutputs: ["Evaluation report", "Award recommendation"] }),
  actor({ id: "actor-type:TEA-AT-APPROVING-AUTHORITY", slug: "approving-authority", name: { en: "Approving Authority", ru: "Утверждающий орган" }, summary: "Формально утверждает решения, выходящие за делегированные полномочия.", sideIds: ["side:TEA-S01"], directness: "direct", represents: "Государство, board или senior management", role: "Даёт approval/no-objection на ключевых контрольных точках.", stages: ["Planning", "Award", "Contract amendment"], authority: "A5", contractualPosition: "Внешний или внутренний контроль", typicalInputs: ["Decision memo", "Evaluation report", "Risk record"], typicalOutputs: ["Approval", "Rejection", "Conditions"] }),
  actor({ id: "actor-type:TEA-AT-CENTRAL-PURCHASING-BODY", slug: "central-purchasing-body", name: { en: "Central Purchasing Body", ru: "Централизованный закупочный орган" }, summary: "Закупает от имени нескольких организаций или управляет framework agreements.", sideIds: ["side:TEA-S01"], directness: "direct", represents: "Группу публичных заказчиков", role: "Консолидирует спрос и проводит централизованные процедуры.", stages: ["Planning", "Tender", "Award", "Framework management"], authority: "A5", contractualPosition: "Заказчик, агент или framework manager", typicalInputs: ["Aggregated demand", "Mandates"], typicalOutputs: ["Framework", "Call-off rules", "Supplier panel"] }),
  actor({ id: "actor-type:TEA-AT-PROCUREMENT-AGENT", slug: "procurement-agent", name: { en: "Procurement Agent", ru: "Закупочный агент" }, summary: "Проводит процедуру по поручению другой организации.", sideIds: ["side:TEA-S01", "side:TEA-S03"], directness: "context-dependent", represents: "Project Owner или Procuring Entity", role: "Администрирует закупку в пределах делегированного мандата.", stages: ["Planning", "Tender", "Evaluation", "Award"], authority: "A3", contractualPosition: "Агентский или consultancy contract", typicalInputs: ["Delegation", "Procurement rules", "Scope"], typicalOutputs: ["Managed procedure", "Compliance record", "Recommendation"], participationNote: "Может быть прямым администратором либо внешним консультантом без decision authority." }),

  actor({ id: "actor-type:TEA-AT-BIDDER", slug: "bidder", name: { en: "Bidder / Tenderer", ru: "Участник тендера" }, summary: "Формально подаёт заявку или предложение.", sideIds: ["side:TEA-S02"], directness: "direct", represents: "Себя, JV или consortium", role: "Принимает условия процедуры и конкурирует за контракт.", stages: ["Registration", "Tender", "Clarification", "Award"], authority: "A1", contractualPosition: "Potential contractor", typicalInputs: ["Tender dossier", "Clarifications"], typicalOutputs: ["Bid", "Evidence", "Price"] }),
  actor({ id: "actor-type:TEA-AT-SUPPLIER", slug: "supplier", name: { en: "Supplier", ru: "Поставщик" }, summary: "Поставляет товары по контракту или через другого участника.", sideIds: ["side:TEA-S02"], directness: "context-dependent", represents: "Коммерческую supply organization", role: "Обеспечивает товары, warranties и related services.", stages: ["Tender", "Contract", "Delivery", "Warranty"], authority: "A1", contractualPosition: "Prime supplier, subcontractor или upstream supplier", typicalInputs: ["Specification", "Order", "Delivery schedule"], typicalOutputs: ["Goods", "Certificates", "Warranty"] }),
  actor({ id: "actor-type:TEA-AT-CONTRACTOR", slug: "contractor", name: { en: "Contractor", ru: "Подрядчик" }, summary: "Выполняет works или комплексное contractual scope.", sideIds: ["side:TEA-S02", "side:TEA-S03"], directness: "direct", represents: "Contracted delivery organization", role: "Исполняет работы, управляет ресурсами и отвечает за результат.", stages: ["Contract", "Mobilization", "Implementation", "Handover"], authority: "A2", contractualPosition: "Prime contractor", typicalInputs: ["Contract", "Design", "Site access"], typicalOutputs: ["Works", "Progress records", "Handover package"] }),
  actor({ id: "actor-type:TEA-AT-CONSULTANT-BIDDER", slug: "consultant-bidder", name: { en: "Consultant as Bidder", ru: "Консультант как участник" }, summary: "Конкурирует за consulting-services contract.", sideIds: ["side:TEA-S02"], directness: "direct", represents: "Consulting firm или individual consultant", role: "Предлагает методологию, команду, сроки и fee.", stages: ["EOI", "Shortlist", "RFP", "Negotiation"], authority: "A1", contractualPosition: "Potential consultant", typicalInputs: ["TOR", "RFP", "Evaluation method"], typicalOutputs: ["Technical proposal", "Financial proposal", "CVs"] }),
  actor({ id: "actor-type:TEA-AT-MANUFACTURER", slug: "manufacturer-oem", name: { en: "Manufacturer / OEM", ru: "Производитель / OEM" }, summary: "Производит товары, оборудование или proprietary solution components.", sideIds: ["side:TEA-S02"], directness: "context-dependent", represents: "Производственную организацию", role: "Подтверждает product origin, capacity, compliance и warranty.", stages: ["Market", "Tender", "Production", "Warranty"], authority: "A1", contractualPosition: "Bidder, supplier или upstream manufacturer", typicalInputs: ["Specification", "Forecast", "Order"], typicalOutputs: ["Product", "Technical data", "Manufacturer authorization"] }),
  actor({ id: "actor-type:TEA-AT-DISTRIBUTOR", slug: "distributor-dealer", name: { en: "Distributor / Dealer", ru: "Дистрибьютор / дилер" }, summary: "Коммерчески поставляет товары производителя на определённой территории.", sideIds: ["side:TEA-S02"], directness: "context-dependent", represents: "Manufacturer channel или собственную компанию", role: "Обеспечивает sourcing, stock, local sales и service interface.", stages: ["Market", "Tender", "Delivery", "Warranty"], authority: "A1", contractualPosition: "Bidder, reseller или subcontractor", typicalInputs: ["OEM authorization", "Price list", "Demand"], typicalOutputs: ["Offer", "Delivery commitment", "Local warranty"] }),
  actor({ id: "actor-type:TEA-AT-JV-CONSORTIUM", slug: "joint-venture-consortium", name: { en: "Joint Venture / Consortium", ru: "Совместное предприятие / консорциум" }, summary: "Временная или зарегистрированная группа, подающая совместную заявку.", sideIds: ["side:TEA-S02"], directness: "direct", represents: "Совокупность участников", role: "Объединяет qualification, capacity и contractual responsibility.", stages: ["Formation", "Tender", "Contract", "Implementation"], authority: "A2", contractualPosition: "Joint bidder/contractor", typicalInputs: ["Member capabilities", "JV agreement", "Workshare"], typicalOutputs: ["Joint bid", "Combined evidence", "Joint delivery"] }),
  actor({ id: "actor-type:TEA-AT-CONSORTIUM-MEMBER", slug: "consortium-member", name: { en: "JV / Consortium Member", ru: "Участник консорциума" }, summary: "Вносит определённую компетенцию, опыт или ресурс в совместную заявку.", sideIds: ["side:TEA-S02"], directness: "direct", represents: "Собственную организацию внутри group bid", role: "Принимает workshare и совместную или раздельную ответственность.", stages: ["Formation", "Tender", "Implementation"], authority: "A1", contractualPosition: "Member under JV/consortium agreement", typicalInputs: ["Workshare", "Qualification requirements"], typicalOutputs: ["Member evidence", "Assigned deliverables"] }),
  actor({ id: "actor-type:TEA-AT-SUBCONTRACTOR", slug: "subcontractor", name: { en: "Subcontractor", ru: "Субподрядчик" }, summary: "Выполняет часть scope под управлением prime contractor.", sideIds: ["side:TEA-S02", "side:TEA-S03"], directness: "context-dependent", represents: "Собственную specialist organization", role: "Предоставляет специализированные works, goods или services.", stages: ["Tender", "Implementation", "Handover"], authority: "A1", contractualPosition: "Contract with prime; иногда nominated subcontractor", typicalInputs: ["Subcontract scope", "Programme", "Standards"], typicalOutputs: ["Specialist deliverable", "Certificates", "Progress evidence"] }),
  actor({ id: "actor-type:TEA-AT-LOCAL-PARTNER", slug: "local-partner", name: { en: "Local Partner / Representative", ru: "Локальный партнёр / представитель" }, summary: "Обеспечивает local presence, service, licensing или market access.", sideIds: ["side:TEA-S02", "side:TEA-S03"], directness: "context-dependent", represents: "Foreign bidder или local delivery entity", role: "Закрывает территориальные, сервисные и административные требования.", stages: ["Tender", "Mobilization", "Delivery", "Warranty"], authority: "A1", contractualPosition: "Agent, partner, subcontractor или consortium member", typicalInputs: ["Territory scope", "Service levels"], typicalOutputs: ["Local coverage", "Permits", "After-sales service"] }),

  actor({ id: "actor-type:TEA-AT-ENGINEER", slug: "engineer-supervision-consultant", name: { en: "Engineer / Supervision Consultant", ru: "Инженер / консультант по надзору" }, summary: "Контролирует техническое исполнение и подтверждает contract milestones.", sideIds: ["side:TEA-S03"], directness: "context-dependent", represents: "Employer/Project Owner при сохранении профессиональной независимости", role: "Проверяет quality, progress, measurements и change requests.", stages: ["Design review", "Implementation", "Acceptance"], authority: "A3", contractualPosition: "Consultancy contract; иногда named Engineer", typicalInputs: ["Design", "Contract", "Site records"], typicalOutputs: ["Instructions", "Certificates", "Progress assessments"] }),
  actor({ id: "actor-type:TEA-AT-DESIGNER", slug: "designer", name: { en: "Designer", ru: "Проектировщик" }, summary: "Создаёт или адаптирует design и technical documentation.", sideIds: ["side:TEA-S03"], directness: "context-dependent", represents: "Project Owner, contractor или отдельного consultant", role: "Определяет design intent и выпускает drawings/specifications.", stages: ["Preparation", "Tender", "Implementation"], authority: "A2", contractualPosition: "Consultant, subcontractor или design-build member", typicalInputs: ["Brief", "Site data", "Standards"], typicalOutputs: ["Design", "Drawings", "Technical specifications"] }),
  actor({ id: "actor-type:TEA-AT-PMC", slug: "project-management-consultant", name: { en: "Project Management Consultant", ru: "Консультант по управлению проектом" }, summary: "Координирует scope, time, cost, risk и reporting.", sideIds: ["side:TEA-S03"], directness: "indirect", represents: "Project Owner", role: "Интегрирует delivery workstreams без обязательного award authority.", stages: ["Planning", "Procurement", "Implementation", "Closeout"], authority: "A2", contractualPosition: "Consultancy contract", typicalInputs: ["Project plan", "Contracts", "Progress data"], typicalOutputs: ["Integrated schedule", "Risk report", "Management actions"] }),
  actor({ id: "actor-type:TEA-AT-CONTRACT-ADMINISTRATOR", slug: "contract-administrator", name: { en: "Contract Administrator", ru: "Администратор контракта" }, summary: "Ведёт formal notices, variations, payments и contractual record.", sideIds: ["side:TEA-S03"], directness: "direct", represents: "Сторону, назначившую администратора", role: "Обеспечивает procedural administration после award.", stages: ["Contract", "Implementation", "Closeout"], authority: "A3", contractualPosition: "Internal role или consultant", typicalInputs: ["Contract", "Claims", "Progress certificates"], typicalOutputs: ["Notices", "Variation record", "Payment recommendation"] }),
  actor({ id: "actor-type:TEA-AT-LOGISTICS-PROVIDER", slug: "logistics-provider", name: { en: "Logistics Provider", ru: "Логистический провайдер" }, summary: "Организует перевозку, customs handling, storage и last mile.", sideIds: ["side:TEA-S03"], directness: "indirect", represents: "Supplier/contractor или buyer", role: "Исполняет физическое перемещение и delivery evidence.", stages: ["Planning", "Shipment", "Delivery"], authority: "A0", contractualPosition: "Service provider или subcontractor", typicalInputs: ["Cargo data", "Incoterms", "Schedule"], typicalOutputs: ["Transport plan", "Shipping documents", "Proof of delivery"] }),
  actor({ id: "actor-type:TEA-AT-INSPECTION-BODY", slug: "inspection-testing-body", name: { en: "Inspection / Testing Body", ru: "Инспекционный / испытательный орган" }, summary: "Независимо или по контракту проверяет product, works или materials.", sideIds: ["side:TEA-S03", "side:TEA-S05"], directness: "context-dependent", represents: "Назначившую сторону или accredited conformity system", role: "Проводит tests, inspection и conformity verification.", stages: ["Production", "Delivery", "Acceptance"], authority: "A2", contractualPosition: "Independent service provider", typicalInputs: ["Specification", "Samples", "Inspection plan"], typicalOutputs: ["Test report", "Inspection certificate", "Non-conformity"] }),
  actor({ id: "actor-type:TEA-AT-INSTALLATION-SERVICE", slug: "installation-service-provider", name: { en: "Installation / Service Provider", ru: "Монтажная / сервисная организация" }, summary: "Выполняет installation, commissioning и after-sales support.", sideIds: ["side:TEA-S03"], directness: "indirect", represents: "Supplier или contractor", role: "Обеспечивает локальное завершение и эксплуатационную готовность.", stages: ["Delivery", "Installation", "Warranty"], authority: "A0", contractualPosition: "Subcontractor или service partner", typicalInputs: ["Installation plan", "Site access", "Product manuals"], typicalOutputs: ["Installed asset", "Commissioning record", "Service response"] }),

  actor({ id: "actor-type:TEA-AT-DEVELOPMENT-BANK", slug: "financing-institution-development-bank", name: { en: "Financing Institution / Development Bank", ru: "Финансирующая организация / банк развития" }, summary: "Финансирует проект и устанавливает применимые procurement conditions.", sideIds: ["side:TEA-S04"], directness: "direct", represents: "Собственный financing mandate", role: "Одобряет финансирование, procurement framework и отдельные no-objection points.", stages: ["Project", "Planning", "Tender", "Award", "Implementation"], authority: "A5", contractualPosition: "Financing agreement, не обязательно procurement contract", typicalInputs: ["Project proposal", "Procurement plan", "Reports"], typicalOutputs: ["Financing", "No-objection", "Supervision findings"] }),
  actor({ id: "actor-type:TEA-AT-BANK-GUARANTOR", slug: "bank-guarantor", name: { en: "Bank / Guarantor", ru: "Банк / гарант" }, summary: "Выдаёт bid, performance, advance-payment и payment guarantees.", sideIds: ["side:TEA-S04"], directness: "context-dependent", represents: "Bidder, contractor или buyer", role: "Принимает финансовое обязательство при наступлении guarantee conditions.", stages: ["Tender", "Contract", "Implementation"], authority: "A1", contractualPosition: "Independent guarantee или banking contract", typicalInputs: ["Guarantee request", "Credit assessment", "Tender wording"], typicalOutputs: ["Guarantee", "Amendment", "Claim payment"] }),
  actor({ id: "actor-type:TEA-AT-INSURER", slug: "insurer", name: { en: "Insurer", ru: "Страховщик" }, summary: "Покрывает указанные contract, cargo, liability или project risks.", sideIds: ["side:TEA-S04"], directness: "indirect", represents: "Застрахованную сторону", role: "Андеррайтит риск и урегулирует покрываемые claims.", stages: ["Tender", "Contract", "Implementation"], authority: "A1", contractualPosition: "Insurance policy", typicalInputs: ["Risk data", "Contract", "Claims"], typicalOutputs: ["Policy", "Certificate", "Claim decision"] }),
  actor({ id: "actor-type:TEA-AT-EXPORT-CREDIT-AGENCY", slug: "export-credit-agency", name: { en: "Export Credit Agency", ru: "Экспортно-кредитное агентство" }, summary: "Поддерживает экспортное финансирование, гарантию или страхование политических рисков.", sideIds: ["side:TEA-S04"], directness: "indirect", represents: "Государственную export-support policy", role: "Снижает financial/political risk международной поставки.", stages: ["Bid preparation", "Financing", "Contract"], authority: "A2", contractualPosition: "Finance, guarantee или insurance instrument", typicalInputs: ["Export contract", "Country risk", "Applicant data"], typicalOutputs: ["Coverage decision", "Guarantee", "Financing terms"] }),
  actor({ id: "actor-type:TEA-AT-TREASURY-PAYMENT-AUTHORITY", slug: "treasury-payment-authority", name: { en: "Treasury / Payment Authority", ru: "Казначейство / платёжный орган" }, summary: "Осуществляет или контролирует бюджетные платежи.", sideIds: ["side:TEA-S04"], directness: "context-dependent", represents: "Государство или Project Owner", role: "Проверяет payment authority и проводит disbursement.", stages: ["Contract", "Payment", "Closeout"], authority: "A4", contractualPosition: "Statutory/payment function", typicalInputs: ["Invoice", "Certificate", "Budget authorization"], typicalOutputs: ["Payment", "Rejection", "Ledger entry"] }),

  actor({ id: "actor-type:TEA-AT-REGULATOR", slug: "government-regulator", name: { en: "Government / Regulator", ru: "Государственный орган / регулятор" }, summary: "Устанавливает обязательные legal, sector или market-access rules.", sideIds: ["side:TEA-S05"], directness: "context-dependent", represents: "Государство и statutory mandate", role: "Регулирует, лицензирует, расследует или применяет меры enforcement.", stages: ["All lifecycle", "Licensing", "Enforcement"], authority: "A5", contractualPosition: "Нет procurement contract", typicalInputs: ["Law", "Applications", "Reports"], typicalOutputs: ["Rule", "Licence", "Enforcement decision"] }),
  actor({ id: "actor-type:TEA-AT-AUDITOR", slug: "auditor", name: { en: "Auditor", ru: "Аудитор" }, summary: "Проверяет финансовую, procedural или performance integrity.", sideIds: ["side:TEA-S05"], directness: "indirect", represents: "Назначивший oversight body или public interest", role: "Собирает evidence и формирует независимые findings.", stages: ["Tender review", "Implementation", "Post-award"], authority: "A3", contractualPosition: "Statutory mandate или audit engagement", typicalInputs: ["Records", "Transactions", "Policies"], typicalOutputs: ["Audit report", "Findings", "Recommendations"] }),
  actor({ id: "actor-type:TEA-AT-INDEPENDENT-MONITOR", slug: "independent-monitor", name: { en: "Independent Monitor / Observer", ru: "Независимый наблюдатель" }, summary: "Наблюдает за fairness, integrity или implementation без управления процедурой.", sideIds: ["side:TEA-S05"], directness: "indirect", represents: "Oversight mandate или public interest", role: "Документирует наблюдения и red flags.", stages: ["Tender", "Evaluation", "Implementation"], authority: "A1", contractualPosition: "Appointment, mandate или consultancy", typicalInputs: ["Procedure access", "Records"], typicalOutputs: ["Monitoring report", "Escalation"] }),
  actor({ id: "actor-type:TEA-AT-REVIEW-BODY", slug: "complaint-review-body", name: { en: "Complaint / Review Body", ru: "Орган рассмотрения жалоб" }, summary: "Рассматривает procurement complaints и назначает remedies.", sideIds: ["side:TEA-S05"], directness: "direct", represents: "Statutory review system", role: "Проверяет законность решений и может приостановить или отменить их.", stages: ["Tender", "Evaluation", "Award"], authority: "A5", contractualPosition: "Нет procurement contract", typicalInputs: ["Complaint", "Procedure record", "Responses"], typicalOutputs: ["Review decision", "Remedy", "Dismissal"] }),
  actor({ id: "actor-type:TEA-AT-COURT-ARBITRATOR", slug: "court-arbitrator", name: { en: "Court / Arbitrator", ru: "Суд / арбитр" }, summary: "Разрешает правовые и contractual disputes.", sideIds: ["side:TEA-S05"], directness: "context-dependent", represents: "Judicial system или agreed dispute mechanism", role: "Выносит binding или enforceable decision.", stages: ["Complaint", "Contract", "Post-award"], authority: "A5", contractualPosition: "Judicial/statutory либо arbitration agreement", typicalInputs: ["Claims", "Evidence", "Contract"], typicalOutputs: ["Judgment", "Award", "Interim measure"] }),
  actor({ id: "actor-type:TEA-AT-INTEGRITY-BODY", slug: "integrity-anti-corruption-body", name: { en: "Integrity / Anti-Corruption Body", ru: "Орган по добросовестности / противодействию коррупции" }, summary: "Расследует fraud, corruption, collusion и prohibited practices.", sideIds: ["side:TEA-S05"], directness: "indirect", represents: "Government, financier или institutional integrity mandate", role: "Проводит investigation и инициирует sanctions/remedies.", stages: ["All lifecycle", "Investigation", "Sanctions"], authority: "A5", contractualPosition: "Нет procurement contract", typicalInputs: ["Allegation", "Records", "Interviews"], typicalOutputs: ["Investigation finding", "Referral", "Sanction recommendation"] }),

  actor({ id: "actor-type:TEA-AT-BENEFICIARY", slug: "beneficiary-end-user", name: { en: "Beneficiary / End User", ru: "Бенефициар / конечный пользователь" }, summary: "Получает или использует результат проекта и закупки.", sideIds: ["side:TEA-S06"], directness: "context-dependent", represents: "Целевую группу или operating organization", role: "Формирует user needs, принимает или оценивает practical outcome.", stages: ["Needs", "Design", "Testing", "Operation"], authority: "A1", contractualPosition: "Обычно отсутствует", typicalInputs: ["Service need", "User experience"], typicalOutputs: ["Requirements feedback", "Acceptance feedback", "Outcome evidence"] }),
  actor({ id: "actor-type:TEA-AT-COMMUNITY-CSO", slug: "community-civil-society", name: { en: "Community / Civil Society Organization", ru: "Сообщество / общественная организация" }, summary: "Представляет общественные интересы, affected groups или transparency concerns.", sideIds: ["side:TEA-S06"], directness: "indirect", represents: "Community или public interest", role: "Участвует в consultation, monitoring и grievance processes.", stages: ["Project", "Consultation", "Implementation"], authority: "A0", contractualPosition: "Обычно отсутствует", typicalInputs: ["Public information", "Community impact"], typicalOutputs: ["Feedback", "Grievance", "Monitoring observation"] }),
  actor({ id: "actor-type:TEA-AT-MEDIA-RESEARCHER", slug: "media-researcher", name: { en: "Media / Research Organization", ru: "СМИ / исследовательская организация" }, summary: "Анализирует и публикует procurement information в общественных интересах.", sideIds: ["side:TEA-S06", "side:TEA-S07"], directness: "indirect", represents: "Public interest или research mandate", role: "Проводит независимое исследование и dissemination.", stages: ["All lifecycle", "Post-award"], authority: "A0", contractualPosition: "Обычно отсутствует", typicalInputs: ["Public data", "Documents", "Interviews"], typicalOutputs: ["Research", "Publication", "Public scrutiny"] }),

  actor({ id: "actor-type:TEA-AT-EPROCUREMENT-OPERATOR", slug: "eprocurement-platform-operator", name: { en: "E-Procurement Platform Operator", ru: "Оператор электронной закупочной платформы" }, summary: "Обеспечивает цифровой канал публикации, подачи и audit trail.", sideIds: ["side:TEA-S07"], directness: "context-dependent", represents: "Government, buyer или platform provider", role: "Поддерживает system availability, identity, timestamps и procedural events.", stages: ["Publication", "Submission", "Opening", "Award"], authority: "A2", contractualPosition: "Statutory platform или technology service", typicalInputs: ["Notices", "User actions", "Documents"], typicalOutputs: ["Published records", "Receipts", "Audit log"] }),
  actor({ id: "actor-type:TEA-AT-REGISTRY-AUTHORITY", slug: "registry-authority", name: { en: "Registry Authority", ru: "Орган ведения реестра" }, summary: "Ведёт authoritative records о компаниях, лицензиях или правах.", sideIds: ["side:TEA-S07"], directness: "indirect", represents: "Statutory information function", role: "Регистрирует и публикует canonical status records.", stages: ["Qualification", "Due diligence", "Contract"], authority: "A3", contractualPosition: "Нет procurement contract", typicalInputs: ["Filings", "Applications", "Official decisions"], typicalOutputs: ["Registry record", "Status", "Extract"] }),
  actor({ id: "actor-type:TEA-AT-STANDARDS-BODY", slug: "standards-body", name: { en: "Standards Body", ru: "Орган стандартизации" }, summary: "Разрабатывает и поддерживает technical standards и classifications.", sideIds: ["side:TEA-S07"], directness: "indirect", represents: "National или international standardization system", role: "Издаёт standards, metadata и revision status.", stages: ["Market", "Specification", "Compliance"], authority: "A2", contractualPosition: "Нет procurement contract", typicalInputs: ["Technical consensus", "Revision proposals"], typicalOutputs: ["Standard", "Classification", "Revision notice"] }),
  actor({ id: "actor-type:TEA-AT-CERTIFICATION-BODY", slug: "certification-body", name: { en: "Certification / Accreditation Body", ru: "Орган сертификации / аккредитации" }, summary: "Подтверждает conformity или компетентность в пределах установленного scope.", sideIds: ["side:TEA-S07"], directness: "indirect", represents: "Conformity-assessment system", role: "Проводит assessment и выдаёт, приостанавливает или отзывает status.", stages: ["Qualification", "Production", "Acceptance"], authority: "A2", contractualPosition: "Certification service или statutory mandate", typicalInputs: ["Audit evidence", "Test results", "Application"], typicalOutputs: ["Certificate", "Accreditation record", "Scope"] }),
  actor({ id: "actor-type:TEA-AT-TRADE-ASSOCIATION", slug: "trade-association", name: { en: "Trade Association / Chamber", ru: "Отраслевая ассоциация / торговая палата" }, summary: "Представляет market segment и поддерживает supplier ecosystem.", sideIds: ["side:TEA-S07"], directness: "indirect", represents: "Членов отрасли или business community", role: "Распространяет информацию, развивает capacity и подтверждает отдельные membership facts.", stages: ["Market", "Pre-tender", "Capacity building"], authority: "A0", contractualPosition: "Обычно отсутствует", typicalInputs: ["Member data", "Market information"], typicalOutputs: ["Market brief", "Member directory", "Training"] }),
  actor({ id: "actor-type:TEA-AT-DATA-PROVIDER", slug: "data-provider", name: { en: "Data / Market Intelligence Provider", ru: "Поставщик данных / рыночной аналитики" }, summary: "Публикует или лицензирует structured market, company или procurement data.", sideIds: ["side:TEA-S07"], directness: "indirect", represents: "Public-data mandate или commercial information business", role: "Обеспечивает access, updates, coverage metadata и usage rights.", stages: ["All lifecycle"], authority: "A0", contractualPosition: "Open licence или commercial subscription", typicalInputs: ["Source records", "Licences"], typicalOutputs: ["Dataset", "API", "Coverage metadata"] }),
];

const side = (code: string, slug: string, en: string, ru: string, summary: string, purpose: string, color: string): TenderSide => ({
  id: `side:TEA-${code}`,
  code,
  slug,
  catalogue: "sides",
  status: "draft",
  version,
  name: { en, ru },
  aliases: [],
  summary,
  sourceRefs: [],
  updatedAt,
  purpose,
  color,
  actorTypeIds: actorTypes.filter((item) => item.sideIds.includes(`side:TEA-${code}`)).map((item) => item.id),
});

export const tenderSides: TenderSide[] = [
  side("S01", "demand-procurement", "Demand & Procurement Side", "Сторона спроса и закупки", "Формирует потребность и проводит процедуру.", "Определяет, покупает, оценивает и заключает контракт.", "#5c6ee5"),
  side("S02", "supply-competition", "Supply & Competition Side", "Сторона предложения и конкуренции", "Конкурирует за возможность и предлагает решение.", "Объединяет bidders, suppliers, contractors, manufacturers и partners.", "#0d8b72"),
  side("S03", "delivery-contract-administration", "Delivery & Contract Administration Side", "Сторона исполнения и администрирования", "Проектирует, контролирует и исполняет contractual scope.", "Обеспечивает delivery, supervision, logistics, acceptance и service.", "#d18b25"),
  side("S04", "finance-risk", "Finance & Risk Side", "Сторона финансирования и риска", "Финансирует и распределяет финансовые риски.", "Обеспечивает funds, guarantees, insurance и payment control.", "#8d5bc7"),
  side("S05", "governance-oversight-remedies", "Governance, Oversight & Remedies Side", "Сторона управления, надзора и защиты", "Регулирует, проверяет и разрешает нарушения и споры.", "Поддерживает legality, integrity, accountability и remedies.", "#d45b64"),
  side("S06", "beneficiary-public-interest", "Beneficiary & Public Interest Side", "Сторона бенефициаров и общественного интереса", "Получает результат и выражает общественные последствия.", "Представляет end users, affected communities и transparency interests.", "#3e9cbf"),
  side("S07", "market-digital-infrastructure", "Market & Digital Infrastructure Side", "Сторона рынка и цифровой инфраструктуры", "Поддерживает рынок информацией, стандартами и платформами.", "Обеспечивает registries, systems, standards, certification и data access.", "#68776f"),
];

export const directnessLabels: Record<Directness, string> = {
  direct: "Direct",
  indirect: "Indirect",
  "context-dependent": "Context-dependent",
};

export const authorityLabels = {
  A0: "No formal authority",
  A1: "Influence / commitment",
  A2: "Operational control",
  A3: "Professional determination",
  A4: "Formal recommendation / approval",
  A5: "Binding / statutory authority",
} as const;
