/**
 * Canonical responsibility profiles for the 64 TenderLab Agents.
 *
 * These records define reusable capability boundaries. Case-specific execution
 * stays in the Case graph and must never rewrite this registry.
 */

import type { AgentCapabilityProfile, AgentDefinitionStatus } from "../../catalog-schema/src/agent-specification";

export type AgentProfile = AgentCapabilityProfile;
export type { AgentDefinitionStatus, AgentOverlapFinding } from "../../catalog-schema/src/agent-specification";

const profile = (value: Omit<AgentProfile, "definitionStatus"> & { definitionStatus?: AgentDefinitionStatus }): AgentProfile => ({
  ...value,
  definitionStatus: value.definitionStatus ?? "structured",
});

export const agentProfiles: Record<number, AgentProfile> = {
  1: profile({
    simply: "Управляет маршрутом кейса: запускает нужную работу, ждёт зависимости и останавливает поток у контрольных точек.",
    responsibilityScope: "Оркестрация ограниченного Case-графа, состояний, зависимостей, повторов и human gates без выполнения предметной экспертизы других Agents.",
    activities: ["Выбирает разрешённые следующие активности", "Отслеживает waits, retries и convergence", "Передаёт критические решения на human approval"],
    exclusions: ["Не рассчитывает scores и цены", "Не извлекает требования", "Не подменяет владельца бизнес-решения"],
    typicalInputs: ["Case context и граф зависимостей", "Agent outputs и confidence", "Human decisions и SLA"],
    trigger: "Создан новый Case либо изменилось состояние активного Case.",
    skipCondition: "Не пропускается для управляемого многоагентного Case; не нужен для одиночного автономного utility-вызова.",
    authority: "Может запускать, приостанавливать, повторять и маршрутизировать разрешённые активности; не имеет права принимать Bid, цену, контракт или submission от имени человека.",
    responsibilityBoundary: "Заканчивает работу на выборе и контроле маршрута; содержательная ответственность остаётся у исполняющего Agent и человека-владельца.",
    keyDistinction: "Единственный Agent, управляющий сквозным состоянием Case, а не отдельным функциональным процессом.",
    workflowStage: "Сквозной контроль: discovery → post-award",
    upstream: ["Case owner", "Все активные Agents", "Human Approval Agent"],
    potentialOverlaps: [{ agentIds: [45], note: "RFQ Orchestrator управляет только RFQ-подпроцессом; TenderLab Orchestrator управляет всем Case-графом." }],
  }),
  2: profile({
    simply: "Показывает ответственному человеку решение, которое система не должна принимать сама, и фиксирует его ответ.",
    responsibilityScope: "Создание human decision gate, назначение approver, сбор решения, условий и audit evidence.",
    activities: ["Формирует decision brief", "Запрашивает approve / reject / revise", "Записывает решение и ограничения"],
    exclusions: ["Не принимает решение за approver", "Не меняет предметные расчёты", "Не утверждает документы без полномочий"],
    typicalInputs: ["Decision package", "Рекомендации и риски", "Список полномочных approvers"],
    trigger: "Workflow достигает обязательного human gate или low-confidence исключения.",
    skipCondition: "Нет решения с человеческой ответственностью и политика разрешает автоматический переход.",
    authority: "Может блокировать следующий этап до ответа и проверить полномочия approver; само бизнес-решение принадлежит человеку.",
    responsibilityBoundary: "Организует и фиксирует approval, но не создаёт исходную рекомендацию и не исполняет утверждённое действие.",
    keyDistinction: "Это контролируемый интерфейс человеческой власти, а не ещё один scoring или decision Agent.",
    workflowStage: "Сквозные decision gates",
    upstream: ["Orchestrator", "Decision Agents", "Risk / QA Agents"],
    potentialOverlaps: [{ agentIds: [35, 56, 58], note: "Эти Agents готовят рекомендацию или пакет; Human Approval фиксирует полномочное решение." }],
  }),
  3: profile({
    simply: "Показывает, откуда взялся каждый важный вывод и насколько ему можно доверять.",
    responsibilityScope: "Claim-level provenance, source linking, confidence и фиксация неподтверждённых утверждений для любых аналитических outputs.",
    activities: ["Связывает claims с источниками", "Оценивает качество evidence", "Помечает gaps и conflicts"],
    exclusions: ["Не хранит версии файлов", "Не решает, соответствует ли заявка", "Не превращает слабое evidence в подтверждённый факт"],
    typicalInputs: ["Agent claims и scores", "Source references", "Document fragments и verification results"],
    trigger: "Agent создаёт вывод, который влияет на score, compliance, recommendation или approval.",
    skipCondition: "Только для низкорискового служебного output без утверждений о внешнем мире.",
    authority: "Может понизить confidence и пометить claim как unsupported; не может принять бизнес-решение.",
    responsibilityBoundary: "Отвечает за доказуемость вывода, тогда как Audit & Version Control отвечает за историю изменений объекта.",
    keyDistinction: "Проверяет происхождение и качество содержания, а не просто версию и timestamp.",
    workflowStage: "Сквозное evidence control",
    upstream: ["Source Ingestion", "Verification Agents", "Все аналитические Agents"],
    potentialOverlaps: [{ agentIds: [4], note: "Provenance доказывает источник claims; Version Control доказывает, когда и как объект изменился." }],
  }),
  4: profile({
    simply: "Хранит историю: что изменилось, кто изменил и какая версия использовалась в решении.",
    responsibilityScope: "Версионирование данных, документов, Agent outputs и human decisions с diff и immutable audit trail.",
    activities: ["Назначает версии и hashes", "Строит diff", "Фиксирует actor, time и reason"],
    exclusions: ["Не оценивает достоверность содержания", "Не интерпретирует amendments", "Не выбирает текущую бизнес-позицию"],
    typicalInputs: ["Новый или изменённый объект", "Предыдущая версия", "Actor и change reason"],
    trigger: "Создана, изменена или утверждена версия значимого объекта.",
    skipCondition: "Эфемерный UI state, не влияющий на Case или evidence.",
    authority: "Может отклонить запись без обязательной audit metadata; не может изменить утверждённое содержание.",
    responsibilityBoundary: "Фиксирует изменение; Amendment & Change Agent определяет его смысл и влияние.",
    keyDistinction: "Системный журнал истории, а не анализ содержания изменения.",
    workflowStage: "Сквозной audit trail",
    upstream: ["Все data-producing Agents", "Human Approval", "External source updates"],
    potentialOverlaps: [{ agentIds: [3, 29], note: "Evidence связывает claim с источником; Amendment анализирует влияние; этот Agent фиксирует версии." }],
  }),
  5: profile({
    simply: "Связывает разрозненные сведения о компаниях, тендерах, документах, awards и контрактах в одну карту знаний.",
    responsibilityScope: "Canonical entity resolution и typed relationships между procurement entities с provenance.",
    activities: ["Создаёт и связывает entity nodes", "Разрешает дубликаты идентичности", "Обновляет graph relationships"],
    exclusions: ["Не ищет тендеры самостоятельно", "Не делает Bid recommendation", "Не подменяет исходные datasets"],
    typicalInputs: ["Нормализованные entity records", "Verified relationships", "Award и outcome updates"],
    trigger: "Появилась подтверждённая сущность или связь, полезная нескольким workflows.",
    skipCondition: "Одноразовый факт не прошёл verification или не требует повторного использования.",
    authority: "Может создать, объединить или оспорить canonical link по правилам identity resolution; не может утверждать коммерческий вывод.",
    responsibilityBoundary: "Хранит reusable relationships; аналитические Agents извлекают из них insights и решения.",
    keyDistinction: "Общая модель связей архитектуры, а не отчёт или case-specific shortlist.",
    workflowStage: "Сквозная knowledge layer",
    upstream: ["Ingestion и Verification", "Award Intelligence", "Outcome Learning"],
    potentialOverlaps: [{ agentIds: [19, 64], note: "Award Intelligence и Outcome Learning создают domain records; Knowledge Graph связывает их с общей моделью entities." }],
  }),
  6: profile({
    simply: "Собирает в одном месте проверенную картину того, кто компания, что она умеет и где может работать.",
    responsibilityScope: "Canonical company profile: identity, products, capacity, geography, experience и evidence references.",
    activities: ["Объединяет company data", "Нормализует profile attributes", "Поддерживает актуальное состояние профиля"],
    exclusions: ["Не проверяет каждый факт самостоятельно", "Не оценивает конкретный tender fit", "Не выбирает Bid / No-Bid"],
    typicalInputs: ["Legal identity", "Product & capability catalog", "Verification, credentials и references"],
    trigger: "Онбординг компании, изменение профиля или запрос оценки возможности.",
    skipCondition: "Есть актуальный подтверждённый профиль нужной полноты.",
    authority: "Может собрать и пометить completeness статуса; не может признать неподтверждённый факт verified.",
    responsibilityBoundary: "Владеет целостным profile object; специализированные Agents владеют verification, catalog и certificates.",
    keyDistinction: "Единый reusable профиль компании, а не проверка или score.",
    workflowStage: "Company onboarding и maintenance",
    upstream: ["Company user", "Product & Capability", "Company Verification", "Credential Agents"],
    potentialOverlaps: [{ agentIds: [7, 8, 9], note: "7 нормализует capabilities, 8 проверяет факты, 9 оценивает readiness; 6 агрегирует профиль." }],
  }),
  7: profile({
    simply: "Переводит каталог компании и её мощности в единый язык, пригодный для поиска и сопоставления.",
    responsibilityScope: "Нормализация продуктов, услуг, технических параметров, capacity и constraints компании.",
    activities: ["Сопоставляет taxonomy", "Структурирует specs и capacity", "Выявляет неизвестные capability attributes"],
    exclusions: ["Не подтверждает существование производства", "Не оценивает tender requirements", "Не выбирает suppliers"],
    typicalInputs: ["Каталоги и datasheets", "Производственные данные", "Service descriptions"],
    trigger: "Добавлен или изменён продукт, услуга либо производственная возможность.",
    skipCondition: "Вход уже нормализован по текущей taxonomy и не изменился.",
    authority: "Может классифицировать и нормализовать capability; не может подтвердить факт без evidence.",
    responsibilityBoundary: "Описывает, что заявляет компания; Company Verification подтверждает, что это действительно существует.",
    keyDistinction: "Capability semantics и taxonomy, а не legal/operational verification.",
    workflowStage: "Company profile structuring",
    upstream: ["Company catalog", "Factory data", "Company Profile"],
    potentialOverlaps: [{ agentIds: [6, 8, 11], note: "Profile агрегирует, Verification доказывает, Supplier Intelligence описывает внешних suppliers." }],
  }),
  8: profile({
    simply: "Проверяет, что компания реальна и её заявленные фабрика, опыт и возможности подтверждаются доказательствами.",
    responsibilityScope: "Legal, operational, capacity и reference verification компании-участника.",
    activities: ["Проверяет legal identity", "Валидирует production evidence", "Подтверждает references"],
    exclusions: ["Не формирует company profile", "Не проверяет tender eligibility", "Не проверяет стороннего supplier в solution"],
    typicalInputs: ["Company claims", "Registries и certificates", "Factory и contract evidence"],
    trigger: "Новый профиль, критическое изменение или требование свежей проверки.",
    skipCondition: "Существующая verification действительна и покрывает нужный scope.",
    authority: "Может присвоить verified / unverified / conflicting и confidence; не может выдавать юридическую гарантию.",
    responsibilityBoundary: "Проверяет собственную компанию-кандидата; Supplier Verification проверяет внешнего поставщика решения.",
    keyDistinction: "Evidence-backed verification company claims, а не profile assembly или tender fit.",
    workflowStage: "Company verification",
    upstream: ["Company Profile", "External registries", "Evidence & Provenance"],
    potentialOverlaps: [{ agentIds: [6, 44], note: "6 агрегирует профиль; 44 проверяет внешнего supplier, тогда как 8 — компанию-участника." }],
  }),
  9: profile({
    simply: "Показывает, насколько компания вообще готова участвовать в тендерах и какие пробелы нужно закрыть заранее.",
    responsibilityScope: "Общая, не привязанная к одному tender, оценка организационной, документной и операционной readiness компании.",
    activities: ["Считает readiness domains", "Выявляет блокирующие gaps", "Формирует improvement plan"],
    exclusions: ["Не измеряет fit к конкретному tender", "Не прогнозирует победу", "Не принимает Bid / No-Bid"],
    typicalInputs: ["Verified company profile", "Credentials и document readiness", "Capacity и process maturity"],
    trigger: "Онбординг, периодическая переоценка или существенное изменение компании.",
    skipCondition: "Есть свежая readiness assessment без значимых изменений.",
    authority: "Может присвоить readiness score и blocker flags; участие и инвестиции утверждает человек.",
    responsibilityBoundary: "Заканчивается на общей готовности; Company-to-Tender Match начинается с пары Company × Tender.",
    keyDistinction: "General readiness 0–100, не tender relevance 92% и не match score.",
    workflowStage: "Pre-tender readiness",
    upstream: ["Company Profile", "Company Verification", "Credential & Certificate"],
    potentialOverlaps: [{ agentIds: [31, 34, 35], note: "31 оценивает конкретный fit, 34 формирует case gap plan, 35 рекомендует Bid / No-Bid." }],
  }),
  10: profile({
    simply: "Следит, какие лицензии и сертификаты у компании есть, что они покрывают и когда истекают.",
    responsibilityScope: "Canonical registry of company certificates, licenses, scopes, issuers, validity и expiry alerts.",
    activities: ["Извлекает credential metadata", "Проверяет validity и scope", "Создаёт expiry alerts"],
    exclusions: ["Не выбирает tender evidence", "Не доказывает весь project experience", "Не решает eligibility"],
    typicalInputs: ["Certificates и licenses", "Issuer/registry checks", "Product и geography scope"],
    trigger: "Credential добавлен, изменился, приближается expiry или требуется для tender.",
    skipCondition: "Нет credential-dependent requirement и реестр актуален.",
    authority: "Может пометить valid / expired / scope mismatch; признание эквивалентности и допуск остаются у соответствующих review gates.",
    responsibilityBoundary: "Управляет reusable credential inventory; Bid Credentials & Experience Agent отбирает evidence под конкретную заявку.",
    keyDistinction: "Жизненный цикл сертификата компании, а не tender-specific evidence pack.",
    workflowStage: "Company readiness и bid evidence",
    upstream: ["Company documents", "Issuers/registries", "Company Verification"],
    potentialOverlaps: [{ agentIds: [55, 25], note: "55 маппит credentials к критериям заявки; 25 определяет eligibility consequence." }],
  }),
  11: profile({
    simply: "Накапливает долгосрочные проверенные сведения о поставщиках, чтобы повторно не исследовать рынок с нуля.",
    responsibilityScope: "Reusable supplier intelligence: identity, offering, history, performance, risks и evidence across cases.",
    activities: ["Обновляет supplier profiles", "Связывает delivery/performance history", "Фиксирует risk signals"],
    exclusions: ["Не ищет supplier под конкретную спецификацию", "Не выполняет case-specific due diligence", "Не выбирает победителя RFQ"],
    typicalInputs: ["Past supplier records", "Delivery outcomes", "Verification и market evidence"],
    trigger: "Появились новые проверенные supplier facts или outcome.",
    skipCondition: "Нет reusable supplier intelligence для обновления.",
    authority: "Может обновлять intelligence confidence и risk history; не может одобрить supplier для конкретного bid.",
    responsibilityBoundary: "Хранит cross-case knowledge; Supplier Discovery ищет кандидатов, Supplier Verification проверяет их для case.",
    keyDistinction: "Долговременный intelligence dataset, а не shortlist или due-diligence dossier.",
    workflowStage: "Supplier knowledge",
    upstream: ["Supplier Verification", "RFQ outcomes", "Execution outcomes"],
    potentialOverlaps: [{ agentIds: [43, 44], note: "43 ищет candidates, 44 проводит case due diligence, 11 сохраняет reusable history." }],
    definitionStatus: "needs-review",
    validationFinding: "Нужна политика, какие supplier facts считаются reusable и когда устаревшая verification должна быть повторена.",
  }),
  12: profile({
    simply: "Показывает, какие проверенные партнёры какими компетенциями и территориями закрывают потребности компании.",
    responsibilityScope: "Reusable graph партнёров, capabilities, geography, relationships и evidence.",
    activities: ["Связывает partners с capabilities", "Показывает coverage и gaps", "Обновляет relationship state"],
    exclusions: ["Не ищет партнёра для конкретного case", "Не проектирует consortium", "Не заключает соглашения"],
    typicalInputs: ["Partner profiles", "Verified capabilities", "Past collaboration outcomes"],
    trigger: "Добавлен партнёр, capability или подтверждённый relationship outcome.",
    skipCondition: "Case не требует партнёров и reusable graph не изменился.",
    authority: "Может представить capability coverage; selection и commitment утверждаются людьми.",
    responsibilityBoundary: "Хранит reusable network; Partner Discovery выполняет case-specific search and ranking.",
    keyDistinction: "Постоянная карта возможностей партнёров, а не shortlist конкретного тендера.",
    workflowStage: "Partner ecosystem knowledge",
    upstream: ["Partner verification", "Company records", "Outcome Learning"],
    potentialOverlaps: [{ agentIds: [40, 41], note: "40 ищет кандидатов для case; 41 проектирует consortium; 12 хранит reusable graph." }],
    definitionStatus: "needs-review",
    validationFinding: "Проверить, должен ли reusable partner graph быть самостоятельным Agent или capability Tender Knowledge Graph Agent.",
  }),
  13: profile({
    simply: "Забирает notice и исходные файлы из официальных источников, сохраняя ссылку и происхождение.",
    responsibilityScope: "Source acquisition, normalization и техническая типизация входящих procurement publications, attachments, metadata и fetch status across procurement sources.",
    activities: ["Мониторит источники", "Скачивает оригиналы", "Определяет source item type для ingestion и routing", "Создаёт source records, version links и deduplication keys"],
    exclusions: ["Не решает релевантность", "Не индексирует внутреннее содержание пакета", "Не выполняет содержательную или бизнес-классификацию tender по сектору, категории, типу закупки, заказчику или процедуре"],
    typicalInputs: ["Procurement source endpoints", "Crawl/API schedules", "Source access rules"],
    trigger: "Источник публикует или изменяет notice/attachment.",
    skipCondition: "Source item уже получен в той же версии и hash не изменился.",
    authority: "Может принять или отклонить fetch/duplicate и присвоить технический source item type с confidence; не может трактовать procurement meaning или присваивать business taxonomy.",
    responsibilityBoundary: "Технически типизирует source item (например notice, amendment, award, cancellation, plan или clarification) только для normalization, deduplication, version linking, storage и routing. Tender Classification Agent выполняет содержательную business-классификацию; Document Intake начинает corpus ingestion.",
    keyDistinction: "Внешнее acquisition и техническая типизация source item, а не business classification или внутреннее document processing.",
    workflowStage: "Opportunity source acquisition",
    upstream: ["Official portals", "IFI feeds", "Buyer websites"],
    potentialOverlaps: [{ agentIds: [15, 19, 21, 14], note: "13 получает и технически типизирует source item; 15 присваивает tender business taxonomy; 19 извлекает и связывает award meaning; 21 индексирует пакет; 14 ранжирует возможности." }],
  }),
  14: profile({
    simply: "Ищет среди доступных закупок те, которые потенциально подходят профилю компании.",
    responsibilityScope: "Candidate retrieval и ranking opportunities по профилю, scope, geography, timing и первичной relevance.",
    activities: ["Формирует candidate set", "Ранжирует relevance", "Объясняет inclusion/exclusion"],
    exclusions: ["Не считает полный Company × Tender match", "Не решает Bid / No-Bid", "Не извлекает детальные requirements"],
    typicalInputs: ["Normalized tender notices", "Company profile и interests", "Classification и filter rules"],
    trigger: "Поступили новые/обновлённые tenders или изменился company search profile.",
    skipCondition: "Нет новых candidates и профиль/filters не изменились.",
    authority: "Может включить opportunity в shortlist или исключить из discovery с reason; не утверждает участие.",
    responsibilityBoundary: "Завершает широкий поиск shortlist; Match Score выполняет глубокую персональную оценку выбранной пары.",
    keyDistinction: "Opportunity discovery и triage, не readiness, match или Bid decision.",
    workflowStage: "Discovery",
    upstream: ["Tender Source Ingestion", "Tender Classification", "Tender Filtering", "Company Profile"],
    potentialOverlaps: [{ agentIds: [16, 31], note: "16 применяет hard filters; 31 оценивает глубокий fit выбранной Company × Tender пары." }],
  }),
  15: profile({
    simply: "Присваивает тендеру понятные категории: что закупают, где, кто заказчик и какая процедура.",
    responsibilityScope: "Canonical classification tender sector, category, geography, buyer type, procedure и procurement method.",
    activities: ["Классифицирует notice", "Нормализует procurement taxonomy", "Помечает uncertainty и multi-label cases"],
    exclusions: ["Не определяет релевантность компании", "Не извлекает все requirements", "Не фильтрует по business rules"],
    typicalInputs: ["Tender notice и metadata", "Procurement taxonomies", "Buyer/source metadata"],
    trigger: "Получен новый или существенно изменённый tender notice.",
    skipCondition: "Canonical classification уже подтверждена и source meaning не изменился.",
    authority: "Может присвоить classification labels и confidence; не может отклонить opportunity по коммерческим причинам.",
    responsibilityBoundary: "Описывает, что это за tender; Filtering и Discovery решают, входит ли он в candidate flow.",
    keyDistinction: "Нейтральная taxonomy-карточка, не relevance filter.",
    workflowStage: "Discovery normalization",
    upstream: ["Tender Source Ingestion", "Source metadata"],
    potentialOverlaps: [{ agentIds: [16, 23], note: "16 применяет pass/reject rules; 23 структурирует внутренний document package, а не notice taxonomy." }],
  }),
  16: profile({
    simply: "Быстро убирает закупки, которые точно не проходят заданные правила компании или платформы.",
    responsibilityScope: "Deterministic/semi-deterministic exclusion по hard filters: geography, sector, budget, deadline, prohibited procedure и policy.",
    activities: ["Применяет filter rules", "Фиксирует pass/reject reason", "Передаёт survivors в Discovery ranking"],
    exclusions: ["Не ранжирует привлекательность", "Не считает tender-specific fit", "Не заменяет eligibility analysis"],
    typicalInputs: ["Classified opportunities", "Company/portfolio filter policy", "Thresholds и exclusions"],
    trigger: "Новая opportunity или изменение filter policy.",
    skipCondition: "Opportunity уже прошла актуальный rule set.",
    authority: "Может исключить из автоматического shortlist по утверждённому hard rule; override требует audit/human policy.",
    responsibilityBoundary: "Выполняет binary pre-filter; Discovery ранжирует оставшиеся, Eligibility проверяет formal tender criteria.",
    keyDistinction: "Hard-rule rejection до глубокого анализа, не score и не qualification.",
    workflowStage: "Discovery triage",
    upstream: ["Tender Classification", "Company policy", "Risk exclusions"],
    potentialOverlaps: [{ agentIds: [14, 25], note: "14 ранжирует candidates; 25 оценивает formal bidder eligibility после документного анализа." }],
  }),
  17: profile({
    simply: "Собирает все важные даты тендера, назначает ответственных и предупреждает об изменениях и приближении сроков.",
    responsibilityScope: "Tender calendar, deadline monitoring, reminders, ownership и time-based alerts across the Case.",
    activities: ["Извлекает контрольные даты", "Назначает reminders", "Пересчитывает сроки после amendment"],
    exclusions: ["Не анализирует содержание amendment", "Не отправляет submission", "Не принимает решение о приоритетности bid"],
    typicalInputs: ["Notice dates", "Document deadlines", "Amendment updates и internal milestones"],
    trigger: "Появилась или изменилась дата, SLA, milestone либо owner.",
    skipCondition: "Case не активен или нет time-bound obligations.",
    authority: "Может создавать alerts и эскалировать просрочку; не может менять официальный deadline.",
    responsibilityBoundary: "Управляет временем; Amendment Agent объясняет изменение, Orchestrator меняет маршрут.",
    keyDistinction: "Единый operational calendar и alerting, не document change analysis.",
    workflowStage: "Сквозное deadline control",
    upstream: ["Tender notice", "Amendment & Change", "Orchestrator"],
    potentialOverlaps: [{ agentIds: [29, 58], note: "29 определяет влияние amendment; 58 управляет final submission package; 17 контролирует даты." }],
  }),
  18: profile({
    simply: "Показывает, где растёт спрос, какие цены встречаются и какие рынки стоит изучать.",
    responsibilityScope: "Aggregate market demand, tender-flow, pricing benchmarks и country/sector opportunity trends.",
    activities: ["Агрегирует market signals", "Строит benchmarks", "Сравнивает рынки и trends"],
    exclusions: ["Не профилирует конкретного buyer", "Не рассчитывает bid price", "Не рекомендует Bid / No-Bid по одному case"],
    typicalInputs: ["Tender history", "Award/contract data", "External market indicators"],
    trigger: "Запрошен market brief либо обновился существенный массив market data.",
    skipCondition: "Case не требует market context и актуальный brief уже существует.",
    authority: "Может публиковать аналитические benchmarks с confidence; не утверждает коммерческое решение.",
    responsibilityBoundary: "Работает на уровне рынка; Buyer & Competitor Intelligence работает на уровне конкретного buyer/competitive field.",
    keyDistinction: "Portfolio/market lens, а не case pricing или buyer dossier.",
    workflowStage: "Market intelligence",
    upstream: ["Tender Knowledge Graph", "Award Intelligence", "External datasets"],
    potentialOverlaps: [{ agentIds: [19, 20], note: "19 связывает award records; 20 профилирует buyer/competitors; 18 агрегирует market trends." }],
  }),
  19: profile({
    simply: "Находит, кто выиграл прошлые тендеры, по какой цене и как notice связан с award и contract.",
    responsibilityScope: "Acquisition, normalization и linkage award notices, winners, prices, lots и resulting contracts.",
    activities: ["Связывает tender → award → contract", "Извлекает winners и award values", "Выявляет award patterns"],
    exclusions: ["Не строит полный competitor strategy", "Не прогнозирует будущую победу", "Не управляет post-award contract"],
    typicalInputs: ["Award notices", "Contract records", "Canonical tender IDs"],
    trigger: "Опубликован award/contract update либо запрошена historical award evidence.",
    skipCondition: "Award data отсутствует или уже связано в текущей версии.",
    authority: "Может подтвердить linked award record по identity/evidence rules; не интерпретирует его как Bid decision.",
    responsibilityBoundary: "Создаёт structured award intelligence; Buyer & Competitor Agent превращает историю в competitive dossier.",
    keyDistinction: "Фактическая связь tender-award-contract, а не общий market trend или outcome model update.",
    workflowStage: "Award intelligence",
    upstream: ["Award sources", "Tender Knowledge Graph", "Source Ingestion"],
    potentialOverlaps: [{ agentIds: [18, 20, 64], note: "18 агрегирует рынок, 20 интерпретирует competition, 64 учится на outcome конкретной компании." }],
    definitionStatus: "needs-review",
    validationFinding: "Уточнить ownership ingestion award sources между Tender Source Ingestion и Award Intelligence.",
  }),
  20: profile({
    simply: "Объясняет, как покупает конкретный заказчик и с кем компания, вероятно, будет конкурировать.",
    responsibilityScope: "Buyer procurement behavior, incumbent/competitor profiles, participation patterns, price/win bands и evidence.",
    activities: ["Строит buyer dossier", "Выявляет likely competitors", "Сравнивает award и participation patterns"],
    exclusions: ["Не собирает raw award notices", "Не выбирает final bid strategy", "Не устанавливает win probability самостоятельно"],
    typicalInputs: ["Buyer history", "Award intelligence", "Supplier/competitor records"],
    trigger: "Opportunity прошла discovery и требуется competitive context.",
    skipCondition: "Нет доступной истории или competitive analysis не влияет на решение.",
    authority: "Может ранжировать вероятных competitors и patterns с confidence; не утверждает claims без evidence.",
    responsibilityBoundary: "Поставляет intelligence; Proposal Strategy определяет позиционирование и win themes.",
    keyDistinction: "Конкретный buyer + competitive field, а не общий рынок или proposal narrative.",
    workflowStage: "Opportunity intelligence",
    upstream: ["Award Intelligence", "Market Intelligence", "Knowledge Graph"],
    potentialOverlaps: [{ agentIds: [18, 19, 52], note: "18 — market trends, 19 — award facts, 52 — response strategy на основе intelligence." }],
  }),
  21: profile({
    simply: "Принимает весь tender package, проверяет файлы и превращает их в управляемый документный корпус.",
    responsibilityScope: "Internal ingestion, manifesting, hashing, indexing и version binding source documents for analysis.",
    activities: ["Проверяет file manifest", "Вычисляет hashes", "Маршрутизирует файлы в OCR/structure pipeline"],
    exclusions: ["Не скачивает notice из внешнего источника", "Не извлекает requirements", "Не собирает final submission"],
    typicalInputs: ["Source package и attachments", "Source metadata", "Amendment files"],
    trigger: "Получен новый или изменённый tender document package.",
    skipCondition: "Package уже проиндексирован с теми же hashes и manifest.",
    authority: "Может пометить corrupt/missing/duplicate file и остановить parsing; не оценивает tender meaning.",
    responsibilityBoundary: "Владеет corpus intake; Source Ingestion получает внешние файлы, Structure/OCR интерпретируют содержимое.",
    keyDistinction: "Контролируемый document corpus, не source crawling и не requirement extraction.",
    workflowStage: "Document acquisition",
    upstream: ["Tender Source Ingestion", "Buyer package", "Amendment & Change"],
    potentialOverlaps: [{ agentIds: [13, 23, 58], note: "13 получает source, 23 структурирует package, 58 собирает outbound submission." }],
  }),
  22: profile({
    simply: "Делает сканы читаемыми и создаёт единый многоязычный текст, с которым могут работать остальные Agents.",
    responsibilityScope: "OCR, language detection, canonical-English translation, user-language translation cache и layout/source alignment.",
    activities: ["Распознаёт сканы", "Определяет язык", "Создаёт и кэширует source-aligned translations"],
    exclusions: ["Не толкует legal meaning", "Не извлекает requirements", "Не исправляет неоднозначность источника догадкой"],
    typicalInputs: ["Scanned PDFs/images", "Digital text", "Approved terminology и language preferences"],
    trigger: "Документ не имеет надёжного searchable text или нужен другой рабочий язык.",
    skipCondition: "Документ уже имеет проверенный текст на требуемом языке.",
    authority: "Может выставить OCR/translation confidence и потребовать review; не изменяет source wording.",
    responsibilityBoundary: "Создаёт faithful text layer; downstream Agents извлекают структуру и требования.",
    keyDistinction: "Language/accessibility transformation, не procurement interpretation.",
    workflowStage: "Document preprocessing",
    upstream: ["Document Intake", "Terminology rules", "Human language review"],
    potentialOverlaps: [{ agentIds: [23, 28], note: "23 создаёт tender structure; 28 сохраняет exact spec semantics; 22 обеспечивает читаемый/переведённый текст." }],
  }),
  23: profile({
    simply: "Разбирает tender package на понятные части: lot, BOQ, формы, приложения и связи между ними.",
    responsibilityScope: "Structural decomposition documents into lots, sections, BOQ rows, forms, annexes и cross-references.",
    activities: ["Строит document tree", "Выделяет lot/BOQ/form entities", "Связывает annex references"],
    exclusions: ["Не извлекает полный semantic requirement register", "Не определяет compliance", "Не заполняет формы"],
    typicalInputs: ["Indexed searchable document corpus", "Page/layout metadata", "Document manifest"],
    trigger: "Corpus готов к structural parsing или изменилась package version.",
    skipCondition: "Надёжная structure map актуальна для текущей версии.",
    authority: "Может создать structural nodes и пометить ambiguous linkage; не решает предметный смысл требования.",
    responsibilityBoundary: "Отвечает где находится и как связано; Requirement Parser отвечает что именно требуется.",
    keyDistinction: "Document topology, не semantic requirement extraction.",
    workflowStage: "Document understanding",
    upstream: ["Document Intake", "OCR & Language"],
    potentialOverlaps: [{ agentIds: [24, 27], note: "24 извлекает требования; 27 превращает forms/deliverables в контрольный реестр." }],
  }),
  24: profile({
    simply: "Превращает длинный tender package в полный список конкретных требований, условий и правил.",
    responsibilityScope: "Semantic extraction atomic requirements, eligibility rules, technical/commercial conditions, delivery obligations и evaluation references.",
    activities: ["Извлекает atomic requirements", "Классифицирует requirement types", "Связывает clauses с source locations"],
    exclusions: ["Не решает, проходит ли компания", "Не пишет proposal response", "Не изменяет exact specification"],
    typicalInputs: ["Structured tender corpus", "Canonical text", "Source-locked clauses"],
    trigger: "Structure map и searchable corpus готовы либо package изменился.",
    skipCondition: "Requirement register подтверждён для текущей version.",
    authority: "Может создать/обновить requirement record с confidence; qualification/compliance decisions принадлежат downstream Agents.",
    responsibilityBoundary: "Заканчивается на факте и структуре требования; Eligibility и Compliance оценивают ответ компании.",
    keyDistinction: "Полный source-linked requirement register, не pass/fail и не proposal answer.",
    workflowStage: "Requirements extraction",
    upstream: ["Tender Structure", "OCR & Language", "Strict-Spec"],
    potentialOverlaps: [{ agentIds: [25, 27, 28], note: "25 применяет eligibility criteria, 27 контролирует forms, 28 защищает exact specifications." }],
  }),
  25: profile({
    simply: "Проверяет, имеет ли компания право участвовать и выполняет ли обязательные квалификационные условия.",
    responsibilityScope: "Tender-specific bidder eligibility and qualification pass/fail against mandatory criteria and evidence.",
    activities: ["Маппит company evidence к criteria", "Выдаёт pass/fail/unknown", "Выявляет curable и fatal gaps"],
    exclusions: ["Не проверяет всё техническое решение", "Не оценивает коммерческую привлекательность", "Не принимает окончательное Bid решение"],
    typicalInputs: ["Eligibility requirements", "Verified company profile", "Credentials, references и financial evidence"],
    trigger: "Извлечены mandatory qualification criteria и выбран candidate company.",
    skipCondition: "Opportunity ещё не прошла discovery либо formal eligibility отсутствует.",
    authority: "Может рекомендовать ineligible/eligible/conditional; final waiver, interpretation и participation gate требуют human governance.",
    responsibilityBoundary: "Только bidder admission; Technical/Commercial Compliance оценивают содержание самой заявки.",
    keyDistinction: "Право и квалификация участника, не solution compliance и не general readiness.",
    workflowStage: "Qualification",
    upstream: ["Requirement Parser", "Company Verification", "Credential & Certificate"],
    potentialOverlaps: [{ agentIds: [9, 48, 49], note: "9 — общая readiness; 48/49 — compliance предложения; 25 — tender admission." }],
  }),
  26: profile({
    simply: "Разбирает, как заказчик будет оценивать заявки: баллы, веса, формулы и минимальные пороги.",
    responsibilityScope: "Formal evaluation model: criteria, weights, formulas, pass thresholds, tie-breakers и evidence requirements.",
    activities: ["Извлекает scoring rules", "Проверяет сумму weights/formulas", "Создаёт machine-readable evaluation model"],
    exclusions: ["Не ставит компании фактический score без evidence", "Не выбирает proposal strategy", "Не меняет buyer formula"],
    typicalInputs: ["Evaluation clauses", "Tables/appendices", "Clarifications и amendments"],
    trigger: "Tender содержит weighted/qualitative evaluation либо pass thresholds.",
    skipCondition: "Только lowest-price procedure без дополнительных criteria, кроме формальной compliance.",
    authority: "Может зафиксировать formal model и inconsistencies; interpretation ambiguity требует clarification/human review.",
    responsibilityBoundary: "Описывает правила buyer scoring; Match/Bid/Strategy Agents применяют их к компании и предложению.",
    keyDistinction: "Buyer evaluation mechanics, не internal opportunity score.",
    workflowStage: "Evaluation modeling",
    upstream: ["Requirement Parser", "Tender Structure", "Amendment & Change"],
    potentialOverlaps: [{ agentIds: [31, 35, 52], note: "31 и 35 создают internal scores; 52 строит response strategy на formal evaluation model." }],
  }),
  27: profile({
    simply: "Создаёт полный checklist того, что нужно заполнить, подписать, приложить и сдать.",
    responsibilityScope: "Tender-specific deliverable/form inventory with owner, due date, source, completion and signature requirements.",
    activities: ["Перечисляет forms/deliverables", "Назначает owners", "Отслеживает completion status"],
    exclusions: ["Не заполняет содержимое форм", "Не собирает final package", "Не оценивает technical compliance"],
    typicalInputs: ["Tender structure", "Requirement register", "Submission instructions"],
    trigger: "Структура и requirements доступны или amendment меняет deliverables.",
    skipCondition: "Нет formal deliverables либо registry актуален.",
    authority: "Может пометить обязательность и completeness по source; owner подтверждает готовность документа.",
    responsibilityBoundary: "Владеет checklist; content Agents создают файлы, Assembly & Submission собирает и подаёт их.",
    keyDistinction: "Что должно быть доставлено в заявке, не само содержание и не submission transport.",
    workflowStage: "Bid planning",
    upstream: ["Tender Structure", "Requirement Parser"],
    potentialOverlaps: [{ agentIds: [23, 58], note: "23 находит structural forms; 58 выполняет final assembly/submission; 27 ведёт checklist." }],
  }),
  28: profile({
    simply: "Не позволяет системе незаметно изменить точные размеры, материалы, допуски или запреты из спецификации.",
    responsibilityScope: "Source-lock exact specifications, units, tolerances, brands/equivalence rules and prohibited substitutions.",
    activities: ["Выделяет exact constraints", "Сохраняет verbatim/source links", "Блокирует unsupported substitutions"],
    exclusions: ["Не предлагает product solution", "Не решает equivalence", "Не оценивает overall compliance"],
    typicalInputs: ["Technical specifications", "Drawings/BOQ", "Amendments и buyer clarifications"],
    trigger: "Requirement содержит precision-sensitive specification или substitution risk.",
    skipCondition: "Requirements не имеют exact technical constraints.",
    authority: "Может запретить generated claim, противоречащий source; equivalence утверждает Technical Compliance/human.",
    responsibilityBoundary: "Охраняет fidelity source spec; Requirement Parser структурирует, Technical Compliance сравнивает solution.",
    keyDistinction: "Guardrail против домыслов, а не parser или checker.",
    workflowStage: "Specification control",
    upstream: ["Tender documents", "Requirement Parser", "Amendment & Change"],
    potentialOverlaps: [{ agentIds: [24, 48], note: "24 извлекает requirement meaning; 48 оценивает response; 28 сохраняет exact source constraint." }],
  }),
  29: profile({
    simply: "Показывает, что именно изменил заказчик и какие части анализа или заявки нужно переделать.",
    responsibilityScope: "Semantic diff amendments and changed document versions, impact analysis and affected-work routing.",
    activities: ["Строит source redline", "Определяет affected requirements/outputs", "Создаёт rework actions"],
    exclusions: ["Не хранит audit trail вместо Version Control", "Не меняет official deadline", "Не исполняет исправления"],
    typicalInputs: ["Old/new document versions", "Requirement mappings", "Current Case dependencies"],
    trigger: "Появился amendment или новая official document version.",
    skipCondition: "Новая версия идентична по hash и semantic content.",
    authority: "Может invalidate affected derived outputs и инициировать rework; substantive acceptance утверждается owners.",
    responsibilityBoundary: "Определяет влияние; Version Control фиксирует историю, owners обновляют affected deliverables.",
    keyDistinction: "Meaning and workflow impact of change, не storage версии.",
    workflowStage: "Сквозной change control",
    upstream: ["Document Intake", "Audit & Version Control", "Requirement mappings"],
    potentialOverlaps: [{ agentIds: [4, 17, 30], note: "4 фиксирует version, 17 обновляет dates, 30 формирует clarification для ambiguity." }],
  }),
  30: profile({
    simply: "Находит противоречия или неясности в tender package и превращает их в точные вопросы заказчику.",
    responsibilityScope: "Detection ambiguities/conflicts/missing instructions and preparation source-linked pre-bid clarification questions.",
    activities: ["Выявляет conflicts", "Оценивает impact", "Формирует buyer-ready questions"],
    exclusions: ["Не отвечает за заказчика", "Не придумывает missing rule", "Не готовит post-submission clarification response"],
    typicalInputs: ["Requirements и source clauses", "Solution/commercial assumptions", "Conflicting document versions"],
    trigger: "Неясность влияет на eligibility, solution, price, risk или submission.",
    skipCondition: "Нет material ambiguity либо clarification deadline закрыт.",
    authority: "Может предложить вопрос и блокирующий flag; отправку и commitments утверждает человек.",
    responsibilityBoundary: "Работает до подачи с вопросами компании buyer; Clarification Response отвечает после подачи на вопросы комиссии.",
    keyDistinction: "Outbound pre-bid question, не inbound post-bid response.",
    workflowStage: "Pre-bid clarification",
    upstream: ["Requirement Parser", "Compliance", "Legal/Commercial review"],
    potentialOverlaps: [{ agentIds: [59, 29], note: "59 отвечает комиссии после submission; 29 анализирует formal amendment." }],
  }),
  31: profile({
    simply: "Измеряет, насколько именно эта компания подходит именно этому тендеру, и объясняет причины оценки.",
    responsibilityScope: "Evidence-backed Company × Tender fit score across capabilities, requirements, geography, experience and constraints.",
    activities: ["Маппит profile к tender", "Считает weighted fit", "Объясняет strengths и gaps"],
    exclusions: ["Не измеряет общую readiness", "Не выбирает participation structure", "Не принимает Bid / No-Bid"],
    typicalInputs: ["Verified company profile", "Tender requirements/classification", "Evaluation model и evidence"],
    trigger: "Выбрана конкретная Company × Tender pair с достаточными structured inputs.",
    skipCondition: "Opportunity не прошла discovery или данных недостаточно для meaningful score.",
    authority: "Может выдать fit score, confidence и missing-data flags; commercial decision остаётся downstream/human.",
    responsibilityBoundary: "Оценивает базовый fit пары; Solution-Based Matching ищет альтернативную модель покрытия gaps.",
    keyDistinction: "Tender-specific fit score, не readiness и не win probability.",
    workflowStage: "Matching",
    upstream: ["Company Profile", "Requirement Parser", "Evaluation Criteria", "Evidence"],
    potentialOverlaps: [{ agentIds: [9, 32, 35], note: "9 — general readiness, 32 — solution path, 35 — overall Bid recommendation/win probability." }],
  }),
  32: profile({
    simply: "Если компания не закрывает тендер напрямую, ищет реалистичный способ участвовать через решение, партнёра, JV или другую роль.",
    responsibilityScope: "Alternative solution-fit modeling beyond direct product match, including partner/JV/subcontract participation options.",
    activities: ["Моделирует coverage вариантов", "Сравнивает direct/partner/JV paths", "Выявляет residual solution gaps"],
    exclusions: ["Не выбирает конкретного партнёра", "Не проектирует final consortium", "Не принимает Bid decision"],
    typicalInputs: ["Company × Tender match", "Requirement/capability gaps", "Partner/supplier capability graph"],
    trigger: "Direct match неполон либо tender требует integrated solution.",
    skipCondition: "Компания полностью покрывает scope напрямую и альтернативная route не нужна.",
    authority: "Может рекомендовать candidate participation models; руководство утверждает обязательства и route.",
    responsibilityBoundary: "Определяет возможные solution paths; Participation Route выбирает роль, Solution Architecture собирает final design.",
    keyDistinction: "Поиск моделей покрытия требований, не выбор роли или построение final solution.",
    workflowStage: "Solution matching",
    upstream: ["Company-to-Tender Match", "Gap Analysis", "Partner/Supplier knowledge"],
    potentialOverlaps: [{ agentIds: [33, 39], note: "33 выбирает organizational role; 39 детализирует утверждённую solution architecture." }],
  }),
  33: profile({
    simply: "Рекомендует, в какой роли компании лучше участвовать: prime, JV member, subcontractor или supplier.",
    responsibilityScope: "Selection and rationale of organizational participation role, control level, workshare and partner requirement.",
    activities: ["Сравнивает participation roles", "Оценивает obligations/control", "Формирует role recommendation"],
    exclusions: ["Не ищет кандидатов-партнёров", "Не создаёт consortium agreement", "Не принимает final management decision"],
    typicalInputs: ["Solution-fit options", "Eligibility gaps", "Risk/capacity/commercial constraints"],
    trigger: "Есть более одной реалистичной participation model или direct route невозможна.",
    skipCondition: "Tender допускает только прямое участие и компания полностью покрывает scope.",
    authority: "Может рекомендовать route и required partner profile; commitments утверждает руководство.",
    responsibilityBoundary: "Выбирает роль компании; Partner Discovery находит людей/организации, JV Agent распределяет final workshare.",
    keyDistinction: "Organizational role decision, не product fit и не consortium design.",
    workflowStage: "Participation design",
    upstream: ["Solution-Based Matching", "Eligibility", "Capacity/Risk"],
    potentialOverlaps: [{ agentIds: [32, 41], note: "32 моделирует solution paths; 41 оптимизирует состав и workshare выбранного consortium." }],
  }),
  34: profile({
    simply: "Составляет конкретный список того, чего не хватает для этого тендера, кто и к какому сроку должен закрыть пробел.",
    responsibilityScope: "Consolidated case-specific gaps across capability, evidence, qualification, solution and execution with action plan.",
    activities: ["Объединяет detected gaps", "Приоритизирует blockers", "Назначает action owners и dates"],
    exclusions: ["Не закрывает gaps самостоятельно", "Не считает readiness score", "Не выбирает partner"],
    typicalInputs: ["Match/eligibility/compliance findings", "Company readiness gaps", "Solution and capacity analysis"],
    trigger: "Один или несколько analyses выявили material gap.",
    skipCondition: "Нет gaps, требующих action или tracking.",
    authority: "Может классифицировать blocker/mitigation и предложить action plan; owner подтверждает feasibility.",
    responsibilityBoundary: "Консолидирует и управляет gap plan; source Agents владеют диагностикой и подтверждают closure.",
    keyDistinction: "Единый actionable gap register для case, а не отдельный score или verification.",
    workflowStage: "Matching и readiness remediation",
    upstream: ["Readiness", "Match Score", "Eligibility", "Compliance", "Capacity"],
    potentialOverlaps: [{ agentIds: [9, 31, 47], note: "9/31/47 выявляют domain gaps; 34 консолидирует cross-domain closure plan." }],
    definitionStatus: "needs-review",
    validationFinding: "Нужен единый owner rule, чтобы Gap Analysis не дублировал issue tracking внутри Compliance Matrix.",
  }),
  35: profile({
    simply: "Собирает fit, шанс победы, деньги и риски в рекомендацию: стоит ли участвовать в этом тендере.",
    responsibilityScope: "Integrated opportunity score, win-probability inputs and evidence-backed Bid / No-Bid recommendation.",
    activities: ["Агрегирует decision factors", "Моделирует win probability", "Формирует Bid/No-Bid rationale"],
    exclusions: ["Не утверждает Bid за руководство", "Не пересчитывает domain analyses", "Не формирует proposal"],
    typicalInputs: ["Match score", "Eligibility/capacity", "Commercial attractiveness", "Risk и competition"],
    trigger: "Доступен минимальный decision package для конкретной opportunity.",
    skipCondition: "Fatal exclusion уже завершил route либо данных недостаточно и Case остаётся в hold.",
    authority: "Может рекомендовать Bid, No-Bid или Conditional Bid и установить unresolved conditions; final gate человеческий.",
    responsibilityBoundary: "Интегрирует отдельные analyses в recommendation, не владеет их методиками.",
    keyDistinction: "Overall opportunity decision layer, не fit score, readiness или commercial model.",
    workflowStage: "Bid decision",
    upstream: ["Match Score", "Eligibility", "Capacity", "Commercial", "Risk", "Buyer Intelligence"],
    potentialOverlaps: [{ agentIds: [31, 37], note: "31 оценивает fit, 37 commercial case; 35 объединяет их с риском и win probability." }],
    definitionStatus: "needs-review",
    validationFinding: "Название TenderScore может смешиваться с Match Score; UI должен всегда показывать Bid / No-Bid scope.",
  }),
  36: profile({
    simply: "Проверяет, сможет ли компания реально произвести, доставить и выполнить обещанный объём в нужный срок.",
    responsibilityScope: "Pre-award execution feasibility: capacity load, schedule, bottlenecks, quality/logistics constraints and mitigations.",
    activities: ["Моделирует capacity load", "Проверяет delivery schedule", "Выявляет bottlenecks и mitigations"],
    exclusions: ["Не управляет реальным контрактом после award", "Не рассчитывает landed price", "Не утверждает production commitment"],
    typicalInputs: ["Tender volume/schedule", "Verified company capacity", "Solution and supplier lead times"],
    trigger: "Opportunity требует material production/service capacity commitment.",
    skipCondition: "Незначительный scope с заведомо свободной подтверждённой capacity.",
    authority: "Может выдать feasible/conditional/not feasible и constraints; operations owner утверждает commitment.",
    responsibilityBoundary: "Оценивает feasibility до Bid; Execution & Logistics управляет фактическим исполнением после award.",
    keyDistinction: "Pre-award capacity proof, не post-award operations tracking.",
    workflowStage: "Bid feasibility",
    upstream: ["Company capability", "Tender requirements", "Solution Architecture", "Supplier lead times"],
    potentialOverlaps: [{ agentIds: [62, 39], note: "62 ведёт реальное исполнение; 39 определяет solution design, на которой строится feasibility." }],
  }),
  37: profile({
    simply: "Проверяет, приносит ли тендер приемлемую прибыль и выдержит ли компания денежный поток и финансовые условия.",
    responsibilityScope: "Pre-bid business case across margin, cash flow, working capital, financing and commercial scenarios.",
    activities: ["Строит margin/cash-flow scenarios", "Сравнивает stress cases", "Проверяет go/no-go thresholds"],
    exclusions: ["Не формирует line-item bid price", "Не проверяет formal commercial compliance", "Не утверждает financial exposure"],
    typicalInputs: ["Preliminary cost/price assumptions", "Payment terms", "Tax/currency/financing inputs"],
    trigger: "Opportunity имеет material budget, payment delay, bonds или margin uncertainty.",
    skipCondition: "Коммерческий impact пренебрежимо мал и policy не требует business case.",
    authority: "Может рекомендовать financially attractive/conditional/unattractive; thresholds и capital commitment утверждает finance.",
    responsibilityBoundary: "Оценивает привлекательность opportunity; Cost/Pricing Agents рассчитывают детальную cost and bid price.",
    keyDistinction: "Business viability and cash flow, не калькуляция BOQ.",
    workflowStage: "Bid decision и commercial strategy",
    upstream: ["Commercial terms", "Cost estimates", "Risk", "Capacity"],
    potentialOverlaps: [{ agentIds: [50, 51, 49], note: "50 считает landed cost, 51 формирует price BOQ, 49 проверяет tender commercial rules." }],
  }),
  38: profile({
    simply: "Проверяет санкции, integrity, страновые и регуляторные риски до того, как компания возьмёт обязательства.",
    responsibilityScope: "Sanctions, restricted-party, integrity, country, regulatory and prohibited-practice risk screening.",
    activities: ["Выполняет screenings", "Оценивает risk severity", "Формирует mitigations и escalation"],
    exclusions: ["Не даёт полноценное legal opinion по контракту", "Не оценивает operational risk", "Не принимает risk acceptance"],
    typicalInputs: ["Companies/owners/countries", "Sanctions and integrity sources", "Tender/buyer/partner context"],
    trigger: "Новый counterparty/geography или изменение risk lists/context.",
    skipCondition: "Policy подтверждает свежий screening на неизменившийся scope.",
    authority: "Может поставить risk hold и требовать compliance review; acceptance/rejection принадлежит authorised humans.",
    responsibilityBoundary: "Проверяет entity/regulatory integrity; Legal & Contract Review анализирует clauses и contractual liabilities.",
    keyDistinction: "Who/where integrity screening, не what-the-contract-says review.",
    workflowStage: "Risk gate",
    upstream: ["Company/partner identities", "Risk sources", "Buyer intelligence"],
    potentialOverlaps: [{ agentIds: [57, 44], note: "57 анализирует contract obligations; 44 делает supplier due diligence, используя risk signals 38." }],
  }),
  39: profile({
    simply: "Собирает продукты, партнёров, поставщиков, поставку и сервис в одно полное решение под требования тендера.",
    responsibilityScope: "End-to-end tender solution design: configuration, coverage, partner/supplier roles, delivery and service model.",
    activities: ["Проектирует solution configuration", "Назначает component owners", "Проверяет end-to-end coverage"],
    exclusions: ["Не пишет final proposal narrative", "Не выбирает participation authority", "Не утверждает technical deviations"],
    typicalInputs: ["Requirements and gaps", "Participation route", "Product/partner/supplier capabilities"],
    trigger: "Bid route одобрена и требуется multi-component solution.",
    skipCondition: "Simple direct product response уже полностью определён и архитектурный design не нужен.",
    authority: "Может рекомендовать configuration и roles; technical/commercial commitments утверждают owners.",
    responsibilityBoundary: "Создаёт design source of truth; Technical Proposal описывает его, Technical Compliance проверяет.",
    keyDistinction: "Что именно будет поставлено и кем, не текст заявки и не compliance verdict.",
    workflowStage: "Solution design",
    upstream: ["Solution-Based Matching", "Participation Route", "Gap Analysis", "Partner/Supplier outputs"],
    potentialOverlaps: [{ agentIds: [32, 53, 48], note: "32 ищет route, 53 пишет narrative, 48 проверяет solution against requirements." }],
  }),
  40: profile({
    simply: "Ищет конкретных партнёров, которые могут закрыть недостающую компетенцию, географию или роль в этом тендере.",
    responsibilityScope: "Case-specific partner search, ranking and contact path against defined capability/role gaps.",
    activities: ["Формирует partner criteria", "Ищет candidates", "Ранжирует capability/evidence fit"],
    exclusions: ["Не хранит весь partner graph", "Не проверяет final due diligence", "Не распределяет consortium workshare"],
    typicalInputs: ["Partner requirement", "Capability graph", "Geography/eligibility constraints"],
    trigger: "Participation/solution gap требует внешнего партнёра.",
    skipCondition: "Компания закрывает scope напрямую или выбранный партнёр уже утверждён.",
    authority: "Может создать shortlist и recommendation; outreach/selection и commitments подтверждает человек.",
    responsibilityBoundary: "Находит кандидатов; JV/Consortium Agent проектирует состав, verification подтверждает facts.",
    keyDistinction: "Case-specific partner shortlist, не supplier sourcing и не reusable graph.",
    workflowStage: "Partner sourcing",
    upstream: ["Participation Route", "Gap Analysis", "Partner Capability Graph"],
    potentialOverlaps: [{ agentIds: [12, 42, 43], note: "12 хранит graph, 42 ищет local service representation, 43 ищет product suppliers." }],
  }),
  41: profile({
    simply: "Проектирует, кто входит в консорциум, какую работу выполняет и как совместно закрываются qualification и delivery.",
    responsibilityScope: "Consortium/JV composition, member roles, workshare, eligibility coverage, governance and dependency optimization.",
    activities: ["Сравнивает consortium configurations", "Распределяет workshare", "Проверяет combined eligibility coverage"],
    exclusions: ["Не заключает JV agreement", "Не ищет всех кандидатов с нуля", "Не даёт final legal approval"],
    typicalInputs: ["Partner shortlist", "Participation route", "Eligibility/solution gaps", "Member evidence"],
    trigger: "Выбран JV/consortium route или требуется combined qualification.",
    skipCondition: "Компания участвует одна, как subcontractor или simple supplier.",
    authority: "Может рекомендовать configuration и workshare; участники утверждают governance, liabilities и commitments.",
    responsibilityBoundary: "Проектирует operating structure; Legal Review проверяет agreement/risks, Proposal Agents оформляют response.",
    keyDistinction: "Optimization конкретного consortium, не просто выбор роли или поиск партнёров.",
    workflowStage: "Consortium design",
    upstream: ["Participation Route", "Partner Discovery", "Eligibility", "Risk/Legal"],
    potentialOverlaps: [{ agentIds: [33, 40, 57], note: "33 выбирает route, 40 находит members, 57 проверяет contractual/legal risk." }],
  }),
  42: profile({
    simply: "Находит местную организацию для представительства, доставки, монтажа, гарантии или сервиса там, где компания сама не присутствует.",
    responsibilityScope: "Case-specific local representation/service network search by geography, licensing, SLA and operational capability.",
    activities: ["Определяет local role", "Ищет региональных providers", "Ранжирует coverage/SLA fit"],
    exclusions: ["Не ищет product supplier", "Не проектирует весь consortium", "Не подтверждает legal appointment"],
    typicalInputs: ["Local service requirements", "Geography and SLA", "Partner intelligence"],
    trigger: "Tender требует local presence, installation, service or representation.",
    skipCondition: "Компания имеет подтверждённую собственную local capability или requirement отсутствует.",
    authority: "Может рекомендовать shortlist; appointment и contractual relationship утверждаются компанией.",
    responsibilityBoundary: "Узкая local-service search; Partner Discovery покрывает более широкий strategic capability gap.",
    keyDistinction: "Географическое присутствие и SLA, не product supply или JV structure.",
    workflowStage: "Local delivery ecosystem",
    upstream: ["Solution Architecture", "Local requirements", "Partner network"],
    potentialOverlaps: [{ agentIds: [40, 43], note: "40 ищет general capability partner; 43 ищет product supplier; 42 — local service/representation." }],
  }),
  43: profile({
    simply: "Ищет внешних производителей или поставщиков нужного товара, когда собственный каталог компании не закрывает решение.",
    responsibilityScope: "Case-specific supplier/product sourcing by specification fit, MOQ, lead time, geography and indicative price.",
    activities: ["Формирует supplier criteria", "Ищет manufacturers/vendors", "Ранжирует spec and commercial fit"],
    exclusions: ["Не проверяет supplier полностью", "Не рассылает RFQ", "Не ищет service/JV partner"],
    typicalInputs: ["Uncovered product requirements", "Specification constraints", "Supplier intelligence/market sources"],
    trigger: "Solution содержит product gap или требуется альтернативный source.",
    skipCondition: "Собственная или утверждённая supply base полностью покрывает need.",
    authority: "Может создать candidate shortlist; supplier approval требует verification/selection.",
    responsibilityBoundary: "Находит product source; Supplier Verification проверяет, RFQ obtains binding quotes.",
    keyDistinction: "Product supplier search, не partner role search и не persistent intelligence.",
    workflowStage: "Supplier sourcing",
    upstream: ["Solution Architecture", "Gap Analysis", "Supplier Intelligence"],
    potentialOverlaps: [{ agentIds: [11, 40, 44], note: "11 — reusable data, 40 — partnership capabilities, 44 — due diligence кандидата." }],
  }),
  44: profile({
    simply: "Проверяет выбранного внешнего поставщика: юридический статус, мощности, сертификаты и риски.",
    responsibilityScope: "Case-specific supplier due diligence covering identity, capacity, certificates, references, integrity and supply risk.",
    activities: ["Проверяет supplier identity", "Валидирует capacity/certificates", "Формирует risk rating"],
    exclusions: ["Не ищет suppliers", "Не проверяет собственную company participant", "Не выбирает коммерчески лучшую quote"],
    typicalInputs: ["Supplier candidate profile", "Required specs/capacity", "Registries, certificates and evidence"],
    trigger: "Supplier candidate попал в shortlist или solution.",
    skipCondition: "Supplier не используется либо свежая verification покрывает exact scope.",
    authority: "Может выдать verified/conditional/reject recommendation; sourcing owner утверждает selection.",
    responsibilityBoundary: "Due diligence внешнего supplier; Company Verification проверяет bidder company, Quote Normalization сравнивает offers.",
    keyDistinction: "Case supplier verification, не discovery и не bid participant verification.",
    workflowStage: "Supplier due diligence",
    upstream: ["Supplier Discovery", "Risk & Integrity", "Credential sources"],
    potentialOverlaps: [{ agentIds: [8, 11, 46], note: "8 проверяет bidder company; 11 хранит history; 46 сравнивает quotes, не trustworthiness." }],
  }),
  45: profile({
    simply: "Готовит единый запрос цены поставщикам, контролирует рассылку, сроки и получение ответов.",
    responsibilityScope: "Bounded RFQ workflow: requirement pack, recipient set, issue tracking, deadlines, responses and clarifications.",
    activities: ["Создаёт RFQ package", "Управляет recipients/status", "Собирает responses и clarifications"],
    exclusions: ["Не управляет всем Tender Case", "Не нормализует котировки", "Не выбирает supplier"],
    typicalInputs: ["Approved specification/RFQ scope", "Verified supplier shortlist", "Commercial instructions"],
    trigger: "Solution требует external quote или market validation.",
    skipCondition: "Нет внешних purchases либо есть актуальная binding quote.",
    authority: "Может выпускать RFQ по approved template и эскалировать non-response; коммерческие commitments утверждает owner.",
    responsibilityBoundary: "Оркестрирует только sourcing RFQ branch; TenderLab Orchestrator управляет full Case.",
    keyDistinction: "RFQ process controller, не global orchestrator и не quote comparison.",
    workflowStage: "RFQ sourcing",
    upstream: ["Solution Architecture", "Supplier Verification", "Technical specs"],
    potentialOverlaps: [{ agentIds: [1, 46], note: "1 управляет Case; 46 преобразует полученные quotes в comparable dataset." }],
    definitionStatus: "needs-review",
    validationFinding: "Уточнить, оправдан ли отдельный Agent либо это bounded workflow/tool внутри procurement capability.",
  }),
  46: profile({
    simply: "Приводит разные предложения поставщиков к одной базе, чтобы цены и условия можно было честно сравнить.",
    responsibilityScope: "Normalize supplier quotations by unit, currency, Incoterms, taxes, MOQ, lead time, exclusions and spec coverage.",
    activities: ["Маппит quote lines", "Нормализует commercial basis", "Выделяет deviations/missing values"],
    exclusions: ["Не рассчитывает final landed cost", "Не выбирает supplier", "Не меняет supplier quote assumptions"],
    typicalInputs: ["Supplier quotations", "RFQ baseline", "Currency/tax/unit rules"],
    trigger: "Получены две и более неоднородные quotes либо нужна validation одной quote.",
    skipCondition: "Нет external quotes или все уже представлены в утверждённой common basis.",
    authority: "Может пометить quote comparable/non-comparable и required clarification; selection остаётся procurement owner.",
    responsibilityBoundary: "Создаёт normalized comparison; Cost & Landed-Price добавляет freight/duties и execution costs.",
    keyDistinction: "Like-for-like supplier quote normalization, не full cost model.",
    workflowStage: "Supplier commercial analysis",
    upstream: ["RFQ Orchestrator", "Supplier quotes", "Technical specs"],
    potentialOverlaps: [{ agentIds: [50, 51], note: "50 строит total landed cost, 51 превращает selected economics в bid BOQ." }],
  }),
  47: profile({
    simply: "Показывает для каждого требования: что ответили, какое есть доказательство, кто отвечает и что ещё открыто.",
    responsibilityScope: "End-to-end requirement-response-evidence-owner-status traceability across bid preparation.",
    activities: ["Создаёт compliance rows", "Связывает responses/evidence", "Управляет owners, status и gaps"],
    exclusions: ["Не принимает technical/legal verdict вместо specialist", "Не пишет ответы", "Не собирает submission files"],
    typicalInputs: ["Requirement register", "Agent/owner responses", "Evidence and review findings"],
    trigger: "Bid route одобрена и существует structured requirement register.",
    skipCondition: "Case завершён до bid либо нет formal response requirements.",
    authority: "Может пометить complete/open/contradictory и блокировать readiness при missing mandatory evidence; subject verdict принадлежит specialist/human.",
    responsibilityBoundary: "Владеет traceability/status, а Technical/Commercial/Legal Agents владеют domain verdicts.",
    keyDistinction: "Сквозная контрольная матрица, не отдельная проверка соответствия.",
    workflowStage: "Bid compliance control",
    upstream: ["Requirement Parser", "Deliverables & Forms", "All response/evidence owners"],
    potentialOverlaps: [{ agentIds: [34, 48, 49, 56], note: "34 консолидирует capability gaps; 48/49 дают verdict; 56 независимо проверяет final bid quality." }],
    definitionStatus: "needs-review",
    validationFinding: "Нужен explicit issue-ownership rule между Compliance Matrix и Gap Analysis, чтобы один gap не управлялся дважды.",
  }),
  48: profile({
    simply: "Сравнивает предлагаемое решение с каждым техническим требованием и фиксирует соответствие, эквивалентность или отклонение.",
    responsibilityScope: "Technical compliance determination for proposed products, solution, method and evidence against tender specifications.",
    activities: ["Проверяет requirement-by-requirement fit", "Оценивает equivalence evidence", "Фиксирует deviations/clarifications"],
    exclusions: ["Не проектирует solution", "Не пишет technical proposal", "Не утверждает material deviation без human gate"],
    typicalInputs: ["Source-locked technical requirements", "Solution architecture", "Datasheets, tests and evidence"],
    trigger: "Solution components готовы для compliance review или изменились.",
    skipCondition: "Нет technical scope либо route завершён до proposal.",
    authority: "Может присвоить compliant/deviation/unknown и потребовать evidence; acceptance of deviation требует authorised decision.",
    responsibilityBoundary: "Проверяет technical truth; Compliance Matrix tracks status, Technical Proposal explains solution.",
    keyDistinction: "Domain technical verdict, не solution design и не traceability ledger.",
    workflowStage: "Technical compliance",
    upstream: ["Requirement Parser", "Strict-Spec", "Solution Architecture", "Evidence"],
    potentialOverlaps: [{ agentIds: [28, 39, 47, 53], note: "28 protects source, 39 designs, 47 tracks, 53 writes; 48 decides technical compliance state." }],
  }),
  49: profile({
    simply: "Проверяет, что цена и коммерческие условия заявки соответствуют правилам тендера и не содержат запрещённых отклонений.",
    responsibilityScope: "Commercial compliance across currency, taxes, payment, bonds, validity, Incoterms, assumptions and tender terms.",
    activities: ["Проверяет commercial clauses/forms", "Выявляет deviations", "Подтверждает required commercial evidence"],
    exclusions: ["Не рассчитывает cost", "Не устанавливает final price", "Не даёт legal opinion по всему контракту"],
    typicalInputs: ["Commercial requirements", "Pricing/BOQ", "Commercial proposal and legal findings"],
    trigger: "Commercial response или pricing version готовы/изменились.",
    skipCondition: "Case не дошёл до bid либо commercial submission отсутствует.",
    authority: "Может присвоить compliant/deviation/unknown и блокировать submission при mandatory defect; acceptance требует approval.",
    responsibilityBoundary: "Проверяет соответствие tender terms; Cost/Pricing создают economics, Legal Review оценивает contractual risk.",
    keyDistinction: "Commercial rules compliance, не profitability, cost или legal liability.",
    workflowStage: "Commercial compliance",
    upstream: ["Commercial requirements", "Pricing & BOQ", "Commercial Proposal", "Legal Review"],
    potentialOverlaps: [{ agentIds: [37, 50, 51, 57], note: "37 — attractiveness, 50/51 — cost/price, 57 — contract risk; 49 — formal commercial compliance." }],
  }),
  50: profile({
    simply: "Считает, сколько реально стоит поставить и выполнить решение с закупкой, фрахтом, пошлинами, налогами и другими затратами.",
    responsibilityScope: "Total cost and landed-price model for selected solution, suppliers, logistics, duties, taxes and execution assumptions.",
    activities: ["Собирает cost components", "Строит landed-cost scenarios", "Документирует assumptions/sensitivities"],
    exclusions: ["Не устанавливает selling price", "Не проверяет tender commercial compliance", "Не утверждает supplier quote"],
    typicalInputs: ["Normalized quotes", "Solution BOM/BOQ", "Freight, duty, tax and execution inputs"],
    trigger: "Solution и базовые sourcing inputs достаточно определены для costing.",
    skipCondition: "Нет pricing decision или cost model ещё невозможна из-за unresolved solution.",
    authority: "Может вычислять scenario costs и flag missing assumptions; finance утверждает final cost basis.",
    responsibilityBoundary: "Определяет cost floor; Pricing & BOQ превращает его в bid price с margin/strategy.",
    keyDistinction: "Полная себестоимость исполнения, не цена предложения.",
    workflowStage: "Costing",
    upstream: ["Solution Architecture", "Quotation Normalization", "Logistics/tax inputs"],
    potentialOverlaps: [{ agentIds: [46, 51, 37], note: "46 нормализует quotes, 51 формирует bid price, 37 оценивает business attractiveness." }],
  }),
  51: profile({
    simply: "Заполняет ценовую ведомость тендера и проверяет, что количества, валюты, налоги, маржа и арифметика согласованы.",
    responsibilityScope: "Bid price construction and BOQ completion from approved cost basis, margin, currency, tax and pricing strategy.",
    activities: ["Заполняет line-item prices", "Проверяет quantities/formulas", "Сводит margin/currency/tax"],
    exclusions: ["Не создаёт underlying cost evidence", "Не утверждает price", "Не пишет commercial narrative"],
    typicalInputs: ["Tender BOQ", "Approved landed cost", "Margin/strategy/FX/tax rules"],
    trigger: "Cost basis и pricing instructions утверждены.",
    skipCondition: "No-Bid либо tender не требует priced BOQ на текущем этапе.",
    authority: "Может рассчитать draft bid price и выявить arithmetic defects; final price утверждает authorised commercial owner.",
    responsibilityBoundary: "Владеет numerical bid price/BOQ; Commercial Proposal оформляет required forms/terms.",
    keyDistinction: "Расчёт и целостность цены, не cost model и не коммерческий текст.",
    workflowStage: "Bid pricing",
    upstream: ["Cost & Landed-Price", "Commercial Attractiveness", "Proposal Strategy", "Tender BOQ"],
    potentialOverlaps: [{ agentIds: [50, 54, 49], note: "50 — cost basis, 54 — commercial document, 49 — compliance review." }],
  }),
  52: profile({
    simply: "Определяет, как заявка будет выигрывать: какие сильные стороны доказывать, что подчёркивать и как строить ответ.",
    responsibilityScope: "Win strategy, positioning, themes, differentiators, evaluator mapping and response plan.",
    activities: ["Формирует win themes", "Маппит messages к criteria", "Определяет response priorities"],
    exclusions: ["Не пишет все proposal sections", "Не изменяет facts/evidence", "Не утверждает unsupported promises"],
    typicalInputs: ["Evaluation model", "Buyer/competitor intelligence", "Match/Bid decision", "Solution differentiators"],
    trigger: "Bid утверждён и доступны buyer/evaluation/solution insights.",
    skipCondition: "No-Bid либо submission — формальная минимальная response без competitive narrative.",
    authority: "Может рекомендовать positioning и content priorities; commitments и claims утверждают owners.",
    responsibilityBoundary: "Определяет что и почему говорить; Technical/Commercial Proposal Agents создают соответствующие documents.",
    keyDistinction: "Strategic message architecture, не solution design и не proposal drafting.",
    workflowStage: "Proposal strategy",
    upstream: ["Evaluation Criteria", "Buyer Intelligence", "Bid decision", "Solution Architecture"],
    potentialOverlaps: [{ agentIds: [20, 53, 60], note: "20 поставляет intelligence, 53 пишет technical response, 60 адаптирует approved story для meeting." }],
  }),
  53: profile({
    simply: "Готовит техническую часть заявки: что будет поставлено, как выполнено и какими доказательствами это подтверждается.",
    responsibilityScope: "Draft and maintain technical proposal narrative, methodology, implementation plan and evidence/annex references.",
    activities: ["Пишет source-grounded technical response", "Структурирует methodology", "Связывает evidence и annexes"],
    exclusions: ["Не проектирует solution", "Не определяет technical compliance", "Не создаёт вымышленные claims"],
    typicalInputs: ["Proposal strategy", "Solution architecture", "Compliance matrix", "Technical evidence"],
    trigger: "Solution и response strategy достаточно стабильны для drafting.",
    skipCondition: "No-Bid или tender не требует technical narrative.",
    authority: "Может создавать draft и flag missing evidence; subject experts утверждают commitments and accuracy.",
    responsibilityBoundary: "Описывает approved solution; Solution Architecture defines it, Technical Compliance validates it.",
    keyDistinction: "Technical bid document authoring, не design или verdict.",
    workflowStage: "Proposal authoring",
    upstream: ["Solution Architecture", "Proposal Strategy", "Technical Compliance", "Credentials"],
    potentialOverlaps: [{ agentIds: [39, 48, 52], note: "39 проектирует, 48 проверяет, 52 задаёт messages; 53 пишет technical submission." }],
  }),
  54: profile({
    simply: "Заполняет коммерческие формы заявки ценами, условиями, допущениями и исключениями в требуемом формате.",
    responsibilityScope: "Author commercial proposal forms, schedules, terms, assumptions and exclusions from approved commercial data.",
    activities: ["Заполняет commercial forms", "Переносит approved price schedules", "Контролирует assumptions/exclusions"],
    exclusions: ["Не рассчитывает price", "Не принимает contractual risk", "Не меняет approved commercial data"],
    typicalInputs: ["Approved Pricing/BOQ", "Commercial requirements", "Legal/compliance decisions"],
    trigger: "Commercial data и templates готовы для proposal drafting.",
    skipCondition: "No-Bid или commercial proposal на этом этапе не требуется.",
    authority: "Может формировать draft documents; finance/legal owners утверждают values, terms and deviations.",
    responsibilityBoundary: "Оформляет commercial response; Pricing computes figures, Commercial Compliance reviews rules.",
    keyDistinction: "Документное оформление коммерческого предложения, не расчёт цены.",
    workflowStage: "Proposal authoring",
    upstream: ["Pricing & BOQ", "Commercial Compliance", "Legal Review", "Deliverables & Forms"],
    potentialOverlaps: [{ agentIds: [51, 49, 58], note: "51 рассчитывает figures, 49 проверяет compliance, 58 assembles final files." }],
  }),
  55: profile({
    simply: "Выбирает из архива компании именно те проекты, CV и сертификаты, которые доказывают нужную квалификацию в этом тендере.",
    responsibilityScope: "Tender-specific selection and mapping references, CVs, experts, certificates and experience evidence to criteria.",
    activities: ["Ранжирует relevant references", "Маппит evidence к criteria", "Проверяет consent/currentness"],
    exclusions: ["Не ведёт lifecycle всех certificates", "Не подтверждает ложный experience", "Не решает eligibility самостоятельно"],
    typicalInputs: ["Eligibility/evaluation criteria", "Company experience registry", "CVs and credentials"],
    trigger: "Bid требует qualification evidence и criterion mapping.",
    skipCondition: "No-Bid или tender не требует credentials/experience.",
    authority: "Может рекомендовать strongest evidence set и flag gaps; accuracy/consent утверждает company owner.",
    responsibilityBoundary: "Отбирает reusable evidence для case; Credential Agent ведёт inventory, Eligibility определяет pass/fail.",
    keyDistinction: "Tender-specific evidence curation, не credential lifecycle.",
    workflowStage: "Qualification evidence",
    upstream: ["Eligibility criteria", "Company Profile", "Credential registry", "Reference records"],
    potentialOverlaps: [{ agentIds: [10, 25, 47], note: "10 хранит credentials, 25 решает qualification, 47 tracks evidence status." }],
  }),
  56: profile({
    simply: "Независимо ищет слабые ответы, пропуски и противоречия в почти готовой заявке и ведёт исправления до закрытия.",
    responsibilityScope: "Independent red-team quality review of complete bid package for compliance defects, consistency, evidence weakness and evaluator impact.",
    activities: ["Проводит adversarial review", "Ранжирует defects", "Ведёт closure/retest log"],
    exclusions: ["Не владеет первичным response", "Не меняет approved commitments сам", "Не заменяет domain compliance checks"],
    typicalInputs: ["Near-final bid package", "Compliance/evaluation model", "Known risks and approvals"],
    trigger: "Bid package достиг reviewable maturity или material rework завершён.",
    skipCondition: "No-Bid; для low-risk minimal response skip требует policy approval.",
    authority: "Может открыть blocking QA finding и требовать retest; waiver/acceptance утверждает authorised human.",
    responsibilityBoundary: "Независимо проверяет интегрированный package; Compliance Matrix tracks requirements, content owners исправляют.",
    keyDistinction: "Adversarial final-quality lens, не ongoing requirement tracker.",
    workflowStage: "Bid QA",
    upstream: ["All proposal outputs", "Compliance Matrix", "Legal/Commercial reviews"],
    potentialOverlaps: [{ agentIds: [47, 48, 49], note: "47 tracks, 48/49 give domain verdicts; 56 tests integrated bid quality and consistency." }],
  }),
  57: profile({
    simply: "Находит опасные обязательства в contract terms и объясняет, что принять, изменить или вынести как deviation.",
    responsibilityScope: "Legal and contract clause review across liabilities, warranties, securities, IP, termination, governing law and exceptions.",
    activities: ["Классифицирует contract risks", "Формирует deviation schedule", "Готовит decision memo"],
    exclusions: ["Не даёт полномочное legal approval", "Не выполняет sanctions screening", "Не управляет contract after award"],
    typicalInputs: ["Draft contract/conditions", "Commercial response", "Risk policy and jurisdiction context"],
    trigger: "Tender содержит contractual obligations или amendment/award меняет terms.",
    skipCondition: "Нет contractual commitment; skip legal review требует explicit policy.",
    authority: "Может flag unacceptable clauses и рекомендовать deviations; licensed/authorised humans принимают legal risk.",
    responsibilityBoundary: "Анализирует clauses до/при award; Risk & Integrity проверяет parties/countries, Award Agent ведёт signing actions.",
    keyDistinction: "Contractual obligation analysis, не integrity screening и не contract administration.",
    workflowStage: "Legal review",
    upstream: ["Tender conditions", "Commercial terms", "Risk policy"],
    potentialOverlaps: [{ agentIds: [38, 49, 61], note: "38 — integrity, 49 — commercial compliance, 61 — award-to-signing workflow." }],
  }),
  58: profile({
    simply: "Собирает утверждённые файлы в правильный пакет, проверяет подписи и формат и помогает выполнить официальную подачу.",
    responsibilityScope: "Final file assembly, manifest validation, signatures, portal packaging, authorised submission and receipt capture.",
    activities: ["Собирает approved deliverables", "Проверяет manifest/signatures/formats", "Выполняет controlled submission и сохраняет receipt"],
    exclusions: ["Не создаёт content", "Не утверждает price/commitments", "Не подаёт без authorised human credentials"],
    typicalInputs: ["Approved final documents", "Deliverables checklist", "Portal rules, signatures and authority"],
    trigger: "Все blocking approvals закрыты и submission window открыт.",
    skipCondition: "No-Bid, route terminated или buyer submission не требуется.",
    authority: "Может блокировать incomplete/invalid package; официальный submit выполняется только с authorised human action/credentials.",
    responsibilityBoundary: "Отвечает за final package and transport; content Agents и approvers отвечают за содержание.",
    keyDistinction: "Последняя контролируемая сборка и подача, не checklist planning или drafting.",
    workflowStage: "Submission",
    upstream: ["Deliverables & Forms", "Proposal outputs", "Bid QA", "Human Approval"],
    potentialOverlaps: [{ agentIds: [27, 54, 56], note: "27 tracks required items, 54 authors commercial docs, 56 QA reviews; 58 packages/submits." }],
  }),
  59: profile({
    simply: "Готовит согласованный ответ на официальный вопрос комиссии после подачи заявки.",
    responsibilityScope: "Post-submission clarification response drafting, evidence gathering, approval, versioning and controlled delivery.",
    activities: ["Разбирает buyer question", "Собирает source-linked answer", "Контролирует new commitments and submission"],
    exclusions: ["Не задаёт pre-bid вопросы", "Не меняет цену/обязательства без approval", "Не ведёт переговоры в целом"],
    typicalInputs: ["Buyer clarification request", "Submitted bid baseline", "Subject-owner facts and evidence"],
    trigger: "Buyer/commission issues formal clarification request.",
    skipCondition: "Запрос отсутствует, вне scope или response не разрешён procedure.",
    authority: "Может создать response draft и flag commitment change; authorised owners approve and submit.",
    responsibilityBoundary: "Отвечает на inbound post-bid question; Ambiguity Agent готовит outbound pre-bid questions.",
    keyDistinction: "Post-submission response against frozen bid baseline.",
    workflowStage: "Evaluation / clarification",
    upstream: ["Buyer request", "Submitted package", "Subject experts", "Human Approval"],
    potentialOverlaps: [{ agentIds: [30, 53, 58], note: "30 — pre-bid question, 53 — original technical proposal, 58 — original submission process." }],
  }),
  60: profile({
    simply: "Превращает утверждённую заявку в понятную презентацию и помогает команде готовиться к вопросам и переговорам.",
    responsibilityScope: "Presentation narrative, talking points, objection-response matrix, negotiation preparation and approved concession boundaries.",
    activities: ["Строит meeting narrative", "Готовит Q&A/objections", "Репетирует roles and negotiation limits"],
    exclusions: ["Не создаёт новые unsupported commitments", "Не ведёт переговоры вместо людей", "Не меняет submitted bid silently"],
    typicalInputs: ["Submitted proposal", "Buyer agenda/questions", "Approved strategy and negotiation authority"],
    trigger: "Buyer назначил presentation/negotiation или internal rehearsal required.",
    skipCondition: "Procedure не предусматривает meeting/negotiation.",
    authority: "Может рекомендовать messaging and response options; human negotiators decide and speak within approved limits.",
    responsibilityBoundary: "Готовит людей к interaction; Proposal Strategy задаёт bid positioning, humans conduct the meeting.",
    keyDistinction: "Live-interaction enablement после/вокруг submission, не written proposal strategy.",
    workflowStage: "Presentation / negotiation",
    upstream: ["Proposal Strategy", "Submitted bid", "Clarification findings", "Human authority"],
    potentialOverlaps: [{ agentIds: [52, 59], note: "52 задаёт proposal positioning; 59 отвечает на formal clarification; 60 готовит live meeting/negotiation." }],
    definitionStatus: "needs-review",
    validationFinding: "Для non-negotiated procurement activation должна оставаться строго условной, иначе Agent создаёт ложную обязательность.",
  }),
  61: profile({
    simply: "После award переводит уведомление о победе в список действий: гарантии, документы, условия и подписание договора.",
    responsibilityScope: "Award notice review and award-to-contract transition: conditions precedent, securities, signing checklist and ownership.",
    activities: ["Проверяет award notice", "Создаёт signing action plan", "Контролирует guarantees and conditions"],
    exclusions: ["Не подписывает контракт", "Не управляет delivery", "Не переоценивает всю bid strategy"],
    typicalInputs: ["Award notice", "Final bid and clarifications", "Contract conditions and required securities"],
    trigger: "Получен award/intent-to-award/contract invitation.",
    skipCondition: "Компания не выиграла или award оспорен/отменён до action.",
    authority: "Может определить required actions and blockers; acceptance/signature belongs to authorised company officers.",
    responsibilityBoundary: "Управляет transition до effective contract; Execution & Logistics и Contract Administration начинают post-award delivery.",
    keyDistinction: "Award-to-signing bridge, не legal clause analysis и не execution management.",
    workflowStage: "Award and contracting",
    upstream: ["Award notice", "Legal Review", "Human Approval", "Submission baseline"],
    potentialOverlaps: [{ agentIds: [57, 62, 63], note: "57 reviews terms, 62 executes delivery, 63 administers effective contract/payments." }],
  }),
  62: profile({
    simply: "Ведёт реальное исполнение выигранного контракта: производство, контроль качества, доставку, монтаж и milestones.",
    responsibilityScope: "Post-award operational execution planning and monitoring across production, QC, logistics, installation and service milestones.",
    activities: ["Ведёт execution schedule", "Отслеживает milestones/deviations", "Координирует operational mitigations"],
    exclusions: ["Не оценивает pre-bid capacity", "Не утверждает contract variation", "Не управляет invoices как основной owner"],
    typicalInputs: ["Effective contract", "Approved solution/schedule", "Production/logistics/QC status"],
    trigger: "Контракт вступил в силу и передан в operations.",
    skipCondition: "Award отсутствует или TenderLab scope заканчивается до execution.",
    authority: "Может обновлять operational status и эскалировать deviation; changes to contract require authorised process.",
    responsibilityBoundary: "Управляет physical/service delivery; Payment & Contract Administration управляет contractual records and money.",
    keyDistinction: "Фактическое post-award исполнение, не pre-bid feasibility.",
    workflowStage: "Contract execution",
    upstream: ["Award & Contract", "Solution Architecture", "Capacity assessment", "Operations systems"],
    potentialOverlaps: [{ agentIds: [36, 63], note: "36 оценивает feasibility до Bid; 63 управляет contractual milestones/invoices после award." }],
  }),
  63: profile({
    simply: "Следит за договорными milestones, актами, счетами, удержаниями, гарантиями и изменениями до закрытия контракта.",
    responsibilityScope: "Post-award contract administration: milestones, deliverable acceptance, invoices, retention, guarantees, variations and payment evidence.",
    activities: ["Ведёт contract register", "Связывает acceptance с invoices", "Контролирует variations/retention/guarantees"],
    exclusions: ["Не выполняет production/logistics", "Не утверждает invoice/payment", "Не переписывает contract terms"],
    typicalInputs: ["Effective contract", "Acceptance/milestone evidence", "Invoices, variations and payment records"],
    trigger: "Effective contract содержит administerable obligations/payment milestones.",
    skipCondition: "Нет award/effective contract либо scope платформы исключает administration.",
    authority: "Может flag overdue/missing/variance and prepare payment package; authorised finance/buyer performs approval/payment.",
    responsibilityBoundary: "Владеет contractual/financial administration; Execution Agent владеет operational delivery.",
    keyDistinction: "Документно-финансовое управление effective contract, не bid commercial compliance.",
    workflowStage: "Contract administration",
    upstream: ["Award & Contract", "Execution status", "Finance and buyer acceptance"],
    potentialOverlaps: [{ agentIds: [49, 61, 62], note: "49 проверяет pre-bid terms, 61 ведёт award transition, 62 ведёт physical execution." }],
  }),
  64: profile({
    simply: "Возвращает результат тендера и исполнения в систему, чтобы будущие поиски, scores и рекомендации стали лучше.",
    responsibilityScope: "Close-loop capture award, evaluation, buyer feedback, actual execution and model/profile corrections with provenance.",
    activities: ["Собирает outcome signals", "Сравнивает прогноз с фактом", "Предлагает knowledge/model/profile updates"],
    exclusions: ["Не меняет модели без governance", "Не создаёт raw award linkage вместо Award Intelligence", "Не стирает неудачные outcomes"],
    typicalInputs: ["Award/evaluation outcome", "Buyer feedback", "Execution/payment performance", "Prior predictions"],
    trigger: "Появился verified outcome, feedback или material post-award result.",
    skipCondition: "Нет проверяемого нового outcome либо data consent/policy запрещает reuse.",
    authority: "Может предложить and stage learning updates with evidence; production model changes require validation/governance.",
    responsibilityBoundary: "Создаёт learning record and corrections; Knowledge Graph stores links, domain models consume approved updates.",
    keyDistinction: "Feedback loop from actual result to future intelligence, not operational contract execution.",
    workflowStage: "Outcome learning",
    upstream: ["Award Intelligence", "Evaluation feedback", "Execution & Contract Administration", "Audit/Evidence"],
    potentialOverlaps: [{ agentIds: [5, 19], note: "5 stores canonical relationships, 19 captures award facts; 64 compares predicted and actual outcomes for learning." }],
    definitionStatus: "needs-review",
    validationFinding: "Нужна formal model-governance policy: какие proposed corrections могут стать production updates и после какой validation.",
  }),
};

const profileIds = Object.keys(agentProfiles).map(Number).sort((left, right) => left - right);
if (profileIds.length !== 64 || profileIds.some((id, index) => id !== index + 1)) {
  throw new Error("Canonical Agent profiles must contain exactly IDs 1–64.");
}

for (const [id, item] of Object.entries(agentProfiles)) {
  const requiredText = {
    simply: item.simply,
    responsibilityScope: item.responsibilityScope,
    trigger: item.trigger,
    skipCondition: item.skipCondition,
    authority: item.authority,
    responsibilityBoundary: item.responsibilityBoundary,
    keyDistinction: item.keyDistinction,
    workflowStage: item.workflowStage,
  };
  const incompleteFields = Object.entries(requiredText)
    .filter(([field, value]) => value.trim().length < (field === "workflowStage" ? 3 : 18))
    .map(([field]) => field);
  if (item.activities.length < 2) incompleteFields.push("activities");
  if (item.exclusions.length < 2) incompleteFields.push("exclusions");
  if (item.typicalInputs.length < 2) incompleteFields.push("typicalInputs");
  if (!item.upstream.length) incompleteFields.push("upstream");
  if (incompleteFields.length) {
    throw new Error(`Agent ${id} has an incomplete canonical responsibility profile: ${incompleteFields.join(", ")}.`);
  }
}
