import type { GlossaryScope, GlossaryTerm } from "../../catalog-schema/src";

const updatedAt = "2026-08-22";

const term = (
  code: string,
  value: string,
  ru: string,
  definition: string,
  scopes: GlossaryScope[],
  aliases: string[] = [],
  relatedTerms: string[] = [],
): GlossaryTerm => ({
  id: `term:TEA-G-${code}`,
  slug: code.toLowerCase().replaceAll("_", "-"),
  catalogue: "glossary",
  status: "draft",
  version: "1.0.0-draft",
  name: { en: value, ru },
  term: value,
  aliases,
  summary: definition,
  definition,
  scopes,
  relatedTerms,
  sourceRefs: [],
  updatedAt,
});

export const glossaryTerms: GlossaryTerm[] = [
  term("AGENT", "Agent", "Агент", "Ограниченная capability с определёнными inputs, process, output и activation conditions.", ["tenderlab", "agents"], ["AI Agent"], ["Orchestration", "Handoff"]),
  term("ORCHESTRATION", "Orchestration", "Оркестрация", "Контекстное управление последовательностью, параллельностью, условиями, повторами и approvals.", ["tenderlab", "agents", "cases"], [], ["Workflow", "Handoff"]),
  term("WORKFLOW", "Workflow", "Рабочий процесс", "Набор связанных действий и состояний, ведущих к определённому outcome.", ["core", "tenderlab", "cases"], [], ["Orchestration"]),
  term("HANDOFF", "Handoff", "Передача результата", "Передача конкретного output, решения или состояния следующему процессу.", ["tenderlab", "agents", "cases"], [], ["Input", "Output"]),
  term("PROVENANCE", "Data Provenance", "Происхождение данных", "Проверяемая информация о происхождении записи, документа, поля или вывода.", ["core", "tenderlab", "data"], ["Provenance"], ["Data Lineage", "Source Record"]),
  term("SIDE", "Tender Side", "Сторона тендерной экосистемы", "Высокоуровневая группа институционально сходных ролей в procurement ecosystem.", ["actors"], ["Side"], ["Actor Type", "Tender Role"]),
  term("ACTOR", "Actor", "Участник / субъект", "Конкретная организация, группа или лицо, участвующее в определённом procurement case.", ["actors", "core"], [], ["Actor Type", "Tender Role"]),
  term("ACTOR_TYPE", "Actor Type", "Тип участника", "Каноническая классификация сущности по её институциональной природе.", ["actors"], [], ["Actor", "Tender Side"]),
  term("TENDER_ROLE", "Tender Role", "Роль в тендере", "Функция, которую Actor выполняет в конкретной процедуре или периоде.", ["actors", "cases"], ["Case Role"], ["Actor Type", "Participation"]),
  term("DIRECT_PARTICIPATION", "Direct Participation", "Прямое участие", "Формальное участие в контроле, подаче, оценке, финансировании, contracting или administration процедуры.", ["actors", "cases"], [], ["Indirect Participation"]),
  term("INDIRECT_PARTICIPATION", "Indirect Participation", "Косвенное участие", "Поддержка, влияние, регулирование, обеспечение или получение результата без обязательного formal tender participation.", ["actors", "cases"], [], ["Direct Participation"]),
  term("DATABASE", "Database", "База данных", "Организованное физическое или логическое хранилище одного или нескольких datasets.", ["data", "core"], [], ["Dataset"]),
  term("DATASET", "Dataset", "Набор данных", "Логически связанный набор записей с определённой схемой, coverage и правилами обновления.", ["data", "core"], ["Data Set"], ["Database", "Dataset Family"]),
  term("DATASET_FAMILY", "Dataset Family", "Семейство данных", "Группа datasets, объединённых устойчивой предметной областью.", ["data"], [], ["Dataset"]),
  term("DATA_SOURCE", "Data Source", "Источник данных", "Первичное происхождение информации: система, registry, document или publication.", ["data", "core"], ["Source"], ["Data Provider", "Source Record"]),
  term("DATA_PROVIDER", "Data Provider", "Поставщик данных", "Организация или система, публикующая либо предоставляющая dataset.", ["data"], ["Provider"], ["Data Source", "Portal"]),
  term("PORTAL", "Portal / Interface", "Портал / интерфейс", "Пользовательский или программный канал доступа к данным; сам по себе не является dataset.", ["data"], ["Portal", "Interface"], ["Data Provider"]),
  term("DOCUMENT_REPOSITORY", "Document Repository", "Репозиторий документов", "Версионируемая коллекция исходных PDF, Word, Excel, drawings, forms и protocols.", ["data", "cases"], ["Document Corpus"], ["Source Record"]),
  term("RAW_DATA", "Raw Data", "Исходные данные", "Информация в полученном виде до normalization, entity resolution или analytical transformation.", ["data"], [], ["Normalized Data", "Source Record"]),
  term("NORMALIZED_DATA", "Normalized Data", "Нормализованные данные", "Очищенные и приведённые к канонической схеме values, units, dates и classifications.", ["data"], [], ["Raw Data", "Master Data"]),
  term("MASTER_DATA", "Master Data", "Мастер-данные", "Канонические records устойчивых сущностей и их authoritative identifiers.", ["data"], [], ["Canonical Entity", "Entity Resolution"]),
  term("REFERENCE_DATA", "Reference Data", "Справочные данные", "Коды, классификаторы, валюты, страны, units и controlled vocabularies.", ["data"], [], ["Master Data"]),
  term("DERIVED_DATA", "Derived Data", "Производные данные", "Информация, рассчитанная, извлечённая или объединённая из других datasets.", ["data"], ["Intelligence Data"], ["Raw Data", "Normalized Data"]),
  term("PROPRIETARY_DATASET", "Proprietary Dataset", "Собственный набор данных", "Dataset, созданный или существенно обогащённый организацией и не существующий в таком виде во внешнем source.", ["data", "tenderlab"], [], ["Derived Data"]),
  term("SOURCE_RECORD", "Source Record", "Исходная запись", "Конкретная полученная запись или document version, сохраняемая как evidence.", ["data"], [], ["Data Source", "Snapshot"]),
  term("SNAPSHOT", "Snapshot", "Снимок данных", "Неизменяемое состояние dataset или source record на определённый момент.", ["data"], [], ["Data Version"]),
  term("DATA_VERSION", "Data Version", "Версия данных", "Идентифицированное состояние record, schema или dataset с temporal context.", ["data", "cases"], [], ["Snapshot"]),
  term("ENTITY_RESOLUTION", "Entity Resolution", "Разрешение сущностей", "Процесс определения, относятся ли разнородные records к одной реальной сущности.", ["data", "actors"], ["Record Linkage"], ["Canonical Entity", "Identifier Crosswalk"]),
  term("CANONICAL_ENTITY", "Canonical Entity", "Каноническая сущность", "Стабильная identity record, объединяющая подтверждённые aliases и identifiers без потери provenance.", ["data", "actors"], [], ["Entity Resolution"]),
  term("IDENTIFIER_CROSSWALK", "Identifier Crosswalk", "Таблица соответствия идентификаторов", "Проверенное соответствие identifiers одной сущности в разных systems.", ["data"], [], ["Entity Resolution"]),
  term("DATA_LINEAGE", "Data Lineage", "Линия происхождения данных", "Цепочка transformations от source record до normalized или derived value.", ["data", "tenderlab"], [], ["Data Provenance"]),
  term("PERMITTED_USE", "Permitted Use", "Разрешённое использование", "Зафиксированный объём действий, допускаемых licence, terms и applicable law.", ["data", "rules"], [], ["Data Licence"]),
  term("DATA_LICENCE", "Data Licence", "Лицензия на данные", "Правовые условия access, copying, modification, redistribution и commercial use.", ["data", "rules"], [], ["Permitted Use"]),
  term("OCDS", "Open Contracting Data Standard", "Стандарт открытых контрактных данных", "Международная модель публикации planning, tender, award, contract и implementation data.", ["data", "rules"], ["OCDS"], ["Dataset"]),
  term("BODS", "Beneficial Ownership Data Standard", "Стандарт данных о бенефициарном владении", "Структурированная модель entities, persons и ownership/control statements.", ["data", "actors"], ["BODS"], ["Beneficial Ownership"]),
];

export const glossaryScopeLabels: Record<GlossaryScope, string> = {
  core: "Core procurement",
  tenderlab: "TenderLab",
  agents: "Agents",
  cases: "Cases",
  actors: "Sides & Actors",
  data: "Data & Sources",
  rules: "Rules",
};
