import type {
  RealAgentImplementation,
  RealAgentLesson,
  RealAgentReusablePattern,
} from "../../catalog-schema/src";

const tenderBalanceId = "implementation:TEA-RAI-TENDERBALANCE" as const;
const logisticsCostId = "implementation:TEA-RAI-LOGISTICS-COST" as const;
const tenderBoostId = "implementation:TEA-RAI-TENDERBOOST" as const;

const evidencePatternId = "pattern:TEA-RAP-EVIDENCE-BEFORE-PRODUCTION" as const;
const sourcePatternId = "pattern:TEA-RAP-SOURCE-ROLE-BEFORE-FACT" as const;
const structurePatternId = "pattern:TEA-RAP-STRUCTURE-BEFORE-SEMANTICS" as const;
const resultPatternId = "pattern:TEA-RAP-COMPLETE-CASE-RESULT" as const;
const workflowPatternId = "pattern:TEA-RAP-TRUTHFUL-HUMAN-WORKFLOW" as const;
const releasePatternId = "pattern:TEA-RAP-RELEASE-EVIDENCE-PARITY" as const;

const realEvidenceLessonId = "lesson:TEA-RAL-001-REAL-EVIDENCE" as const;
const sourceRoleLessonId = "lesson:TEA-RAL-002-SOURCE-ROLE" as const;
const structureLessonId = "lesson:TEA-RAL-003-STRUCTURE" as const;
const workflowLessonId = "lesson:TEA-RAL-004-WORKFLOW-STATES" as const;
const caseIdentityLessonId = "lesson:TEA-RAL-005-CASE-IDENTITY" as const;
const trustLessonId = "lesson:TEA-RAL-006-TRUST" as const;
const financialPeriodsLessonId = "lesson:TEA-RAL-007-FINANCIAL-PERIODS" as const;
const incotermLessonId = "lesson:TEA-RAL-008-INCOTERM-TRANSFORMATION" as const;
const releaseLessonId = "lesson:TEA-RAL-009-RELEASE-EVIDENCE" as const;

export const realAgentImplementations: RealAgentImplementation[] = [
  {
    id: tenderBalanceId,
    slug: "tenderbalance",
    name: "TenderBalance",
    ownerAgentId: "agent:TL-A008",
    clientProductId: "product:TA-BALANCE",
    descriptor: "Source-traceable balance-sheet digitization and FIN-1 preparation",
    tor: "Read, structure, validate, review, and retain supplied balance-sheet evidence without making tender-eligibility decisions.",
    primaryInputs: ["Digital or scanned balance sheets", "Comparative reporting periods", "Explicit client corrections"],
    primaryOutput: "A versioned, source-traceable, human-reviewable financial evidence Case with optional FIN-1 output",
    downstreamConsumer: "Later tender qualification, comparison, and matching workflows under separate authority",
    maturity: "validated-client-workflow",
    evidenceStrength: "local-production-build-replay",
    deploymentStatus: "deployed-test-surface",
    runtimeReadiness: "static-client-workflow",
    methodologyVersion: "2.0.0",
    methodRefs: [
      "docs/real-tender-agent-development-methodology.md",
      "docs/real-tender-agent-development-policy.json",
    ],
    playbookRefs: [
      "docs/balance-sheet-digitization-mvp.md",
      "packages/catalog-schema/schema/balance-sheet-review.schema.json",
      "packages/catalog-schema/schema/fin1-historical-performance.schema.json",
    ],
    knownLimitations: [
      "Browser-local Cases are not durable tenant-isolated Artifacts.",
      "OCR remains bounded and requires review for uncertain scans.",
      "Only FIN-1 is implemented; broader financial due diligence remains out of scope.",
    ],
    patternIds: [evidencePatternId, sourcePatternId, structurePatternId, resultPatternId, workflowPatternId, releasePatternId],
    lessonIds: [
      realEvidenceLessonId,
      sourceRoleLessonId,
      structureLessonId,
      workflowLessonId,
      caseIdentityLessonId,
      trustLessonId,
      financialPeriodsLessonId,
      releaseLessonId,
    ],
    updatedAt: "2026-08-28",
  },
  {
    id: logisticsCostId,
    slug: "tender-logistics-cost",
    name: "TENDER LOGISTICS COST",
    ownerAgentId: "agent:TL-A050",
    clientProductId: "product:TA-LANDED-COST",
    descriptor: "Evidence-aware logistics and Incoterms cost transformation",
    tor: "Transform a sourced commercial position into a reviewable logistics-cost scenario while preserving estimates, assumptions, and human authority.",
    primaryInputs: ["Supplier quotation", "Cargo and packing evidence", "Source and target Incoterms", "Route and transport assumptions"],
    primaryOutput: "One reconciled preliminary logistics estimate with provenance, loadability, uncertainty, and commercial consequence",
    downstreamConsumer: "Pricing, BOQ, commercial proposal, and participation analysis",
    maturity: "validated-client-workflow",
    evidenceStrength: "local-production-build-replay",
    deploymentStatus: "deployed-test-surface",
    runtimeReadiness: "static-client-workflow",
    methodologyVersion: "2.0.0",
    methodRefs: [
      "docs/real-tender-agent-development-methodology.md",
      "docs/real-tender-agent-development-policy.json",
    ],
    playbookRefs: [
      "docs/contract-logistics-incoterms-architecture.md",
      "docs/contract-logistics-test-evidence.md",
      "docs/contract-logistics-migration-readiness.md",
    ],
    knownLimitations: [
      "Freight, insurance, tax, FX, and capacity inputs are not governed live feeds.",
      "Benchmark-derived values remain estimates and require dated replacement evidence.",
      "Browser-local Cases and number arithmetic are not an enterprise money runtime.",
    ],
    patternIds: [evidencePatternId, sourcePatternId, structurePatternId, resultPatternId, workflowPatternId, releasePatternId],
    lessonIds: [
      realEvidenceLessonId,
      sourceRoleLessonId,
      structureLessonId,
      workflowLessonId,
      trustLessonId,
      incotermLessonId,
      releaseLessonId,
    ],
    updatedAt: "2026-08-28",
  },
  {
    id: tenderBoostId,
    slug: "tenderboost-ai",
    name: "TenderBoost AI · TenderApps Agent 03",
    ownerAgentId: "agent:TL-A031",
    clientProductId: "product:TA-TENDERBOOST",
    descriptor: "Audited Company × Tender evidence support and consultant-controlled campaign preparation",
    tor: "Compare one historical Company × Tender estimate with a separately evidence-gated audited result, explain supported and missing components, retain the consultant decision, and prepare a campaign brief without making Bid/No-Bid decisions or claiming external outreach.",
    primaryInputs: [
      "Versioned tender record with absolute deadline and source snapshot",
      "Versioned supplier profile and evidence records",
      "Frozen legacy match inputs, reviewed pair-to-evidence mappings, and consultant decisions, suppression, consent, and risk state",
    ],
    primaryOutput: "A versioned Company × Tender opportunity Case with immutable legacy metrics, an evidence-gated audited result or explicit MISSING state, consultant decision, blockers, and optional non-sending campaign brief",
    downstreamConsumer: "Consultant review, later participation/Bid-No-Bid analysis, and future separately authorized campaign services",
    maturity: "concept-or-simulation",
    evidenceStrength: "unit-or-synthetic-fixture",
    deploymentStatus: "not-deployed",
    runtimeReadiness: "static-client-workflow",
    methodologyVersion: "2.0.0",
    methodRefs: [
      "docs/real-tender-agent-development-methodology.md",
      "docs/real-tender-agent-development-policy.json",
    ],
    playbookRefs: [
      "docs/tenderboost-agent-03-integration.md",
      "docs/tenderboost-scoring-model-card.md",
      "packages/tenderboost/src/types.ts",
      "packages/tenderboost/src/engine.ts",
    ],
    knownLimitations: [
      "The migrated 16-tender/10-supplier fixture is a dated demonstration snapshot, not a live authorized feed.",
      "Only 6 of 18 historically assessed pairs have both distinct audited evidence components; the other 12 remain MISSING.",
      "The experiment uses a dated demonstration fixture with source references, not freshly replayed underlying source documents.",
      "Legacy Match Score and readiness remain historical estimates and are excluded from claims of audited truth.",
      "Browser-local Cases are not durable tenant-isolated Artifacts.",
      "No sending, CRM, consent, suppression, response, or campaign-event integration is connected.",
      "The relationship view is a fixed schematic, not a geospatial map, distance model, coordinate plot, or routing result.",
    ],
    patternIds: [],
    lessonIds: [],
    updatedAt: "2026-08-30",
  },
];

export const realAgentReusablePatterns: RealAgentReusablePattern[] = [
  {
    id: evidencePatternId,
    slug: "evidence-before-production",
    title: "Real evidence before production intelligence",
    problem: "Synthetic success can hide failures in real document structure, terminology, and client workflow.",
    rule: "Test uncertain intelligence on authorized realistic evidence in an isolated experiment before production integration.",
    methodologyGateIds: ["evidence-plan", "isolated-experiment", "actual-output-audit", "methodology-approval"],
    confirmedByImplementationIds: [tenderBalanceId, logisticsCostId],
    lessonIds: [realEvidenceLessonId],
    evidenceStrength: "local-production-build-replay",
    status: "validated",
  },
  {
    id: sourcePatternId,
    slug: "source-role-before-fact",
    title: "Source role before fact extraction",
    problem: "Templates, supporting material, product specifications, and user entries can be mistaken for authoritative client facts.",
    rule: "Classify input role first and preserve SOURCE, CALCULATED, ESTIMATED, ASSUMED, and MISSING as orthogonal meanings.",
    methodologyGateIds: ["canonical-data-contract", "actual-output-audit", "production-integration"],
    confirmedByImplementationIds: [tenderBalanceId, logisticsCostId],
    lessonIds: [sourceRoleLessonId],
    evidenceStrength: "local-production-build-replay",
    status: "validated",
  },
  {
    id: structurePatternId,
    slug: "structure-before-semantics",
    title: "Preserve format structure before semantic mapping",
    problem: "Flattened PDF or spreadsheet text destroys columns, table grain, periods, totals, and commercial relationships.",
    rule: "Use format-aware intermediate structures, then map them into one canonical result.",
    methodologyGateIds: ["canonical-data-contract", "isolated-experiment", "failure-layer-diagnosis"],
    confirmedByImplementationIds: [tenderBalanceId, logisticsCostId],
    lessonIds: [structureLessonId],
    evidenceStrength: "local-production-build-replay",
    status: "validated",
  },
  {
    id: resultPatternId,
    slug: "complete-case-result",
    title: "One complete Case-scoped result",
    problem: "Separate UI, export, explanation, or latest-Case models can disagree while appearing valid in isolation.",
    rule: "Persist one explicit, versioned Case result containing the answer, explanation, provenance, trust, workflow, and artifact identities.",
    methodologyGateIds: ["canonical-data-contract", "production-integration", "production-verification"],
    confirmedByImplementationIds: [tenderBalanceId, logisticsCostId],
    lessonIds: [caseIdentityLessonId, trustLessonId],
    evidenceStrength: "local-production-build-replay",
    status: "validated",
  },
  {
    id: workflowPatternId,
    slug: "truthful-human-workflow",
    title: "Truthful human workflow without dead ends",
    problem: "Disabled controls and approval-only persistence force clients to infer hidden state or lose useful partial work.",
    rule: "Explain exact blockers and keep draft, preliminary, reviewed, approved, and released states distinct.",
    methodologyGateIds: ["human-workflow-integration", "production-verification"],
    confirmedByImplementationIds: [tenderBalanceId, logisticsCostId],
    lessonIds: [workflowLessonId],
    evidenceStrength: "local-production-build-replay",
    status: "validated",
  },
  {
    id: releasePatternId,
    slug: "release-evidence-parity",
    title: "Release claims require artifact parity",
    problem: "A successful build, stale export, or copied test count can be mistaken for proof of the current deployed result.",
    rule: "Bind release evidence to input, Case/result, code or model version, output artifact, trust verdict, authorization, and representative replay.",
    methodologyGateIds: ["release-evidence-gate", "authorized-deployment", "deployed-equivalent-replay"],
    confirmedByImplementationIds: [tenderBalanceId, logisticsCostId],
    lessonIds: [releaseLessonId],
    evidenceStrength: "deployed-smoke-verification",
    status: "validated",
  },
];

export const realAgentLessons: RealAgentLesson[] = [
  {
    id: realEvidenceLessonId,
    title: "Real inputs reveal method failures that simulations cannot",
    classification: "general",
    status: "validated",
    evidenceScope: "multiple-implementations",
    implementationIds: [tenderBalanceId, logisticsCostId],
    failureLayer: "method selection",
    whatHappened: "Synthetic flows appeared successful while straightforward real documents exposed extraction and mapping failures.",
    rootCause: "The client interface had become the experiment and fixture success was treated as real-world evidence.",
    reusableRule: "Benchmark uncertain intelligence independently on authorized realistic evidence before production integration.",
    methodologyImpact: "Established the evidence-plan, isolated-experiment, and methodology-approval gates.",
    playbookRefs: [],
    regressionRefs: ["tests/balance-sheet-review.test.mjs", "tests/logistics-costing.test.mjs"],
    learnedAt: "2026-08-28",
  },
  {
    id: sourceRoleLessonId,
    title: "Input provenance must be classified before values are promoted",
    classification: "general",
    status: "validated",
    evidenceScope: "multiple-implementations",
    implementationIds: [tenderBalanceId, logisticsCostId],
    failureLayer: "semantic mapping",
    whatHappened: "Template figures and non-shipment product attributes were eligible to become client facts.",
    rootCause: "Input origin, document role, value class, confidence, and review status were collapsed.",
    reusableRule: "Assign source roles before mapping and preserve value semantics without silent substitution.",
    methodologyImpact: "Created the canonical source-role and value-resolution contract.",
    playbookRefs: [],
    regressionRefs: ["tests/tender-balance-fin1.test.mjs", "tests/logistics-costing.test.mjs"],
    learnedAt: "2026-08-28",
  },
  {
    id: structureLessonId,
    title: "Flattened text is not a trustworthy document model",
    classification: "general",
    status: "validated",
    evidenceScope: "multiple-implementations",
    implementationIds: [tenderBalanceId, logisticsCostId],
    failureLayer: "structural reconstruction",
    whatHappened: "Reporting columns collapsed in PDFs and priced rows lost their commercial grain in spreadsheets.",
    rootCause: "Semantic extraction began after discarding geometry and table relationships.",
    reusableRule: "Recover format-aware intermediate structure before semantic mapping and arithmetic.",
    methodologyImpact: "Added format-aware extraction and structural-reconstruction regression families.",
    playbookRefs: [],
    regressionRefs: ["tests/balance-sheet-review.test.mjs", "tests/logistics-costing.test.mjs"],
    learnedAt: "2026-08-28",
  },
  {
    id: workflowLessonId,
    title: "Persistence, approval, and release are different states",
    classification: "general",
    status: "validated",
    evidenceScope: "multiple-implementations",
    implementationIds: [tenderBalanceId, logisticsCostId],
    failureLayer: "human review or readiness",
    whatHappened: "Clients met disabled approval controls or could not retain a useful preliminary result.",
    rootCause: "Internal readiness and approval conditions were exposed as opaque UI state and persistence shared the same gate.",
    reusableRule: "Guide the next action and keep draft, preliminary, reviewed, approved, and released transitions explicit.",
    methodologyImpact: "Added the human-workflow integration gate and truthful partial persistence rule.",
    playbookRefs: [],
    regressionRefs: ["tests/tender-balance-client-workflow.test.mjs", "tests/logistics-costing.test.mjs"],
    learnedAt: "2026-08-28",
  },
  {
    id: caseIdentityLessonId,
    title: "Case outputs cannot rely on latest-state fallback",
    classification: "general",
    status: "validated",
    evidenceScope: "single-implementation",
    implementationIds: [tenderBalanceId],
    failureLayer: "Case persistence or navigation",
    whatHappened: "Result and FIN routes could resolve stale or latest Case state instead of the selected Case.",
    rootCause: "Agent-level navigation and Case-scoped result identity shared implicit state.",
    reusableRule: "Every Case-scoped result, export, and handoff retains an explicit Case ID with no silent latest fallback.",
    methodologyImpact: "Added explicit Case identity to the canonical result invariant.",
    playbookRefs: [],
    regressionRefs: ["tests/tender-balance-navigation.test.mjs"],
    learnedAt: "2026-08-28",
  },
  {
    id: trustLessonId,
    title: "Extraction confidence is not overall trust",
    classification: "general",
    status: "validated",
    evidenceScope: "multiple-implementations",
    implementationIds: [tenderBalanceId, logisticsCostId],
    failureLayer: "validation and presentation",
    whatHappened: "Mechanically readable or precisely displayed values could still be structurally, semantically, or evidentially unreliable.",
    rootCause: "Recognition confidence, provenance, domain validation, and review status were presented as one certainty signal.",
    reusableRule: "Evaluate recognition, structure, semantics, arithmetic/domain checks, and human review separately.",
    methodologyImpact: "Added the multidimensional trust model and contradiction downgrade rule.",
    playbookRefs: [],
    regressionRefs: ["tests/balance-sheet-review.test.mjs", "tests/logistics-costing.test.mjs"],
    learnedAt: "2026-08-28",
  },
  {
    id: financialPeriodsLessonId,
    title: "FIN periods must come from eligible statement evidence",
    classification: "agent-specific",
    status: "validated",
    evidenceScope: "single-implementation",
    implementationIds: [tenderBalanceId],
    failureLayer: "financial semantic mapping",
    whatHappened: "Template years, unrelated dates, and Average columns could be promoted as historical FIN periods.",
    rootCause: "Document-wide dates were mapped before statement isolation and source-role eligibility.",
    reusableRule: "TenderBalance isolates statement context and derives FIN periods only from eligible source columns.",
    methodologyImpact: "Retained as TenderBalance playbook knowledge; only the source-role pattern entered the general method.",
    playbookRefs: ["docs/balance-sheet-digitization-mvp.md"],
    regressionRefs: ["tests/tender-balance-fin1.test.mjs"],
    learnedAt: "2026-08-28",
  },
  {
    id: incotermLessonId,
    title: "Logistics transformation needs separate source and target scopes",
    classification: "agent-specific",
    status: "validated",
    evidenceScope: "single-implementation",
    implementationIds: [logisticsCostId],
    failureLayer: "logistics semantic mapping",
    whatHappened: "Supplier Incoterm, requested destination condition, and logistics-only scope could be conflated or double-counted.",
    rootCause: "Source commercial state, target state, and calculated difference were not modeled independently.",
    reusableRule: "TENDER LOGISTICS COST preserves source Incoterm, target Incoterm, and component difference as separate records.",
    methodologyImpact: "Retained as Logistics playbook knowledge; the general method keeps only source-to-target transformation traceability.",
    playbookRefs: ["docs/contract-logistics-incoterms-architecture.md"],
    regressionRefs: ["tests/logistics-costing.test.mjs", "tests/logistics-costing-simulations.test.mjs"],
    learnedAt: "2026-08-28",
  },
  {
    id: releaseLessonId,
    title: "Release evidence must identify the artifact actually verified",
    classification: "general",
    status: "validated",
    evidenceScope: "multiple-implementations",
    implementationIds: [tenderBalanceId, logisticsCostId],
    failureLayer: "release evidence",
    whatHappened: "Stale exports and copied test counts could be read as proof of the current build.",
    rootCause: "Input, result, code/model version, output artifact, and validation verdict were not bound in one release ledger.",
    reusableRule: "Treat old artifacts as history and require versioned artifact parity plus representative replay for current release claims.",
    methodologyImpact: "Added the release-evidence gate and deployed-equivalent replay.",
    playbookRefs: [],
    regressionRefs: ["tests/real-tender-agent-development-methodology.test.mjs"],
    learnedAt: "2026-08-28",
  },
];

export const realAgentImplementationById = new Map(realAgentImplementations.map((item) => [item.id, item]));
export const realAgentPatternById = new Map(realAgentReusablePatterns.map((item) => [item.id, item]));
export const realAgentLessonById = new Map(realAgentLessons.map((item) => [item.id, item]));

export function realAgentImplementationsForAgent(agentId: string) {
  return realAgentImplementations.filter((item) => item.ownerAgentId === agentId);
}
